### ISSUE TITLE
[Bug] Unwanted test run after dbt build --select <seed_name>

### ISSUE THREAD

**Issue by tmirko** [dbt-labs/dbt-core#10086]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After executing `dbt build --select <seed_name>` command is also starting a generic test run in which `<seed_name>` is referenced. 

### Expected Behavior

Not run tests that aren't referenced.  

### Steps To Reproduce

* Create files as referenced here https://gist.github.com/tmirko/b1c6e85fd75336c5285ce35e501872f4
* execute `dbt --no-use-colors build --target dev_cloud --select fqn:downstream.country_codes`

### Relevant log output

```shell
$ dbt --no-use-colors build --target dev_cloud --select fqn:downstream.country_codes
13:33:23  Running with dbt=1.7.12
13:33:23  dbt-loom: Patching ref protection methods to support dbt-loom dependencies.
13:33:23  dbt-loom: Loading manifest for `dbt_loom_1_one` from `file`
13:33:23  Registered adapter: bigquery=1.7.7
13:33:23  dbt-loom: Injecting nodes
13:33:23  Found 10 models, 22 tests, 1 seed, 5 sources, 0 exposures, 0 metrics, 457 macros, 0 groups, 0 semantic models
13:33:23  
13:33:25  Concurrency: 2 threads (target='dev_cloud')
13:33:25  
13:33:25  1 of 2 START seed file downstream_dev.country_codes ............................ [RUN]
13:33:28  1 of 2 OK loaded seed file downstream_dev.country_codes ........................ [INSERT 2 in 3.54s]
13:33:28  2 of 2 START test is_country_valid_stg_asset_daily_api_country ................. [RUN]
13:33:28  2 of 2 ERROR is_country_valid_stg_asset_daily_api_country ...................... [ERROR in 0.31s]
13:33:28  
13:33:28  Finished running 1 seed, 1 test in 0 hours 0 minutes and 4.99 seconds (4.99s).
13:33:28  
13:33:28  Completed with 1 error and 0 warnings:
13:33:28  
13:33:28    Runtime Error in test is_country_valid_stg_asset_daily_api_country (models/data_product_example/api/schema.yml)
  404 Not found: Table  was not found in location ; reason: notFound, message: Not found:  was not found in location 
  
  Location: 
  Job ID: 
  
13:33:28  
13:33:28  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
```

### Environment

```markdown
- OS: wsl2 ubuntu image
- Python: 3.10
- dbt: 1.7.12
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thanks for providing those example files @tmirko ! 🤩 

Could you try out the `buildable` [indirect selection](https://docs.getdbt.com/reference/global-configs/indirect-selection) mode?
```
dbt build --select country_codes --indirect-selection buildable
```

There's a little more explanation and diagrams here: https://github.com/dbt-labs/dbt-core/issues/9746#issuecomment-1989027389

**Comment by tmirko** [comment]
Thanks for quick response @dbeatty10.

So mentioned command works as expected. 

However I would expect the same happening without --indirect-selection buildable i.e. not executing is_country_valid test. 

Is this expected behavior? Should I add --indirect-selection buildable to build commands from now on?

**Comment by dbeatty10** [comment]
The behavior you are seeing is expected for the `eager` indirect selection mode, which is the default.

The `buildable` mode can often be more intuitive and desirable, but it would be a breaking change if we promoted it to be the default instead. Since there's may ways for users to configure the indirect selection mode, we've opted not to change the default.

### Configuring the indirect selection mode

If you want to configure it for yourself, here are the options:
1. [`--indirect-selection` CLI argument](https://docs.getdbt.com/reference/global-configs/command-line-options)
1. [`DBT_INDIRECT_SELECTION` environment variable](https://docs.getdbt.com/reference/global-configs/environment-variable-configs)
1. [`indirect_selection` global config flag in `dbt_project.yml`](https://docs.getdbt.com/reference/global-configs/project-flags)

It can also be configured within any [YAML selectors](https://docs.getdbt.com/reference/node-selection/yaml-selectors#full-yaml) that you have defined.

Since dbt is behaving as expected here, I'm going to close this as "not planned".
