### ISSUE TITLE
[Bug]Jobs discovering and attempting parse potentially premature manifest - v12  

### ISSUE THREAD

**Issue by mateo-persona** [dbt-labs/dbt-core#10163]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Current Version: DBT 1.7

In DBT Cloud and DBT Cloud CLI, a job is discovering and attempting to parse a manifest version (V12) that is not yet listed publicly on any DBT documentation. According to [DBT documentation](https://docs.getdbt.com/reference/artifacts/manifest-json), V12 is not a valid manifest version. Upon examining manifest V12, it appears it is for an unreleased version of DBT. 
No changes were made to our DBT versioning and 

Link to V12 manifest schema: https://schemas.getdbt.com/dbt/manifest/v12.json

```
{
  "properties": {
    "metadata": {
      "type": "object",
      "title": "ManifestMetadata",
      "description": "Metadata about the manifest",
      "properties": {
        "dbt_schema_version": {
          "type": "string"
        },
        "dbt_version": {
          "type": "string",
          "default": "1.9.0a1"
        }
      }
    }
    ...
  }
}
```

### Expected Behavior

- DBT Cloud and DBT Cloud CLI should only discover and parse manifest versions that are publicly documented and valid according to the current DBT documentation.
- When using DBT 1.7, the job should not encounter or attempt to parse manifest version V12, as it is not listed in the public documentation and appears to be for an unreleased version of DBT.
- The job should correctly identify and parse the appropriate manifest version (up to V11) as specified in the current DBT documentation.

### Steps To Reproduce

`dbt deps`
`dbt build --select state:modified+1`

### Relevant log output

```shell
# DBT Job commands:
dbt deps
dbt build --select state:modified+1

# Output:

dbt run --select state:modified+1 --exclude staging.segment marts.segment

dbt command failed21:34:24  Running with dbt=1.6.14
21:34:25  Registered adapter: snowflake=1.6.8
21:34:25  Unable to do partial parsing because saved manifest not found. Starting full parse.
21:34:30  Encountered an error:
Runtime Error
  Expected a schema version of "https://schemas.getdbt.com/dbt/manifest/v10.json" in /tmp/defer-artifacts/manifest.json, but found "https://schemas.getdbt.com/dbt/manifest/v12.json". Are you running with a different version of dbt?
```

### Environment
- OS: Sonoma 14.4.1 
- Python: 3.9
- dbt: 1.7

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reaching out @mateo-persona !

Could you submit to the dbt Cloud support team via the "Create a support ticket" or "Leave feedback" button in dbt Cloud?
Link to this GitHub issue in your description. See screenshots below for an example.

Since this is specific to dbt Cloud and not dbt Core, I'm going to close this issue as "not planned" for the dbt-core repo.

### Screenshots in dbt Cloud

Here's a couple screenshots of the process of leaving feedback in dbt Cloud (for this one you might choose "Create a support ticket" instead):

1. 
<img width="250" alt="Screenshot 2024-03-22 at 7 09 17 AM" src="https://github.com/dbt-labs/dbt-core/assets/44704949/44457c35-fc83-47d7-8737-2ceddc763042">

2. 
<img width="400" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/de9a4773-f7a7-43f3-b0de-54d4e6b21582">

**Comment by jtcohen6** [comment]
dbt Core v1.8 is using v12, we just need to update the docs:
- https://github.com/dbt-labs/docs.getdbt.com/issues/5525
