### ISSUE TITLE
[Feature] Flag for adding the updating timestamp as a column in seeds

### ISSUE THREAD

**Issue by JavierLopezT** [dbt-labs/dbt-core#10170]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When loading a seed, I would like to have a column named like `updated_at` with the timestamp of when the seed was loaded in the table. Thus, there could be config value that could be named `add-updated-at` or something similar that could be used as a flag in the cli or as a config parameter in the yml files.

This would work for both `full-refresh` loads or incremental loads.

**Comment by dbeatty10** [comment]
Thanks for reaching out @JavierLopezT !

Currently, the only thing in dbt that adds metadata columns is dbt snapshots, and we aren't looking to expand further. So we're not keen to add configuration to dbt seeds that adds any metadata columns that aren't present in the seed CSV (e.g. a column like `updated_at`).

But being able to transform datasets is what dbt does best, so you can get your desired result by pairing a model downstream of your seed like this:

`seeds/my_seed.csv`

```csv
id
1
```

`models/my_table.sql`

```sql
select
    *,
    {{ dbt.current_timestamp() }} as updated_at

from {{ ref("my_seed") }}
````

```shell
dbt build -s my_seed my_table
dbt show -s my_table
```

| id |           updated_at |
| -- | -------------------- |
|  1 | 2024-05-17 13:13:... |

Since dbt already provides lots of capabilities for this type of use-case, I'm closing this as "not planned".

**Comment by Will-Gaines** [comment]
hi @dbeatty10 I've found this thread while looking at similar questions.

I understand the rationale for not adding the feature, but in your suggested solution is there a way to not have `my_seed` create an object in your database (ie to treat it like an `ephemeral` materialised model)?
