### ISSUE TITLE
[Bug] dbt config format

### ISSUE THREAD

**Issue by ciolo15** [dbt-labs/dbt-core#10293]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have the following code and I click the Format button. First attempt, nothing happens:
![image](https://github.com/dbt-labs/dbt-core/assets/18404205/0eb89752-b1bf-4edd-98e2-ef662c613aef)
On the second attempt, I will add a few more characters to the unique_key property:
![image](https://github.com/dbt-labs/dbt-core/assets/18404205/766b7261-94aa-471b-88a9-dcc22d6fbb5f)
On the third attempt, I will some other characters:
![image](https://github.com/dbt-labs/dbt-core/assets/18404205/222bb17d-9b09-4a8a-be09-2542685b4182)

### Expected Behavior

The expected behaviour is what happens on the third attempt but it looks like the formatting is working based on the number of character that I have in the config macro.

### Steps To Reproduce

Just follow the code in the attached photos

### Environment

```markdown
- OS:
- Python:
- dbt:1.7
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @ciolo15 !

Could you submit to the dbt Cloud support team via the "Create a support ticket" or "Leave feedback" button in dbt Cloud?
Link to this GitHub issue in your description. See screenshots below for an example.

Since this is specific to dbt Cloud and not dbt Core, I'm going to close this issue as "not planned" for the dbt-core repo.

### Screenshots in dbt Cloud

Here's a couple screenshots of the process of leaving feedback in dbt Cloud (for this one you might choose "Create a support ticket" instead):

1. 
<img width="250" alt="Screenshot 2024-03-22 at 7 09 17 AM" src="https://github.com/dbt-labs/dbt-core/assets/44704949/44457c35-fc83-47d7-8737-2ceddc763042">

2. 
<img width="400" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/de9a4773-f7a7-43f3-b0de-54d4e6b21582">
