### ISSUE TITLE
[Feature]  Support `--empty` flag for snapshots

### ISSUE THREAD

**Issue by d-cole** [dbt-labs/dbt-core#10372]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Support the empty flag for snapshots. Currently, `dbt snapshot --empty` results in the error: "Error: No such option: --empty Did you mean --help?". This means unit tests for models downstream of snapshots cannot run with the usual workflow.

### Describe alternatives you've considered

Running upstreams of snapshots with --empty then running the snapshots. This makes configuring unit tests in CI much more complex as you need the additional steps:
 - Identify snapshots upstream of modified models
 - Run upstreams of snapshots as empty
 - Run snapshots

### Who will this benefit?

Users of unit tests and snapshots

**Comment by dbeatty10** [comment]
Thanks for opening this @d-cole !

We've got something similar open for seeds as well: https://github.com/dbt-labs/dbt-core/issues/8981

We've added your issue for snapshots to https://github.com/dbt-labs/dbt-core/issues/10151.

**Comment by d-cole** [comment]
Great, thank you @dbeatty10!

**Comment by mazzma12** [comment]
Hey - I was initially looking for a bug related to the behavior of `dbt snapshot --empty`. The behavior of this feature is quite misleading. IIUC, it does not write a new output line; however, it does update the current records with the new dbt_valid_to value.
In my case, I used it to add a new column to a snapshot schema without having to run the schema. Since the added column was in the "check" config of the snapshot, the job expired all the dbt records, without outputting new lines, leaving the snapshot output in a broken state.
 
The expected behavior on my side was that it would leave the table untouched and migrate the schema.

Is this a side effect or the expected behavior? Could this benefit from a warning somewhere?
