### ISSUE TITLE
[Feature] Python Materialization for dbt-postgres and dbt-core

### ISSUE THREAD

**Issue by PratikshaPanpaliya** [dbt-labs/dbt-core#10496]
### Is this a new bug in dbt-core?

- [ ] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Running a simple Python module (Postgres) gives
Materialization "materialization_table_default" only supports languages ['sql']; got "python"
While creating python model which is connecting to Greenplum (Postgres Adapter)

and I have the following versions
`Core:

installed: 1.8.4
latest: 1.8.4 - Up to date!
Plugins:

postgres: 1.8.2
dbt-python
sqlalchemy 

### Expected Behavior

 expect not to see this error as python should be supported!

### Steps To Reproduce

I have added information in the body of the issue above

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Additional Context

NA

**Comment by dbeatty10** [comment]
Thanks for reaching out @PratikshaPanpaliya !

dbt Python models are only [supported on Snowflake, Databricks, and BigQuery/GCP](https://docs.getdbt.com/docs/build/python-models#specific-data-platforms). The reason for those platforms specifically is that they all have a mechanism for the Python code to use the compute resources of the platform itself.

This isn't the case for Redshift and Python, so that is why neither dbt-redshift nor dbt-postgres support dbt Python models. So I'm closing this issue as "not planned".

**Comment by derycck** [comment]
You can use an old version of DBT core with the 'dbt-fal' adapter to support python-models in the postgres database.

You should be aware that the dbt-fal adapter was discontinued in September/2023.
So although it allows you to use python-models in postgres, you will never have access to the new DBT features.

In a legacy project, I use the requirements below:
- dbt-postgres==1.5.5
- dbt-fal[postgres]

With this, I can use python-models in a postgres database.
But be aware that **this is not being maintained**.
---
If you know of another adapter that supports python-model in a postgres database, please let us know.
