### ISSUE TITLE
[Feature] Unwrap the dbt functions in tests names

### ISSUE THREAD

**Issue by Syed-Ahamed-S** [dbt-labs/dbt-core#10533]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Actully I have created a generic test with a argument which is a ref(). But when i execute the test Im getting the test name like this (not_zero_my_first_dbt_model_ref_my_second_dbt_model_). If dbt could unwrap the dbt's native functions during the runtime to provide clear namings that would be appreciated. And also kindly check the naming convention for all resource types (like models, tests, macros, ....) and try to strip the ( '_' ) if it doesn't have any word after that.
![Screenshot 2024-08-07 032719](https://github.com/user-attachments/assets/f8b22e0c-bb0e-4e25-a974-86c3f266602b)
![Screenshot 2024-08-07 032833](https://github.com/user-attachments/assets/b0f32c82-4e6a-4c99-ab78-5b6a7ef095b4)

Kindly refer the above pictures.

### Describe alternatives you've considered

Try to provide a macro for all resource types naming conventions. Otherwise unwrap in the parser class itself.

try like this
![Screenshot 2024-08-07 033413](https://github.com/user-attachments/assets/ff37d1c2-549b-443a-b8f9-284118a9fefc)

or

add some code here to unwrap the dbt functions
![Screenshot 2024-08-07 033313](https://github.com/user-attachments/assets/e9d0b1c9-e83c-493b-87ae-b0bb2ec35a86)

Thank you !!!

**Comment by dbeatty10** [comment]
Thanks for reaching out @Syed-Ahamed-S !

Can you give a code example of how you'd use the macro that you're looking for? That would help us better understand what you're proposing.

In relation to stripping trailing `_`, we'd be unlikely to adopt that since users can already specify a [custom data test name](https://docs.getdbt.com/reference/resource-properties/data-tests#custom-data-test-name), and that's our way of letting users get full control over how the test will appear in log messages and metadata artifacts. It also allows select the test by that name.
