### ISSUE TITLE
[Feature] Support Fallback to Full Parse When Using --partial-parse-file-path

### ISSUE THREAD

**Issue by d-cole** [dbt-labs/dbt-core#10559]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When using the default target path or specifying `--target-path` without a `partial_parse.msgpack` file present, dbt falls back to a full parse, "Unable to do partial parsing because saved manifest not found. Starting full parse". This is very useful for cases where the existence of partial_parse.msgpack can't be guaranteed. However, when `--partial-parse-file-path` is used we lose this behaviour due to the error "Error: Invalid value for '--partial-parse-file-path': ... does not exist."

### Describe alternatives you've considered

Getting around this today requires the use of --target-path or copying artifacts to the default target/ prior to running dbt. Both of these are viable options but have two minor downsides:
        1. --target-path requires you modify the output path of artifacts to the directory where the partial p
arse artifacts may be stored.
        2. Optionally copying artifacts to the desired target path requires an extra step prior to a dbt run.

### Who will this benefit?

Users of --partial-parse-file-path who can't gaurantee artifact existence (e.g. CICD setup).

### Are you interested in contributing this feature?

Yes

**Comment by dbeatty10** [comment]
Thank you for proposing this idea @d-cole !

I can definitely see how it would be convenient to provide an empty (or non-existent) folder when using `--partial-parse-file-path`. It could be similarly handy to do something similar with the `--state` or `--defer-state` flags.

But since `--partial-parse-file-path` is an [intentionally](https://github.com/dbt-labs/dbt-core/issues/7911#issuecomment-1602428387) undocumented private/hidden flag not meant for dbt users, I'm going to close this as "not planned" (along with https://github.com/dbt-labs/dbt-core/issues/10561).

But even if `--partial-parse-file-path` was a "public" flag meant to be used by end users, the "does not exist" error is what we've chosen for other flags like `--state`, `--defer-state`, etc. whenever the expected file doesn't exist. So this would have been not planned either way.
