### ISSUE TITLE
[Bug] partial_parse.msgpack Only Written to --target-path When Project Is Modified

### ISSUE THREAD

**Issue by d-cole** [dbt-labs/dbt-core#10561]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When there are no changes to a dbt project and the flags --partial-parse-file-path and --target-path are used all artifacts except for partial_parse.msgpack are written to --target-path. This can lead to unexpected results when configuring CI to update artifacts for partial parsing.

**This is easily resolvable by checking for the existence of <new_target_path>/partial_parse.msgpack so I'm not sure if this qualifies as a bug or a code docs issue.**

### Expected Behavior

partial_parse.msgpack is written to --target-path even when the dbt project has no modifications. 

### Steps to reproduce
1. Follow setup steps here: https://github.com/dbt-labs/jaffle_shop_duckdb

2. Run `dbt parse` writing artifacts to default target/
```
dbt parse
15:14:17  Running with dbt=1.8.0
15:14:17  Registered adapter: duckdb=1.8.0
15:14:17  Unable to do partial parsing because saved manifest not found. Starting full parse.
...

ls target/
manifest.json           partial_parse.msgpack   perf_info.json          semantic_manifest.json
```

3. Run `dbt parse --partial-parse-file-path target/partial_parse.msgpack --target-path ./new_target_path`
```
dbt parse --partial-parse-file-path target/partial_parse.msgpack --target-path ./new_target_path
15:26:31  Running with dbt=1.8.0
15:26:31  Registered adapter: duckdb=1.8.0
...

ls ./new_target_path
manifest.json           perf_info.json          semantic_manifest.json
```

### Environment

```markdown
- OS: macOS-14.5-arm64-arm-64bit
- Python: 3.9.10
- dbt: 1.8.0
```

### Which database adapter are you using with dbt?

dbt-bigquery=1.8.0
duckdb=1.8.0

**Comment by dbeatty10** [comment]
Thanks for reaching out @d-cole !

I see what you are saying: when there _are_ modifications and when the `--partial-parse-file-path` flag is used, then `partial_parse.msgpack`  is written to the `--target-path` but it isn't written otherwise.

But since `--partial-parse-file-path` is an [intentionally](https://github.com/dbt-labs/dbt-core/issues/7911#issuecomment-1602428387) undocumented private/hidden flag not meant for dbt users, I'm going to close both this and https://github.com/dbt-labs/dbt-core/issues/10559 as "not planned".
