### ISSUE TITLE
[Bug] prevent dbt clone from attempting snapshots

### ISSUE THREAD

**Issue by AsimpleCommit** [dbt-labs/dbt-core#10572]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`dbt clone --state production_files/ --full-refresh 
`
```
 Database Error in snapshot src_grading_snapshot_service_level (snapshots/grading/src_grading_snapshot_service_level.sql)
  Cannot clone data from and to the same table: collectors-data:dw_src_snapshots.src_grading_snapshot_service_level
  compiled Code at target/run/data_platform/snapshots/grading/src_grading_snapshot_service_level.sql
```

### Expected Behavior

`dbt clone --state production_files/ --full-refresh ` actually runs something like 

`dbt clone --state production_files/ --full-refresh --exclude-resource-type snapshot`

### Steps To Reproduce

1. dbt core
2. 1.8.4
3. big query 

### Environment

```markdown
- OS:
- Python:
- dbt:1.8.4
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thanks for reaching out @AsimpleCommit !

I see what you are saying about getting an error when cloning snapshots that have hard-coded values for `target_database` and `target_schema` when using commands like these:

```shell
dbt build --target-path production_files --target prod
dbt clone --state production_files --full-refresh --target dev
```

For example, this snapshot will give the same error that you reported:

`snapshots/my_snapshot.sql`

```sql
{% snapshot my_snapshot %}

{{
    config(
      target_database=target.database,
      target_schema="dbt_dbeatty_prod",
      unique_key='id',
      strategy='check',
      check_cols='all',
    )
}}

select 1 as id

{% endsnapshot %}
```

But if the `target_database` and `target_schema` config for the snapshot are **not** hardcoded and vary depending on the `--target` value, then I **didn't** get the error because it was able to accomplish the clone.

Since we do want to be able to support cloning snapshots, I'm going to close this as "not planned".

To accomplish your goal, I'd suggest using a workaround similar to what you mentioned:

```shell
dbt clone --state production_files/ --full-refresh --exclude-resource-type snapshot
```

or

```shell
dbt clone --state production_files/ --full-refresh --exclude "resource_type:snapshot"
```
