### ISSUE TITLE
[Bug] unit test use source name for cte name and source identifier for table name

### ISSUE THREAD

**Issue by zhoujia74** [dbt-labs/dbt-core#10667]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I try to unit test a model that has a source table configured with both identifier and name. When we run the unit test, the test fails with error 

>  TABLE_NOT_FOUND: line xxx:xx: Table 'xxx.__dbt__cte__test' does not exist.

source config:
```yaml
  tables:
  - identifier: test
    name: test_table
```

model.sql:
`select * from {{ source("test_table") }}`

After checking the log, the generated sql uses source name for the generated cte name and source identifier to replace the source table name.

`__dbt__cte__test_table as (
xxxx
)
select * from __dbt_cte__test`

If we rename the source identifier to match the name, then the error will be gone.

### Expected Behavior

unit test should use same way to generate both the cte name and source table name

### Steps To Reproduce

Follow the steps in the current behavior.

### Environment

```markdown
- OS: mac
- Python: 3.10.2
- dbt: both 1.8.4 and 1.8.6
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

dbt-athena adapter

**Comment by dbeatty10** [comment]
Thanks for raising this issue @zhoujia74 !

What version of the `dbt-adapters` package do you have installed?

If you are using `pip` to install dbt, you can do a command like the following to get that version:
```
pip freeze | grep dbt-adapters
```

If I try a scenario like you described with dbt-core==1.8.6 dbt-adapters==1.4.0, then I get an error message similar to you.

But if I try it again with dbt-core==1.8.6 dbt-adapters==1.4.1, then it works.

**Comment by dbeatty10** [comment]
> Maybe something was fixed in both dbt-core and dbt-adapters.

It was!

There are two PRs in dbt-core and dbt-adapters that need to work in concert with each other:
- https://github.com/dbt-labs/dbt-core/pull/10290 (dbt-core>=1.8.6)
- https://github.com/dbt-labs/dbt-adapters/pull/236 (dbt-adapters>=1.4.1)

So either of these combinations will have the desired behavior ✅ , but anything else will not ❌ :
- dbt-core>=1.8.6 and dbt-adapters>=1.4.1, or
- dbt-core<1.8.6 and dbt-adapters<1.4.1

Since this is working for you now with the latest versions, I'm going to close this as already covered. But please reach out if you run into anything else.
