### ISSUE TITLE
Config precedence not implemented correctly

### ISSUE THREAD

**Issue by prdpsvs** [dbt-labs/dbt-core#10711]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Hi,

I have a model and in the model's .sql-file I have set {{ config(materialized='incremental') }}.
In the dbt_project.yml I set a materialization under the models key for the whole project like this:

```
models:
  my_fabric_project:
      +materialized: view
```
What I observe:
The value of model.config.materialized inside the is_incremental-macro is the one set inside the dbt_project.yml instead of the config block. The behaviour is same for views and tables as values for +materialized:.
is_incremental then returns false, therefore dbt is always running in full-refresh-mode.

Removal of setting the materialization in the dbt_project.yml fixed it and the model is correctly run in incremental mode because the value of model.config.materialized is incremental.

### Expected Behavior

What I expect:
The materialization from the config-block supersedes the one from the dbt_project.yml.

### Steps To Reproduce

in the model's .sql-file I have set {{ config(materialized='incremental') }}.
In the dbt_project.yml I set a materialization under the models key for the whole project like this:

```
models:
  my_fabric_project:
      +materialized: view
```
Removal of setting the materialization in the dbt_project.yml fixed it and the model is correctly run in incremental mode because the value of model.config.materialized is incremental.

### Environment

```markdown
- OS: Linux/Windows
- Python: 3.11
- dbt-adapters: dbt-fabric adapter
```

**Comment by dbeatty10** [comment]
Thanks for raising this issue @tkiehn (and thanks for sending it over here for further troubleshooting @prdpsvs)!

I was **not** able to reproduce the same issue that was reported.

I used dbt-duckdb rather than dbt-fabric, but I would expect them both to behave the same way for the issue that you reported. See below for the project files I used.

@tkiehn Could you double check that when you run the same command twice in a row that it **doesn't** run in incremental mode the 2nd time around?

```shell
dbt run -s your_incremental_model
dbt run -s your_incremental_model
```

If indeed it **doesn't**, could you do the following?
1. Try running the simplified project code below and see if it behaves the way you expect or not
1. Try re-running your code using the overridden definition of `macros/is_incremental.sql` that is provided in the project files below? It contains some debugging code that will allow you to better inspect what is going on.

<details>

<summary>

### Example files
</summary>

`dbt_project.yml`

```yaml
name: "my_project"
version: "1.0.0"
config-version: 2
profile: "duckdb"

models:
  my_project:
    +materialized: view
```

`models/my_incremental.sql`

```sql
{{ config(materialized="incremental") }}

{% do log("is_incremental(): " ~ is_incremental(), True) %}
{% do log("my_incremental.sql model.config.materialized: " ~ model.config.materialized, True) %}

select 1 as id
```

I overwrote [this](https://github.com/dbt-labs/dbt-adapters/blob/858a8686d839ab91a6ca4a334c35d90f4767278e/dbt/include/global_project/macros/materializations/models/incremental/is_incremental.sql) macro just so that we could inspect what is going on -- everything looks fine to me!

`macros/is_incremental.sql`

```sql
{% macro is_incremental() %}
    {#-- do not run introspective queries in parsing #}
    {% if not execute %}
        {{ return(False) }}
    {% else %}
        {% do log("is_incremental() model.config.materialized: " ~ model.config.materialized, True) %}
        {% set relation = adapter.get_relation(this.database, this.schema, this.table) %}
        {{ return(relation is not none
                  and relation.type == 'table'
                  and model.config.materialized == 'incremental'
                  and not should_full_refresh()) }}
    {% endif %}
{% endmacro %}
```

Output:

You should see that it does a full refresh the 1st time, and then uses an incremental update the 2nd time.

```
(dbt_1.8) $ dbt run -s my_incremental                   
22:32:37  Running with dbt=1.8.6
22:32:38  Registered adapter: duckdb=1.8.3
22:32:38  Found 5 models, 411 macros
22:32:38  
22:32:38  Concurrency: 1 threads (target='dev')
22:32:38  
22:32:38  1 of 1 START sql incremental model feature_456.my_incremental .................. [RUN]
22:32:38  is_incremental() model.config.materialized: incremental
22:32:38  is_incremental(): False
22:32:38  my_incremental.sql model.config.materialized: incremental
22:32:38  1 of 1 OK created sql incremental model feature_456.my_incremental ............. [OK in 0.11s]
22:32:38  
22:32:38  Finished running 1 incremental model in 0 hours 0 minutes and 0.31 seconds (0.31s).
22:32:38  
22:32:38  Completed successfully
22:32:38  
22:32:38  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1

(dbt_1.8) $ dbt run -s my_incremental
22:32:41  Running with dbt=1.8.6
22:32:42  Registered adapter: duckdb=1.8.3
22:32:42  Found 5 models, 411 macros
22:32:42  
22:32:42  Concurrency: 1 threads (target='dev')
22:32:42  
22:32:42  1 of 1 START sql incremental model feature_456.my_incremental .................. [RUN]
22:32:42  is_incremental() model.config.materialized: incremental
22:32:42  is_incremental(): True
22:32:42  my_incremental.sql model.config.materialized: incremental
22:32:42  1 of 1 OK created sql incremental model feature_456.my_incremental ............. [OK in 0.20s]
22:32:42  
22:32:42  Finished running 1 incremental model in 0 hours 0 minutes and 0.37 seconds (0.37s).
22:32:42  
22:32:42  Completed successfully
22:32:42  
22:32:42  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

</details>

**Comment by tkiehn** [comment]
Hi @dbeatty10 and thanks for the detailed response!

After getting back to the issue I found that the problem comes up when using models from a package.

So my root-project has a package installed in which are several models which are configured using a config block.

For example my_incremental_model(inside the package):
``` 
{{ config(materialized = 'incremental') }}
{{ log(is_incremental(), info=True) }}
select 1 as id
```

dbt_project.yml of my root-project:
```
name: project
config-version: 2

profile: 'profile'
models:
  my_installed_package:
      +materialized: view
  my_root_project:
      +materialized: table
```
The dbt_project.yml of the package does not contain any model configs except tagging.

My overridden is_incremental-macro:
<details>

```
{% macro is_incremental() %}
    {#-- do not run introspective queries in parsing #}
    {% if not execute %}
        {{ return(False) }}
    {% else %}
        {% set relation = adapter.get_relation(this.database, this.schema, this.table) %}
        {{ log(model.name ~ ' model.config.materialized: ' ~ model.config.materialized, info=True) }}
        {{ return(relation is not none
                  and relation.type == 'table'
                  and model.config.materialized == 'incremental'
                  and not should_full_refresh()) }}
    {% endif %}
{% endmacro %}
```

</details>

Terminal output showing it is configured as a view:
<details>

```
(.venv) PS C:\Projects\project> dbt run -s my_incremental_model
08:38:30  Running with dbt=1.8.3
08:38:30  Registered adapter: fabric=1.8.7
08:38:30  Unable to do partial parsing because a project config has changed
08:38:34  False
08:38:36  Found 61 models, 205 data tests, 11 seeds, 9 sources, 1107 macros
08:38:36
08:38:38  Concurrency: 8 threads (target='dev')
08:38:38
08:38:38  1 of 1 START sql view model dbt-tkiehn-1.my_incremental_model .................. [RUN]
08:38:38  my_incremental_model model.config.materialized: view
08:38:38  False
08:38:40  1 of 1 OK created sql view model dbt-tkiehn-1.my_incremental_model ............. [OK in 1.54s]
08:38:40
08:38:40  Finished running 1 view model in 0 hours 0 minutes and 3.99 seconds (3.99s).
08:38:40  
08:38:40  Completed successfully
08:38:40
08:38:40  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```
</details>

When i change the model-config inside the `dbt_project.yml` from view to table the model.config.materialized value changes accordingly.

I would have expected the model's config block to override the config from the dbt_project.yml.

Is there a misconfiguration on my side?

**Comment by tkiehn** [comment]
After checking the docs and finding the sentence `Model configurations in your root dbt project have higher precedence than configurations in installed packages. This enables you to override the configurations of installed packages, providing more control over your dbt runs.` I think this can be closed.

**Comment by dbeatty10** [comment]
Yep, that is precisely the relevant documentation that explains it! Closing accordingly.

Side note: this specific documentation was also relevant to https://github.com/dbt-labs/dbt-core/issues/10707.
