### ISSUE TITLE
DBT Predefined variables like `invocation_id` and `run_started_at` cached between DBT runs when used in pre or post hooks

### ISSUE THREAD

**Issue by jdglaser** [dbt-labs/dbt-core#10837]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Hello,

We noticed an issue where variables that should be different between each DBT invocation (example `invocation_id` or `run_started_at`) are not changing between dbt runs when running locally from the command line. This only seems to be happening specifically in pre or post hooks. For example If I add the following in a model

```
{{ config(post_hook="INSERT INTO MY_TABLE VALUES ('" ~ invocation_id ~ "','" ~ run_started_at ~ "')") }}
{{ log("Logged run_started_at: " ~ run_started_at ) }}
{{ log("Logged invocation_id: " ~ invocation_id ) }}
```

And then run that model - The first time, I see the following log messages
```
16:07:16  Logged run_started_at: 2024-10-09 16:07:12.418977+00:00
16:07:16  Logged invocation_id: 43371064-bdfd-45b8-9618-6e13987512f9
```

And the record is properly written to the table
|invocation_id|run_started_at|
|---|---|
|43371064-bdfd-45b8-9618-6e13987512f9|2024-10-09 11:07:12.418 -0500|

However, if I run the same command again, I see the proper log messages have updated
```
16:07:34  Logged run_started_at: 2024-10-09 16:07:30.455385+00:00
16:07:34  Logged invocation_id: 9f22ac65-af39-47fa-b023-fbd7578eba6a
```

But, I see in the table in the database the records were the same as the last run
|invocation_id|run_started_at|
|---|---|
|43371064-bdfd-45b8-9618-6e13987512f9|2024-10-09 11:07:12.418 -0500|
|43371064-bdfd-45b8-9618-6e13987512f9|2024-10-09 11:07:12.418 -0500|

This tells me that the values of the variable used in the post hook are somehow being cached differently than the ones actually used in the context of the model.

One thing I noticed that does fix this is by passing any argument to the command that is different than the previous run. Even just passing some garbage value in the `--vars` arg that is different from run to run causes the values in the post hook to update.

The example above is more to prove out this issue, but the capability we want here is to actually use the run_started_at variable to be able to query changed records in incremental and snapshot models in a post hook. So we'd like to try to see if there is a way to fix this.

### Expected Behavior

I would expect that between DBT invocations, the invocation_id and run_started_at (and any other "run specific" variables) are different and those values are properly represented in the post and pre hooks.

### Steps To Reproduce

See "Current Behavior" for examples of how to reproduce.

### Relevant log output

```shell
See "Current Behavior" for examples of log output.
```

### Environment

```markdown
- OS: Mac
- Python: Python 3.11.8
- dbt: 1.8.5
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reaching out @jdglaser!

The "late rendering" behavior of pre- and post-hooks is something we know is confusing and [want to document better](https://github.com/dbt-labs/docs.getdbt.com/issues/2818).

In the meantime, I think you want something like this:

```
{{ config(post_hook="insert into {{ ref('my_seed') }} values ('{{ invocation_id }}', '{{ run_started_at }}')") }}
```

Instead of:

```
{{ config(post_hook="insert into {{ ref('my_seed') }} values ('" ~ invocation_id ~ "','" ~ run_started_at ~ "')") }}
```

### Explanation

dbt will use ["late rendering"](https://github.com/dbt-labs/docs.getdbt.com/issues/2818) for variables like `invocation_id` and `run_started_at` during [parsing/compilation/execution](https://github.com/dbt-labs/dbt-core/tree/main/docs/guides).

The net effect is that:

- When [partial parsing](https://docs.getdbt.com/reference/global-configs/parsing#partial-parsing) is disabled (e.g. `--no-partial-parse`), then the hooks and the log statements will match up no matter what because it won't use the cache at all
- When partial parsing is enabled with the code you are currently using, dbt will render those variables in hooks **earlier** than your log statements, so they will be mismatched if there is cached info.
- If the suggested code example is used, dbt will "late render" your hooks and ignore the cache when doing so (regardless if partial parsing is enabled or not)

### Example

Create these files:

`seeds/my_seed.csv`

```csv
source,invocation_id,run_started_at
NA,xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx,1900-01-01 00:00:00.000000+00:00
```

`models/my_model.sql`

```sql
{{ config(
    post_hook=[
        "insert into {{ ref('my_seed') }} values ('using partial parsing', '" ~ invocation_id ~ "','" ~ run_started_at ~ "')",
        "insert into {{ ref('my_seed') }} values ('using late rendering', '{{ invocation_id }}', '{{ run_started_at }}')",
    ]
) }}

{{ log("Logged run_started_at: " ~ run_started_at, True ) }}
{{ log("Logged invocation_id: " ~ invocation_id, True ) }}

select 1 as id
```

Run these commands:

```shell
dbt seed --full-refresh
dbt run --no-partial-parse
dbt run
dbt show --inline 'select * from {{ ref("my_seed") }}' --limit 20
```

Get this output:

```
| source               | invocation_id        | run_started_at       |
| -------------------- | -------------------- | -------------------- |
| NA                   | xxxxxxxx-xxxx-xxx... | 1900-01-01 00:00:... |
| using partial par... | a38b7090-af82-480... | 2024-10-12 16:43:... |
| using late rendering | a38b7090-af82-480... | 2024-10-12 16:43:... |
| using partial par... | a38b7090-af82-480... | 2024-10-12 16:43:... |
| using late rendering | a4083647-6a1e-4cf... | 2024-10-12 16:43:... |
```

### Summary

I think what you are observing is the behavior we expect, so I'm going to close this as "not planned". But I'll still be curious to hear if the suggested code change works for you.

We could re-evaluate this as a feature request depending on the feedback from you and others (e.g., prevent partial parsing altogether for certain variables like `invocation_id` and `run_started_at`).

**Comment by jdglaser** [comment]
Thank you for the response here. This all makes sense. I will give the code changes a try and respond here with what we find.
