### ISSUE TITLE
Feature: DBT should allow tests to be environment-specific

### ISSUE THREAD

**Issue by mikekaminsky** [dbt-labs/dbt-core#1083]
### Feature description

Users should be able to indicate which tests are "production only" (or, more generally, which tests should be run in which environments). I'd like to be able to do something like this in my `model_name.yml` file:

```
        {% if target.name == 'prod' %}    
        - name: my_col_name
          tests:
              - not_null
        {% endif %}
```

### Who will this benefit?

Some people have dedicated "development" environments that do not contain all of their production data. When developing in an environment like this, some tests might consistently fail (e.g., foreign-key constraints) because the development environment only has random subsets of tables.

In this situation, it's important to be able indicate which tests will work in the development environment and which tests are only for production.

**Comment by raybuhr** [comment]
➕ 💯 to this idea. `dev` and `prod`environments probably do want to share many tests, but also almost certainly have different requirements. If the `dev` environment of the warehouse is exactly the same as the `prod`, just ahead in terms of commits, that's a lot of duplicative computation. in situations where the `dev` warehouse is only a subset, some tests should be able to have flags to:
- turn off tests
- change priority of test failures from errors to warnings

Since `dbt` currently completes the build regardless of test results as long as the SQL is valid, this isn't a major issue. If `dbt` ever prevents builds from completing due to test failures, having target toggles or test priority switches like #1005 will make a big impact on usability.

**Comment by antonysouthworth-halter** [comment]
was this ever implemented?

**Comment by antonysouthworth-halter** [comment]
oh I just found this is basically possible using what's described in https://github.com/dbt-labs/dbt-core/issues/5307
