### ISSUE TITLE
[Feature] Do several actions on a table

### ISSUE THREAD

**Issue by Simon-Free** [dbt-labs/dbt-core#11010]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I need (i think) to have 2 models inserting in the same table, is there any way currently to implement this ? Here is a simple example detailing why.

I have ``my_table`` that has 3 columns, ``A``, ``B`` and ``C``. ``A`` is my primary_key.

Given ``my_source``, that contains 2 columns ``A`` and ``B``, I want to upsert in ``my_table`` new lines, leaving for now ``C`` null. 

From ``another_source``, that contains ``B``, ``C``, ``D``, and ``my_table`` I want to deduce ``my_final_table``, which is e.g. 

```select B, sum(C), sum(D) from another_source group by B```

Then, this is a long operation, i want to avoid doing it twice.

Finally, I want to update ``my_table`` values using something like 

```select B, 1 if sum(C) > 100 else 0 from my_final_table join my_table using B```

The simplest way I see to do this would be to write 2 scripts that are doing operations on the same table, but is it feasible using dbt ? 

Thank you for the answer :)

**Comment by dbeatty10** [comment]
Hi @Simon-Free Could you please ask this question in dbt Discourse [here](https://discourse.getdbt.com/) or the `#advice-dbt-help` Slack channel [here](https://getdbt.slack.com/archives/CBSQTAPLG)?

We focus on bug reports and features requests in GitHub and use Discourse and Slack for product questions. So I'm going to close this as "not planned" since it is a product question.

I can provide some quick links before closing this issue though.

dbt has several features that may be relevant to your use-case:
- [standard incremental materialization](https://docs.getdbt.com/docs/build/incremental-models-overview)
- [custom incremental materialization strategy](https://docs.getdbt.com/docs/build/incremental-strategy#custom-strategies)
- [custom materialization](https://docs.getdbt.com/guides/create-new-materializations?step=1)

Please ask this question in Discourse and Slack to hear what others suggest for your situation.
