### ISSUE TITLE
[Feature]Enable DBT to work with Apache Cloudberry, a open source fork of Greenplum Database

### ISSUE THREAD

**Issue by dedekind1986** [dbt-labs/dbt-core#11105]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I was previously a user of the open-source Greenplum Database. After Broadcom acquired VMware, they shut down the Greenplum Database open-source community. Due to the specific nature of our industry, open-source software is our preferred choice. Therefore, Greenplum Database is no longer a viable option for us.

Recently, a new open-source massively parallel processing (MPP) database, Apache Cloudberry, has entered the Apache Incubator. Based on its GitHub page, it's an open-source fork of Greenplum Database but with an upgraded PostgreSQL kernel version. As a result, I'm evaluating whether we can migrate from Greenplum Database to Apache Cloudberry.

Additionally, our company is preparing to use dbt to restructure our entire data pipeline process. So, I'm particularly interested in knowing if there is dbt support for Apache Cloudberry.

### Describe alternatives you've considered

There is a github project:

https://github.com/markporoshin/dbt-greenplum

which enables DBT to work with Greenplum Database.

I am still determining if this project is a direct fit for Apache Cloudberry.

### Who will this benefit?

Anyone who is interested in using both DBT and Apache Cloudberry

### Are you interested in contributing this feature?

Yes

### Anything else?

I think we need something like this: https://docs.getdbt.com/reference/resource-configs/greenplum-configs

but for Apache Cloudberry.

**Comment by dbeatty10** [comment]
Thanks for reaching out @dedekind1986 !

> Additionally, our company is preparing to use dbt to restructure our entire data pipeline process. So, I'm particularly interested in knowing if there is dbt support for Apache Cloudberry.

There is not currently a [trusted](https://docs.getdbt.com/docs/trusted-adapters) or [community](https://docs.getdbt.com/docs/community-adapters) dbt adapter for Apache Cloudberry.

But if you or someone else was interested in creating an adapter for Apache Cloudberry, you could follow our guidance for [building, testing, document, and promoting an adapter](https://docs.getdbt.com/guides/adapter-creation?step=1). You could either fork the code for the preexisting [`dbt-greenplum`](https://github.com/markporoshin/dbt-greenplum) adapter or start from scratch.

Here's the [dbt Slack](https://www.getdbt.com/community/join-the-community) channel where other 3rd party adapter maintainers hang out:
[`#adapter-ecosystem`](https://getdbt.slack.com/archives/C030A0UF5LM)

dbt has an interface to enable folks to bring their own dbt adapter for their database. dbt Labs maintains a small set of these adapters ourselves, but most adapters are maintained by third parties.

Since we wouldn't be interested in creating and maintaining this adapter at dbt Labs, I'm going to close this issue as not planned.
