### ISSUE TITLE
Add a Function to Allow Easy Hyperlinking Between Model Documentation

### ISSUE THREAD

**Issue by jrandrews** [dbt-labs/dbt-core#1334]
### Feature description

Right now, if you are writing a doc block for a model and want to embed a hyperlink to a different doc block, it is necessary to do syntax like this: [link text][link title](#!/model/model.package.model_name). This is a bit clunky and difficult to follow. It would be nice to have a function like "link(model_name)" to make it easier to embed hyperlinks to other models in documentation.

### Who will this benefit?

All users who want to be able to construct links between various documentation pages for models when using the "dbt docs" functionality.

**Comment by drewbanin** [comment]
Really great idea! I think this should be relatively straightforward for someone to add to dbt -- going to add a `Good first issue` label here. Happy to help out anyone who wants to take a stab at it!

**Comment by jrandrews** [comment]
In addition, it would be nice to have the ability to have SQL queries executed and have their output actually appear in dbt docs. One use case could be including a line of documentation that says "The earliest record in X table has a timestamp of XXXXXXX" and have the value of the timestamp populated at runtime. Or have an aggregate query execute to count the number of transaction values by a certain lookup value, e.g. cars by color, and then have a table get populated in the documentation output to actually display what this looks like in the database.

**Comment by drewbanin** [comment]
Tentatively pulling this issue in the wilt-chamberlain release, pending questions about what sort of dbt context we can provide in the `docs` blocks. See also: https://github.com/fishtown-analytics/dbt/issues/1255

**Comment by drewbanin** [comment]
Kicking this one out of Wilt Chamberlain, but excited to tackle it for a subsequent release! Just prioritized for Louisa May Alcott, which should be the first feature release after 0.14.0 (so, either 0.14.x, or 0.15.0, depending)

**Comment by cmcarthur** [comment]
related to #1503

**Comment by eugene-nikolaev** [comment]
Hi! Keen to get model references in docs!
What is the current status of this request. Will it be implemented?

**Comment by jtcohen6** [comment]
Hey @eugene-nikolaev, this isn't prioritized right now, but it's good to hear this is something you're interested in!

All resources in the dbt-docs site today have URLs like:
```
[base url]/#!/[resource_type]/[resource_type].[package_name].[resource_name]
```

So if you want to link to a specific model in a Markdown description, it can be as simple as:
```yml
- name: model
   description: >
     Check out this [other_model](/#!/model/model.my_project.other_model)
     Or this [source](/#!/source/model.my_project.my_source.src_table)
     Or this [macro from a package](/#!/macro/macro.dbt_utils.date_spine)
```

It is possible to render Jinja templates in the `description` fields, but dbt doesn't have access to its full custom Jinja context today: it's just the base context plus `doc()`. The proposal in this issue is to add another special function that provides shorthand for the link construction above—perhaps a `link()` function, in lieu of trying to incorporate the `ref()` or `source()` macros themselves. I think that's feasible as a community contribution, with two small challenges:
- It will require following some dbt-Jinja code paths around (e.g.) `DocumentationExtension` and `get_docs_macro_name`
- The `link` function would need to introspect the parsed manifest to figure resource type and package name

**Comment by eugene-nikolaev** [comment]
@jtcohen6 thanks for reply!

**Comment by superfinn23** [comment]
Would love to have this function in the future! Glad to have the href though!

**Comment by ConstantinoSchillebeeckx** [comment]
What's the status on this? As someone who makes heavy use of docs, I'd love to see this feature. How can I help?

**Comment by keunsoopark** [comment]
Waiting for this being released!!

**Comment by olsavmic** [comment]
I'm sad to see this closed, any possibility to revive this idea? Even the official docs says current solution with markdown href is quite hacky

https://docs.getdbt.com/reference/resource-properties/description#link-to-another-model-in-a-description
