### ISSUE TITLE
Snapshots shouldn't fail when checking boolean columns on redshift

### ISSUE THREAD

**Issue by tconbeer** [dbt-labs/dbt-core#1669]
### Describe the bug
When creating a snapshot and checking a boolean field, `dbt snapshot` fails and returns the error:
`Invalid operation: cannot cast type boolean to character varying`

The issue seems to be the sql that generates the `dbt_scd_id` field, since it casts the check columns before concatenating them. For whatever reason, Redshift doesn't support casting boolean fields to anything else (see [here](https://docs.aws.amazon.com/redshift/latest/dg/r_Type_conversion.html))

You can check for yourself that `select true::varchar` fails

For now, my workaround is to create a new column for each boolean I'd like to check, like:

```
{% snapshot my_snapshot %}
  {{ config(
        ...,
        check_cols = [..., bool_field_1_varchar, bool_field_2_varchar]) 
  }}
  select
    *,
    case 
      when bool_field_1 is true then 1::varchar
      when bool_field_1 is false then 0::varchar
      else null::varchar
      end as bool_field_1_varchar,
    case 
      when bool_field_2 is true then 1::varchar
      when bool_field_2 is false then 0::varchar
      else null::varchar
      end as bool_field_2_varchar

  from
    source
{% endsnapshot %}
```

### Steps To Reproduce
On Redshift, create a snapshot using the check strategy; include a boolean field in the `check_cols` list

### Expected behavior
I would expect Snapshots to work normally with boolean check columns

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.14.0
```

**The operating system you're using:**
```
Windows 10
```

**The output of `python --version`:**
```
Python 3.7.0
```

**Comment by drewbanin** [comment]
Hey @tconbeer - thanks for the report! This is pretty unfortunate, across all of the data types and databases that dbt works with, I believe `boolean` columns on Redshift are the only columns that can't be converted to strings :/

Your analysis of what's happening here is spot-on!

There could be a way for dbt to understand when some of the provided columns are boolean, then replace `cast(column as text)` with `case when column then 'true' else 'false' end`, or similar in the dbt_scd_id expression. This would require an extra query to the information schema, and `dbt snapshot` already runs more of these than I would really like.

I think you have a couple of options here:
1. generate strings from your boolean columns in your snapshot sql (as shown in your issue description)
2. generate a surrogate key in your snapshot query, then specify only that column as your `check_cols` column.
3. pass an expression as the `check_cols` config, eg:
```
{{ config(
        ...,
        check_cols = [
               "field_1",
               "field_2",
               "case when bool_field then 1 else 0 end",
               ...
  }}
```

You could actually use a macro which implements the case-when logic if you felt so inclined:
```
{{ config(
        ...,
        check_cols = [
               "field_1",
               "field_2",
               bool_to_string('bool_field'),
               ...
  }}
```

Of these, I think the approach you took, converting the booleans to strings, is probably the one I'd recommend. I hesitate to recommend approach 3, though it is interesting, because that would really make it difficult for dbt to infer column types and do something intelligent if this is something we choose to prioritize in the future. If that's not something that concerns you, then feel free to give it a shot!

For now though, I think accounting for this in the snapshot query is your best bet. I'll update the docs on snapshots with this caveat accordingly!

**Comment by tconbeer** [comment]
Thanks Drew. I tried approach 3 previously, and it worked for the initial snapshot, but failed on subsequent runs... the issue is that the `where` statement assumes the check cols directly reference a field from the `snapshotted_data` and `source_data` cte. From the logs:
```
snapshotted_data.case when enabled is true then 1::varchar else 0::varchar end != source_data.case when enabled is true then 1::varchar else 0::varchar end
            or
            (snapshotted_data.case when enabled is true then 1::varchar else 0::varchar end is null) != (source_data.case when enabled is true then 1::varchar else 0::varchar end is null) or 
```
The surrogate key approach would certainly work; to be honest, I was a little surprised that snapshots wasn't doing that with the check_cols fields to detect changes

**Comment by drewbanin** [comment]
ah! Really good point - thanks for following up on that.

Yeah - we opted to do a column-by-column comparison, as that felt a little less inscrutable than comparing a hash. This is definitely one point in favor of doing a hash-based comparison.

**Comment by ilmari-aalto** [comment]
Hi,

It's an old issue but I can see this is still open, and thought I'd add my two cents. I just faced this same issue because I was piggybacking the helper macro `snapshot_hash_arguments` from the `snapshot` materialization. Here's the macro source:
https://github.com/fishtown-analytics/dbt/blob/dev/margaret-mead/core/dbt/include/global_project/macros/materializations/snapshot/strategies.sql#L43-L48

The workaround in my case is to pass a list of `Column` objects instead of a list of column names, and creating a custom Redshift macro that uses a different logic for `boolean` datatype, along these lines:

```sql
{% macro calculate_column_hash(cols) -%}
  md5({%- for col in cols -%}
    {%- if col.dtype == 'boolean' -%}
      decode({{ col.name }}, true, 't', false, 'f', '') :: varchar
    {%- else -%}
      coalesce({{ col.name }} :: varchar, '')
    {%- endif %}
      {% if not loop.last %} || '|' || {% endif %}
  {%- endfor -%})
{%- endmacro %}
```
