### ISSUE TITLE
Provide an interface to allow statements to fail

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/dbt-core#1968]
Use case: I have an operation that vacuums each table one by one. If one of those statements fails, I actually want to keep continuing rather than exit.

Thoughts:
- Can we add an argument to statements?
- Do we instead want to implement a `{% try %}`, `{% except %}`, `{% endtry %}` block?
- How do we get back the exception? Do we need it?

**Comment by drewbanin** [comment]
I want to do a better job of codifying my design philosophy going into the new year. My big opposition here is that I _really_ dislike the idea of adding a lot of complexity to dbt in order to work around a series of Redshift quirks (putting it nicely). The feature is requested at least in part because:
1. redshift tables need to be periodically vacuumed
2. those vacuum statements can sometimes fail for dumb reasons (only one vacuum is allowed at a time, right?)

So, this feature is intended to do error handling for an operation that I think you shouldn't need to do in the first place!!

Are there other use cases where a try/except flow is useful? I think a better understanding of when we'd want to use this pattern would help us better prioritize the change. I do believe that there are other good uses cases for this - just having a hard time of coming up with them at the moment.

I do think that if we prioritize this change, some new jinja tags are a really elegant way of supporting  exception handling. The big challenge is that the `except` block should probably be able to identify which exceptions it catches. The two big classes of exceptions that dbt raises at the moment are:
1. `CompilerError`
2. `DatabaseError`

There are other exceptions that dbt can raise here too, and putting them all in the context might be challenging. Maybe a simplified version of this implementation would just catch _any_ exception? That seems convenient for macro authors, but it's generally considered a bad practice in programming circles.

What do you think @clrcrl?

**Comment by clrcrl** [comment]
The only other use case I can imagine was when we used to run `alter warehouse transforming resume` statements, and they would fail because the warehouse had already been resumed. Snowflake has since added a parameter so that we can work around it (i.e. `alter warehouse transforming resume if suspended`) which has made it a non issue.

No other use cases spring to mind though, so I'm happy for this to be closed as a `wontdo`.

I would be happy to just catch any exception. Sure it's not best practice amongst programmers, but it's such an edge case that I'm happy to leave a rough edge here.

**Comment by drewbanin** [comment]
> Snowflake has since added a parameter so that we can work around it (i.e. alter warehouse transforming resume if suspended) which has made it a non issue

:+1:

I bet there are good use cases around more complex run-operations, like in https://github.com/fishtown-analytics/dbt-external-tables. I'm happy to leave this issue open until a time comes that we have some more concrete uses in mind and the bandwidth to pick it up. It's a good idea for sure!

**Comment by sethwoodworth** [comment]
Adding my $.02:  It would be helpful for my use case, where I am auto-generating my warehouse's sources, to be able to use the `doc()` function that when no matching `docs` macro block is found, doesn't halt the execution of dbt.
My work-around is to parse manifest.json and ensure the existence of any docs blocks for new schemas, tables, columns that I add to my yml.
Generally, I would be very excited if I could add my own jinja extensions that can implement functionality like this, but I've heard you're wary of allowing too much python extension of dbt.
