### ISSUE TITLE
Give DBT access to current git information, if it exists

### ISSUE THREAD

**Issue by nelsonauner** [dbt-labs/dbt-core#2159]
### Describe the feature
From my experience, almost all dbt users use git. 
Right now, it is not easy to tell what dbt code generated the current populated data. 
This feature proposes we allow dbt to access git-related information. For example, what commit was the current dbt run against? What branch? Who made the last change? 

This is a nice-to-have that assists analysts when debugging why data looks different than expected. I've found occasionally a well-intentioned analyst run against production instead of test, etc. 

### Describe alternatives you've considered

1. Everytime you run dbt, put the GIT_SHA as an environmental variable. Cons: People forget to do this, not backwards compatible

2. Run a shell script that puts git info into a csv, use dbt seed to upload. Cons: Need to run shell script every-time you change dbt. 

3. Try lean on pipenv to inject git data into dbt's sessions, via a .env file or some pipenv hook. Con: hacky, complicated

### Additional context
This is not database-specific, but the the solution must be "back-wards compatible" insomuchas as users who choose not to use git have no errors. The current idea I have for this is for the loaded variable to simply be an empty dict that becomes populated. Users wishing to check the git hash, last commit, etc, can simply first check if this dictionary is populated before accessing variables.

### Who will this benefit?
This will benefit DBT users who also use git, and who want to have visibility into the latest code that produced their data.

**Comment by drewbanin** [comment]
Thanks for making this issue @nelsonauner! I think this is a great idea! 

If you're interested in lending a hand with the implementation, you should check out:
- [the git client](https://github.com/fishtown-analytics/dbt/blob/dev/barbara-gittings/core/dbt/clients/git.py) - this is where we should invoke git to check the commit sha/branch name/etc
- [the base context](https://github.com/fishtown-analytics/dbt/blob/e8d321cbab3aa7ea93b6b831de4c0539f6ca02cb/core/dbt/context/base.py#L49) - this is where we'll probably want to add a dict like `git` to the context containing the sha/branch/etc

My general recommendations for implementation are:
- be aggressive in error handling around git operations. This code shouldn't brick a dbt run if you're outside of a git repo, or if your git repo has no commits in it (this is super gnarly, and worth checking for explicitly!)
- let's figure out a way to `cache` these git values so that we're not polling git every time we build up the context. Instead, it _could_ be a good idea to cache the git state in the [tracking module](https://github.com/fishtown-analytics/dbt/blob/e8d321cbab3aa7ea93b6b831de4c0539f6ca02cb/core/dbt/tracking.py#L95) as we do for other values like `invocation_id` and `run_started_at`. These will persist throughout the run, and you can see how we use these values in the base context as an example

Let me know if you have any questions or thoughts here!

**Comment by nbdaniels** [comment]
Hi there! I saw this thread and couldn't find much help anywhere else after searching for a bit. Is it possible to do something like this now with DBT's current version?

For some background, I'm looking to track changes made to data from PRs using Python. I'm looking to grab git information (like current branch and user who committed most recently to that branch) from a specific DBT run triggered from a PR. With this information I believe I can pull it into a Python script and run with FAL (https://github.com/fal-ai/fal) to understand what changes are planned to be made to production data and who is making the change.

Please let me know if this isn't the right place or if I'm missing something from other DBT resources!

**Comment by nandanathreya** [comment]
Hi There,

I'm looking for the exact feature described here.
We use GIT along with DBT and I'm looking for a feature to add git information to the data populated from the DBT.

The purpose is to identify which tag, commit, PR is behind the data populated in the table.

@nbdaniels Perhaps you figured out something? Please share if you did.
  @drewbanin  or @nelsonauner Did you guys figure out something maybe?

**Comment by coreywebber** [comment]
bump
