### ISSUE TITLE
Add an integration test for db_groups/autocreate on redshift

### ISSUE THREAD

**Issue by beckjake** [dbt-labs/dbt-core#2285]
### Describe the feature
I want to add some integration tests for #2262

It seemed unreasonable to make a third party contributor go through the hassle of writing tests against env variables that don't yet exist on circleci/azure/my local test.env file for an account that didn't at the time exist.

I believe the test should work like this, based on my (probably poor) understanding of redshift permissions/credentials:

- add a new profile to the test suite that sets `db_groups`/`autocreate=True`
  - the `db_groups` value should contain a group that the given user _isn't_ in.
- add a new test that:
    - creates a table accessible to the given group, but not the user, using the default profile(?)
    - switches to the new profile
    - selects from the above table as a source

cc @kyleabeauchamp - does this seem reasonable? Is there a use-case in particular that you have that I should try to cover?

### Describe alternatives you've considered
no tests?

### Additional context
Redshift only

### Who will this benefit?
Tests are for everyone.

**Comment by kyleabeauchamp** [comment]
I think this sounds reasonable to me.  I think the low-hanging fruit are just making sure the arguments get piped into boto correctly.  During my initial testing, it seems like boto is pretty strict on typing so that's a good crutch as well.

In terms of full integration testing, I'm afraid I'm not enough of a Redshift DBA to give advice on what coverage is desirable :(.
