### ISSUE TITLE
Describing an argumentless macro implies there are missing details

### ISSUE THREAD

**Issue by MartinGuindon** [dbt-labs/dbt-core#2371]
### Describe the bug
When describing an argumentless macro, the docs site will indicate `Details are not available for this macro` in the **Arguments** section. This implies that there are potentially arguments but that details haven't been documented.

### Steps To Reproduce
Describe an argumentless macro in a schema.yml file, eg.:

```
version: 2
macros:
  - name: my_macro
    description: Some description
```

### Expected behavior
Hide the Arguments section completely or mention that this macro doesn't take any arguments.

**The output of `dbt --version`:**
```
installed version: 0.16.1
   latest version: 0.16.1
```

**The operating system you're using:**
MacOS Catalina

**The output of `python --version`:**
Python 3.7.6

**Comment by jtcohen6** [comment]
IMO we could go in two directions here:
1. Parse the set of arguments from the macro definition and merge them with user-provided information in the `arguments` dict.
- That way, at least the arguments will show up by name (no description) in the docs site's "Arguments" box. This is more informative than the status quo, but not _much_ more informative; the argument names are equally available in the macro SQL right below.
- How to handle macros that explicitly accept `kwargs` or `varargs`?
2. If a user hasn't configured any arguments, we hide the "Arguments" box entirely. If that's our choice, we should transfer this issue to the dbt-docs repo, where this is a straightforward change.

I don't have a strong feeling that one is these is preferable, so I'm leaning toward the latter because it's easier.

**Comment by drewbanin** [comment]
- kwargs/varargs are probably not going to be easy/possible to capture, but maybe that's ok
- just noting that to capture these arguments, we'll probably need to do some _static analysis_ of the jinja macros :)

**Comment by jtcohen6** [comment]
> just noting that to capture these arguments, we'll probably need to do some _static analysis_ of the jinja macros :)

you caught my drift

**Comment by MartinGuindon** [comment]
I believe this issue is still relevant.

**Comment by hvassard** [comment]
Hello ! Just like @MartinGuindon I think this issue may be reopened as I find the message _"Details are not available for this macro"_ a bit confusing. 

Maybe updating this message with something like _"Details are not available for this macro. This may be due to the fact that this macro doesn't have any argument or that they haven't been documented yet."_ would be a first quick win to disambiguates the message without too heavy changes ? :)

**Comment by jtcohen6** [comment]
@hvassard I buy it! I think that could be a super quick change over in the `dbt-docs` repo - want to open [a new issue over there](https://github.com/dbt-labs/dbt-docs/blob/5f791fe466906df556855b0f2ac2fd9ff29019fc/src/app/components/macro_arguments/index.html#L13-L15)? Quick hint that [this is where the change would need to happen](https://github.com/dbt-labs/dbt-docs/blob/5f791fe466906df556855b0f2ac2fd9ff29019fc/src/app/components/macro_arguments/index.html#L13-L15)

**Comment by hvassard** [comment]
@jtcohen6 Thank you so much for you fast response ! I just [created an issue](https://github.com/dbt-labs/dbt-docs/issues/358) in the dbt-docs project and gave in the description the link of where in source code you think the change would happen ;)
