### ISSUE TITLE
Snapshot creating duplicates (updated)

### ISSUE THREAD

**Issue by Hayleycsck2** [dbt-labs/dbt-core#2607]
### Describe the bug
Snapshots are not inserting new rows. (This seems to be causing another issue around trying to merge/update multiple rows, however it may be an unrelated issue)

When I run the same SQL that is generated by dbt, this works just fine, so I don't believe it to be the data itself causing the issue. 

### Steps To Reproduce

There doesn't seem to be anything odd about the data itself, below is one model that is facing this issue ...

```
{% snapshot dim_jobs_order_item %}

{{
    config(
        target_schema='commercial',
        alias='dim_jobs_order_item',
        tags=["daily"],
        unique_key= 'order_item_number',
        strategy='check',
        check_cols=['order_item_number'
                    , 'start_date'
                    , 'end_date'
                    , 'opportunity_id'
                    , 'order_number'
                    , 'client_cam_id'
                    , 'account_id'
                    , 'account_name'
                    , 'category'
                    , 'type'
                    , 'product_type'
                    , 'product_string'
                    , 'territory_code'
                    , 'account_relationship'
                    , 'quantity'
                    , 'oracle_net_price'
                    , 'net_price'
                    , 'business_type'
                    , 'recruitment_category'
                    , 'discount_reason'
                    ],

        post_hook="delete from {{ this }} where end_date < DATE_SUB(CURRENT_DATE(), INTERVAL {{ env_config('retention_6_years_in_days') }} DAY)"
    )
}}

SELECT DISTINCT
              oi.order_item_number                                              AS order_item_number
            , oi.start_date                                                     AS start_date
            , oi.end_date                                                       AS end_date
            , oi.opportunity_id                                                 AS opportunity_id
            , oi.order_number                                                   AS order_number
            , oi.client_cam_id                                                  AS client_cam_id
            , oi.account_id                                                     AS account_id
            , oi.account_name                                                   AS account_name
            , oi.category                                                       AS category
            , oi.type                                                           AS type
            , oi.product_type                                                   AS product_type
            , oi.product_string                                                 AS product_string
            , oi.territory_code                                                 AS territory_code
            , oi.account_relationship                                           AS account_relationship
            , oi.quantity                                                       AS quantity
            , oi.oracle_net_price                                               AS oracle_net_price
            , oi.net_price                                                      AS net_price
            , oi.business_type                                                  AS business_type
            , oi.recruitment_category                                           AS recruitment_category
            , oi.discount_reason                                                AS discount_reason

FROM        {{ source('staging', 'jobs_salesforce_order_line_item') }} oi

{% endsnapshot %}
```

### Expected behavior
when running a snapshot, I expect to get a MERGE(x) notification at first, and then followed by MERGE(0) on the second run. Additionally, I expect all records in the target table to match the records in the source table. 

Instead, I repeated get MERGE(x), and the target table is missing that x number of records. 

### Screenshots and log output

![image](https://user-images.githubusercontent.com/48437782/86269329-886abc00-bbc1-11ea-946c-bb142bb9282c.png)
![image](https://user-images.githubusercontent.com/48437782/86269469-ae905c00-bbc1-11ea-8785-efd7ed3a6a16.png)

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.0
   latest version: 0.17.0
```

(also tested with previous versions)

**The operating system you're using:**
Windows 10

**The output of `python --version`:**
Python 3.8.2

### Additional context

Originally found this problem trying to chase down a MERGE/UPDATE error. As such, I believe this is somehow creating duplicates at the point of the snapshot - although these may be unrelated issues.

**Comment by jtcohen6** [comment]
@Hayleycsck2 It's hard to know exactly what's going wrong here. Here's one theory:

You have a `post_hook` configured to delete records from the snapshot after running if it has an old `end_date`. If those underlying records remain in the source table, and they have either
   * (a) a different `order_item_number` from the records in your target table; or
   * (b) the same `order_item_number` as a record in your target table, with a different combination of distinct values of your check cols,

Every time you run `dbt snapshot`, dbt is going to:
1. identify those X records as (a) new or (b) updated
2. add or update them via a `MERGE(X)` DML operation
3. delete all X records in the post-hook

As a result, you'll always see `MERGE(X)` (where X > 0) and yet those X records will appear to be missing from the target table.

I think you could avoid this by doing one of the following:
* Include your filter on `end_date` within the snapshot's actual `select` logic, instead of or in addition to the post hook
* Simplify! Let the snapshot do its snapshotting, and create a view model to perform the filter instead:
```sql
select * from {{ ref('dim_jobs_order_item') }}
where end_date < DATE_SUB(CURRENT_DATE(), INTERVAL {{ env_config('retention_6_years_in_days') }} DAY)
```

I'm happy to follow up on your [Slack thread](https://getdbt.slack.com/archives/C0VLZPLAE/p1593602279152600) to continue debugging this. Since this doesn't seem to reflect a bug in dbt's snapshot logic or require a code change in this repository, I'm going to close the issue.

**Comment by jtcohen6** [comment]
On second thought: there's a _lot_ going on here, including what sounds to be an adjacent issue:

> Originally found this problem trying to chase down a MERGE/UPDATE error. As such, I believe this is somehow creating duplicates at the point of the snapshot - although these may be unrelated issues.

As excited as I am by my "the post-hook's the thing" theory, I'm going to reopen until I have a chance to hear back and get to the bottom of what's really going on here. In particular, we'll need answers to:

* Do the X records that are being merged and then missing _actually_ have old values of `end_date`?
* Is `order_item_number` actually unique in the snapshot query? The `select distinct` is of twenty columns in combination...
* I see that `order_item_number` is both the `unique_key` and in the list of `check_cols`. Is there unexpected behavior when one column is both? That _would_ be grounds for a code change to dbt's `check` strategy.

**Comment by Hayleycsck2** [comment]
Hi @jtcohen6 

Thank you for looking into that for me. I have tested out the post hook, and that was the issue with not inserting new data. Our prod & dev environments have different retention variables, and the variables set in prod (about 6 years) allowed for a successful merge, at least locally.

However, this still leaves the question of the MERGE/UPDATE error, as this seems to be the real issue here. 

I hit this error when I remove the posthook entirely, so that's not the source of this issue.  If I remove `order_item_number` from the 'check' list, I still encounter the error. Also, I can confirm `order_item_number` is definitely unique for this table.  

However, when I *only* include `order_item_number` in the 'check' list, it merges just fine. However, this won't allow us to capture any other changes to the data.

I will keep testing, and update as I find out more...

**Comment by Hayleycsck2** [comment]
Found It!

I was right that dbt is creating duplicates at the point of snapshot... and its down to the union statement at the very end ...
![image](https://user-images.githubusercontent.com/48437782/86363122-4c416500-bc6e-11ea-93e9-0c7a64d340a0.png)


If you just do a quick (hack) to select distinct from that union, we get unique keys again
![image](https://user-images.githubusercontent.com/48437782/86363504-d8538c80-bc6e-11ea-9314-918f04208a22.png)


Now... I have no idea why the `insert ` CTE was creating duplicates... but I think we have it. I'm gonna see if I can test this out  locally :D

**Comment by Hayleycsck2** [comment]
@jtcohen6 

Update #2 

It works! For reference, I did this
![image](https://user-images.githubusercontent.com/48437782/86364931-bce98100-bc70-11ea-92d9-4a3c9ee3c507.png)

Would you be able to make this change to on your side?

**Comment by Hayleycsck2** [comment]
Hi @jtcohen6 any update on pushing that fix? I would open a PR my side, but I don't have permissions :)

**Comment by jtcohen6** [comment]
This is weird! If the issue is resolvable by adding `select *` to the bottom of the snapshot staging query, I feel that something must be afoot.

Could you confirm that `order_item_number` is unique in `dim_jobs_order_item`, by running a query like:
```sql
select count(*) as duplicates
from (

    select
        order_item_number

    from commercial.dim_jobs_order_item
    where order_item_number is not null
    group by order_item_number
    having count(*) > 1

) dupes
```

### Rationale

In trying to reproduce this locally with scratch data ([here's a gist](https://gist.github.com/jtcohen6/5b634f192feea6b54208d7b646727f39)), I'm stuck on how the `insertions` CTE in dbt's check snapshot logic could be creating _exact duplicates_... unless there are duplicate values of `dbt_unique_key` already in the existing snapshot target table.

As part of creating the staging table of updates and inserts, `dbt snapshot` should be running a query that looks roughly like:
```sql
...
insertions as (

        select
            'insert' as dbt_change_type,
            source_data.*

        from insertions_source_data as source_data
        left outer join snapshotted_data on snapshotted_data.dbt_unique_key = source_data.dbt_unique_key
        where snapshotted_data.dbt_unique_key is null
           or (
                snapshotted_data.dbt_unique_key is not null 
                and snapshotted_data.dbt_valid_to is null 
                and (
                        (
                            snapshotted_data.order_item_number != source_data.order_item_number
                            or (snapshotted_data.order_item_number is null) != (source_data.order_item_number is null) 
                            or snapshotted_data.start_date != source_data.start_date
                            or (snapshotted_data.start_date is null) != (source_data.start_date is null) 
                            
                            -- and so on, for every check column
                        
                )
            )
        )
    ),
...
 ```
This is the query to the bottom of which you added `select distinct *`, and the duplicates are removed. How is that possible?

* They have to be _exact_ duplicates (every column the same), otherwise `select distinct *` wouldn't have any effect.
* They _can't_ be coming in from the original snapshot query. You have a `select distinct` to take care of that, and the column list for selection is identical to the list of columns for value-checking.
* I feel like the culprit _has_ to be a fan-out in the `left outer join`. If the existing snapshot table has multiple "active" records where, e.g.,
```sql
order_item_number = 'ORD-2122772-1' and dbt_valid_to is null
```
Then we end up with exact duplicates for insertion, which can be resolved by adding `select distinct *`.

**Comment by Hayleycsck2** [comment]
Regarding the first question, this `dim_jobs_order_item` table is the table we are snapshotting into. Because of this, will have duplicates for the order_item_number - with different `dbt_valid_to` values.

However, I accounted for this and ran the following query ... 
![image](https://user-images.githubusercontent.com/48437782/86898090-2994cd80-c100-11ea-9960-9ce57d5aa019.png)

**Comment by jtcohen6** [comment]
Good call, thanks for adjusting and running the query. It looks like there are no _historical_ duplicates in `dim_jobs_order_item`, which is good, and seems to be a point against my hypothesis.

Could you run another query or two, to disprove it for good and send us back to the drawing board?

Let's see if there are any _current_ duplicate values of `order_item_number`:
```sql
select count(*) as duplicates
from (

    select
        order_item_number

    from commercial.dim_jobs_order_item
    where order_item_number is not null
      and dbt_valid_to is null
    group by order_item_number
    having count(*) > 1

) dupes
```

Then, assuming there aren't any, could you run standard `dbt snapshot`? That's _without_ the addition of `select distinct *` to `snapshot_staging_table`. If it still results in the insertion of exact duplicate records, I'll need to rethink.

**Comment by Hayleycsck2** [comment]
Sorry for the delay. No current duplicates, I'm going to see if I can drill into this problem on my side...

![image](https://user-images.githubusercontent.com/48437782/87281740-6f300c80-c4eb-11ea-95c8-b29ca1729fd1.png)

**Comment by funnel-arvid** [comment]
Hi, I had a similar problem and it's also BigQuery. In my case though I found that there were actually duplicates in the snapshot. 3 dbt_scd_id's existed twice, i.e. this was 6 rows. They were totally duplicates. This seems like a dbt bug, because all these rows where created by dbt built-in code. Just wanted to share this.
