### ISSUE TITLE
Insert a BigQuery table only when the last modified timestamp is after a given timestamp

### ISSUE THREAD

**Issue by yu-iskw** [dbt-labs/dbt-core#2668]
### Describe the feature
The idea is probably very close to `dbt_utils.insert_by_period_materialization`, but I would like to decide to insert a BigQuery table. Because, a BigQuery table doesn't potentially any timestamp field. And even running queries just to get the information about the latest value is potentially costly.

And consider if a project has a hundred of models and it takes a long time to execute `dbt run`. moreover, it is accidentally killed or failed in the middle of the process. So, we have to rerun `dbt run` again, however we want to resume the process as much as possible in order to reduce cost and elapsed time. It would be nice to skip models whose last updated is within a specified period.

For instance, if we want to insert a table whose last updated timestamp is only more than 24 hours, a possible config is like below.
```sql
{{
  config(
    materialized="insert_by_last_modified",
    period="24 hours",
    enabled=(target.type == 'bigquery')
  )
}}

...
```

### Describe alternatives you've considered
No idea.

### Additional context
NA

### Who will this benefit?
I think the feature is probably very useful for many BigQuery users.

### Are you interested in contributing this feature?
Yes, I am interested in implementing it. But, I am not sure what is the best approach, since I am still very new to dbt. I need

**Comment by jtcohen6** [comment]
Hi @yu-iskw, take a look at [incremental models](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models/). In particular, the BigQuery-specific [insert_overwrite strategy](https://docs.getdbt.com/reference/resource-configs/bigquery-configs/#the-insert_overwrite-strategy) sounds like it might be what you're after.

Have you joined our [community](http://community.getdbt.com/)? If not, you should! By asking a question like this one in Slack, community members would help you uncover the larger problem and talk through the available approaches. (I notice you opened https://github.com/fishtown-analytics/dbt/issues/2667 as well, which someone in Slack could have quickly answered.) Of course, [StackOverflow](https://stackoverflow.com/questions/tagged/dbt) is still best for debugging specific errors.

There is one specific point you made that I want to call out:

> however we want to resume the process as much as possible in order to reduce cost and elapsed time. It would be nice to skip models whose last updated is within a specified period.

This is a great idea! We have some thinking about a future approach here that would let you point to a previous build, and run only models that failed or skipped in that build. That's not here yet, but it's not far off.

In the meantime, if you materialize your biggest models incrementally, there's little pain felt by running them twice in quick succession, since the max timestamp that feeds into `{% is_incremental() %}` logic jumps ahead on the first go-round.

Otherwise, I do think it would be valuable to add BigQuery support for the `insert_by_period` materialization. There's an open issue for that (and more) in the dbt-utils repo, which is where that code is defined: https://github.com/fishtown-analytics/dbt-utils/issues/192

**Comment by yu-iskw** [comment]
@jtcohen6 Thank you replying to my suggestion. I joined the community and I just start taking advantage of it like [Show meta on the web UI like tags \- Water Cooler \- dbt Discourse](https://discourse.getdbt.com/t/show-meta-on-the-web-ui-like-tags/1521).

I am not familiar with `incremental` materialization. I will give it a try. Even if I figure out missing piece against what I want to do, I will let you know.
