### ISSUE TITLE
Include a unique identifier as part of the temporary relation name

### ISSUE THREAD

**Issue by samwedge** [dbt-labs/dbt-core#2881]
### Describe the feature
We schedule our DBT models using Airflow. Each day, our models run with a run date that allows us to populate all data for that specific day. We also trigger runs with "old" run dates to allow us to run DBT with historic dates to backfill the table with a full history, or sometimes run it for ad-hod days to fix a data issue.

When DBT runs, it creates a temporary table name which comprises the model name with the suffix `__dbt_tmp`. This means if we were to run DBT for two different dates simultaneously, they would interfere with each other with one run deleting another run's temp table or loading the wrong data into the database. Including a date or, more generically, some sort of UUID as part of the temporary name would prevent this issue from occurring.

### Describe alternatives you've considered
We currently work around this by being very careful when running jobs. We need to ensure that we don't run the same model twice simultaneously.
We have also in some instances rewritten sql to load all data between a specified date and the current date, which then precludes the need for "backfilling". But this only works for smaller datasets and also means the DBT run isn't repeatable (the data inserted depends on the data already present in the table).

### Additional context
We use BigQuery. I imagine this is an issue for all databases.

### Who will this benefit?
This will have a speed improvement for anyone running DBT on a day-by-day basis as they will be able to run multiple dates simultaneously. It will help reduce the potential for conflicts to occur.

### Are you interested in contributing this feature?
Absolutely happy to create a PR for this. I may need some assistance to ensure adding this feature does not cause/exacerbate issues such as the one highlighted here: https://github.com/fishtown-analytics/dbt/issues/2869

**Comment by jtcohen6** [comment]
Thanks for the detailed writeup @samwedge. This varies quite a bit depending on the database you're using, since it sits at the intersection of transactions and temporary tables.

> When DBT runs, it creates a temporary table name which comprises the model name with the suffix `__dbt_tmp`.

To my knowledge, the only times dbt creates tables on BigQuery with the suffix `__dbt_tmp` are:
- incremental models with dynamic `insert_overwrite` strategy ([here](https://github.com/fishtown-analytics/dbt/blob/dev/kiyoshi-kuromiya/plugins/bigquery/dbt/include/bigquery/macros/materializations/incremental.sql#L60))
- snapshots ([here](https://github.com/fishtown-analytics/dbt/blob/dev/kiyoshi-kuromiya/core/dbt/include/global_project/macros/materializations/snapshot/snapshot.sql#L178))

Those _could_ be "real" temp tables (a relatively new feature on BigQuery), created and used inside of a script. At the moment, they're still artificial temp tables (12-hour time-to-live) for historical reasons.

In the standard table and view materializations, dbt-bigquery uses `create or replace`, skipping the creation of a tmp object entirely.

By comparison, on Postgres: 
- We need to truncate identifiers to accommodate suffixes because of stringent length requirements. This isn't an issue on BQ.
- We can create and use temp tables inside of atomic transactions, and they automatically disappear soon after, avoiding any risk of conflict. Transactions aren't available on BQ; the closest thing we have is scripting.

### Recommendation

By design, dbt _really_ is not intended to have multiple concurrent runs that are mutating the same database objects—especially on databases without transactions. You could be running a query to replace an object in one run, meanwhile it's an active dependency for another run's query. Instead, dbt supports concurrency via threading and environments.

> We currently work around this by being very careful when running jobs. We need to ensure that we don't run the same model twice simultaneously.

I get that this is a constraint, but I still think it's a useful one. I highly recommend that, as much as you can, you orchestrate your backfill runs in Airflow such that they do not overlap with daily runs in the same production environment.

### Resolution

Rather than adding a unique identifier to the temp suffix, I think the real resolution here is to switch the incremental and snapshot materializations to use "real" temp tables, run inside of scripts. (The incremental materialization already uses scripting; this would require some reworking or BQ-specific reimplementation of the snapshot materialization.) To my mind, that would solve any possibility of conflict on BigQuery entirely. 

Let me know if that's something you'd be interested in taking on!

**Comment by danielerapati** [comment]
Hi,
we definitely run into a related problem in Redshift.
We have a setup similar to @samwedge with different airflow jobs running `dbt run` with different configurations but sharing a few models and running at different times. 
Rarely (annoyingly this is often when jobs have failed for a different reason and need to be manually restarted from Airflow) two jobs would clash on the same model and hit the same `__dbt_backup` table/view (I think transactions prevent the same happening on the `__dbt_tmp` object).

A solution is a macro that we can override for choosing how to name the temporary and backup objects. Something similar to what we can already do for schemas or aliases.
So the view materialization [here](https://github.com/dbt-labs/dbt/blob/v0.21.0b2/core/dbt/include/global_project/macros/materializations/view/view.sql#L4) and the table materialization [here](https://github.com/dbt-labs/dbt/blob/v0.21.0b2/core/dbt/include/global_project/macros/materializations/table/table.sql#L3) (and other materializations too) would call that macro instead of hard-coding the suffix.
I noticed there is something similar called [`make_temp_relation`](https://github.com/dbt-labs/dbt/blob/a2bdd08d88241389a696b5f4834715309e9e10a2/core/dbt/include/global_project/macros/adapters/common.sql#L298) but my impression is only the Snowflake plugin uses it in a slightly different setting.

**Comment by meisam-napster** [comment]
Hi, running into the same issue now and wondering if there are any updates / solutions to this scenario? Will DBT support "real" temp tables for BigQuery as opposed to creating tables with "__tmp" at the end or is there another solution?

**Comment by Dikootje** [comment]
> Hi, running into the same issue now and wondering if there are any updates / solutions to this scenario? Will DBT support "real" temp tables for BigQuery as opposed to creating tables with "__tmp" at the end or is there another solution?

FYI: On snowflake I've ran into a similar issue. We now work around this now by overriding the macro's `make_intermediate_relation` and `make_temp_relation` and using the invocation_id as a suffix instead. (Without the dashes)

**Comment by andtrott** [comment]
We've run into the same issue with Airflow/BigQuery. I think it's a misrepresentation describing this as 
> multiple concurrent runs that are mutating the same database objects
The reality is that multiple concurrent jobs are mutating different partitions of the same table. Which is why they're using insert_overwrite and designed incrementally. I don't see how this is poor design. Airflow is designed to run concurrently for big backfills and dbt should be able to handle this with this enhancement.

Real temp tables including a unique identifier should fix it in my mind.

**Comment by Prokos** [comment]
We're also running into this issue using BigQuery (through Airflow). 

Every day we run our complete data model for one day, there are a lot of incremental models adjusting one partition at a time, this all works.
 
However there are valid use-cases for running a model for multiple partitions in parallel, we have models that we both want to run for yesterday's data and re-run it for a few days back as data might have updated. Additionally, we might want to set up a backfill, if that's large enough it might also intersect with our daily run. 

To me it seems like you should be able to run a model for different partitions in parallel, as they are not effectively operating on the same data. I'm not sure what the downsides are of a unique identifier for the tmp tables per run, but it would fix these issues. Options exist in Airflow to circumvent this issue, but it makes data runs slower than necessary plus overcomplicates DAG and dependency logic.

Actually IMO dbt should also be able to handle two parallel runs on the same partition elegantly, now you get duplicates but it should just use the last result. Not a valid use-case, but something dbt could catch nonetheless.

As a final note, these data problems are not obvious. Our experience was data randomly being messed up and not understanding why until we finally caught the fact that tmp tables were being re-used. Now that we're aware of this limitation we are faster to fix it if a new use-case runs the same model in parallel, but I can easily imagine more people running into this and never understanding why their data is "randomly" messed up.
