### ISSUE TITLE
Run requires datasets.update permission on auth view when access is assigned in terraform

### ISSUE THREAD

**Issue by phlope** [dbt-labs/dbt-core#2912]
### Describe the bug
Access for authorised views is assigned via terraform, when a scheduled DBT task runs our scheduler errors with the below, that DBT doesn't have datasets.update permission. I'm opening the request to enquire as to why DBT should need to have this specific permission if it (the grant_access_to configuration) isn't managed in the view itself

### Steps To Reproduce
n/a

### Expected behaviour
Since the access is configured in terraform, and the view built in DBT, i would expect that DBT would not need to re-update any access in bigquery. Does DBT require datasets.update to perform any run against an auth view in DBT even if no access is being changed?

### Screenshots and log output
```
INFO - b'\x1b[33mDatabase Error in model deleted_user_ids (PATH/TO/MODEL)
INFO - b'  Access Denied: Dataset [PROJECT:DATASET]: User does not have bigquery.datasets.update permission for dataset [PROJECT:DATASET]
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [*] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.18.1
```

**Comment by jtcohen6** [comment]
@phlope Do you have `grant_access_to` configured for that view in your dbt project? dbt checks for it at the end of the view materialization:

https://github.com/fishtown-analytics/dbt/blob/fec0e31a25d5b922cb1833cffcb5095eb4ee642b/plugins/bigquery/dbt/include/bigquery/macros/materializations/view.sql#L17-L21

If found, dbt will try to execute the following steps via the BigQuery python client, which includes `update_dataset`:

https://github.com/fishtown-analytics/dbt/blob/fec0e31a25d5b922cb1833cffcb5095eb4ee642b/plugins/bigquery/dbt/adapters/bigquery/impl.py#L789-L819

If you're already managing those grants elsewhere (i.e. in terraform), and you don't want dbt to have the permissions to authorize the view by granting access to otherwise-inaccessible datasets, then you should remove the `grant_access_to` config. (I imagine the risk is that, if dbt handles the view creation and terraform handles the permissions, there could be downtime between dbt creating/replacing the view and Terraform granting it the access it needs.)

Let me know if I'm missing something. I'd support adding a note to [our docs on authorized views](https://docs.getdbt.com/reference/resource-configs/bigquery-configs/#authorized-views) stating the explicit permissions that dbt needs to use the feature.

**Comment by phlope** [comment]
@jtcohen6 Thanks for the reply! 
Interesting ok, we originally specified `grant_access_to` but have since tested creating views and granting access solely via terraform and encounter the same error.

**Comment by jtcohen6** [comment]
@phlope What's the exact SQL that dbt runs before you see that error message?

**Comment by philip-hope** [comment]
@jtcohen6 Sorry for the delay, we are encountering this behaviour across several views, the simplest of which is:

```
SELECT

column_1,
column_2,
column_3

FROM {{ ref('dataset') }}

**Comment by jtcohen6** [comment]
Thanks for the reply @philip-hope! I'm still a little confused, but I think we can figure this out.

If you have `grant_access_to` configured on _any_ view in your dbt project, dbt is going to `update_dataset`. If dbt doesn't have the permissions to do that, it's going to raise an `Access Denied` error.

When your model _doesn't_ have `grant_access_to` configured, either via in-file `config()` block or `dbt_project.yml`, it sounds like you're still seeing the `Access Denied` error. This is surprising; though I suppose it would make sense if a BigQuery user cannot `replace` a view that it originally created, if that view has since become an authorized view _and_ that user doesn't have sufficient permissions on its authorizations. I don't remember seeing in anything in the docs about this, so it would be good to know if so.

Could you paste here the relevant lines from `logs/dbt.log`? From when dbt executes the compiled SQL that creates/replaces the view, to when BigQuery returns the `Access Denied` error message.

**Comment by phlope** [comment]
@jtcohen6 Thanks for the information, yes i can confirm that with each re-run of a dbt task we hit the update.dataset error regardless of whether a change has been made to the view. This occurs with or without `grant_access_to` configured.

**Comment by marcellovictorino** [comment]
Adding to the thread, since I experienced a similar issue:

**Our case:**
* there is no mention of `grant_access_to` in our codebase
* use dbt to perform transformation and materialize views in Big Query
* authorized views are handled by a separate tool 
* the required **update** permission error arises only after an **authorized view** is applied

> After some testing, I can confirm the issue is on BigQuery, not dbt side!

**The Problem:** 👎 
When executing a `CREATE OR REPLACE VIEW...` query (which is generated by dbt) on a view that already has authorized views, Big Query will try to **update** the source reference - causing a permission issue.

**The solution:** ✔️ 
For now, we assign a special role with **write** and **update** permission for the service account in production.

Thanks @jtcohen6 for the attentive support on the Slack community!

**Comment by sdeutscherkobayashi** [comment]
Was there ever a solution to this other than elevating the service account permissions? I am facing a similar situation where its not a possible solution (Dataset creation is locked down in order to enforce certain dev ops practice)

**Comment by nathangriffiths-cdx** [comment]
> Was there ever a solution to this other than elevating the service account permissions? I am facing a similar situation where its not a possible solution (Dataset creation is locked down in order to enforce certain dev ops practice)

@sdeutscherkobayashi  We worked around this by authorising at the dataset level instead of the view level. This is implemented in Terraform e.g. 

```
resource "google_bigquery_dataset_access" "my_dataset_a_access" {
  dataset_id = google_bigquery_dataset.my_dataset_a.dataset_id
  dataset {
    dataset {
      project_id = var.project_id
      dataset_id = google_bigquery_dataset.my_dataset_b.dataset_id
    }
    target_types = ["VIEWS"]
  }
}

```
In dbt views are just implemented normally, `grant_access_to` is not used.
