### ISSUE TITLE
Static checks aren't defined in configs

### ISSUE THREAD

**Issue by max-sixty** [dbt-labs/dbt-core#2926]
### Describe the bug

Ref https://github.com/fishtown-analytics/dbt/pull/2908#discussion_r534398007 & https://github.com/fishtown-analytics/dbt/pull/2908#discussion_r534360840

Currently running `mypy .` & `flake8 .` returns enough errors to overflow my terminal. It sounds like that's because the ignores & excludes are defined in the tox file, rather than in python config files, like `setup.cfg` / `pyproject.toml` / etc.

The tox file isn't picked up by editors, or by anyone running these tools in the standard way.

**Comment by jtcohen6** [comment]
Good points @max-sixty. We use `tox` as the basis for all our testing via via [make](https://github.com/fishtown-analytics/dbt/blob/34869fc2a2a354a18a232e21315c3901aafab0b6/Makefile#L14), [CI](https://github.com/fishtown-analytics/dbt/blob/34869fc2a2a354a18a232e21315c3901aafab0b6/.circleci/config.yml#L10), and dev shorthand ([scripts/dtr.py](scripts/dtr.py)).

That said, I'm in favor of moving these configs down a level so that folks who run `mypy` or `flake8` directly will see the same errors.
