### ISSUE TITLE
If generate_schema_name returns an empty string, a strange error is encountered

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/dbt-core#3013]
### Steps to reproduce
1. Write your own logic:
```sql
$ cat macros/generate_schema_name.sql
{% macro generate_schema_name(custom_schema_name, node) -%}
    {%- set default_schema = target.schema -%}
    {%- if custom_schema_name is none -%}
        {{ default_schema }}
    {%- else -%}
        {{ custom_schema_name | trim }}
    {%- endif -%}
{%- endmacro %}
```
2. Pass through an empty string as a schema config
```sql
$ cat models/my_model.sql
{{ config(schema='') }}

select 1 as id
```
3. Run the model 
```
$ dbt run -m my_model
Running with dbt=0.19.0-rc1
Found 6 models, 24 tests, 0 snapshots, 0 analyses, 144 macros, 0 operations, 0 seed files, 3 sources

Encountered an error:
Database Error
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 38 unexpected '<EOF>'.
  syntax error line 1 at position 37 unexpected '.'.
```

On closer inspection of the logs, we can see that dbt is trying to run this statement:
```
create schema if not exists analytics.
```

### Expected behavior
We should have a validation step that the output of `trim(generate_schema_name) != ''`

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**Comment by jtcohen6** [comment]
I don't think this even requires a custom `generate_schema_name ` macro. It's effectively the same logic that's here:
https://github.com/fishtown-analytics/dbt/blob/42a85ac39f34b058678fd0c03ff8e8d2835d2808/core/dbt/include/global_project/macros/etc/get_custom_schema.sql#L17-L30

I think the issue is in this line:
```
{%- if custom_schema_name is none -%}
```
Technically, `'' is not none`. We might instead check for:
```
{%- if custom_schema_name is not none and custom_schema_name != '' -%}
```

**Comment by clrcrl** [comment]
With the default implementation, I end up using a schema named `dbt_claire_`, so I think this only arises when using a custom `generate_schema_name` macro.

I think we actually want to write some logic here:
https://github.com/fishtown-analytics/dbt/blob/dev/kiyoshi-kuromiya/core/dbt/parser/base.py#L134

Like:
```
if new_value == '':
  # raise an error

**Comment by jtcohen6** [comment]
I don't think `dbt_claire_` is the desired behavior; the macro should recognize that `''` should be treated like `none`, and use the default schema instead. I call out the default `generate_schema_name` macro(s) that are built into dbt, because I imagine most custom implementations are adapted (copy-paste-edit) from there.

That said, I'd also be in favor of raising an error if someone tries to set a relation's namespace component to `''`, via `generate_x_name` macro or other means.
