### ISSUE TITLE
Create a column that captures why a snapshot record was invalidated

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/dbt-core#3021]
### Describe the feature
With the introduction of the `invalidate_hard_deletes` config, there's now two reasons why a record can be invalidated — either the record got updated, _or_ it was deleted. It may be useful to differentiate between the two.

It's possible to handle this in a downstream modeling layer, but it feels like it might be a more reasonable solution to instead handle this in the snapshot by adding a column, `dbt_invalidate_reason` with values of `'hard_delete'`, `'update'` or `null`.

This information could be useful if someone wants to create a "current view w/ soft deletes" of the data (i.e. create the view of their data that should have existed in the first place hehe)

```
select
  *
from {{ ref('my_snapshot') }}
where (dbt_valid_to is null or dbt_invalidate_reason = 'hard_delete')
```

### Describe alternatives you've considered
Handling in the modeling layer:

```sql
select
    lead(dbt_valid_from) over (partition by {{unique_key}} order by dbt_valid_from) as next_record_started,
    dbt_valid_to - next_record_started as next_record_diff,
    case
      -- invalid, no next record
      when next_record_started is null and dbt_valid_to is not null then 'deleted'
      -- lead time until next record
      when next_record_diff > 0 then 'deleted'
      -- no lead time until next record
      when next_record_diff = 0 then 'updated'
      -- this record is still valid
      else null end as dbt_invalidated_reason
from {{ ref('my_snapshot') }}
```

### Additional context
- If we introduce this, we might want to provide an operation for people to backfill this reason.
- Is it also useful to include a sort of `dbt_new_record_reason` with one of `['new', 'update', 'returned']`

### Who will this benefit?
Advanced users of snapshots. As always when it comes to snapshots, curious to hear inputs from @joellabes and @codigo-ergo-sum

### Are you interested in contributing this feature?
Could do if you wanted me to

**Comment by joellabes** [comment]
I talked to Claire about this a bit in DMs, and my argument was that if I’d done this feature, I would have had an explicit `dbt_is_deleted` column. Deleted rows would have that set to true with a null `dbt_valid_to`. (I _didn’t_ do the feature though so am happy to take what I get 😂)

I’ve thought a bit more about how we use snapshots and realised we always filter out the deleted ones once we finish date spining anyway, so including them just to remove them again doesn’t make a heap of sense. 

I still support this because being more explicit is better than less, but I don’t _think_ I have an immediate use case beyond making auditing easier (which ain’t nothing!)

**Comment by codigo-ergo-sum** [comment]
I do like the idea of having in snapshots a specific field showing whether the data being referred to is still present in the source or underlying model that the snapshot is pointing at. I'm being specific and not just saying "source" because I also would like to see snapshots expand in the future to be full-fledged DAG-aware entities, perhaps literally just another type of materialization, to handle the use cases where you want to snapshot the results of another model (let's call it model A) and then maybe have a model that points at the snapshot. So, like this:

(Model A) -> (Snapshot) -> (Model B)

But, I digress. That is another discussion. 

Now, I think the tricky thing about this - does this additional field show a) what the current state is of any given row in the snapshot with regards to the source, and whether the record with the relevant primary key still exists in the source when the snapshot was last updated or (mutually exclusively) b) solely the reason that a given record was end-dated at the last time it was end-dated? I think that's @clrcrl 's original suggestion above is b) and not a). 

The reason that I ask about a) is that sometimes what you want to ask is "give me all the history of records, but only those records that are still at the source/have not been hard deleted." This is how we handle that problem in our code, by writing what we call a "filter" on top of the snapshot. The filter  cleans up names, datatypes, adds an `is_current` field (although in this example we're filtering only for the most recent records so it's always set to `TRUE`), and most importantly then also adds the `is_present_in_src` field by doing a `LEFT OUTER JOIN` back to the relevant source that the snapshot is already generated from:

```SELECT
    CAST(ss.Id AS INT64) AS qb_account_id, 
    CAST(NULLIF(ss.Name,'') AS STRING) AS qb_account_name,
    CAST(NULLIF(ss.FullyQualifiedName,'') AS STRING) AS qb_account_fqname,
    CAST(NULLIF(ss.Classification,'') AS STRING) AS classification,
    CAST(NULLIF(ss.AccountType,'') AS STRING) AS qb_account_type,
    CAST(NULLIF(ss.AccountSubType,'') AS STRING) AS qb_account_subtype,
    CAST(NULLIF(ss.AcctNum,'') AS STRING) AS qb_account_number,
    CAST(ss.Active AS BOOLEAN) AS is_active,
    CAST(ss.SubAccount AS BOOLEAN) AS is_subaccount,
    CAST(ss.ParentRefvalue AS INT64) AS qb_parent_id,
    CAST(CASE WHEN src.Id IS NULL THEN FALSE ELSE TRUE END AS BOOLEAN) AS is_present_in_src,
    CAST(ss.dbt_scd_id AS STRING) AS dbt_scd_id,
    CAST(ss.dbt_updated_at AS TIMESTAMP) AS dbt_updated_at,
    CAST(ss.dbt_valid_from AS TIMESTAMP) AS dbt_valid_from,
    CAST(COALESCE(ss.dbt_valid_to, {{ var('future_eternity_ts') }}) AS TIMESTAMP) AS dbt_valid_to,
    -- For this model, only looking at the most current row so is_current will always be true.
    CAST(TRUE AS BOOLEAN) AS is_current
    FROM {{ref('qb_account_snapshot')}} ss
    LEFT OUTER JOIN {{ source('qb','qb_account')}} src
        ON ss.Id = src.Id
    WHERE dbt_valid_to IS NULL
```

In this case, `qb_account_snapshot` also is generated based off of `qb_account`. 

@clrcrl 's proposal would help move the logic to the modeling layer if you're asking question b) , which is "Of the most recent records, which no longer/still do exist in the source" but it wouldn't help answer question a) "Of all records, show only those which are still present in the source". And we ask question b) a _lot._

If we had a `dbt_is_deleted_in_src` flag in the snapshot, you could answer both questions.

"Of the most recent records, which still do exist in the source":
```
select
  *
from {{ ref('my_snapshot') }}
where dbt_valid_to is null and NOT dbt_is_deleted_in_src
```

"Of all records, which still do exist in the source":
```
select
  *
from {{ ref('my_snapshot') }}
where NOT dbt_is_deleted_in_src
```

Now, the tricky thing about setting this flag is that you can't just set it for the most recent record - you potentially may need to go back and update any arbitrary amount of rows in the snapshot, including potentially every row, depending on how rows are present/absent/returning from absence to the source. So I don't know how hard that is to do. It could potentially be costly from a performance perspective for very large snapshots.

One nice thing about adding this flag is that there is no need for manual intervention on the part of users to backdate it - it can automatically be calculated/backdated based on solely what exists in the source and the snapshot together.

What does this approach not provide? We wouldn't be able to see for a given record if it had been absent and then returned, whereas in @clrcrl 's proposal you could see that via the `returned` value in the `dbt_invalidate_reason` field. 

Thoughts?

**Comment by joellabes** [comment]
Conceptually, I don't think I love the idea of snapshots changing from a static, uh... snapshot, to a dynamic dataset. This feels like a parallel to the `is_current_version` pattern which is calculated via `dbt_valid_to is null` as opposed to the snapshot code being responsible for re-calculating everything on each run. 

>And we ask question b) a lot.

Just checking, is this meant to be question *a*, given that you said Claire's proposal solves question b?

>But, I digress. That is another discussion.

This is a discussion I'm also _very_ interested in having. I've been going back and forth in my mind all week about whether I snapshot a model with the new functionality in 0.19.0 or do an incremental model with the date as part of its key to get a new insert each day. Might write something up on Discourse.
