### ISSUE TITLE
dbt init support for optional --project-dir arg

### ISSUE THREAD

**Issue by srjonemed** [dbt-labs/dbt-core#3024]
### Describe the bug
Currently the --project-dir argument doesn't seem to be supported within `dbt init` command although it appears in the Usage help message

### Steps To Reproduce
`dbt init --project-dir $DBT_HOME/ops ops_project1`

### Expected behavior
Ideally am expecting the `ops_project1` folder would be initialized under the given --project-dir argument, but it gets init'ed in current folder instead

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - bigquery: 0.18.1
  - postgres: 0.18.1
  - redshift: 0.18.1
  - snowflake: 0.18.1
```

**The operating system you're using:**
macos

**The output of `python --version`:**
3.7.9

**Comment by jtcohen6** [comment]
Thanks for opening @srjonemed, this makes sense. I think we should do two things:
- Support `--project-dir` and `--profiles-dir` as arguments that change where `dbt init` creates the starter project and profile scaffolding (if none exists), respectively
- Clean up the `dbt init --help` optional arguments, since several (`--profile`, `--target`, `--vars`, `--bypass-cache`) are not relevant to `init`
