### ISSUE TITLE
Using non-deterministic code such as "invocation_id" in post_hooks causes "state:modified" to see changes

### ISSUE THREAD

**Issue by dmateusp** [dbt-labs/dbt-core#3047]
### Describe the bug

With 0.19, I am trying to move my CI back to using `state:modified`. I noticed that some models were always seen as "modified".

After some digging, I noticed the post_hooks were using a macro that used invocation_id to create a temporary table.
I imagine the same would be true for anything that generates a random text/number.

### Steps To Reproduce

Create a simple macro that uses "invocation_id":
```sql
{% macro my_macro() %}
{% set table_name = 'token_' ~ invocation_id | replace('-', '_') %}
create temporary table {{ table_name }} as (select 1 as id);
{% endmacro %}
```

Use that macro in a post_hook:
```sql
post_hook=[my_macro()]
```

Now run the model:
```bash
dbt run -m my_model --full-refresh
```

And compare the state against the manifest you just created:
```bash
dbt ls --select "state:modified" --state ./target/
```

You'll see my_model there

### Expected behavior
Initially, add a note about the above in the `state:modified` documentation (do not use random generated identifiers in macros).
Expose a `--defer` friendly macro that creates unique IDs (through UUIDs for example like invocation_id) but uses a "seed" to have deterministic behavior. The seed could be a dbt-wide environment variable, which we can overwrite in CI (to have something consistent.) 

### Screenshots and log output
N/A

### System information
**Which database are you using dbt with?**
N/A

**The output of `dbt --version`:**
```
installed version: 0.19.0
   latest version: 0.19.0

Up to date!

Plugins:
  - bigquery: 0.19.0
  - snowflake: 0.19.0
  - redshift: 0.19.0
  - postgres: 0.19.0
```

**The operating system you're using:**
Mac OSX

**The output of `python --version`:**
Python 3.8.2

### Additional context
In my scenario, replacing the invocation_id with `model["name"]` was a good fix.

**Comment by jtcohen6** [comment]
Thanks for the detailed write-up @dmateusp! The issue here is specific to `post-hook` being a model config set via an in-file `config()` macro. The ultimate resolution here is complex; you can read more in #2714. This is something we want to do, eventually; and if we manage to do a good job, it will enable _lots_ of other cool things.

Some good news: In v0.19.0, we enabled dbt to store the un-resolved forms of configs _if and only if they are set in **dbt_project.yml**_ (#2713). (This was more technically feasible in the near term.) While you can't use a macro here, you can pass the Jinja expression to the `post_hook` config. dbt will store and compare the un-resolved form, i.e. the Jinja code, rather than its compiled (always-different) result:
```yml
models:
  +post_hook:
    - > {% set table_name = 'token_' ~ invocation_id | replace('-', '_') %}
        create temporary table {{ table_name }} as (select 1 as id);
```
I tested locally:
```bash
$ dbt compile -t prod
$ mv target/manifest.json prod-artifacts/
$ dbt ls -m state:modified --state prod-artifacts/
```
```
The selector 'state:modified' does not match any nodes and will be ignored
No nodes selected!
```

In the meantime, this is a known limitation of `state:modified`, in the sense of "False Positives," as described [here in the docs](https://docs.getdbt.com/reference/node-selection/state-comparison-caveats/#false-positives). That said, we can and should clarify that "False Positives" includes `config()` arguments with environment-based behavior _and_ `config()` arguments with non-deterministic behavior (always different, no matter the environment). Any chance I could trouble you to write a few lines for that docs article? :)

**Comment by dmateusp** [comment]
Oh thank you for the clarification: I read the docs and saw:
> If you're interested in learning more, read open issues tagged "state" in the dbt repository.

Could we just add the "state" tag to this issue?
