### ISSUE TITLE
Ephemeral model materialization should not allow partition_by and cluster_by in the config.

### ISSUE THREAD

**Issue by ericxiao251** [dbt-labs/dbt-core#3055]
### Describe the bug

An ephemeral model does not actually get materialized but rather becomes a CTE in a downstream model. This means that the partition_by and cluster_by parameters are not used.

I think it may be a bit confusing/misleading to the users to see these two arguments passed into a model that is materialized as `ephemeral`.

i.e.

```sql
{{ seamster_config('ephemeral', cluster_by='shop_id') }}

SELECT 1 as column_one
```

---

Sidenote... I would love to make this change to DBT if it's a good proposal. Where would I start looking in the codebase :).

**Comment by jtcohen6** [comment]
Thanks @ericxiao251, you raise an interesting question!

Check out a related conversation over in https://github.com/fishtown-analytics/dbt/issues/2606. While dbt does have an enumerated list of its supported configurations, and the ones that each adapter supports (e.g. `sort` + `dist` in `dbt-redshift`), it's also possible for a custom materialization to use a `config(custom_val = 'someting')` value via `config.get('custom_val')`. We don't have a way to know all the meaningful user-defined configs—short of statically analyzing all the Jinja code in the project, which would be a very cool but very significant undertaking—and that makes it hard for dbt to say with certainty, "Hey, you supplied a config `materizalied`, but it's actually spelled `materialized`."

Your issue goes one level further—you're not just thinking about raising a warning or error if a generally invalid/unused config is supplied, but rather if an otherwise valid/used config is supplied alongside a materialization that does not use it. This would require: dbt to know which [model configs](https://docs.getdbt.com/reference/model-configs/) are specific to certain materializations. I don't usually think of `persist_docs` and `database`/`schema`/`alias` as specific to certain materializations, but of course, they don't apply to ephemeral models.

In reading your issue, I also assume you're talking exclusively about in-file `config()` blocks. There is another way to set model configs, of course, and in **dbt_project.yml** it's quite common to see:
```yml
models:
  +transient: true   # only relevant to snowflake tables
  +bind: false         # only relevant to redshift views
```
The way dbt works today, _all_ models in the project now have the `transient = true` and `bind = false` configurations, unless they're set again more precisely via per-model `config()`. I don't think we should raise a warning or error in a Snowflake view model because it can't use `transient`, or in a Redshift table model because `bind` need not apply.

So, thinking through where to go from here:
- Are you thinking about the more-general problem of unused-yet-misleading model configs?
- Is your interest here specific to ephemeral models, which don't use hardly _any_ model configs? (I think `enabled` and `tags` are the two exceptions.) It would be straightforward enough to add a warning message along the lines of, "Your `config()` defines the model materialization as 'ephemeral' and includes other arguments that are thereby irrelevant."

**Comment by ericxiao251** [comment]
Yes, my interest is specific to the `ephemeral` model use case, I think it might be a bit misleading to users and they may come to us for questions like:

"Hey my downstream model (not materialized as `ephemeral`) is trying to take only partitions of this other model (materialized as `ephemeral`), but I pick up way more data than I expect... what's happening?"

---

Ah I see, reading the linked issue, that makes sense, that we need something before we can enable the behaviour I'm describing...

---

I like the warning message suggestion, but when would you encounter the warning message? I believe when you run an ephemeral model, nothing actually gets ran? Would it be a bit more confusing to users that now they also get a warning message?

**Comment by jtcohen6** [comment]
I imagine this would be a warning message, logged any time you compile/invoke a dbt project with any model containing:
```sql
-- models/my_ephemeral.sql
{{ config(
    materialized = 'ephemeral',
    not_tags_or_enabled = 'something'
) }}
```
```bash
$ dbt compile
Running with dbt=0.19.0
[WARNING]: There is 1 ephemeral model with inapplicable config() arguments:
- models.my_ephemeral
```
That's regardless of whether you're executing a resource that has any direct relationship to `my_ephemeral`. Similar to how we raise error messages when `dbt_project.yml` config does not refer to any resources:
```yml
models:
  irrelevant:
    +materialized: table
```
```bash
$ dbt compile
Running with dbt=0.19.0
[WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.irrelevant
```
What do you think?

**Comment by ericxiao251** [comment]
I like it! Will this warning also show when running `dbt run model` as well, probably not cause that would require static analysis? But I think having it in the compile is a great first step.

**Comment by jtcohen6** [comment]
This would be a warning that appears _any_ time you invoke dbt. I'm not the pro on dbt parsing these days, so I'd love to get @gshank's eyes on this as well, especially to make sure that any changes we make here don't have unintended consequences for parsing performance.

I think this warning message needs to happen at a point where:
- We have access to config from both `dbt_project.yml` + in-model `config()`, to know if our model is `materialized: ephemeral`
- We can still distinguish between the two config types (`node.config` vs. `config._config_calls`), since we want to raise an error IFF an irrelevant value is passed to `config()`, and not as a result of extraneous/inherited config from `dbt_project.yml`

I think that looks like `render_update` in the `ConfiguredParser`:
https://github.com/fishtown-analytics/dbt/blob/36d1bddc5b3ec7b0f503972d7138e8260693da38/core/dbt/parser/base.py#L376-L385

In particular, I got the following (bad) code to work:
```python
            self.update_parsed_node(node, config)
            
            if node.resource_type == NodeType.Model and \
                node.config.materialized == 'ephemeral':
                    config_args = list(config._config_calls[0].keys())
                    for k in ('materialized', 'enabled', 'tags'):
                        if k in config_args:
                            config_args.remove(k)
                    if len(config_args) > 0:
                        bad_args = ", ".join(config_args)
                        warn_or_error(
                            f"The ephemeral model {node.name} has inapplicable "
                            f"config() arguments, which will be ignored: "
                            f"{bad_args}",
                            log_fmt=warning_tag("{}")
                        )
                
        except ValidationError as exc:
```
```
$ dbt run
Running with dbt=0.19.0
[WARNING]: The ephemeral model my_model has inapplicable config() arguments, which will be ignored: cluster_by, partition_by
```
