### ISSUE TITLE
Populate graph Jinja variable with sources at parse time

### ISSUE THREAD

**Issue by panasenco** [dbt-labs/dbt-core#3072]
### Describe the feature
I understand the reasoning behind making the nodes of the [graph variable](https://docs.getdbt.com/reference/dbt-jinja-functions/graph/) empty at parse time, but I don't see why sources can't be populated at parse time.

### Describe alternatives you've considered
Just going without lineage information for views generated with variable sources.

### Who will this benefit?
Anyone building queries from a dynamic list of sources as shown in the [Accessing sources](https://docs.getdbt.com/reference/dbt-jinja-functions/graph/#accessing-sources) example.

### Are you interested in contributing this feature?
Not right now since none of my internal customers are asking for this lineage yet

**Comment by jtcohen6** [comment]
@panasenco Just to be clear, are you referring to the fact that the example code leveraging `graph.sources()`, despite technically working as a dynamic way to template model code, results in missing lineage because the DAG is not properly constructed at parse time?

<img width="1412" alt="Screen Shot 2021-02-11 at 11 57 02 AM" src="https://user-images.githubusercontent.com/13897643/107627960-4417c200-6c60-11eb-88d8-9c8c714c2024.png">

<img width="1394" alt="Screen Shot 2021-02-11 at 11 56 25 AM" src="https://user-images.githubusercontent.com/13897643/107628127-7c1f0500-6c60-11eb-8b0d-96d6e0fcb8e0.png">

If so, you're right! And it's plausible that, by intentionally placing the parsing of sources and the construction of `manifest.sources` prior to the parsing of any models, we might be able to resolve this issue. As you say, that still treats `sources` as a special case. From another angle, this is a form of dynamic node referencing, in the same vein as a more generic (and very popular) proposal for dynamic `ref`s (#1212).

In either case, this is something I'm interested in eventually supporting. It's not something we can prioritize today. Happy to keep this issue open for folks who are pushing on the limits of what's possible with the `graph` object.

**Comment by Gregory108** [comment]
My take on this problem, based on [How to](https://discourse.getdbt.com/t/unioning-identically-structured-data-sources/921)

```
{%- set suffixes= [
    '_suffix_A',
    '_suffix_B', 
    '_suffix_C', 
    ] 
-%}

{% set list_of_sourcer= [] %}
{% for suffix in suffixes %}
    {%- do list_of_sourcer.append(source('root_' ~ suffix , 'table_name')) -%}
{% endfor %}

{{- dbt_utils.union_relations(
list_of_sources,
column_override={'id': 'string'}
)
-}}
```

This allows me to get DAG from sources with some minimal hardcode. Any other solution is not compatible with dbt core (versions users 19-21) because of manifest and resources compilation sequence.
