### ISSUE TITLE
dbt run execution time

### ISSUE THREAD

**Issue by tcboles** [dbt-labs/dbt-core#3115]
### Describe the bug
I have a model that when I run by itself completes in less than 5 seconds. But when I run the model with the entire pipelien or even dbt run -m model_name, it takes an outrageous amount of time. 

My first thought was that the 5 seconds was due to the model being a view or looking at views. However this pipelien is completely made up of tables. 

What could be causing this?

### Steps To Reproduce
dbt run -m model name (completes in 5 seconds)
dbt run -m +model_name (completes in 1000 seconds)

### Expected behavior
dbt run -m +model_name (completes in 5 seconds)

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.0
   latest version: 0.19.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.17.0
  - snowflake: 0.17.0
  - redshift: 0.17.0
  - postgres: 0.17.0
```

**The operating system you're using:**
Mac OSX
**The output of `python --version`:**
Python 3.9.0

**Comment by jtcohen6** [comment]
Hey @tcboles, it's hard to know what's going on here! How many models run when you select `+model_name`? Is the 1000 seconds spent running all of those various models? Or does dbt seem to be getting stuck somewhere along the way, perhaps due to a lock on one of the tables it's trying to replace?

As a next step to debug this, could you include the debug-level log output (`logs/dbt.log`) from both runs? Of course, please scrub any sensitive information, I'm mostly curious to see where the big jump in timestamps happens.
