### ISSUE TITLE
IAM Authentication for Aurora Postgres RDS

### ISSUE THREAD

**Issue by rajeshmese** [dbt-labs/dbt-core#3122]
Is there any way to implement IAM Based authentication in DBT for Aurora PostgreSQL?

**Comment by jtcohen6** [comment]
Hey @rajeshmese! Both dbt-postgres and dbt-redshift build connections using psycopg2, and the latter inherits much of its base functionality from the former, with a few additions for things like IAM-based authentication. It sounds like you'd want that functionality pushed upstream into the dbt-postgres adapter as well.

Here's where dbt-postgres builds a basic psycopg2 connection:

https://github.com/fishtown-analytics/dbt/blob/344a14416d22f0cfbeb56b9904092c8a4f38b1fc/plugins/postgres/dbt/adapters/postgres/connections.py#L97-L104

In dbt-redshift, if `method == 'iam'`, then `boto3` is used to grab temporary credentials and pass them into the psycopg2 connection string:

https://github.com/fishtown-analytics/dbt/blob/344a14416d22f0cfbeb56b9904092c8a4f38b1fc/plugins/redshift/dbt/adapters/redshift/connections.py#L167-L169

https://github.com/fishtown-analytics/dbt/blob/344a14416d22f0cfbeb56b9904092c8a4f38b1fc/plugins/redshift/dbt/adapters/redshift/connections.py#L100-L109

https://github.com/fishtown-analytics/dbt/blob/344a14416d22f0cfbeb56b9904092c8a4f38b1fc/plugins/redshift/dbt/adapters/redshift/connections.py#L148-L150

So I think a lot of the code for this already exists, it's just in the dbt-redshift adapter instead of the dbt-postgres adapter, where you'd need it to be for Aurora PostgreSQL. Is this a change you'd be interested in contributing?
