### ISSUE TITLE
Unique Test Column in the console is returning a different value than when running the compiled test in the BigQuery CLI

### ISSUE THREAD

**Issue by tconticello** [dbt-labs/dbt-core#3125]
### Describe the bug
I have a Unique test setup on a stg model. When running the test in dbt console is saying that column is not unique. Got 16 Results.
But when running the compiled test into bigquery is returning 12 records instead of 16. 
I'm curious why the difference between 12 and 16.

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<**0.18.1**>
```

**The operating system you're using:**
Windows
**The output of `python --version`:**
**Python 3.7.1**

**Comment by jtcohen6** [comment]
Hey @tconticello, it's hard to know what's going on here without a lot more context!

Could you check the compiled SQL (either from `target/compiled` or `logs/dbt.log`) to ensure that the unique test is running the same SQL both times?

Is it possible that you're using a different target schema name between local development and the dbt Cloud IDE (?) console?

Unless we can fully understand and reproduce this discrepancy, and do so in a way that goes against expected behavior, it doesn't sound like this is a bug with dbt.
