### ISSUE TITLE
Refactor `use_profile`

### ISSUE THREAD

**Issue by JCZuurmond** [dbt-labs/dbt-core#3193]
During my work on pr #3176 (@jtcohen6 and @kwigley) I broke my head over the `use_profile` decorator. As I understand it does two things:

1. Set a [pytest mark](https://docs.pytest.org/en/stable/mark.html)
2. Test if the test name contains one of the profiles as defined [here](https://github.com/fishtown-analytics/dbt/blob/77c10713a325d2bee91d1822951ce5d91ccc3278/test/integration/base.py#L84). This happens in the [`_profile_from_test_name`](https://github.com/fishtown-analytics/dbt/blob/77c10713a325d2bee91d1822951ce5d91ccc3278/test/integration/base.py#L1195)

IMHO both are unexpected, especially if you are new to `dbt`. What is the goal of this decorator?

My assumption is that we intend to do two things:
1. Limit the allowed markers. Pytest has functionality to do this in the [pytest.ini](https://docs.pytest.org/en/stable/mark.html#raising-errors-on-unknown-marks).
2. Restrict naming functions -> if you have the mark `profile_postgres` you must have `postgres` in your name. Why do we want this? I think this is not needed, if we want it we could write a test for this.

I think this would allow us to replace `use_profile(<profile name>)` with `@pytest.mark.profile_<profile name>`, which is easier to understand

**Comment by jtcohen6** [comment]
@JCZuurmond Thanks for opening this, and sharing your thoughts! I appreciate the time you've spent diving into  dbt's testing patterns, and the subsequent befuddlement.

Today, dbt integration tests use the `@use_profile` decorator to specify which databases/adapters a given test should actually run against, and we invoke the test using marks like `profile_postgres` and `profile_snowflake`. It sounds like you have a lot of prior experience using `pytest`, and would prefer if dbt did _less_ special "wrapping" around builtin `pytest` constructs, and instead exposed them more explicitly. Does that sound right?

I think dbt contributors tend to be a mix of folks with plenty of prior python experience, prior OSS contributing experience, and none of either. In abstract, I like the idea of being less "special," where possible, so that folks can benefit from the vast trove of python/pytest documentation online.

**Comment by JCZuurmond** [comment]
Yes, you said it perfectly. I think we - the dbt project - would benefit from `less special wrapping around builtin pytest` as it is easier for new contributors to understand what is happening.

I myself was bent over the "random" assert error, I did not easily make the link between the `use_profile` decorator and my test name (not having the mentioned profile).
