### ISSUE TITLE
`dbt clean` fails to remove parent directories of packages with folder hierarchies

### ISSUE THREAD

**Issue by sgoley** [dbt-labs/dbt-core#3380]
### Describe the bug
`dbt clean` does not remove empty directories or "top level" package directories.

### Steps To Reproduce
First, install any package from the hub which utilizes a nested directory within dbt_modules. Example: [fivetran_asana](https://hub.getdbt.com/fivetran/asana/latest/)
Then, run the `dbt clean` command to remove the installation. 
After which, any dbt command will fail because a directory exists in "dbt_modules" which is empty and does not contain a dbt_project.yml file.

### Expected behavior
`dbt clean` should remove not only the "fivetran_asana" module directory, but also its parent the "fivetran_utils" directory.

### Console output:
```
Running with dbt=0.19.1
Encountered an error:
Runtime Error
  Failed to read package: Runtime Error
    no dbt_project.yml found at expected path \user\my_dbt_project\dbt_modules\fivetran_utils\dbt_project.yml

Error encountered in  \user\my_dbt_project\dbt_modules\fivetran_utils
```

### System information
**Which database are you using dbt with?**

Irrelevant, applies to all. 

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - bigquery: 0.19.1     
  - postgres: 0.19.1     
  - redshift: 0.19.1     
  - snowflake: 0.19.1  
```

**The operating system you're using:**
Windows 10

**The output of `python --version`:**
Python 3.7.9

**Comment by jtcohen6** [comment]
@sgoley You're right! While I'm not able to reproduce this behavior on my work mac, I _was_ able to reproduce it on a personal Windows machine. In particular, I see that almost everything was removed from `dbt_modules`, but `dbt_modules\fivetran_utils\.git` remains.

When I try to remove those files by manually running [`shutils.rmtree`](https://docs.python.org/3/library/shutil.html#shutil.rmtree), I get a permissions error:
```
PermissionError: [WinError 5] Access is defined: 'dbt_modules\\fivetran_utils\\.git\\objects\\01\\db863e485a247c87fcad441274e808250a7ce1`
```
In our code, we set `ignore_errors=True`, so the error is hidden:

https://github.com/fishtown-analytics/dbt/blob/7418f36932bc0e223c61c5af17c930ce62675c5f/core/dbt/task/clean.py#L39

I'm hardly an expert in Windows file systems, so I'm not sure what the right solution here is. I believe the reason for `fivetran_utils` having a `.git` folder included is because it's a [`git`-type dependency](https://github.com/fivetran/dbt_asana_source/blob/f22c52b5e8196dd8a27764bdec9bf0108b330015/packages.yml#L5-L6) (downloaded directly from a git URL), rather than a `package`-type dependency (downloaded from hub site). If Fivetran were to put `fivetran_utils` on the hub site, and specify it as a `package` instead, that would resolve the immediate problem. But it still wouldn't solve the larger issue: `dbt deps` for `git`-type dependencies includes `.git` files that `dbt clean` does not have sufficient permission to remove.

Does anyone with more git + Windows experience want to offer a suggestion?
