### ISSUE TITLE
[CT-172] `--quiet` flag for run-operations

### ISSUE THREAD

**Issue by jaypeedevlin** [dbt-labs/dbt-core#3451]
### Describe the feature
Currently, when you run `run-operation` you get the output of your macro _after_ a few lines of text, for example:

```
Running with dbt=0.19.1
[WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- seeds
- snapshots

{macro output here}
```

I'm proposing a `--quiet` flag for `run-operation` that would remove the `Running with dbt` and any other warnings, leaving just the output of the macro.

### Describe alternatives you've considered
I've previously wrapped calls to `run-operation` in bash script which trims the first line from the output, however when warnings are triggered (like the example above) it's hard to tell in advance how many lines to trim.

### Who will this benefit?
Anyone who uses the codegen macro (and similar macros) outside of dbt cloud

### Are you interested in contributing this feature?
Yes — I've poked around the logger code but couldn't see a straightforward way of doing this, but I'm open to trying with some input!

**Comment by jtcohen6** [comment]
@jaypeedevlin This makes sense to me. I know this has been a challenge when using the codegen package in particular, and I feel more comfortable with this answer than with Jinja-based file generation (#3428).

It sounds like the ask is: Everything info-level that would normally log to stdout, should be ignored in stdout and log to `logs/dbt.log` instead, **except** for user-defined Jinja macros that call `{{ log(..., info = true) }}`. Does that sound right to you?

I don't know exactly how this ought to work, beyond that it will require some changes to [`core/dbt/logger.py`](https://github.com/fishtown-analytics/dbt/blob/develop/core/dbt/logger.py). Here's one idea, which may be over-engineering it:

- We define a custom [logging level](https://docs.python.org/3/library/logging.html#logging-levels), `LOUD (35)`, that's between `WARNING` and `ERROR`. (I understand it [can be tricky](https://stackoverflow.com/questions/2183233/how-to-add-a-custom-loglevel-to-pythons-logging-facility) to define custom logging levels, so that may be easier said than done.)
- When the `--quiet` flag is passed, the [output log level](https://github.com/fishtown-analytics/dbt/blob/14507a283e6acd710363aab9fc8fbcac1658002d/core/dbt/logger.py#L135) is set to `LOUD (35)` instead of `INFO (10)`. Any errors or critical messages (>35) will still print to stdout, but any warnings or info messages (including `logger.info`) will not.
- When the `--quiet` flag is passed, the Jinja `log()` context method (defined below) should use `logger.loud()` instead of `logger.info()`, so that its messages still land in stdout:

https://github.com/fishtown-analytics/dbt/blob/14507a283e6acd710363aab9fc8fbcac1658002d/core/dbt/context/base.py#L430-L449

That's just one idea. I'd curious to hear from other members of the Core team, who likely have better ones.

**Comment by jtcohen6** [comment]
This is significantly easier than previously I thought, since I realized we already do it for `list`:

https://github.com/dbt-labs/dbt/blob/b9d5123aa37786425f7429c91f4513839eea6a65/core/dbt/logger.py#L506-L510

If the `--quiet` flag is passed, the `run-operation` task need only include code like:

https://github.com/dbt-labs/dbt/blob/b9d5123aa37786425f7429c91f4513839eea6a65/core/dbt/task/list.py#L59-L63

Going to call this one a good first issue!

**Comment by jtcohen6** [comment]
@jaypeedevlin I definitely see merit in that argument. Some run-operations are more like quasi-tasks (thinking about `redshift.vacuum` or `dbt_external_tables.stage_external_sources`), where it might be nice to include prefatory matter like the dbt version, but I don't think there's any functional reason it needs to be there—whereas piping stdout to jq/file/etc represents a real functional gain.

All in all, the code in `list` can serve as a model here, though it's not going to be an exact replica of what we're after. Deprecations and other warnings still show up if `_output_handler.level = logbook.WARNING `. So I think something like my thought above, defining a `LOUD` level between `WARNING` and `ERROR`, will still be necessary. The most important thing will be finding a way to treat user-supplied, Jinja-defined info logging as "loud." This won't accomplish its goal if it swallows _all_ log output.

**Comment by vergenzt** [comment]
Is there a reason why dbt log messages go to stdout by default instead of always to stderr?

The convention I'd expect from a shell utility command is for "log" messages to always go to stderr and for there to be a separate call used to explicitly write to stdout (maybe `print`?). You could even limit the `print` function to only be in the Jinja context during a `run-operation` command, since it seems like it'd be a bit weird to be allowed to "print" anything during a dbt model or test run.

**Comment by jtcohen6** [comment]
@vergenzt That's effectively the function of `log.info`—things that dbt wants to print to stdout. By routing everything through a centralized logger, , something like this (and https://github.com/dbt-labs/dbt/issues/3440) is more possible.

One complication to my proposal above: [`logbook` doesn't support custom log levels](https://logbook.readthedocs.io/en/stable/designdefense.html#no-custom-log-levels), but it does support custom log _processors_. That's a decidedly better way to go about this, by tagging user-supplied Jinja `log` input with a tag that allows it to go through, while suppressing all other logging.

**Comment by jaypeedevlin** [comment]
Commenting to leave this open, I'd like to take a pass at this in the new year.

**Comment by jtcohen6** [comment]
Since we reworked logging in v1, most of my comments above are no longer relevant! In fact, I'm hopeful it will be much easier to plumb through the logic that sets log levels

**Comment by jtcohen6** [comment]
@jaypeedevlin @ehmartens Hooray!

I do think this will be significantly easier in the new logging system, which [has a README](https://github.com/dbt-labs/dbt-core/blob/c43c79a9954f9a7c19b1933e6ad4d251a5e21212/core/dbt/events/README.md) :)

It should give us much more flexibility than with the old system, such that we should also be able to find a better way than how the `list` task has done this in the past. I think we can piggy-back off the approach @emmyoop took for `--log-cache-events` over in #4369. If she's down to help, she could probably advise on an even better approach.

Here's what I'm thinking:
- A new flag in `main.py` + `flags`, `--quiet` (following the example of `--debug` or `--log-cache-events`)
- A new [base event type](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/base_types.py) (= a new class) named `Loud()`
- The event type [`MacroEventInfo`](https://github.com/dbt-labs/dbt-core/blob/f3c7b6bfd158df9cda3077a090f430fb9cd6e147/core/dbt/events/types.py#L383-L389) adds a subclass of `Loud`
- When `flags.QUIET`, the `fire_event` function should eat all stdout logs, unless they're `isinstance(e, Loud)` or `e.level_tag() == 'error'` — I wonder if that can happen in [the same spot](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/functions.py#L350-L353) where it checks the `--debug` flag and eats debug-level logs?

I took a quick crack at that, and ended up with:
```
$ dbt run-operation let_the_macro_do_the_talking
13:28:07  Running with dbt=1.0.1
13:28:07  [WARNING]: Deprecated functionality
The `source-paths` config has been renamed to `model-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
13:28:07  [WARNING]: Deprecated functionality
The `data-paths` config has been renamed to `seed-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
13:28:07  This is my custom log message! Wahoo!
```
```
$ dbt --quiet run-operation let_the_macro_do_the_talking
13:28:29  This is my custom log message! Wahoo!
```

Note this will include _all_ info-level log events fired via the dbt-Jinja `{{ log() }}` macro — including any fired from materializations, global macros, etc. We struck up an issue to think about ways to offer more power + precision to user-space logging: https://github.com/dbt-labs/dbt-core/issues/4184

**Comment by emmyoop** [comment]
It's exciting just how much easier this is with the new logging system!

This approach seems spot on but happy to help out if there are any more questions.  

Small note: I don't love the class name of `Loud`.  It seems counterintuitive that when you flag for `quiet` the `Loud` class is all that's written out.  But I could be convinced otherwise.

**Comment by jtcohen6** [comment]
> Small note: I don't love the class name of `Loud`. It seems counterintuitive that when you flag for `quiet` the `Loud` class is all that's written out. But I could be convinced otherwise.

Heh, super legit note - I was having a bit too much fun on a Friday. (`NotQuiet`, `CannotBeSilenced`, ...?)

**Comment by emmyoop** [comment]
After giving this a bit more thought I'm thinking we may want to go down the path of a new log level.  I'd like to think through the implications of it a bit more before saying we should definitely go that route.  But wanted to put a note here so @jaypeedevlin and @ehmartens don't start down the `Loud` path unnecessarily (yet).

**Comment by emmyoop** [comment]
@jaypeedevlin and @ehmartens the team and I have come up with an even more robust solution that will fix a few different situations.  While my previous solution would work, this is better long term.  #4687 recently requested the ability to silence logs to stdout as well.

The general solution is two fold.  

**First**, add a flag `--quiet` whose sole purpose is to silence logs to stdout.  This will be a global flag that is added to `flags.py` and `main.py` (following the example of --debug or --log-cache-events).  In this new context where it's only purpose is to not log anything to stdout, `--quiet` makes more sense as the flag name.

No new event base classes need to be created with this route either.  We can leverage the already existing [`NoStdOut`](https://github.com/dbt-labs/dbt-core/blob/2d0b975b6c2023cde219f0a045709a1fa5c6c840/core/dbt/events/base_types.py#L112).  

You will need to modify the below code to swallow the log for `flags.QUIET` as we do for `flags.DEBUG` on line 352.
https://github.com/dbt-labs/dbt-core/blob/2d0b975b6c2023cde219f0a045709a1fa5c6c840/core/dbt/events/functions.py#L349-L367

**Second**, let's add a `{{ print() }}` function to macros!  It will be very similar to `{{ log() }}`.  The difference being that `print` is not a log statement, it will just print to stdout.

To do this, you can copy the approach we have for log.  It should always just print to stdout.

https://github.com/dbt-labs/dbt-core/blob/2d0b975b6c2023cde219f0a045709a1fa5c6c840/core/dbt/context/base.py#L475-L494

These two changes (and a change to `codegen` to use this new `print` statement) would result in `dbt --quiet run-operation my_macro` to print to stdout any `print` statements in `my_macro` but no logs.  Logs would however still be written to the file.

**Comment by emmyoop** [comment]
Flagging @joellabes so he's aware we're going to add a `print` statement to macros that will allow printing to stdout, unrelated to logging.

**Comment by joellabes** [comment]
Thank you!
