### ISSUE TITLE
Problems of table names conversion by dbt

### ISSUE THREAD

**Issue by cyang110** [dbt-labs/dbt-core#3453]
I use dbt snapshot and dbt models to create tables, and use tableau to visualize the data. I use SQL server as database. The problem is after some hours, the table name will automatically change to schema.tablename_dbt_backup and schema.tablename_ dbt_tmp. snapshots and models run normally and create tables with no problem. But every day at some point dbt renames tables and appends “dbt_temp” or “dbt_backup” at the end of the table name,and that messes up our BI because it is looking for a table that no longer exists. Anyone knows why this happens and how to solve it? Really appreciate the help.

for example, after running dbt, I can get cyang110.student table. After several hours, it becomes cyang110.student_dbt_backup and cyang110.student_dbt_tmp.

**Comment by jtcohen6** [comment]
Hi @cyang110, this is meant to be a feature, not a bug. The goal of `dbt run` is to refresh your table and view models in an atomic operation, so that if any one step goes wrong (SQL syntax error, or for any other reason), the operation can be rolled back and the preexisting version of those models left in place.

When `dbt run` goes to replace a table model that already exists, in order to replace it atomically on databases that don't support `create or replace table` DDL statements, dbt's [table materialization](https://github.com/fishtown-analytics/dbt/blob/develop/core/dbt/include/global_project/macros/materializations/table/table.sql):
- starts a transaction
- creates the new version of the table in a temporary location (suffixed `__dbt_tmp `)
- renames the existing version of the table to be the backup version (suffixed `__dbt_backup`)
- renames the new version of the table (`__dbt_tmp` &rarr; no suffix)
- commits the transaction
- drops the old/backup version (on many databases, drops need to happen outside of transactions)

Because all renaming happens within a transaction, there should be no time delay (sub-second at most) where the old and new versions of the table are swapped. At any point, if any step fails, dbt rolls back the transaction. Your BI tool doesn't need to know the difference: it's just selecting from `cyang110.student` all the way through.

Given your report that:

> After several hours, it becomes cyang110.student_dbt_backup and cyang110.student_dbt_tmp.

It sounds like the final renaming step, to transfer `student_dbt_tmp` --> `student`, isn't succeeding, and yet the overall transaction is still committing. At this point, I'm not sure why that's occurring; it may be a bug with the table materialization, or in its interaction with the dbt + SQLServer plugin. With that, could you report back:

- Which dbt + SQLServer plugin are you using? Is it [`dbt-sqlserver`](https://github.com/dbt-msft/dbt-sqlserver)?
- What versions of dbt-core + plugin are you using? You can find this by running `dbt --version`

**Comment by ckdake** [comment]
For anyone digging into this in the future, the "table materialization" link above has moved to: https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/models/table/table.sql
