### ISSUE TITLE
Address issue with python3.9 unit testing and turn on by default

### ISSUE THREAD

**Issue by kwigley** [dbt-labs/dbt-core#3689]
### Describe the bug
Unit test run as expected for all python versions except 3.9. We should understand why these tests fail, implement fix, and turn on 3.9 tests.

### Steps To Reproduce
run unit test with python3.9

### Screenshots and log output
```console
test/unit/utils.py:356: in load_internal_manifest_macros
    return ManifestLoader.load_macros(config, macro_hook)
core/dbt/parser/manifest.py:635: in load_macros
    macro_manifest = loader.create_macro_manifest()
core/dbt/parser/manifest.py:606: in create_macro_manifest
    for path in macro_parser.get_paths():
-----
    def get_paths(self) -> List[FilePath]:
>       return list(FilesystemSearcher(
            project=self.project,
            relative_dirs=self.project.macro_paths,
            extension='.sql',
        ))
E       TypeError: object.__new__() takes exactly one argument (the type to instantiate)

core/dbt/parser/macros.py:21: TypeError
```

### Additional context
I believe this is related to how we mock FilesystemSearcher in other tests? I found that debugging this issue is quite hard. I'll continue to put comments on this issue if I find more info.

**Comment by gshank** [comment]
I had this same error but it went away after bringing up the docker database and running integration tests. My guess is that it has something to do with creating the adapter singleton, though you wouldn't think so from the test output. But an internet search shows at least a few people running into the same error trying to instantiate a singleton. The FilesystemSearcher class clearly has 3 arguments so that's not a strong candidate for this error.

**Comment by gshank** [comment]
Or it could be something to do with inheriting from Iterable

**Comment by gshank** [comment]
It was a mock in test_graph.py
