### ISSUE TITLE
dbt debug avoid dependency checking 

### ISSUE THREAD

**Issue by leoch20** [dbt-labs/dbt-core#3735]
### Describe the feature
We deployed dbt in AWS managed Airflow MWAA. Currently we perform some system checks to ensure the deployment is successful. Among them is `dbt debug` . The issue is that **git** is not install in MWAA and there is no reason to install it (please correct me if there is a need to have it). Because git is not install, every time we run the system checks `dbt debug` fails. 

It would be great if we could manually bypass checking the dependencies so that if debug fails we know it is not because of missing git.

**Comment by jtcohen6** [comment]
@leoch20 Thanks for opening! Honestly, I'm of two minds about this one.

On the one hand, you're completely right that it's possible to use dbt _without_ having git installed, assuming you don't need to install any `git`-based packages.

On the other hand, `dbt debug` is really intended as a helper check for CLI users who have installed dbt locally, to help them make sure they're ready to start up with dbt development—not a step in automated orchestration processes. I can appreciate that, if something is going to fail in Airflow (e.g. a faulty database connection), it's nicer to fail with the clear error early on, rather than a slightly more-buried error during the early steps of a run. But it's going to fail either way.

(I could imagine a local user who doesn't want to have `git` installed, but that seems much less likely.)

Having said all that, the codepath here is quite straightforward:
https://github.com/dbt-labs/dbt/blob/d2dbe6afe4ecff25e4fa8ba471716bc8bd0ef760/core/dbt/task/debug.py#L124-L126

I don't think it would be a big lift to add [debug task flags](https://github.com/dbt-labs/dbt/blob/d2dbe6afe4ecff25e4fa8ba471716bc8bd0ef760/core/dbt/task/debug.py#L124-L126) like:
```
dbt debug --skip-configuration
dbt debug --skip-dependencies
dbt debug --skip-connection
```
And check before running each check:
```python
    if not self.args.skip_configuration:
        self.test_configuration()
    if not self.args.skip_dependencies:
        self.test_dependencies()
    if not self.args.skip_connection:
        self.test_connection()
```
So, if this is something you'd like to open a PR for, I'd be happy to review it.
