### ISSUE TITLE
Start measuring test coverage

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#3748]

**Comment by kwigley** [comment]
Quick personal take: https://about.codecov.io/ is perfect for this, because out how automated testing is organized, there are multiple tests runs testing different OS, python version, and warehouse adapters. With codecov, you can fire off the coverage report for different test runs in the same workflow and it will combine the reports server side. It also allows us to turn on checks to unsure that there is test coverage for code added in PRs to ensure _new_ code is covered by tests. I like this vs. requiring a certain percentage of the codebase being covered by tests.
