### ISSUE TITLE
Deferring "previous state" of incremental model instead of full refresh

### ISSUE THREAD

**Issue by tmshn** [dbt-labs/dbt-core#3761]
### Describe the feature

When running dbt in a sandbox environment with `state:modified+`, a referenced (but not selected) models are deferred to production environment, which is good for sliming CI as described in [the dbt Cloud docs](https://docs.getdbt.com/docs/dbt-cloud/using-dbt-cloud/cloud-enabling-continuous-integration-with-github#slim-ci).

```sh
dbt run --models state:modified+ --state target_prd --defer --target sandbox
```

However, selected models are ran in a usual manner; if the table does not exist in the sandboxed environment, it builds the model from scratch (i.e.: full refresh), even for incremental models.

It would be much more efficient if dbt copies production tables into sandboxed environment before it runs incremental updates, as full rebuild of incremental model is usually very heavy.

### Describe alternatives you've considered

Manually coping tables beforehand like

```sh
dbt ls --models state:modified,config.materialized:incremental --state target_prev --output name \
| xargs -I{} bq cp -f "${production_scheme}.{}" "${sandboxed_scheme}.{}"
```

### Additional context

I personally have BigQuery in my mind, but believe it's quite backend agnostic topic.

### Who will this benefit?

Whoever running sandboxed test on CI, both dbt Cloud user and dbt CLI user (I'm the latter).

### Are you interested in contributing this feature?

Yes for BigQuery, but not for other database types

**Comment by jtcohen6** [comment]
@tmshn Thanks for the thoughtful issue!

### Changes to `--defer`

We know that the version of `--defer` which exists today is, in many senses, the simplest and most limited version of how to treat unbuilt upstream resources. There's some good discussion about this over in https://github.com/dbt-labs/dbt/issues/2968. I could imagine expanding deferral functionality to support a few different modes:
- rewriting refs (current implementation)
- clone/copy (Snowflake/BigQuery)
- pointer views (just `select * from prod_version`)

The big appeal of the second and third options is that unbuilt relations still exist in your CI schema, allowing you to hook up your schema to a BI tool or report. Only the second option _really_ supports incremental models in the way you've envisioned, and it's constrained by the disparate implementations across databases.

### Or, a `clone_schema` macro?

Even then, that isn't _exactly_ the purpose served by `--defer` (or whatever future name / expanded functionality it takes on), since an incremental model both wants to be copied _and_ run. So this feels less like an adaptation to `--defer`, and more like providing a `clone_schema` macro that can be run as an operation.

Snowflake's implementation feels most intuitive and most powerful: you can simply [create clones](https://docs.snowflake.com/en/sql-reference/sql/create-clone.html) of every view, table, etc in your production schema, without incurring the storage or compute costs associated with instantiating actual copies. That sets the high water mark, and `snowflake__clone_schema` would simply template out `create schema ... clone`.

BigQuery's approach is, to my mind, a bit trickier: costless table copying is compelling, but there's no `COPY` DDL command, only a `bq` command / python API method. That's what you're hinting at here:

> ```
> bq cp -f "${production_scheme}.{}" "${sandboxed_scheme}.{}"
> ```

`dbt-bigquery` does wrap that capability in a method, [`adapter.copy_table`](https://github.com/dbt-labs/dbt/blob/2980cd17df52714d44c65d38a9f684b76a63af34/plugins/bigquery/dbt/adapters/bigquery/impl.py#L432-L447), that's available to the Jinja context; it forms the basis of the (undocumented) [`copy` materialization](https://github.com/dbt-labs/dbt/blob/develop/plugins/bigquery/dbt/include/bigquery/macros/materializations/copy.sql). (There are some proposed improvements in the works, over in #3606.)

In order to achieve feature parity here, I think `bigquery__clone_schema` would need to:
- Run `copy_table` for every table + incremental model in the project (perhaps via a `run-operation`)
- Select + run all view models in the project: `dbt run -m config.materialized:view`

Then you'd be ready to `dbt run --models state:modified+ --state target_prd --defer --target sandbox`, and have the incremental models build atop most recent data.

### Alternative approach

That feels complex! It's probably worth the trouble, in some cases. For my part, I find the best success with the following pattern:
1. Use env-specific logic in big incremental models to limit their data volume in dev/CI, following [this example](https://docs.getdbt.com/reference/dbt-jinja-functions/target#use-targetname-to-limit-data-in-dev):
```sql
select
  *
from source('web_events', 'page_views')
{% if target.name in ('dev', 'ci') %}
where created_at >= dateadd('day', -3, current_date)
{% endif %}
```
2. Rebuild incremental models twice (once full-refresh, once partial-refresh) to test both logical branches
```
dbt run -m state:modified --full-refresh
dbt run -m state:modified,config.materialized:incremental
```

What do you think? To me, the ask feels feels like a change to `--defer` functionality, and more like a useful macro to enable "cloning" on BigQuery, as a step prior to deferral + state comparison.

**Comment by tmshn** [comment]
Thank you for the detailed explanation.

> ### Alternative approach

First, I don't like the approach due to its nature of incompleteness. That might not matter on development stage, but what's in mind is CI stage, which is the (almost) last gate before production. Tests like `is_unique` should be run on complete table.

In addition to that, it requires an extra care to model developer of both the target and its downstreams (note: most of model developers in my organization aren't well-trained engineer; they're just data analyst who can write SQL).

> ### Changes to `--defer`
> ### Or, a `clone_schema` macro?

Yes, these sounds like a solution fits to my use case.

The point is: incremental models need to be both copied _and_ run, as you mentioned, while others are not. And only target incremental models. It's optimal if unnecessary copy does not run (while I know it increases complexity...).

| | table, view | incremental |
|:---|:---|:---|
| target (and its downstream) | just run | **_copied and run_** |
| non target | refer to prod scheme | refer to prod scheme | 

> Then you'd be ready to `dbt run --models state:modified+ --state target_prd --defer --target sandbox`, and have the incremental models build atop most recent data.

If your approach is adopted, maybe we don't need `--defer` option since the tables is already "deferred" (means "cloned" here)?

**Comment by tmshn** [comment]
> but there's no `COPY` DDL command,

Regarding this point; I'v just found `CREATE TABLE COPY` DDL statement has released this August, so now you can copy table using SQL.

https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_copy

**Comment by jtcohen6** [comment]
@tmshn That's an incredible find!

**Comment by xemuliam** [comment]
@jtcohen6 TBH those are different approaches.
`create table copy` works with one and only source table.
Copy API can use several source tables to be copied into single target.
Thus ciopy API implementation is still very useful :)
