### ISSUE TITLE
Event-based dbt runs

### ISSUE THREAD

**Issue by aodhan-domhnaill** [dbt-labs/dbt-core#3887]
### Describe the feature

Based on configurable database events (eg. LISTEN/NOTIFY), execute `dbt run` for configurable models

### Describe alternatives you've considered

External python script that listens for events, but annoying to have to build this outside of dbt config.

### Who will this benefit?

Anyone with event based data flows.

### Are you interested in contributing this feature?

**Yes**. If you want this feature, please give guidance on how to best implement it. For example,

* Separate CLI command
* `run --daemon`
* Kinds of triggers you want
* etc.

**Comment by jtcohen6** [comment]
@aidan-plenert-macdonald Whoa, very interesting! Could you say more about... pretty much all of it?

> configurable database events (eg. LISTEN/NOTIFY)

I assume you're talking about [`LISTEN`](https://www.postgresql.org/docs/current/sql-listen.html) and [`NOTIFY`](https://www.postgresql.org/docs/current/sql-notify.html) in Postgres? Could you share more about the specific use case(s) you have in mind?

We've thought plenty about how tools deploying/orchestrating dbt Core ought to integrate with lifecycle events from complementary tooling: data ingestion ("the raw table has finished loading"), BI / reporting ("this model has finished running, refresh this dashboard's cache"). In almost all cases, we've talked about using restful APIs to power these integrations; _maybe_ dedicated messaging queues, though only if performance calls for it. I don't think we've ever considered baking the notifications directly into the data warehouse itself, to be placed down and picked up with pure SQL. (At least, pure non-ANSI PostgreSQL).

I think we'd need to change a _lot_ of the internal workings of dbt Core to make something like this possible. It's not possible today to compile a dbt Core project operation, such as `run`, to a python executable—let alone compiling it down to SQL "source code" or a stored procedure. At the same time, I'm open to learning more here. What would be required to trigger dbt Core invocations with in-database notifications? An always-on server, running a dbt Core invocation that's actually a _very_ long-lived query, holding open an indefinite `LISTEN` transaction, just waiting to trigger a `dbt run`?

**Comment by aidan-plenert-macdonald** [comment]
Most data pipelines I see run some kind of message queue, so I'd suggest two types of integrations.

One would be "upon getting a message from RabbitMQ/SNS/etc., run the incremental flow". Preferably avoiding "ingesting" the actual data, but just triggering an execution. This could also use LISTEN/NOTIFY in Postgres, but that's limited to only Postgres.

The second would be compiling a network of triggers that get installed into a DB so that after insert the data can flow downstream while staying within a database.

I think the second is more interesting personally because triggers in a DB have great potential for ETL pipelines, but they are painful to maintain and generate massive amounts of SQL.


This could be broken down into stages.

1. Set up LISTEN/NOTIFY support for executing a DBT workflow OUTSIDE of the DB (ie. the first approach)
2. Basic triggers in a DB send messages via NOTIFY to trigger downstream incremental builds
3. Migrate the materializing inside the triggers so that the events never leave the DB 

I like the vision that everything stay in the DB, but 1 and 2 are just to bridge that the gap.

Let me know what you think.
