### ISSUE TITLE
Split up integration tests per database adapter

### ISSUE THREAD

**Issue by kwigley** [dbt-labs/dbt-core#3923]
- Ignore tests in `test/rpc`

**Comment by jtcohen6** [comment]
This is done for Redshift, Snowflake, and BigQuery. Still left to do:
- Remove Presto tests (hah!) from `test/integration`
- Move the remainder of `test/integration` under `plugins/postgres/tests`...? I could go either way on this one. We're leaving the dbt-postgres codebase colocated with the dbt-core codebase because it's so essential to our testing today. At the same time, we should continue to aspire and work toward decoupling them more.

**Comment by jtcohen6** [comment]
This is done, enough to be serviceable for the time being. Our integration testing scaffolds badly need an overhaul. That's going to be a significant project for next year.
