### ISSUE TITLE
Overriding/Extending default adapters in dbt project

### ISSUE THREAD

**Issue by ismailsimsek** [dbt-labs/dbt-core#3962]
### Describe the feature
is it possible to override/extend current adapters with dbt project? if yes where is the correct location to add new adapter code? is there any custom adapter location similar to {`source-paths, analysis-paths, test-paths, data-paths, macro-paths,snapshot-paths`}?

is it possible to extend existing adapters without building new adapter plugin?
for-example:
```
class BigQueryAdapterCustomized(BigQueryAdapter):
....
def mynew_method(self)
```

### Who will this benefit?
such feature could add flexibility to dbt.

**Comment by jtcohen6** [comment]
@ismailsimsek It is possible to override, reimplement, or otherwise adapt any built-in dbt core or adapter code _written in Jinja_. It isn't possible today to implement any user-space code, in python, in your own project. This isn't a position I see us changing in the near future; we find it to be a valuable guardrail, from a security and complexity perspective.

Eventually, I do want to enable defining more python assets outside of the core codebase (e.g. custom tasks, https://github.com/dbt-labs/dbt/issues/2381), or reworking complex macros (i.e. materializations) in python to make unit testing them easier. Even then, I think that may look like installing an additional `dbt-` plugin, or a special kind of package. I'm not sure yet if it will be possible to write that python in your own project code.

I appreciate that this can be frustrating with dbt-bigquery in particular, since there's always more BigQuery functionality available from the python client vs. the StandardSQL "API." Out of curiosity, what's the specific functionality you're hoping to implement in dbt + BigQuery? We may already have a ticket for it, or could open a new one.

I'm going to close this issue for the time being, but happy to continue the conversation.

**Comment by ismailsimsek** [comment]
@jtcohen6 created discussion here https://github.com/dbt-labs/dbt-adapters/discussions/259
