### ISSUE TITLE
flake8: Undefined name 'source_file' in test_parse_manifest.py

### ISSUE THREAD

**Issue by cclauss** [dbt-labs/dbt-core#3994]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

$ `flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics`
```
./dbt/test/unit/test_parse_manifest.py:105:71: F821 undefined name 'source_file'
        self.parser.parse_file.assert_called_once_with(FileBlock(file=source_file))
                                                                      ^
1     F821 undefined name 'source_file'
1
```
### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

$ `flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics`

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by jtcohen6** [comment]
Thanks for the report @cclauss!

First: The specific test you're looking at, `test/unit/test_parse_manifest.py`, was rendered obsolete by our top-to-bottom partial parsing rework in v0.20:

https://github.com/dbt-labs/dbt/blob/3789acc5a7b3f71b4e333ac6e235c62ee0c957f5/test/unit/test_parse_manifest.py#L107-L108

@gshank Any reason why we shouldn't delete that file in its entirety?

Second: Today, we only run `flake8` on code that we package and distribute. Since we just moved several plugins out of this repo, that now looks like `core/dbt` and `plugins/postgres`:

https://github.com/dbt-labs/dbt/blob/3789acc5a7b3f71b4e333ac6e235c62ee0c957f5/tox.ini#L9-L11

I strongly agree that we should be writing high-quality, readable code for our unit and integration tests, and I think enforcing code style is a solid first step. I think we should first prioritize fixes to code checks on distributed code, however (e.g. #3203).

cc @leahwicz: Putting this on your radar re: improvements to our test suite

**Comment by cclauss** [comment]
> enforcing code style

flake8 F821 is not about code style, it is about program correctness.

* __F82__ tests are almost always _undefined names_ which are usually a sign of a typo, missing imports, using a variable before defining it, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python, a __NameError__ may be raised which will halt/crash the script on the user.

**Comment by gshank** [comment]
I think the comment about not making sense applied to the tests that I removed (test_model_no_cache, test_model_cache, test_model_cache_mismatch_checksum, test_model_cache_missing_file). The line referring to the source_file should be removed; that was an oversight.
