### ISSUE TITLE
Issue with snapshots compilation after upgrading to 0.21.0

### ISSUE THREAD

**Issue by andrewlee-trouva** [dbt-labs/dbt-core#4039]
### Describe the bug
I've just upgraded our dbt instance from 0.20 to 0.21, and tried to compile dbt locally to check for any issues. I received the following error:

```
Encountered an error:
Snapshots must be configured with a 'strategy', 'unique_key', and 'target_schema'.
```

This occurs despite all my snapshots (we have 8, a combination of timestamp and check_cols strategies) having `strategy`, `unique_key` and `target_schema` all declared in configs. 

### Steps To Reproduce
with a dbt instance at 0.20, with snapshots, using redshift, upgrade dbt-redshift to 0.21 and run `dbt ls` or `dbt compile`
 
### Expected behavior
dbt will output the above error

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.21.0
   latest version: 0.21.0

Up to date!

Plugins:
  - bigquery: 0.20.0
  - snowflake: 0.20.0
  - redshift: 0.21.0
  - postgres: 0.21.0
```

**The operating system you're using:**
Mac, Catalina version 10.15.7

**The output of `python --version`:**
```
Python 3.8.2
```

**Comment by andrewlee-trouva** [comment]
@jtcohen6 Very weird 🤔 , I'll try moving up to `3.8.9` and see that does, and I'll let you know what happens

**Comment by jtcohen6** [comment]
@gshank Would you expect to see this error if all snapshots define these configs via the in-file `config()` macro?

**Comment by andrewlee-trouva** [comment]
hey @jtcohen6, we don't define anything config wise in a yml, we leave it all in the `config()` macro. The only thing we have in our `dbt_project.yml` regarding macros is a couple pre/post hooks for logging and a call to our grant select macro on run start and end.

```on-run-start:
  - "{{ grant_select_on_schemas(schemas, 'system_users') }}"

on-run-end:
  - "{{ grant_select_on_schemas(schemas, 'analysts') }}"
  - "{{ grant_select_on_schemas(schemas, 'data_engineers') }}"
  - "{{ grant_select_on_schemas(schemas, 'system_users') }}"  


models:
  trouva:
      # Applies to all files under models/demo/
      demo:
          materialized: view
  pre-hook: "{{ logging.log_model_start_event() }}"
  post-hook: "{{ logging.log_model_end_event() }}"
```

**Comment by gshank** [comment]
We still haven't been able to recreate this. If somebody could boil this down to a minimal test case that would be a big help.

**Comment by thisiscab** [comment]
Hello, I am having the same issue with 

* Snowflake
* Also in a Docker Container

```
16:54:03  Running with dbt=1.0.1
dbt version: 1.0.1
python version: 3.8.12
python path: /usr/local/bin/python
os info: Linux-5.10.76-linuxkit-x86_64-with-glibc2.2.5
Using profiles.yml file at /root/.dbt/profiles.yml
Using dbt_project.yml file at /usr/src/dbt_project.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]

Required dependencies:
 - git [OK found]
```

The snapshot works for DBT `0.20.x` but it doesn't work for `0.21.x` and `1.0.x` 

I've removed all "snapshots" and it worked. When I add only one snapshot file that looks like this:

```
{% snapshot my_snapshot %}

{{
    config(
        unique_key='id',
        strategy='check',
        target_schema='snapshots',
        check_cols=['my_cols'],
    )
}}

select * from my_source

{% endsnapshot %}
```

It throws `Snapshots must be configured with a 'strategy', 'unique_key', and 'target_schema'`.

**Comment by ashlee3209** [comment]
Hi, we faced the similar issue after upgrading to 0.21.0 and I tried with 1.0.3 which seems still has the same error. 

It works ok if we only have config block in the sql file like 

```
{{
    config(
        target_database='dev',
        target_schema='snapshots',
        unique_key='contract_key',
        strategy='check',
        check_cols=['contract_id'],
)

}}
```

But when we add the property file with config:

```
- name: contract_snapshot
    description: This is a description that comes from dbt /snapshots/schema.yaml
    schema: snapshots
    meta:
      owner:
        - xxxx
    config:
      target_schema: snapshots
      unique_key: contract_key
      strategy: check
      check_cols: [ contract_id ]
    columns:
      - name: snapshot_date
      - description: xxx
```

It goes to the wrong schema (the default_schema) instead of target_schema "snapshots".
If we removed the config block in the property file and leave the rest fields in the file, It throws `Snapshots must be configured with a 'strategy', 'unique_key', and 'target_schema'.`

Any suggestion on how to fix this error? Is that a bit strange to mandatory have config in the property file if we already have config block in the sql file? And I do not know why it changes the schema if we have config in both places.

**Comment by ashlee3209** [comment]
Some update about our problem:
We added schema to the config in the property file, then it goes to the correct schema. So basically, we create a macro about generate_schema_name to differentiate model node and snapshot node, then it created snapshots using target_schema instead. But still I think it is a bit wired to make the config 'strategy', 'unique_key' and 'target_schema' mandatory if we use property file since we already have config block in the sql file.
