### ISSUE TITLE
[Feature] dbt should know about metrics

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-core#4071]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

dbt should know about *metrics*. A metric is a timeseries aggregation over a table that supports zero or more dimensions. Some examples of metrics include:

- active users
- churn rate
- mrr (monthly recurring revenue)

dbt should support metric definitions as a new node type. Like exposures, metrics participate in the dbt DAG and can be expressed in yaml files. By defining metrics in dbt projects, analytics engineers can encode crucial business logic in tested, version controlled code. Further, these metrics definitions can be exposed to downstream tooling to drive consistency and precision in metric reporting.

### The ecosystem

There is some prior art for defining metrics in dbt projects. In particular, see

- [The MetricQL implementation](https://metriql.com/reference/measure/) (using meta fields)
- [The Lightdash implementation](https://docs.lightdash.com/references/metrics) (using meta fields)

While these two implementations differ (measures vs. metrics), more on that below, there exists a need in the community for a first-class way to define these metrics in dbt code. It is really neat to see that some folks have already made these definitions possible with dbt, but it would better if metrics were treated as well-defined nodes with field validation and helpful utilities inside of dbt Core.

### Specification

A metric is a timeseries aggregation over a table that supports zero or more dimensions. These metrics can be encoded in schema.yml files. In the example below, a `new_customers` metric is defined as a count of customer records created in a given time grain.

```yaml
# models/marts/product/schema.yml

version: 2

models:
 - name: dim_customers
   ...

metrics:
  - name: new_customers
    label: New Customers
    model: dim_customers
    description: "The number of paid customers who are using the product"

    type: count
    sql: user_id # superflous here, but shown as an example

    timestamp: signup_date
    time_grains: [day, week, month]

    dimensions:
      - plan
      - country
    
    filters:
      - field: is_paying
        value: true

    meta: {}
```

Given this information, a downstream process (or a dbt macro!) can generate a sql SELECT statement that correctly calculates this metric with a specified time grain and set of dimensions. Here is a breakdown of supported fields:

| Field       | Description                                                 | Example                         | Required? |
|-------------|-------------------------------------------------------------|---------------------------------|-----------|
| name        | A unique identifier for the metric                          | new_customers                   | yes       |
| model       | The dbt model that powers this metric                       | dim_customers                   | yes       |
| label       | A short for name / label for the metric                     | New Customers                   | no        |
| description | Long form, human-readable description for the metric        | The number of customers who.... | no        |
| type        | The type of calculation to perform when evaluating a metric | count_distinct                  | yes       |
| sql         | The expression to aggregate/calculate over                  | user_id                         | yes       |
| timestamp   | The time-based component of the metric                      | signup_date                     | yes       |
| time_grains | One or more "grains" at which the metric can be evaluated   | [day, week, month]              | yes       |
| dimensions  | A list of dimensions to group or filter the metric by       | [plan, country]                 | no        |
| filters     | A list of filters to apply before calculating the metric    | See below                       | no        |
| meta        | Arbitrary key/value store                                   | {team: Finance}                 | no        |

**Model reference**

A reference to a dbt model. This model may be any "materialized" model, or a reference to an ephemeral model. Direct table references are not allowed, and alternate node types (seeds, snapshots) are not supported.

**Metric types**

The following metric types should be supported:

 - count
 - count_distinct
 - sum
 - average
 - min
 - max

In the future, alternative metric types (ratios, deltas, etc) should be supported in this model.

**Filters**

Filters should be defined as a list of dictionaries that define predicates for the metric. Filters are ANDed together. If more complex filtering is required, users can (and should) push that logic down into the underlying model.

```yaml
filters:
  - field: is_paying
    value: true
```

### Functional requirements

- Metrics should participate in the dbt DAG as a distinct node type
- Metric nodes should be accessible in the dbt Core compilation context via:
    - the `graph.metrics` variable
    - one or more accessor functions like `metrics.find_by_name('...')` (exact mechanism TBD)
- Metric nodes should be emitted into the `manifest.json` artifact
- Metrics should work with partial parsing
- Metric nodes should be supported in node selection and should be selectable with the `metric:` selector
    - When listing nodes, existing graph operators (`+`, `&`, etc) should be supported
- (in a different issue) Metrics should be surfaced in the dbt Docs website
    
dbt Core should not, itself, evaluate or calculate metrics. Instead, dbt Core should expose the definition of metrics to downstream tools or packages for evaluation and analysis. In this way, it is critical that dbt Core provides hooks into metrics that can be leveraged in both macro code, or by processes that consume dbt Core `manifest.json` files.

### Describe alternatives you've considered

**Don't implement metrics as distinct node types and keep encoding them in `meta` properties:**
- This information is untyped and semantically unrepresented in dbt, so it would be a net-improvement to instead create a first-class node type in dbt Core for these logical DAG nodes

**Metrics vs. Measures**

Metrics are strongly-typed objects. It is *extremely* common to see folks perform syntactically correct but semantically meaningless calculations over data. This looks like averaging an average, or adding two distinct counts together. You get a number back... but it's not a useful or meaningful result.

To that end, I think we should start with *metrics* instead of *measures*. The difference here (and maybe a strawperson of my own creation - tell me if you think so) is that measures are untyped aggregations, whereas metrics are rigorously defined summaries over well-defined datasets. The creation of *metrics* does not preclude us from teaching dbt about more generic types of aggregations in the future, but I'd prefer to start with a narrow set of functionality and expand over time. It is easy to remove constraints, but it is hard to add them 🙂

**Include support for joins**
- Joins make metric calculations _really_ complicated. dbt should absolutely know about foreign key relationships (outside of the existing `relationships` test) in the future, but this would be a meaningful expansion of scope for our first cut of this feature
- While these joins would be semantically useful, they are not a blocker to defining metrics today. Join logic can be pushed down into model code (whether materialized or ephemeral). We should experiment with this single table paradigm, see how it feels, and then consider the best approaching for teaching dbt about semantic joins in the future.

**Where metrics are defined**

Should metrics be a property of a model? While that could be functional today, I think this would make it hard to extend metrics to work with joins (see above). Instead, declaring metrics as independent nodes that participate in the DAG is a more future-proof idea, and we'd probably do well to avoid the "patching" flow required to get schema tests (properties of models today) translated into their own independent nodes in the DAG.

**Inheriting configuration from models**

Should metrics be namespaced under a model? This would make it possible to define some "shared" properties for all of the metrics derived from a model (eg. valid dimensions, the time field, supported time grain). This would be good for ergonomics, but not a *huge* value-add IMO. I'd like to keep this simple for the initial implementation and then make decisions like this with some more information from the community around example use-cases.

Example:

```yaml
metrics:
  - model: dim_customers
    # dimensions are shared for all metrics defined in terms of this model
    dimensions:
      - country
      - plan

    definitions:
      - name: new_customers
      - name: churned_customers
```

**SQL calculations in dimensions**

Should dimensions be allowed to provide arbitrary SQL expressions? I don't think so — that SQL is best encoded in model code, and it would be confusing and dissonant to break up dimension definitions across SQL and yaml files.

Example:

```yaml
metrics:
  - name: dim_customers

    # This logic should be represented in the underlying model
    dimensions:
      - field: plan_type
        sql: case when plan in ('pro', 'extra pro') then 'paid' else 'free' end
        
```

### Who will this benefit?

**Analytics engineers**
    - As with models, AEs will be able to define metric logic under version control. By colocating model and metric code, new metrics or changes to existing metrics can be made in a tested, versioned, documented, code reviewed environment
    - Further, dbt Core's built in lineage can surface information about how changes to an upstream model may impact a downstream metric

**BI/Analytics tooling (and therein, data consumers)**
    - Organizations use metrics to understand performance and make decisions. To that end, the correctness and precision of these metrics is really paramount! By defining metrics rigorously under version control, and then exposing their definitions globally, dbt Core can help ensure consistency in reporting.

**The data ecosystem**
    - There are *so many* tools, both existing and yet to be created, that can benefit from an open source mechanism for defining a semantic model on top of the data warehouse. I believe that this business logic is just too valuable and strategically important for end-users to be locked up in proprietary tooling. To that end, this feature, and future types of semantic logic like this, should be addressable in an open source way

### Are you interested in contributing this feature?

I sure am :)

### Anything else?

**From around the internet:**
- [https://basecase.vc/blog/headless-bi](https://basecase.vc/blog/headless-bi)
- [https://benn.substack.com/p/the-data-os](https://benn.substack.com/p/the-data-os)
- [https://benn.substack.com/p/metrics-layer](https://benn.substack.com/p/metrics-layer)

**Comment by owlas** [comment]
This is awesome! And completely agree that it'll be a huge boon to the community and tooling to move toward a standard. It's something we've been really excited about at Lightdash.

I think the proposal looks like a great direction overall, similar also to how metrics are specified in existing tools, adding to your list:
* CubeJS: https://cube.dev/docs/schema/reference/measures
* Looker: https://docs.looker.com/reference/field-reference/measure-type-reference

Some more detailed questions:

### Joins

Agreed these can get confusing. But they're also becoming less essential, we're seeing teams move to big wide tables (where all models are prejoined for a given analysis). So seems like a reasonable omission

### Time-dimension requirement (aka metrics vs measures)

I was interested to see that a time-dimension is a requirement, this excludes a lot of useful aggregates, for example:

* Which user has purchased the most products? (metric: count purchases, dimension: user id)
* What was the clickthrough rate on our most recent campaign (metric: click % rate, dimension: campaign name) 

Does this relate to your dimension of metrics vs measures:

> measures are untyped aggregations, whereas metrics are rigorously defined summaries over well-defined datasets

I found this quote really confusing but is the idea that a metric always has a time dimension and evaluates to a float? (e.g revenue over time, user count over time), hence giving a more rigorous "type"? 

### Metrics on models? 

There is definitely some benefit earned because for analysis tables: there tends to be a subset of columns that are destined to be dimensions and some destined to become metrics in the semantic layer. The ability to just go through all columns and tag them with dimension / metric-type can make it really easy to bootstap metrics from a dbt model.

While joins aren't supported, then metrics only map to a single model so I think there's a strong argument to keep them on models. However, dbt needs to retain flexility to define metrics across models it would make more sense to define them on exposures / a new resource.

### SQL implementation

One noticeable omission here is the actual implementation of how these metrics actually compile to SQL. I think it would be even more powerful, if the metrics definitions were paired with an expected SQL for certain target warehouses. Is that in scope for the project?

It would be troublesome for example if I have my centralised metric definitions but downstream tools interpret those metrics differently. I imagine something like a reference implementation of the complied SQL statements coming out of metrics (e.g. a dbt macro / package).

Or perhaps the idea here (as with dbt models) is that it doesn't take an opinion on how a metric definition becomes SQL and people are free to essentially build their own metrics layers using a common set of metrics definitions.

### Last one...
* Heck no to complex sql definitions for dimensions, this definitely duplicates the holy work of dbt models.

**Comment by willweld** [comment]
@owlas 

Yeah absolutely agree with you. And the other things like pop_increase: [good/bad] could (should) be stored in the `meta` as well. As long as these attributes do exist and I can parse them out in dbt, I'm a happy camper :)

**Comment by tayloramurphy** [comment]
I would echo @owlas's points about the Time-Demension requirement. It feels overly explicit for no clear benefit.

> Include support for joins

or 

> SQL implementation from @owlas 

Many moons ago at Meltano we implemented a SQL:1999 compliant algorithm for properly handling JOINs and generating SQL. We call these "Hyper Dimensional Aggregates".  The original issue documenting it is in https://gitlab.com/meltano/meltano/-/issues/286 and the SQL:1999 compliance part is in https://gitlab.com/meltano/meltano/-/issues/344

This code is all MIT licensed and could most likely be ported (famous last words) over to dbt if that makes sense. Perhaps @drewbanin you're thinking of having a similar adapter model to SQL generation that dbt has for everything else (a la https://docs.getdbt.com/docs/available-adapters#dbt-labs-supported)

Maybe this discussion is too much for the specification issue, but I wanted to call it out and put that bug in people's brains 🙂

**Comment by miike** [comment]
> Seem more related to visualisation and I think would be strong candidates for the `meta` tag.

Agreed @owlas format / precision are a good fit for meta as they seem like presentation attributes rather than core to the metric. That said I'd love to see `units` as a first class citizen as this is something critical to the metric definition (kilometers / meters, seconds / milliseconds etc).

>Not sure if I understood correctly, is the difference that a metric always has a time dimension and evaluates to a float?

Not sure I fully grasped this either. I think there are certainly instances (and some you've mentioned) where a metric (or measure?) may not necessarily evaluate to a float, but may still be quite useful (e.g., the mode of a categorical variable).

**Comment by buremba** [comment]
Great to see that dbt will support metric definitions! The proposal looks great and we're specifically interested in exposing these metrics to the downstream tools including SQL clients, BI tools, and data science tools. There are a couple of limitations to the proposed features:

### `dimensions`
Unfortunately, most of the BI tools don't support this feature so most of the BI tools might be missing this information. We can ideally throw a user-friendly exception in the implementation as a workaround for now. I see the use case and am happy to implement it in our spec in case dbt has this feature but I'm not sure if it's a common use case and I believe that the name might be confusing for some users. I would suggest using something like `allowed_dimensions` or so. 

### `time_grains` and `timestamp`
Not all the metrics are time-series metrics and I believe that both of the properties should be optional. If `time_grains` is defined and `timestamp` is not, we can use all the available time frames, that's what we're doing at Metriql. I'm in favor of defining them under models rather than explicitly for metrics even though it's not flexible compared to the suggested approach. Most BI tools support time-series datasets but it's not at the metrics level and requiring the users to define them for each metric might be verbose in most cases. What about having a `mapping` property ([example in Metriql](https://metriql.com/reference/mapping)) for dbt resources (models, sources, seeds) so that we can define them at dataset level and provide an option for the users to override it for individual metrics?

## Features

### `filters`
It looks good and we already support filters. I see two different implementations for the filters though:
1. Having an additional property such as `operator` to define the filter operation. ([Metriql](https://metriql.com/reference/measure#filters) follow this approach)
2. Or let the user define the `value` and figure out the operation with some special characters such as `-`. ([Looker example](https://help.looker.com/hc/en-us/articles/360001286007-Creating-Filtered-Measures-))

Even though we follow `1`, we're happy to implement `2` for better readability but we should probably think more about the coverage and user experience.

### BI-tool specific properties under `meta`
Each BI tool has its own naming and semantic types and we believe that they should also be defined in YML files. It's one of the most used features of Metriql ([see example](https://metriql.com/integrations/bi-tools/google-data-studio#step-3)) but it's hard to standardize so they can fit under `meta` property I guess.

### `approx_distinct` aggregation type
Modern cloud data warehouses support approximation already and it's the preferred approach for big datasets. It's also additive unlike `count_distinct` and I believe that we should support both aggregation types. We can either have something like [`approximate` of Looker](https://docs.looker.com/reference/field-params/approximate) and use approximation if the aggregation type is `count_distinct` but we're [in favor of ](https://metriql.com/reference/measure#aggregation) adding as an additional aggregation type for convenience since some of the databases don't support it.

### Join relations
I believe that metric stores should support joins but I see the reasoning here. We aim to help analytics engineers automate creating dbt models for dimensional modeling and denormalizing the datasets into wide tables might be confusing for some use-cases. We can extend the standard in our implementation and denormalize the dimensions & metrics when exposing them to the downstream tools as we have customers using join relations at the moment.

**Comment by alexanderdean** [comment]
Supportive, this would mean Snowplow dbt packages can have the metrics built-in. As package authors who already have multiple data stores/SQL flavors to support 💸, it would be great to see market standardization at the metrics definition layer 💯!

**Comment by joellabes** [comment]
🎩  _Written without my dbt Labs employee hat on, not that it changes anything_ 🎩 

> dbt Core should not, itself, evaluate or calculate metrics. Instead, dbt Core should expose the definition of metrics to downstream tools or packages for evaluation and analysis. In this way, it is critical that dbt Core provides hooks into metrics that can be leveraged in both macro code, or by processes that consume dbt Core `manifest.json` files.

This seems to imply outsourcing the SQL generation that actually calculates the metric to each tool. Does that mean that (best case) the engineers at `$BI tool 1` might write more efficient SQL than `$BI tool 2` or (worst case) `$BI tool 1` might generate results that disagree with the same metric as rendered in `$BI tool 2`?

Or does 
>packages

above imply a reference implementation that vendors deviate from at their own risk?

**Comment by jpmont** [comment]
> $BI tool 1 might generate results that disagree with the same metric as rendered in $BI tool 2?

Regarding tests for metrics, it could still be valuable to have expectations defined in dbt (even if not evaluated in dbt) and used as a reference for the BI tools to guarantee correctness.

**Comment by buremba** [comment]
@fabrice-etanchaud that's a great idea! I contacted Julian a while ago for a call for help but it looks like it might be a conflict of interest since he's working for Looker. The idea was to parse [MDX queries](https://docs.microsoft.com/en-us/analysis-services/multidimensional-models/mdx/mdx-query-the-basic-query?view=asallproducts-allversions) with [Olap4j of Mondrian](https://github.com/olap4j/olap4j) and compile it to SQL for the underlying data warehouse without any caching / storage mechanism, unlike Mondrian. We can generate the dimensional tables as dbt incremental / table models instead of using an additional caching mechanism and reference these roll-up tables in the compiled SQL query.

We have pending work but MDX seems to be much more complex than we imagined. I would love to collaborate if there's any interest.

**Comment by fabrice-etanchaud** [comment]
> @fabrice-etanchaud I didn't know about dremio's reflections but it looks like they store the data in external storage rather than in the same data warehouse, which is the main point of dbt. The idea is to create dbt models and utilize them rather than moving data from your data warehouse to an OLAP engine. I believe that it's more dbt-native and it aligns with the modern data stack since it's we will be pushing all the work into the data warehouse. dbt and the metrics layers can potentially replace the OLAP solutions with less overhead, I wrote an opinionated [blog post](https://metriql.com/blog/2021/09/07/olap-in-modern-data-stack) about this topic recently.

Hi @buremba , dremio can be used as a datawarehouse (it stores its data in parquet files or even in iceberg format ). As it connects to your enterprise sources, there is little if no need for pipelines. You are right, if you already have a dwh, dremio would add an extra layer.

Best

**Comment by mistercrunch** [comment]
> I would challenge the idea of having virtual columns calculated in dbt .yml files. Is this sufficiently different from having a model of type view, which contains all my dimensions and columns needed for metrics? I think virtual columns already have a home in dbt .sql models.

I'm not convinced as you then would have to systematically duplicate models for the sake of these "virtual columns" (which are pretty common imho), potentially doubling the size of your DAGs creating more indirections. Maybe DBT compiles in that form physically in the database (with an extra view on top), but hopefully we don't have to create a new file and carry the list of fields forward (or whatever DRY version of that) for that sake.

**Comment by bashyroger** [comment]
**On the topic of Joins:**
While this indeed can get complicated, I think support is vital as it makes it possible do build a proper Dimensional Model / Kimball star model with conformed dimensions.

A first implementation of join logic could be made easier in the following way:

- Joins are only valid when the are made between a **Fact** table and **Dimension** table, They therefore should be **many to one** always!
- Metric calculations can **only** be created on the central fact table

As in: you should **NOT** want to implement logic to resolve casm / fan traps! (https://biguru.wordpress.com/2008/05/01/its-all-in-the-universe-handling-chasm-and-fan-traps/)

**Comment by nhandel** [comment]
Nick here from transform.co. I want to share some learnings that we're building off of at Transform from working on metrics tools at Airbnb. We would be eager consumers of these definitions and support the development of a more universal spec. A snippet of our current spec can be seen [here](https://blog.transform.co/metrics-framework/). We'll do a better job of pushing out the full spec and the opinions we're building on soon.

At a high level, I'm excited about this direction for dbt. Centralizing this information and creating strong ties with the data transformation pipelines is an exciting direction. The opportunity to connect metrics to their data lineage through the entire data modeling process and then downstream is compelling and will benefit end-users. This also presents an exciting opportunity to solve one of the more significant challenges with metrics frameworks, building out a dependency graph. 

Some good ideas in this thread will push this in the right direction, but some gaps are fairly similar to the gaps that Airbnb ran into with early iterations. I'm skeptical of the idea that starting simply and then evolving this spec will work. Metric specs, in particular, are complicated because of the number of end applications that consume from them and the flexibility required to serve them all. There have been multiple backward-incompatible evolutions of metrics frameworks across Airbnb and other companies, and the ones I participated in were all ~painful~. This is a lot of logic to migrate, and it's not always 1-1. 

**Philosophical Level**

Before diving in too deep, I'm sensing a philosophical gap between some of the writing in this thread and how larger companies who have built this internally have used this type of technology. Specifically, [Airbnb's framework](https://medium.com/airbnb-engineering/how-airbnb-achieved-metric-consistency-at-scale-f23cc53dea70) (and the [older version](https://medium.com/airbnb-engineering/https-medium-com-jonathan-parks-scaling-erf-23fd17c91166)) evolved to be thought of as a "denormalization engine" and I get the sense that there are advocates here for a different direction (no virtualization, push to rely on manual modeling for complexities, dimensions and joins as a second step in spec design, etc.). I fear that the impact will be limited if end-users are expected to define these metrics on top of denormalized tables. That's not to say that these ideas are right or wrong, but they do deviate from a path that has been tested. If the context on the evolution of Airbnb's spec is helpful, I'm happy to share more. 

[Here](https://getdbt.slack.com/archives/CJN7XRF1B/p1634163000020000?thread_ts=1634116586.013000&cid=CJN7XRF1B) is a good explanation of why you should pass flexibility to frameworks like this. The virtualization of logic is seen as a plus for some of the reasons @mistercrunch mentioned above. If the abstractions are chosen thoughtfully, you can end up with DRYer code and a more flexible framework that can handle more of the boiler-plate logic associated with metric construction.

**Joins / Identifiers**

Joins are by far the most complicated component of this concept. The core difference between the way we have thought about this vs. others in this space and the posts I've seen here is that we build the joins for the end-user rather than the framework built on top of this spec needing to be robust enough to handle fan-out and chasm joins. I don't think symmetric aggregates in SQL construction are necessary. We get around this by using "identifiers," which are the join keys and their types (primary, foreign, unique) as joinable entities rather than defining join paths one by one.

The framework determines the join that the requested data set requires. This is a much more flexible and DRY abstraction that enables the framework to manage the complexity around joins. This pushes the optimization to the framework with all of the above benefits around declarative languages with flexible planning engines.

It's probably not worth digging in too deep here since this appears to be a future discussion point, but this is one of the more significant differences of how we've approached building Transform relative to frameworks like LookML or most other semantic layers.

**Dimensions**

First, since this is a loaded and ambiguous term, I define a dimension as an attribute of an entity/identifier... i.e., user's country, product's type, etc., or that entity itself. I have pretty strong opinions on this one -- A metrics spec should treat a dimension as a first-class object. Treating a dimension as an attribute of the metric will become quite repetitive as companies adopt this at any form of scale. This goes back to the philosophical idea above, but if you are required to pull dimensions into every metric, business consumers will become frustrated, and the analytics engineer will become a blocker to the outcomes this layer aims to enable.

Hierarchies: Folks have shared some interesting ideas here. This is an important concept and shouldn't be ignored. The expression of time granularities is a dimension hierarchy. There are many more types of dimension hierarchies, and these should be expressible by the user. Everyone's business has unique dimension hierarchies(e.g., Sales Region → Territory → Market), and this needs to be an abstraction of its own that looks similar to a nestable case statement to get real DRY. One way to think about a dimensional hierarchy is that it is a discretely aggregatable object rather than a measure that is a continuously aggregatable object.

Time granularity: Except for a point-in-time metric (e.g., 2021 revenue or 2021 revenue by country), metrics only make sense in the context of time. We've had a lot of debate about representing time and whether time itself should be a component of the metric. Some metrics require time in their definition (i.e., a cumulative metric), and some may make sense in the context of a single timestamp (transactions by last updated vs. transactions by created at)

**Measure and Metrics**

The differentiation you identified in your first post between measures and metrics is close to how we defined these two objects, although we use both. Put simply, metrics are functions of measures. The measure & metric abstraction allows us to maintain a flatter dependency structure and increase the reuse of objects.

We define measures as aggregatable expressions (columns or SQL statements that fit in a select) and an aggregation type. What is defined in the original spec as a metric would be measure and a `measure` metric type in our framework. We define metrics as functions that take measures and other parameters as inputs. They can be as simple as a proxy of a measure or more complicated like cumulative or rolling window metrics. 

Reusing metrics or deriving metrics from other metrics is another idea that seems appealing, but it can become quite a mess, both technically and organizationally. There are a few reasons, but the most challenging part is generating nested metrics and joining in dimensions at different aggregation levels.

**Summary**

The goal of a spec in my mind should be to create a sufficient semantic understanding of the warehouse that tools can build the logic necessary to serve metrics to various applications. There are many applications for metrics, and that is a tall order and ultimately the challenge of defining a ~universal~ spec. That spec should also probably be exchangeable between data applications for them to do their analytical work.

I would love to help with this but also don't want to grandstand on these beliefs if there is a desire to go in a different direction. That was a very high level and possibly too short to fully articulate these points. There was so much pain and frustration learning how to make these configs organized and simple, and I would love to help shortcut that.

**Comment by jtcohen6** [comment]
We've got a first stab at teaching dbt about metrics (#4235), which we're going to be including in v1.0.0-rc1. This is an intentionally limited schema, just enough for this to be an experimental feature. We're reserving the right to add more over time.

Major-version one isn't usually the time for brand-new experimental features. We want to keep innovating, even as we lock in the foundation; and it's because of all our other efforts—toward stability, performance, and maturity—that we feel able to take this swing.

Needless to say, this conversation is far from over. I'm so appreciative of all your time and thoughtfulness in the threads above, and I'm excited to see our thinking on this topic continue to develop over the next weeks and months. I know there are already some exciting follow-on issues, to which I owe responses :)

**Comment by fabrice-etanchaud** [comment]
Concerning the implementation of "cubing/metrics" whatever the way they will be specified in dbt, it could be interesting  to see how the [unified star schema](https://towardsdatascience.com/the-new-unified-star-schema-paradigm-in-analytics-data-modeling-review-a245b2641dc8) paradigm based on SQL UNIONing could help.
dbt's DAG and puppini's Oriented Data Model notion superpose and that could systematically prevent [data traps](https://showmethedata.blog/sql-traps-unified-star-schema).

**Comment by bashyroger** [comment]
One note on the naming of this functionality @jtcohen6 , I would propose to call this feature the **(BI) semantic layer** or **Information semantic layer** _instead_ of the metrics layer. 
A bit more abstract indeed, but a better fit.
Why? When I think about metrics, _I don't necessarily think about this functionality also incorporating 'logic' for joins, dimension hierarchy's and all the other more complex logic that is discussed in this thread... And I think most agree it should

**Comment by mike-weinberg** [comment]
Just putting this out there:

_we cannot avoid joins forever_

To weigh in a little more concretely, I strongly favor the semantics defined by @owlas in which dimensions/measures are defined on the model-column, and relationships are defined in exposures, albeit a first class `semantics` tag in place of the `meta` tag would be nice.

While the INTP in me would like to see an explicit syntax for asserting foreign keys in model-column properties so that lattices can be generated, the reality of most businesses is this: 
> just because a lattice is _possible_ that does not mean that lattice is _useful_, 

and so that pretty strongly suggests that using exposures to explicitly define _intentional explores_ is a pragmatic solution

**Comment by igorlukanin** [comment]
Integrations with dbt Metrics incoming!

I think that @owlas was the first one to mention [Cube](https://cube.dev) in this thread (thanks!), and I'm happy to share that now Cube is able to read metrics definitions from dbt and provide caching, access control, and a variety of APIs for downstream data consumers like BI tools, notebooks, custom apps, embedded analytics, etc.

Here's some details on this integration (https://cube.dev/blog/dbt-metrics-meet-cube/) and there's also a topic on dbt's forum where we can discuss this further (https://discourse.getdbt.com/t/combining-dbt-metrics-with-api-caching-and-access-control/4033).

**Comment by abdel-87** [comment]
Very happy with the integration released by Cube JS!!

To get back on the core of the **dbt metrics** feature. 
When you look at metrics from a Star Schema perspective, something that is very widely used as a presentation layer for data warehouses, **Joins** are inevitable to have in scope.

Take just this simple example (where I appreciate the way Cube JS implemented support for joins), when you want to use dbt metrics as the source of truth.

metrics:
- Total Revenue
- Average Revenue

Dimensions:
- Customer Country (ref('dim_customer'))
- Product Category (ref('dim_product'))

You would want to calculate your metrics, and break them down by the specified dimensions that are not part of the current model. Dbt Metrics, should not force users to denormalize the star schema into one big table to be able to use the dbt metrics feature, what is now unfurtunately the case.

I think it would be very helpful to look on the Cube JS implementation, and take the lessons learned from there to be able to provide the same support for Joins.
