### ISSUE TITLE
[Feature] The insert_by_period materialization should graduate to part of the main project

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4174]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Since 0.10.1, dbt-utils has contained a Redshift-specific macro called [insert_by_period](https://github.com/dbt-labs/dbt-utils#insert_by_period-source) to do incremental loads. 

Recently, there's been some interest from the community in modernising this: 
- a [PR to bring Snowflake compatibility](https://github.com/dbt-labs/dbt-utils/pull/410) 
- [a SQLFluff user](https://getdbt.slack.com/archives/C2JRRQDTL/p1632155701394000) who is running into linting issues with the non-standard `__PERIOD_FILTER__` block. 

Although we could leave it in utils, I think it's time for it to make the jump to being a first-class materialization.  

### Describe alternatives you've considered

- Leaving it in dbt-utils and making it compatible with the four adapters utils commits to supporting. Either way, other databases will need to implement their own shims if their implementation isn't compatible with the default and they want to offer it. 
- Writing up my hacky method from the EP days (use a standard incremental model, but process no more than a month at a time. Works using only inbuilt functionality, but takes multiple runs to complete the backfill 🤢 )

I'd be happiest if this could just be extra parameters on the existing incremental materialisation. IDK if that's actually possible; if not, then it would need to be the fifth inbuilt option and I'd probably swing closer to leaving it in utils because it's not as cut-and-dried and so adding the extra friction maybe isn't so bad.

### Who will this benefit?

- SQLFluff users
- Snowflake users, probably BQ/PGSQL/etc too (I always assumed that it was a bandaid for the fact that Redshift would fall over at higher volumes, but obviously it also has value for more scalable warehouses)
- Cautious developers: When I was at EP, I shied away from this materialisation because it didn't feel robust enough (when I looked at it it was already 6 minor versions "out of date", and it had a hacky feel to it)

### Are you interested in contributing this feature?

Sure am, despite how scary materialization code is

**Comment by balmasi** [comment]
There's also an interesting `insert_by_rank` variation which I've [seen in the dbtvault project](https://dbtvault.readthedocs.io/en/latest/macros/#vault_insert_by_rank) which allows you to iterate over any arbitrary ranking function rather than only dates/times. 

It's been pretty handy.

**Comment by jtcohen6** [comment]
Thanks for opening this @joellabes, and getting the conversation started. All in all, I find myself agreeing with your assessment here:

> I'd be happiest if this could just be extra parameters on the existing incremental materialisation. IDK if that's actually possible; if not, then it would need to be the fifth inbuilt option and I'd probably swing closer to leaving it in utils because it's not as cut-and-dried and so adding the extra friction maybe isn't so bad.

I'm wary of our ability to modify the existing incremental materialization, without adding a _ton_ of new complexity. The ability to `--full-refresh` with one query is a pretty significant piece of the current implementation. We'd also need to introduce a new context variable for the period being inserted, or use a similar string-replacement hack (`__PERIOD_FILTER__`) to the one being used currently.

I sense more significant overlap with the proposal for **sharded tables** in https://github.com/dbt-labs/dbt-core/issues/1637. When a table gets so big that it's impossible to create it with a single query (however long-running or expensive), perhaps the right answer is to make it multiple tables. Then, rather than inserting period chunks into one table, we create _many_ tables, and a view to union them together.

Sharding tables is a hard problem—there's a strict 1:1 mapping between database objects and project resources today, a rule we'd need to break—but it feels like the right hard problem to tackle. Support for sharded tables will also, I believe, offer us a way toward native support for ["lambda views"](https://discourse.getdbt.com/t/how-to-create-near-real-time-models-with-just-dbt-sql/1457). After all, the only difference is that the "latest" shard needs to be materialized as a view instead of a table.

BigQuery has long had a native approach to this, with some wonky/legacy syntax, as ingestion-time-partitioned tables. We've removed support for those from dbt-bigquery ahead of v1 (it was effectively deprecated code). Whether we re-add support for the native approach there—or opt for one in which dbt more actively coordinates between shards and the union view, as it will have to on other adapters—that should be an implementation detail to figure out when we have a chance to tackle this project in earnest.

So: Support for table sharding is on the list of big improvements we should consider making after v1. I think it may obviate the need to add `insert_by_period` into the global project. This will definitely require changes within dbt-core, but a lot of the most important logic will live in macros and materialization code. If anyone has some time on their hands, and wants to play around with the possibilities of many-tables, one-model before then — I'd love to see what you can come up with!

**Comment by joellabes** [comment]
OK! Until the glory days of sharded tables are upon us, I'll start thinking a bit harder about how a modernised version of the current insert_by_period materialization should behave in utils.

**Comment by graciegoheen** [comment]
Closing this in favor of our epic to add new "microbatch" incremental strategy:
- https://github.com/dbt-labs/dbt-core/issues/10624
- https://github.com/dbt-labs/dbt-core/discussions/10672
