### ISSUE TITLE
When dbt finds existing approximate matches via `adapter.get_relation()` use the same quoting when printing error message

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-core#4187]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

A user reported this issue to me (https://github.com/firebolt-analytics/dbt-firebolt/issues/62 private repo). But their error message is copied below and it looks as if there are two models: one that is quoted (`"oz_account"`) and one that isn't (`oz_account`). In reality, I think there is a namespace overlap? What's driving me crazy is that 4/5 of current users are not having this quoting issue, and one user is having this issue. So I don't understand how this can happen when the adapter code is the same...

My suggestion would be to make them both be quoted so users don't think there's a quoting issue going on, but rather should know that it is indeed a problem with the model name already being used. 

```log
Completed with 3 errors and 0 warnings:

Compilation Error in model account (models/adtech/staging/account.sql)
  When searching for a relation, dbt found an approximate match. Instead of guessing 
  which relation to use, dbt will move on. Please delete "oz_account", or rename it to be less ambiguous.
  Searched for: oz_account
  Found: "oz_account"
  
  > in macro materialization_table_firebolt (macros/materializations/table.sql)
  > called by model account (models/adtech/staging/account.sql)
```

### Describe alternatives you've considered

Unless this user is experiencing #3835. I'm going to have the user try the fix proposed in #4076 and see if that fixes their problem. If so, we know what's going on.

If #4076 does not fix the user's issue, it seems I have to deep dive more into `adapter.get_relation()` to see what's going on

### Who will this benefit?

users of dbt-firebolt!

### Are you interested in contributing this feature?

![yep.GIF](https://media.giphy.com/media/XMBJ0l20sNWEM/giphy.gif)

### Anything else?

![nope.GIF](https://media.giphy.com/media/wYyTHMm50f4Dm/giphy.gif)

**Comment by joemirizio** [comment]
I believe we are experiencing this issue with the Netezza adapter, which has an `identifier` quoting policy of `False`. When relations are loaded into the cache and then matched against, the `BaseRelation._is_exactish_match` is failing - this happens in certain macros and dbt server.

After debugging we’ve found that `BaseRelation._is_exactish_match` is returning `False` because it is comparing the table identifiers _exactly_, rather than lowercasing both sides of the comparison - which is ONLY done if the quoting policy is set to `False` (it is) **AND the relations `dbt_created` field is `True`** .

When we dove into the `cache_added` method, it appears that the incoming relation’s `dbt_created` field is correctly set to `True`, but when retrieving the value from the cache, it is set to `False`. Due to a relation's field `dbt_created` not preserving after a cache read, it causes the match to fail.

### Steps to reproduce
1. Using any adapter, set a breakpoint at https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/adapters/base/impl.py#L447
2. `dbt run` a project with a model
3. Evaluate the following in the debugger
```python
> relation.dbt_created
True
> [cache_relation for cache_relation in self.cache.get_relations(relation.database, relation.schema) if cache_relation.identifier == relation.identifier.lower()][0].dbt_created
False
```
