### ISSUE TITLE
Conditional severity test `severity: error` is not working

### ISSUE THREAD

**Issue by antongoncharuk** [dbt-labs/dbt-core#4277]
Hey team, I’m trying to set a conditional severity test using the following [guidance](https://docs.getdbt.com/reference/resource-configs/severity), to throw an error if there are more than 3 fails, to warn if there are more than 0 and pass otherwise. But it is not working, I’m still getting the following error  - `Got 3 results, configured to fail if != 0`. Please see the screenshot attached. Running with dbt=0.21.0.

      - name: organization_id
        description: 
        tests:
          - not_null
          - unique:
              config:
                severity: error
                error_if: "> 3"
                warn_if: "> 0"

![ScreenShot 2021-11-12 at 22 14 54@2x](https://user-images.githubusercontent.com/55678713/141608357-f8232049-fe42-4511-90c9-b451971ec595.png)

Note: works when `severity: warn`

**Comment by jtcohen6** [comment]
@antongoncharuk Thanks for the report!

I believe this is the result of a typo, included in v0.21.0:
https://github.com/dbt-labs/dbt-core/blob/79aa13630125abbdbc9abb482399267f62a1d91e/core/dbt/parser/generic_test_builders.py#L360-L361

This bug was previously reported (https://github.com/dbt-labs/dbt-core/issues/4051), and fixed (https://github.com/dbt-labs/dbt-core/pull/4070) for a v0.21.1 patch release, which is currently available as a release candidate. Could you try installing that, and confirm that it fixes the issue?
```
pip install dbt==0.21.1rc1
```

We're hoping to have a final v0.21.1 release next week. In the meantime, I'm going to close this as a duplicate.
