### ISSUE TITLE
Add option to Run Source Freshness in dbt Cloud to mark job as failed

### ISSUE THREAD

**Issue by badge** [dbt-labs/dbt-core#4284]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

We have a job in dbt Cloud that we use to source freshness, which we want to do two things:

1. Generate the nice `Data Sources` artifact for checking source freshness
2. Notify us if source freshness results in errors

Currently, checking the _Run Source Freshness_ execution option in a job's settings doesn't result in (2), while running a `dbt source freshness` step doesn't result in (1).

It'd be great to be able to add an option to _Run Source Freshness_ which marks the job as failed if the source freshness step fails.

### Describe alternatives you've considered

Our current workaround is to have job that runs `dbt source freshness` _and_ has _Run Source Freshness_ checked, but this doubles up on job execution time and associated costs to all parties.

### Who will this benefit?

Everyone using source freshness on dbt Cloud.

### Are you interested in contributing this feature?

No, only because it's part of dbt Cloud

### Anything else?

I ❤️  dbt!

**Comment by jtcohen6** [comment]
Thanks for the thoughtful write-up @badge! This is a totally valid feature request, and I think it would be entirely possible if not for:

> while running a `dbt source freshness` step doesn't result in (1)

This is actually a bug in dbt Cloud today! Our `Data Sources` logic is hard-coded to look for `dbt source snapshot-freshness` in a job definition, and needs to make the upgrade/rename to `dbt source freshness` in v0.21. The responsible teams are looking into it as we speak.

For the time being, you can get this working by switching to the older syntax in your job definition (see [docs](https://docs.getdbt.com/reference/commands/source)):
```
dbt source snapshot-freshness
```
This will work on v0.21 as well.

I think this should definitely get you what you're after. The intent behind checking _Run Source Freshness_ is that it should do _the exact same thing_ as an explicit job step, but it _won't_ cause your job to fail if it finds stale sources.

I'm going to close this issue, since dbt Cloud is where we'll be making the fix for the associated bug. Hope to have one soon!

**Comment by badge** [comment]
Awesome! I'll update our job with the old syntax and wait for the update. ☺️
