### ISSUE TITLE
[Feature] Automated cleaning / filtering of data based on YAML configs

### ISSUE THREAD

**Issue by pawelngei** [dbt-labs/dbt-core#4306]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

DBT gives data engineers a great framework for writing tests for their data via the YAML files, but expects them to do the data cleanup and filtering manually. This doesn't necessarily need to be the case, since the testing framework already in place could allow data cleaning / filtering with minimal code changes.

Consider such a config:
```
    tables:
      - name: library_users
        columns:
          - name: first_name
            filters:
              - not_null:
                  error_after: 50
```

It could generate a similar SQL file as the test, but instead of outputting a True / False statement for the test to pass, it could generate a new, filtered table in a chosen schema, like `cln_library_users` with not-null values and a `drt_library_users` with just nulls. Optionally, the filter could error out if the number of the users without `first_name` is above 50.

This can be currently achieved by rewriting the `not_null` test macro with a custom one, with one exception: when another table uses DBT's `source` [Jinja function](https://docs.getdbt.com/reference/dbt-jinja-functions/source), it automatically reaches for `library_users`. With the Filter framework in place, it could look for `cln_library_users` first, and if that table doesn't exist / is too old, fall back to `library_users`.

`drt_library_users` could exist for the data analysts to preview when debugging.

### Describe alternatives you've considered

1. Creating an intermediate table to clean the data manually per every table we want to clean. This doesn't work well with huge codebases, potentially adding a lot of files which only filter data. We feel that it would be much easier to define this in a YAML, which is much cleaner to read and version-control.
2. Writing the filters as custom tests, as described above. Sadly, it doesn't work because of how the `source` function is structured.
3. Using third-party filtering tools such as AWS Glue DataBrew. This is an extra cost compared to running it in DBT.

### Who will this benefit?

Everyone who would like to clean / filter their own data in an automated manner, especially teams dealing with consistently dirty data without using third-party tools.

### Are you interested in contributing this feature?

maybe, but not within this calendar year

### Anything else?

This feature could be introduced in steps, the first being just adding the ability to coalesce / fall back in the `source` function. This way, we could use `{{ source('schema', 'cln_table', fallback='table') }}` and the custom test macros to achieve this feature locally and beta-test it / gather move feedback from other DBT users.

**Comment by jtcohen6** [comment]
@pawelngei Thanks for the thoughtful write-up, and so sorry for the delayed response on our end!

I totally get what I think you're after in this proposal, and it's been bouncing around in my head for the past few weeks. I also sense two different approaches at work in your thinking; I propose splitting them apart and treating them separately.

### Automated staging models

It would be very, very standard practice for us to notice that `first_name` is frequently null in the raw `library_users` table, and code up a staging model for just that purpose:
```sql
with source as (
    select * from {{ source('public_library_network', 'library_users')}}
),

renamed as (

    select
    
        id as user_id,
        firstName as first_name,
        lastName as last_name

    from source

),

filtered as (

    -- after investigating users with null first names, we realized that most
    -- were created as test accounts during initial system launch,
    -- with last name 'test'
    -- filter out test accounts here, they're never useful for analytics

    select * from renamed
    where last_name not like '%test%'

)

select * from filtered
```

Then, we'd simply move the `not_null` test from the source table to its staging model:
```yml
models:
  - name: stg_library_users
    columns:
      - name: first_name
        tests:
          - not_null:
              config:
                error_if: "> 50"
```

This isn't a built-in product feature of dbt, but it's a pattern that we (as practitioners of analytics engineering with dbt) highly, highly recommend. In the projects we work on, _every source table gets its own dedicated 1:1 staging model_. Some docs about this:
- https://docs.getdbt.com/blog/how-we-structure-our-dbt-projects/#staging-raw-data
- https://docs.getdbt.com/tutorial/refactoring-legacy-sql#identifying-staging-models

It's fair to say that many folks buy that premise, and they still want better tooling from dbt-core (or dbt plugins) to avoid the significant manual work of creating staging models—at least the initial repetitive scaffolding. There are a few tools that help with that sort of code generation today—such as the [`codegen` package](https://hub.getdbt.com/dbt-labs/codegen/latest/) or [`dbt-generator`](https://github.com/tuanchris/dbt-generator) helper. Even in that case, the premise stands that this is _a different node in your DAG_, which maps to a different object (probably view) the database—not a separate database table that dbt creates behind the scenes, and to which it subtly redirects subsequent `{{ source() }}` calls.

### Tests --> column types

The first approach is the one I feel high confidence around, and my initial thought was to close this issue on that basis. But I kept thinking... What if tests weren't actually _tests_, but rather _statements of truth_ (perhaps even "types") for columns in your project—and it's the responsibility of dbt to see that those statements are actually true, that those types are actually enforced, by applying checks accordingly. Generating the SQL to "fix" these assertions makes some sense for simple types (never null, only XYZ accepted values), though it gets progressively more complex as we think about more complex tests/assertions.

In that world, these are _column attributes_ more than they're really _tests_. I also think an implementation of this approach would be plausible today, leveraging the `meta` attribute:
```yml
sources:
  - name: public_library_network
    tables:
      - name: library_users
        columns:
          - name: first_name
            meta:
              filters:
                - not_null
```
Then imagine a custom `source` macro that, instead of resolving `{{ source() }}` calls to the raw table identifier, wraps that table in a subquery with the filter logic applied. The code below is untested pseudo-code, but just to give a sense of what's possible today:
```sql
{% macro source(source_name, table_name) %}
  (
  
    {% set src = builtins.source(source_name, table_name) %}   ​
    ​select * from {{ src }}
    ​where 1=1

     ​{% if execute %} {# only go here after parsing is done, for sql compilation / runtime #}
       ​{# pseudo code using `graph` variable, to look up full source specification - do not use verbatim #}
       ​{% set this_source = (graph.sources.values | selectattr('source_name', source_name) | selectattr('source', name) | list).pop() %}
       ​{% for column in this_source.columns %}
         ​{% for filter in column.meta %}
           ​{# hand wave: we look up the test/filter/assertion type to generate this sql #}
           and {{ column.name }} is not null
         ​{% endfor %}
       ​{% endfor %}
     ​{% endif %}

   ) src_subquery

{% endmacro %}
```

Upshot: When I call this in my model SQL:
```sql
select

  first_name,
  count(*)

from {{ source('public_library_network', 'library_users')}}
```
I actually get:
```sql
select

  first_name,
  count(*)

from (
  select * from public_library_network.library_users
  where 1=1
    and first_name is not null
```

To be clear, that's a different answer from creating a new database object, with the filtering logic applied, and redirecting `source()` calls to that object.

I'm not convinced that this is a more desirable approach than creating a separate staging model. There's one specific piece of this approach that does appeal to me, though: dbt now knows an attribute (again, perhaps "type") of the `first_name` column, explicitly, in a way that the `not_null` test on a staging model column only implies. In a world where dbt can know/infer DAG lineage at the column level, we could also think about that "type" being inherited by downstream models which select from the source—whether they contain the same `first_name` column, or another column computed from it, in such a way that dbt could _know_ whether the downstream column contains nulls. That's a pretty far-out future, but it's exciting to think about the possibility, and helpful as an orientation for the semantic model we're building in the meantime.
