### ISSUE TITLE
[Feature] run_ended_at

### ISSUE THREAD

**Issue by Mavtti** [dbt-labs/dbt-core#4316]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Currently with Jinja we can access run_started_at variable but there is no run_ended_at to use in post_hooks.

As such, in dbt-logging package, it forces to creates 2 entries, 1 for the start and 1 for the end of each run. With this variable it would allow to have a single entry for each run with 2 timestamp columns, 1 for the start and 1 for the end date.

### Describe alternatives you've considered

None

### Who will this benefit?

logging package users and anyone who wishes to monitor dbt runs.

### Are you interested in contributing this feature?

No sorry.

**Comment by pgoslatara** [comment]
@Mavtti I'm trying to understand your desired behaviour here. `run_started_at` returns the time the run was started, hence if you've multiple models that use this variable in pre-hooks then all these pre-hooks receive the same value. Question is: do you want similar behaviour for `run_ended_at`?

Reason for asking is that if you want similar behaviour then this may result in a race scenario, if you have two non-dependent models call `run_ended_at` in post-hooks then there's an issue because the model 1 post-hook might call the variable but the variable will not be defined until model 2 finishes.

If instead you want a unique `run_ended_at` value per model then this avoids race scenarios (although a different name may be needed to avoid conflations with `run_started_at`).

Want to make sure which behaviour you desire.

**Comment by Mavtti** [comment]
Hello, thx for looking into it, seems like I misunderstood run_started_at behavior. I first thought that it was a timestamp per model.
The ideal would be 1 start & 1 end timestamp per model.

**Comment by pgoslatara** [comment]
@Mavtti If you want one start and one end time per model (rather than run) then I think you can already use your database's equivalent of `CURRENT_TIMESTAMP()` in the pre_hook and post_hook. Does this make sense or am I missing something?

**Comment by emmyoop** [comment]
Thank you so much for your thorough response @pgoslatara!

@Mavtti,  thanks for submitting an issue. I'm going to close this one for now since I believe @pgoslatara gave you a way to accomplish what you need.  Please reopen it with more details if this is not true.
