### ISSUE TITLE
[CT-461] Capture exceptions at top level of threads and cli

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#4357]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

discovered while coding up #4326. Somewhere in [here](https://github.com/dbt-labs/dbt-core/blob/a9b4316346e3c25b82fc59fa1f090e14b57a65db/core/dbt/adapters/base/impl.py#L191-L202) when an exception is raised, the thread just hangs and you have to step through a debugger to read the exception message. Exceptions should bubble all the way to the top even in threaded environments.

you can recreate this by making `fields_to_json` throw.

**Comment by gshank** [comment]
I saw a similar problem when adding the event_status dictionary to ParsedNodeDefaults. It hung executing a test in test/integration/059... because the SourceDefinition didn't have that attribute. Did not see anywhere the actual error, but since I had just added that attribute I guessed, added it to SourceDefinition, and it fixed it.

**Comment by nathaniel-may** [comment]
Estimation:
- guess is that when an exception is thrown inside a thread, it's not caught and handled correctly
- rpc server would benefit from this fix as well. Possibly fix existing tickets?
- This is basically one big unknown unknown
- Might be a better fit for the execution team
- suggesting a 2 day spike instead of estimating.

**Comment by gshank** [comment]
Note: this failure was experienced while running tests. On a particular type of test failure, the tests would hang and not complete. I was able to recreate this failure by removing "NodeInfoMixin" from the ParsedSourceDefinition class and executing: ".tox/py-integration/bin/python -m pytest -nauto --full-trace tests/functional/sources".  (The "--full-trace" was suggested by pytest.)  The resulting stacktrace started in /_pytest/main.py, and ended in threading.py, in the wait function, on the line "gotit = waiter.acquire(True, timeout)".

It looks like this might actually be a pytest threading/timeout issue and not an actual dbt thread hanging issue. It's possible that installing the pytest-timeout package and setting a timeout might help, but we'd have to experiment with the length of the timeout. Or maybe there's someplace in the test suite that we could be capturing exceptions that pytest would be happier with?

Since this looks like a pytest/testing issue rather than an actual dbt bug, I'm going to put this on the backburner.

**Comment by gshank** [comment]
Closing this issue in favor of new ticket #5602, as requested.
