### ISSUE TITLE
Duplicate dbt_utils folder when running dbt deps

### ISSUE THREAD

**Issue by abalila** [dbt-labs/dbt-core#4372]
### Describe the bug
When running `dbt deps`, it creates another dbt-utils folder which results in an error. The only way to be able to fix dbt from breaking, is to manually delete dbt-utils-x.x.x and not run dbt deps.
Running `dbt deps` and the duplicated folder will appear, but after going back and forth with deleting the folder and running the command again, all of a sudden the command would run successfully. Note, I deleted the duplicated folder after each time I got the winerror 32

### Steps to reproduce
Simply running the command `dbt deps`

### Expected results
Having `dbt deps` run successfully and receiving  a message `Up to date!` as a final output

### Actual results
When running the command `dbt deps`, a duplicate folder of dbt_utils will be created but with a specific version of the package. In the dbt_modules folder, there will be two dbt_utils folders (dbt_utils folder and dbt-utils-x.x.x folder) 

### Screenshots and log output
![image](https://user-images.githubusercontent.com/85891122/142641166-bbcc4fcd-d02d-422d-9c61-bb2c9bc3096a.png)
![image](https://user-images.githubusercontent.com/85891122/142641196-af221da5-b4ed-43e9-86ab-231af527ce20.png)

### System information
**The contents of your `packages.yml` file:**
The content in my `packages.yml` file is as follows
```
packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.7.0", "<0.8.0"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.21.0
   latest version: 0.21.0

Up to date!

Plugins:
  - bigquery: 0.21.0
  - postgres: 0.21.0
  - redshift: 0.21.0
  - snowflake: 0.21.0
```

### Additional context
As mentions above, when deleted the duplicated folder and running `dbt deps` several time, it will eventually execute correctly. In the screenshot below, I run the command everytime and deleted the duplicated folder right after each command until the command executed successfully
![image](https://user-images.githubusercontent.com/85891122/142642124-f15112d5-9b36-4445-b2e0-7ce58e85f1ed.png)

### Are you interested in contributing the fix?

``

**Comment by jtcohen6** [comment]
Great video, nice work reproducing @joellabes @jasnonaz!

I think there are two relevant spots to look at. First up, what's happening when you run `deps` for a Hub package:

https://github.com/dbt-labs/dbt-core/blob/d973ae9ec663259d224b4171ab5b27cc5200b5a3/core/dbt/deps/registry.py#L70-L74

Line by line:
1. Get the URL of the tarball (package) we want to download. This is after version/dependency resolution.
2. Download the tarball (package), with retries, and stick it in a temp location (`tar_path`). On my machine, that path resolves to something like `'/private/var/folders/7h/hj5_fw9j291c58hwfdvy5xbm0000gp/T/dbt-downloads-4xj3oo5t/dbt-labs/dbt_utils.0.7.4.tar.gz'`. (Note that the final name is `dbt_utils.0.7.4.tar.gz`, version number included)
3. Get the `deps_path`, the place this package actually wants to go. (In v1, we're renaming its default value from `dbt_modules` &rarr; `dbt_packages`)
4. Get the `package_name` for the package we just downloaded, i.e. the thing we actually want to call it (`dbt_utils`)
5. Use `system.untar_package` to extract all files from the tarball, _and_ rename the resulting directory to `package_name`

Ok! So let's look at `system.untar_package` in more detail. This is defined in the `dbt.clients.system` module, which is where we try to define common methods that handle differences across operating systems.

https://github.com/dbt-labs/dbt-core/blob/d973ae9ec663259d224b4171ab5b27cc5200b5a3/core/dbt/clients/system.py#L483-L494

Step by step:
1. Get the path where the package tarball has been stored (`'/private/var/folders/...'`)
2. We don't yet know the `tar_dir_name`, that is, the name of the folder that will be created when we extract the tarball
3. Open the tarball
4. Extract the tarball into a directory. _This is the step that creates a folder named `dbt-utils-0.7.4`_
5. Get the name of the just-created directory
6. If we're renaming the just-created directory (and indeed we are):
7. Get the relative path of the directory we just created (`'dbt_packages/dbt-utils-0.7.4'`)
8. Get the relative path of the directory we _desire_ to create (`'dbt_packages/dbt_utils'`)
9. Use `dbt.clients.system.rename()` to rename the directory from the current name to the desired name. _This is where the error must be occurring on Windows_. In particular, the rename is disallowed because Windows detects a symlink from `'dbt_packages/dbt-utils-0.7.4/integration_tests'`. The `rename()` method has logic that's meant to handle that symlinking, but it's clearly not working:

https://github.com/dbt-labs/dbt-core/blob/d973ae9ec663259d224b4171ab5b27cc5200b5a3/core/dbt/clients/system.py#L469-L480

At this point, we need someone with Windows expertise and/or a Windows machine (ideally both!) to help us figure out the right way to handle that rename

**Comment by joellabes** [comment]
> we need someone with Windows expertise and/or a Windows machine (ideally both!)

I have neither 😭

**Comment by sophiad96** [comment]
Just a heads up, I had a user report this happening with the fivetran/jira package as well.

**Comment by sophiad96** [comment]
@joellabes it was on the CLI! I should've mentioned that!

**Comment by eli-zarzar** [comment]
We're experiencing the same issue on the CLI in Windows with the fivetran/jira package. There are no issues when we run dbt deps in the cloud.

**Comment by dweaver33** [comment]
Same issue here for some Windows users.

**Comment by JasonMcKenzie1977** [comment]
I overcame this issue by installing dbt into a new directory. I got a similar error when trying to delete the old directory (Folder In Use - The action can't be completed because the folder or a file in it is open in another program). This prompted me to install [docs.microsoft.com/en-us/sysinternals/downloads/…](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to try to find what was hanging up... I couldn't see anything so I tried deleting the old directory again to see if that helped pinpoint things, but that time I was successful deleting it. Very strange...

**Comment by joellabes** [comment]
lol i wish, but keep it open

**Comment by andersbergren** [comment]
I had this problem using dbt-sqlserver 1.3.1 in VS Code on Windows and got it working by pausing my OneDrive sync

**Comment by joellabes** [comment]
Interesting @andersbergren! Is OneDrive configured to watch/sync/etc your dbt project's directory?

**Comment by natej-eb** [comment]
I'm having this same problem on Windows 10. I setup a new project and tried to start with `dbt-snowflake==1.4.1` and
```
packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0
```

Couldn't ever get it to work so I figured out that by downgrading to `dbt-snowflake==1.3.0` worked.

I've since upgraded `dbt-snowflake` to 1.4.2 via `pip install --upgrade dbt-snowflake` and the upgrade was successful. But I wanted to add a new package and running `dbt deps` failed again like it did before.

**Comment by tanderson-hp** [comment]
Not sure if this is what other people are seeing but I got past this by temporarily disabling the dbt-poweruser extension. It seems like it's related to this [issue in the dbt-poweruser extension](https://github.com/innoverio/vscode-dbt-power-user/issues/334)

**Comment by JasonMcKenzie1977** [comment]
> Not sure if this is what other people are seeing but I got past this by temporarily disabling the dbt-poweruser extension. It seems like it's related to this [issue in the dbt-poweruser extension](https://github.com/innoverio/vscode-dbt-power-user/issues/334)

That's interesting.  My colleagues and I have been overcoming this issue by closing out of VS Code and running dbt deps in Powershell.  It works every time & then we can resume working in VS Code.

**Comment by ElioAccardo-new** [comment]
For anyone running on VSCode: Disable Power User extension

https://discourse.getdbt.com/t/dbt-packages-error-cannot-access-the-file/7408/5
