### ISSUE TITLE
[Feature] Use Poetry for development

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-core#4446]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Poetry makes developing projects extremely easy, making getting started as simple as:

```
poetry install
poetry shell
```

**Comment by jtcohen6** [comment]
Thanks for opening @NiallRees, and so sorry for the long delay in getting back to you!

I haven't (yet) tried `poetry`, but broadly it reminds me of some thinking we did around `pipx` a year ago: https://github.com/dbt-labs/dbt-core/issues/3022

From perusing the docs, I sense that this change would/could involve:
- Replacing `setup.py` with `pyproject.toml`
- Updating `CONTRIBUTING.md` + `Makefile`
- Our [release process](https://github.com/dbt-labs/dbt-core/blob/main/.github/workflows/release.yml), which is (at least) much more clearly laid out than it used to be

Do you see the biggest benefit here as making it easier for external contributors to install `dbt-core` from source locally? That's a barrier I'm always interested in lowering

**Comment by NiallRees** [comment]
> Do you see the biggest benefit here as making it easier for external contributors to install dbt-core from source locally? That's a barrier I'm always interested in lowering

Yes absolutely. Poetry handles the creation of the development environment (no more venv invocation), and will create a poetry.lock file for a deterministic set of dependencies. There's also a bunch of other stuff which is over my head in relation to the [pyproject.toml and PEP 518](https://www.python.org/dev/peps/pep-0518/).

We should very soon see editable installations too once a new release is cut: https://github.com/python-poetry/poetry/issues/5056

**Comment by kwigley** [comment]
I attempted to do this with Core about a year ago. A blocker I ran into was due to the monorepo setup that dbt had at the time (dbt-core + dbt-postgres + dbt-snowflake + dbt-redshift + dbt-bigquery) and editable installing these packages for development. I wasn't able to figure out how to install local packages in editable mode when setting up a development environment and require the same packages from PyPI when publishing the packages without editing the `pyproject.toml`. This is probably not an issue anymore because:
1. the dbt package does not exist anymore
2. we split out the database adapters into separate repos

and, even if we still run into this issue, this may help! https://github.com/jacksmith15/poetry-workspace-plugin

I'm very much in favor of this! vitualenvs are.. not fun to manage

**Comment by iknox-fa** [comment]
> @iknox-fa have you ever used this with Python before? Just curious if you have any background on this

I have!  Poetry is nice, but in the long run I don't know that I'd ever advocate for enforcing it's use.  

That said, I would highly support switching to using pyproject.toml over the dumpster fire that is setuptools (or even in conjunction with setuptools if we have to).  

As @kwigley says though... we need to have fully separated repos for it to work (I'm looking at you `dbt-postgres`) well.  This has come up elsewhere recently so I made [a specific ticket for just that effort.](https://github.com/dbt-labs/dbt-core/issues/4674)
