### ISSUE TITLE
[Bug] dbt_project.yml does not fully support semantic versioning

### ISSUE THREAD

**Issue by b0lle** [dbt-labs/dbt-core#4453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

One can read [in the docs](https://docs.getdbt.com/reference/project-configs/version) that semantic versioning is supported. If so, pre-versions like 1.0.0-pre.1 should be supportes (as the link in the docs says).
Currently the version number causes a Runtime Error:
```
Encountered an error while reading the project:
  ERROR: Runtime Error
  at path ['version']: '0.0.0-pre.1' is not valid under any of the given schemas
```

```
# dbt_project.yml

version: '1.0.0-pre.1'
```

### Expected Behavior

Version 1.0.0-pre.1 should be an accepted version, because it follows the rules of [semantic versioning](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions)

### Environment

```markdown
- OS: macOS 11.5.2
- Python: 3.9.7
- dbt: 21.1
```

**Comment by jtcohen6** [comment]
@b0lle Thanks for opening!

The codepath for this one is fairly straightforward, and leads us to a comment indicating that `version` only supports "semver lite":

https://github.com/dbt-labs/dbt-core/blob/3fc715f06673f24718c761e5d0cf173766954816/core/dbt/contracts/project.py#L172

https://github.com/dbt-labs/dbt-core/blob/3fc715f06673f24718c761e5d0cf173766954816/core/dbt/contracts/project.py#L25-L40

At the same time, [the docs say](https://docs.getdbt.com/reference/project-configs/version):

> The version must be in a semantic version format, e.g. 1.0.0

Why not support real semver? Well... the `version` field isn't used for _anything_ today. It serves no functional purpose. But it is required, in all projects—and I could imagine it being useful for something, someday. In particular, there's no way currently to see the _currently installed versions_ of any packages, because there's no actual correspondence between the `version` in their `dbt_project.yml`, and the `version` (GitHub tag) specified in `packages.yml`. But imagine if they did correspond—if we did a good job of enforcing their alignment—which would unlock the ability for a `dbt deps freeze` to do something like:
```text
$ dbt deps freeze
dbt-utils==0.7.1
snowplow==0.13.0

Updates available for packages: ['dbt-labs/dbt_utils', 'dbt-labs/snowplow']
Update your versions in packages.yml, then run dbt deps
```
Currently, that version report is only available by running `dbt deps`, i.e. actually re-installing packages based on the specification in `packages.yml`.

So, I think we have two valid options:
1. Validate this via an actual semantic version specification, such as by using [`dbt.semver.VersionSpecifier.from_version_string`](https://github.com/dbt-labs/dbt-core/blob/0ed14fa2361c98e5119f52afebb3d5d8ee18c419/core/dbt/semver.py#L93)
2. Support any string in the `version` field, because it serves no functional purpose today. (If we do this now, though, it will be much harder to do anything useful with it in the future.)

I'm inclined to prefer the former: This should be a semantic version, rather than an anything-goes string. We already have logic (a whole module, even) dedicated to validating semantic versions.

I think the lift here would be pretty small, so I'm going to mark this a `good first issue`! Would you be interested in contributing the fix? :)

**Comment by alswang18** [comment]
I can handle this if no one else is @jtcohen6.

**Comment by b0lle** [comment]
I'm sorry @jtcohen6, I just didn't see your post.
Thanks for the explanation. Even though dbt does not use this flag, we have a use case where we extract the version from dbt_project to feed our CI/CD pipeline that creates a package in the package registry.

Thanks @alswang18 for creating the PR
