### ISSUE TITLE
[CT-64] Model `meta` missing from top-level node `meta` in manifest

### ISSUE THREAD

**Issue by troyel** [dbt-labs/dbt-core#4459]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

### Steps To Reproduce
Add any meta tags to a model. e.g.
```
{{ config(
    meta = {
    'single_key': 'override'
    }
    ) 
}}
```

Or similarly specified using .yml schemas.

### Expected behavior
Expect this to show up like it does in "Exposures" as a table detail formatted key-value list (also like tags does)

How it looks in a model:
![image](https://user-images.githubusercontent.com/22769102/145233967-2b936966-ba9a-4ca8-903d-bfac41994c38.png)
How it is expected to look (like it does implemented the same in an exposure):
![image](https://user-images.githubusercontent.com/22769102/145234238-8302eb08-23b1-4d9d-979d-f9e61b8656dd.png)

### Screenshots and log output

**The output of `dbt --version`:**
```
installed version: 0.21.0
   latest version: 1.0.0

Plugins:
  - spark: 0.21.0
  - postgres: 0.21.0
  - redshift: 0.21.0
  - bigquery: 0.21.0
  - snowflake: 0.21.0
```

**Comment by turbo1912** [comment]
related to the same problem, consumers of the `graph` jinja variable also have access to meta tag information of a model in `graph["model_name"].config.meta` rather than `graph["model_name"].meta`

**Comment by gshank** [comment]
The 'meta' dictionary is copied to the top-level node in core/dbt/parser/base.py, update_parsed_node_config. I would have thought that would be called for config in a model. Clearly there's some hole here.

**Comment by jeremyyeo** [comment]
@jtcohen6 continuing this from https://github.com/dbt-labs/dbt-docs/issues/230 - is there some sense in not having to duplicate the meta config to the top level meta for this?

Just thinking out loud since typically `manifest.json` gets to be quite large plus now we have to maintain logic that does the `node.config.meta` bits as well as the `node.meta` bits. On top of that we may introduce new `config` that we similarly want to display in the future thus having to duplicate them too. Feels a bit wasteful. But I suppose as you pointed out we want to keep to some expected behaviour (_editors note: but at the cost of manifest size and additional complexity_) and I'm certainly missing additional context on why we need to have this meta repeated.

**Comment by saraleon1** [comment]
+1 in dbt Core version 1.0.1 in dbt Cloud - let me know if there's any additional context I can provide!
