### ISSUE TITLE
[Feature] configure an alias on snapshots

### ISSUE THREAD

**Issue by jvenezia** [dbt-labs/dbt-core#4469]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

With standard models, we have the ability to configure an `alias` which makes the resulting database table name different from the model name.

This makes it easier to manage large projects, as all our models are prefixed with the schema name, bug generates a tables without the schema name.

Right now it is not doable for Snapshot. The table generated by snapshots always has the same name as the model.

### Describe alternatives you've considered

Overriding the Snapshot macro, or build snapshots ourselves.

Keeping the snapshot without aliases is not an option for us since it generates model naming collisions.

Example `my_system_1.users_history` and `my_system_2.users_history` are both referenced using `ref('users_history')`.

### Who will this benefit?

Everyone using Snapshot on large dbt projects.

**Comment by jtcohen6** [comment]
@jvenezia Thanks for opening!

Snapshots _do_ support the `alias` config, just like other resource types (models/seeds/tests/etc). Give this a try:

```sql
{% snapshot my_snapshot %}

{{
    config(
      target_schema='my_schema',
      unique_key='id',
      strategy='timestamp',
      updated_at='updated_at',
      alias='a_different_name'
    )
}}

select 1 as id, current_timestamp as updated_at

{% endsnapshot %}
```
For me, that looks like:
```
10:29:25  1 of 1 START snapshot my_schema.a_different_name..................................... [RUN]
10:29:36  1 of 1 OK snapshotted my_schema.a_different_name..................................... [SELECT in 10.85s]
```
And generates SQL like:
```sql
  create  table
    "database"."my_schema"."a_different_name"
...
```

I agree this is confusing because:

- The docs on `alias` are very sparse right now: https://docs.getdbt.com/reference/resource-configs/alias (one issue for improving them: https://github.com/dbt-labs/docs.getdbt.com/issues/890)
- The docs on "Snapshot configurations" do not include `alias` as an option: https://docs.getdbt.com/reference/snapshot-configs
- Snapshots use slightly different nomenclature for their other two namespace components, `target_database` (instead of `database`) and `target_schema` (instead of `schema`). This is to indicate that they behave differently across environments than other resource types. When it comes to `alias`, though, it's the same behavior as always.

I do think the resolution here is updates to docs.getdbt.com, rather than a change to `dbt-core` code. As such, I'm going to close this issue.

**Comment by jvenezia** [comment]
Thank you very much! Indeed it probably just needs to be more explicit in the docs :)
