### ISSUE TITLE
[CORE-20] [Bug] Jobs running on dbt 1.0.0 are failing when setup to defer to a pre 1.0.0 manifest

### ISSUE THREAD

**Issue by GideonShils** [dbt-labs/dbt-core#4470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a job with `defer` set is updated from a pre 1.0.0 version of dbt-core to 1.0.0, the job fails with the following error:

`Field "metrics" of type Mapping[str, ParsedMetric] is missing in WritableManifest instance`-

### Expected Behavior

Jobs with `defer` set should be able to be updated to dbt-core 1.0.0 without error.

### Steps To Reproduce

1. Have a job set to 0.21.1 (last pre-release)
2. Enable the defer option to defer to previous manifests of the same job
3. Run the job
4. Upgrade the job to 1.0.0
5. Run the job again

### Relevant log output

```shell
`Field "metrics" of type Mapping[str, ParsedMetric] is missing in WritableManifest instance`-
```

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by antongoncharuk** [comment]
Having the same issue in dbt cloud, works fine in the CLI.

<img width="2342" alt="ScreenShot 2021-12-10 at 15 52 46@2x" src="https://user-images.githubusercontent.com/55678713/145655081-12ae38b5-1447-43c1-82a5-85e899017d41.png">

**Comment by jtcohen6** [comment]
This is a tricky chicken-and-egg problem. Artifacts are versioned, such that we should be able to compare artifact version and raise a helpful error message:

https://github.com/dbt-labs/dbt-core/blob/3fc715f06673f24718c761e5d0cf173766954816/core/dbt/exceptions.py#L271-L296

That error message is supposed to be raised in the `try`/`except` where we raise this error:
https://github.com/dbt-labs/dbt-core/blob/3fc715f06673f24718c761e5d0cf173766954816/core/dbt/contracts/state.py#L16-L20

Unfortunately, we raise a different error here:

```python
ipdb> self.manifest = WritableManifest.read(str(manifest_path))
*** mashumaro.exceptions.MissingField: Field "metrics" of type Mapping[str, ParsedMetric] is missing in WritableManifest instance
```

Is there any way we can trip the `IncompatibleSchemaException` instead?

---

It would definitely be preferable to raise a different error message, one that more clearly indicates the cause of the problem is a version mismatch. The job would still fail, though.

In this particular case, there are things that dbt Cloud could do here to help, such as including dbt version in the deferral candidate logic: the run must be successful _and_ using the same dbt version as the current job definition. That's even more feasible, post-v1, since dbt Cloud will consider all versions `1.0.x` to be `1.0 (latest)`.

There's a desirable future world in which such logic would be _too_ strict, because artifact schema versions aren't changing with each new minor version of `dbt-core`. That's something we need to build toward.

**Comment by ChocoletMousse** [comment]
> Having the same issue in dbt cloud, works fine in the CLI.
> 
> <img alt="ScreenShot 2021-12-10 at 15 52 46@2x" width="2000" src="https://user-images.githubusercontent.com/55678713/145655081-12ae38b5-1447-43c1-82a5-85e899017d41.png">

I've also encountered this issue in the CLI when using the state:

![image](https://user-images.githubusercontent.com/40128954/146367409-e11b2166-f2fe-4b0b-8671-0ebe530ed499.png)

**Comment by leoebfolsom** [comment]
I see a PR is now open! Thank you @gshank and team. 

Just to clarify before I pull others on my team in, does this update make it so that I can run 

`dbt seed --select state:modified+ --full-refresh`

without the error:

`Field "metrics" of type Mapping[str, ParsedMetric] is missing in WritableManifest instance`

or will I still receive an error, but a more descriptive and clear one? Thank you!

**Comment by gshank** [comment]
Avoiding the state comparison is the right way to go. We can't load a pre-1.0.0 manifest because several of the field definitions have changed, so the "fix" is to give a better error message. Glad that you were able to get around it!
