### ISSUE TITLE
[Feature] Set default value for `--state` flag to be the target folder to enable local `dbt run --select result:error` based on previous run

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-core#4481]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Right now, running

```
dbt run   --select   result:error
```

without a `--state` flag results in a `No comparison run_results` error. It seems like it would be useful for the default flag value to be the target folder (or if that wouldn't work as the state is modified as it is referenced, some kind of `previous_state` folder which is auto generated).

### Are you interested in contributing this feature?

sure

**Comment by ChenyuLInx** [comment]
Hey @NiallRees, thanks for submitting this. I actually got very confused about those state configs when I was trying to reproduce #4570. From my experience and understanding, the problem here might have another solution: if you are doing a comparison and didn't specify state to compare to, dbt provides clearer warnings/error messages that tells you how to fix it(like you should add the --state that points to your previous manifest) rather than just a plain error. 
The reason we are thinking better error message over default location is that default location makes folks don't notice what they are comparing against right away thus might cause confusion. And you can also set this once via env var: `DBT_ARTIFACT_STATE_PATH=target`. 
Let us know what you think and whether you want to contribute a PR for it.

Thanks again!
