### ISSUE TITLE
[Bug] Macro dispatch/override of `ref` not working as explained in docs

### ISSUE THREAD

**Issue by harshadwaj** [dbt-labs/dbt-core#4491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Macro dispatch/override of `ref` not working as intended. Below is my test setup. It skips the custom `ref` logic and links to `person.sql` as usual.

```
   /core
        /macros/ref.sql
      
                {% macro ref(model_name) %}
                   {{ return(adapter.dispatch('ref','core')(model_name)) }}
                {% endmacro %}
                
                {% macro default__ref(model_name) %}
                   {% do log('coming here', info=true) %}
                   {# custom ref logic #}
                {% endmacro %}

  /project
    dbt_project.yml
       dispatch:
          - macro_namespace: dbt
            search_order: ['project', 'core', 'dbt']
    packages.yml
       - local: ../core
  
    /models
       person.sql
       test.sql
         select * from {{ ref('person') }}
```

### Expected Behavior

In the above test setup, it should print 'coming here' to the console & log thereby dispatching the custom logic macro in the linked package.

### Environment

```markdown
- OS: Windows 10 (WSL)
- Python: v3.9.5
- dbt: v1.0.0
```

### What database are you using dbt with?

snowflake

**Comment by jtcohen6** [comment]
@harshadwaj Thanks for opening, and for the really clear reproduction case!

The reason this doesn't work is because the global `ref` macro, within dbt, isn't dispatched—so it does not respect the project-level `dispatch` config. (In fact, it isn't even a proper Jinja macro—[it's a context property](https://github.com/dbt-labs/dbt-core/blob/0ed14fa2361c98e5119f52afebb3d5d8ee18c419/core/dbt/context/providers.py#L784), defined in Python.)

You _can_ get this working by splitting up your same logic across your `core` package + root project:
```
-- /project/macros/macro.sql
{% macro ref(model_name) %}
   {{ return(adapter.dispatch('ref', 'core')(model_name)) }}
{% endmacro %}
```
-- /core/macros/macro.sql
{% macro default__ref(model_name) %}
   {% do log('coming here', info=true) %}
   {# custom ref logic #}
{% endmacro %}
```

Because `ref()` has been reimplemented in the root project, it succeeds in overriding the builtin, and then tells dbt to go looking in the `'core'` package for valid implementations / dispatch candidates. From that point, the `dispatch` project config is not actually needed.

To make this work the way you'd expect, we'd need to dispatch `ref` _within_ dbt-core, which is tricky because `ref` is a context member, not a macro. I'd like to revisit this when we have the appetite to revisit macro resolution more broadly, in particular, I'd be interested in:
- "universalizing" dispatch capabilities to all macros
- making the adapter-specific prefixes optional
- finding a way to fit the oldest and most consistent behavior — "root project can always override any built-ins" — in terms that are consistent with how dispatch works

**Comment by harshadwaj** [comment]
Thanks @jtcohen6 for the explanation and the alternate solution. I was able to get it working based on your suggestion.

**Comment by harshadwaj** [comment]
As this answers my question and as @joellabes has raised separate issue to update the docs, I will be closing this.
