### ISSUE TITLE
[Bug] When installing dbt-postgres, env var for psycopg2 vs psycopg2-binary doesn't always work

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#4528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unlike the rest of the adapters which live in their own repo, `dbt-postgres` lives inside the codebase for `dbt-core`.  This behavior leads to inconsistencies and recently was root cause (or a large contributor) for a multi-hour outage in cloud.
(see incident #39).

### Expected Behavior

All dbt db adapters operate in the same way.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### Additional Context

Some additional context as to why `dbt-postgres` is a special snowflake:
https://github.com/dbt-labs/dbt-core/issues/3968#issuecomment-941081542

**Comment by iknox-fa** [comment]
@kwigley You did more looking into this than I did-- anything incorrect/missing here?

**Comment by jtcohen6** [comment]
It's true that `dbt-postgres` stands alone with respect to:
- Code location: `dbt-core` repo, instead of a separate `dbt-postgres` repo. This has implications for installing from source, including when we want to build Docker images.
- Versioning: lockstep with `dbt-core`

When it comes to installing fully released versions, however, `pip install dbt-postgres` should work just like all other adapter plugins.

Do we know for sure that it's _this_ attribute of `dbt-postgres`, rather than (e.g.) tricky system dependencies of `psycopg2`, that caused the multi-hour outage in Cloud?

> why `dbt-postgres` is a special snowflake

This gave me a good chuckle :)

**Comment by iknox-fa** [comment]
> Do we know for sure that it's this attribute of dbt-postgres, rather than (e.g.) tricky system dependencies of psycopg2, that caused the multi-hour outage in Cloud?

Yep.  The issue's primary root cause cause was a change in `setuptools` which caused `pip` to break on `pip install dbt-postgres` because we have to do special things with `setuptools` in `dbt-postgres`'s `setup.py` in order to make pip work correctly with the different code location..

**Comment by jtcohen6** [comment]
@iknox-fa Could you say more about this:

> we have to do special things with `setuptools` in `dbt-postgres`'s `setup.py` in order to make pip work correctly with the different code location..

Following @kwigley's explanations in the incident channel, my sense is that:
- `dbt-postgres` checks an environment variable at build time, `DBT_PSYCOPG2_NAME`, which can be either `psycopg2-binary` (default) or `psycopg2`. For some light background reading on this: https://github.com/dbt-labs/dbt-core/issues/1221#issuecomment-511546464
- dbt Cloud sets this env var to be `psycopg2` in its base image. Since this env var (with non-default value) must be checked at build time, we use `pip install --no-binary dbt-postgres`, i.e. installing from source rather than from wheel/binary
- The breaking change in `setuptools` causes it to use its own vendored version of `distutils`, rather than the `stdlib` version, and it sticks source-built code in a different location (`site-packages` instead of `dist-packages`)

That is, we would have run into this issue whether the `dbt-postgres` code was located in `dbt-core` or a separate repo. The determining factor is the need to build from source, given the need to check an env var at build time to identity the right `psycopg2` package dependency.

**Comment by kwigley** [comment]
Right on @jtcohen6! There is nothing particularly special about the dbt-postgres python package other than the fact that it can read an env var at when installing it from source as opposed to wheels to determine what `psycopg2` package to require. I just want to clarify that the dbt-core repository is a "monorepo" for both the dbt-core python package as well as the dbt-postgres package.

I don't think there is anything we can do today to avoid this other than documenting how this env var works and that it is only picked up when installing the package from the source distribution (https://github.com/dbt-labs/dbt-core/issues/4552#issuecomment-1005850984). I think we should keep our 👀 on https://github.com/psycopg/psycopg and explore using `extras_require` ([optional dependency docs](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies)) to avoid using an environment variable. E.g. `pip install dbt-postgres` and `pip install dbt-postgres[no-binary]` or something similar

**Comment by jtcohen6** [comment]
I'm going to retitle this issue to reflect the root cause of the issue

> E.g. `pip install dbt-postgres` and `pip install dbt-postgres[no-binary]` or something similar

@kwigley I missed this in your original comment! It sounds like there's a way we can get this working so that:
- `pip install dbt-postgres` still uses the `psycopg2` binary by default (easiest)
- offer a `[no-binary]` extra that's the equivalent of the [`--no-binary` pip flag](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-binary)
- move away from the env var, since this only works when installing from source (not wheels)

**Comment by bkktimber** [comment]
@jtcohen6 I found the related issue to this issue. My development setup runs in Docker on Apple Silicon machine has an issue with `psycopg2-binary`. It failed to connect to Postgres with this error:

> pg_connect(): Unable to connect to PostgreSQL server: SCRAM authentication requires libpq version 10 or above.

My workaround is to change `psycopg2-binary` to `psycopg2` and everything works perfectly.  My question is, should we `psycopg2` instead of the `psycopg2-binary`? Regarding [psycopg2's documentation](https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary):

>The psycopg2-binary package is meant for beginners to start playing with Python and PostgreSQL without the need to meet the build requirements.
If you are the maintainer of a published package depending on psycopg2 you shouldn't use psycopg2-binary as a module dependency. For production use you are advised to use the source distribution.

Is there any reason to use `psycopg2-binary` in the firt place?

**Comment by StefanoFedeli** [comment]
How did you manage to workaround the issue? Compiling the package from scratch ?

**Comment by bkktimber** [comment]
> How did you manage to workaround the issue? Compiling the package from scratch ?

Sorry @StefanoFedeli, I just saw your message. I simply switched to `psycopg2`. works like a charm!
