### ISSUE TITLE
[Bug] Test file skipped when referencing a non-existing model in bespoke test

### ISSUE THREAD

**Issue by Minjia-Z** [dbt-labs/dbt-core#4532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When writing a bespoke sql test for model A, sometimes other upstream models (model B) might be referenced in the test. If there is an error in model B (model B not yet exist, typo in name/prefix etc.) The entire test would be skipped therefore creating confusion and increase difficulty for debugging especially if the test is migrated from elsewhere or if the test is very long.

Currently, when above situation arises, we get the following message: 
`WARNING: Nothing to do. Try checking your model configs and model specification args`

### Expected Behavior

A reference error should be thrown rather than skipping the file entirely. Such as: the model "Model B" you reference does not exist. 

### Steps To Reproduce

1. Successfully creating a model
2. Write a bespoke test (model_A.sql) and reference upstream model B that haven't been created
3. run the test: dbt test .......

### Environment

```markdown
- OS:macOS
- Python: 3.9.6
- dbt:0.21.0
```

### What database are you using dbt with?

postgres

**Comment by jtcohen6** [comment]
@Minjia-Z Thanks for opening!

Starting in v1.0.0, dbt will report a warning (while parsing your project) if it comes across a test that's defined on / selecting from a disabled or nonexistent model.

For example, if I define a new singular (a.k.a. bespoke/data) test:
```sql
-- tests/my_custom_singular_test.sql
select * from {{ ref('my_fake_model') }}
```
Then:
```
$ dbt test
09:45:36  Running with dbt=1.0.0
09:45:36  [WARNING]: Test 'test.testy.my_custom_singular_test' (tests/my_custom_singular_test.sql) depends on a node named 'my_fake_model' which was not found
09:45:36  Found 0 models, 0 tests, 0 snapshots, 0 analyses, 165 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
09:45:36
09:45:36  [WARNING]: Nothing to do. Try checking your model configs and model specification args
```

If I enable the [global config to treat warnings as errors](https://docs.getdbt.com/reference/global-configs#warnings-as-errors), this warning will return an error instead, just as you had in mind:
```
$ dbt --warn-error test
09:50:03  Running with dbt=1.0.0
09:50:03  Encountered an error:
Compilation Error
  Test 'test.testy.my_custom_singular_test' (tests/my_custom_singular_test.sql) depends on a node named 'my_fake_model' which was not found
```

I'm going to close this issue, since I believe it's resolved by a newer version of dbt.
