### ISSUE TITLE
[CT-26] Pre-hooks should be conditional while runnning a DBT job

### ISSUE THREAD

**Issue by AuroChowdhury-UA** [dbt-labs/dbt-core#4555]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Here is an observation, let's say if we are deleting data from the same table in pre-hook and if there is metadata change and even though we are running with the  Full-refresh option it's failing as the Delete statement is using a new attribute, now I understand that this might be working as designed but I think if we are saying Full-refresh then ideally the pre-hook part should be skipped if there is any DML operation happening on the same table, else there needs to be a manual intervention of dropping the table first and checking if the table exists then only run the pre-hook.

Now if we have an option in the dbt build/run the command as a boolean value to select the pre-hook that needs to be run that will enable us not to drop the table in case there is any metadata change.

### Describe alternatives you've considered

There needs to be a manual intervention of dropping the table first and checking if the table exists then only run the pre-hook .

### Who will this benefit?

This will beneficial during deployment as the developer can just pass an option and skip the pre-hook and not involve the DBA.

### Are you interested in contributing this feature?

I would ave loved to but my work schedule is too demanding right now

### Anything else?

I have spoken with Sung and he also sees value in this so I am pretty sure others will as well, as the idea is to make DBT  more stateless.

**Comment by sungchun12** [comment]
@AuroChowdhury-UA, can you provide a code snippet of the pre-hook you're running that outputs conditional results? I can see a pre-hook exiting its functionality similar to how python has `sys.exit()` depending on the query results.

For the actual feature, do you imagine a command like?: `dbt run --skip-pre-hook`

**Comment by AuroChowdhury-UA** [comment]
Sure .

@Saini, Deepak ***@***.***> Can you please provide the same ?

**Comment by ChenyuLInx** [comment]
Hey @AuroChowdhury-UA, @jtcohen6 also mentioned that there are also (flags)[https://docs.getdbt.com/reference/dbt-jinja-functions/flags] you can access in pre-hook logic/macro, including flags.FULL_REFRESH (true/false) and flags.WHICH (run, build, test, etc), and use that to condition the hook logic accordingly.
But we kind of believe that the intended use case is a bit of dbt anti-pattern since we encourage all DML/DDL should live in the materialization logic, which can be fully context / invocation-aware. Also doing so might cause the model SQL to no longer be an idempotent transformation(if the prehook accidentally runs twice, no guarantee it will yield the same results).
