### ISSUE TITLE
[CT-31] [Bug] Macro in compile command

### ISSUE THREAD

**Issue by chaimt** [dbt-labs/dbt-core#4563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running dbt compile, all macros are run, and some cannot run without other external contexts.
This is not how it should work.
Additional packages like dbt_mock and dbt_expectations, for running need connection to db and other prerequisites. 
I do not expect this to be the case for compile.

### Expected Behavior

Each macro should take into consideration the compile flag, and not run, just compile the code

### Steps To Reproduce

1. clean env
2. run with package (dbt_mock, dbt_expectations...) that need external connection
3. dbt compile will fail
4. only dbt run will succeed, then dbt compile will work

### Environment

```markdown
- OS: mac
- Python: 3.9.9
- dbt: 1.0.0
```

### What database are you using dbt with?

other (mention it in "Additional Context")

**Comment by emmyoop** [comment]
@chaimt thanks for writing this up!   The `compile` command needs a database connection because when compiling the sql, it may need to run introspective queries against the database in order to template out the model SQL.  Two common introspective queries are `run_query` and `get_columns_in_relations`, both of which `dbt_expectations` use.  If the tables do not yet exist, those introspective queries fail and so `dbt compile` fails.  

It's important to note when you run `dbt compile` [`execute`](https://docs.getdbt.com/reference/dbt-jinja-functions/execute) is actually `True` because dbt may need to connect to the database for those introspective queries.  The `compile` and `run` commands are more similar than they seem at first.  The most important difference is that `dbt run` materializes the tables/views/etc in the database while `dbt compile` _does not._

I think it may also be worth noting, although I'm not sure if this is relevant to your specific use case, that you can use `dbt ls` to parse your project and generate the `manifest.json` file without a database connection.  It will not however produce the `compiled_sql` in `manifest.json` since it is not compiling it.

We've opened up issue [#922](https://github.com/dbt-labs/docs.getdbt.com/issues/922) to add more documentation around this, as this is a common question that gets asked.  I'm going to close this as it isn't a bug.  It 100% needs more documentation around the behavior though!

**Comment by tphillip33** [comment]
@emmyoop   I agree with your response on the current behavior.    However, I still have a need for a "compile flag" to indicate dbt is compiling vs running.

In my case, I have a macro which inserts a row into a table indicating it is running.  When dbt compile runs, execute = true and the code inserts a row into the database indicating it is running, which it is not.  This causes downstream impact, indicating the process ran, when it actually did not.

I understand the rational, but we need a "compile" flag to test against to exclude this row insert from dbt compile.

**Comment by dbeatty10** [comment]
Hey @tphillip33 👋 

There's actually a "compile flag" that you can use:
- [`flags.WHICH`](https://docs.getdbt.com/reference/dbt-jinja-functions/flags)

Here's a couple examples of it in use:
- https://github.com/dbt-labs/dbt-utils/blob/eb1292268b58c0ba1ab6a2c8ec062a53f3955a62/macros/sql/star.sql#L16-L18
- https://github.com/dbt-labs/dbt-utils/blob/eb1292268b58c0ba1ab6a2c8ec062a53f3955a62/macros/sql/union.sql#L76-L80

Could you take a look and see if it meets your needs?

**Comment by dbeatty10** [comment]
🙌 awesome @tphillip33 !

I'm going to close this issue in favor of an addition to the docs that I just opened:
- https://github.com/dbt-labs/docs.getdbt.com/issues/2825
