### ISSUE TITLE
[CT-46] [Feature] Better error messages: include filename for SQL compilation errors

### ISSUE THREAD

**Issue by tekumara** [dbt-labs/dbt-core#4574]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

When encountering a compilation error it's not clear which file the error is in, eg:
```
$ dbt run-operation drop_dev_schema
04:09:46  Running with dbt=1.0.1
04:09:49  Encountered an error while running operation: Database Error
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 29 unexpected '-'.
```

### Who will this benefit?

Anyone trying to debug compilation errors

### Are you interested in contributing this feature?

Yes

### Anything else?

dbt 1.0.1

**Comment by jtcohen6** [comment]
Agree that this would be valuable!

My sense is that the log message here is coming from the `RunningOperationCaughtError` event:

https://github.com/dbt-labs/dbt-core/blob/72ecd1ce74641ea0675399f251564cc7f7fbf974/core/dbt/task/run_operation.py#L58-L61

https://github.com/dbt-labs/dbt-core/blob/72ecd1ce74641ea0675399f251564cc7f7fbf974/core/dbt/events/types.py#L1132-L1138

The line numbers here are from the database (Snowflake), and they represent the line/position in _the templated SQL_ where the database is encountering the error, rather than the line in the original macro file/code. That mapping is pretty difficult for us to create today.

The actual entrypoint to the `run-operation` functionality is https://github.com/dbt-labs/dbt-core/blob/72ecd1ce74641ea0675399f251564cc7f7fbf974/core/dbt/adapters/base/impl.py#L935, and the entrypoint to actually running SQL are these line:
https://github.com/dbt-labs/dbt-core/blob/72ecd1ce74641ea0675399f251564cc7f7fbf974/core/dbt/adapters/base/impl.py#L989-L992

That is, the same functionality we hook into when we execute materializations. We're just calling a macro, that might call arbitrary other macros, that call `run_query` / a `statement` block, that (in turn) [call `adapter.execute`](https://github.com/dbt-labs/dbt-core/blob/72ecd1ce74641ea0675399f251564cc7f7fbf974/core/dbt/include/global_project/macros/etc/statement.sql#L10).
