### ISSUE TITLE
[CT-54] [Bug] dbt --version doesn’t identify patch releases as candidates for upgrade

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#4582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run dbt --version with 1.0.0 installed, I get: 
```
(dbt-prod) joel@Joel-Labes GitHub % dbt --version
installed version: 1.0.0
   latest version: 1.0.0

Up to date!

Plugins:
  - snowflake: 1.0.0
  - postgres: 1.0.0
```

Even though 1.0.1 is out. 

When I run `(dbt-prod) joel@Joel-Labes GitHub % pip install dbt-core dbt-postgres --upgrade`, followed by `dbt --version`, I then get 
```
(dbt-prod) joel@Joel-Labes GitHub % dbt --version                              
installed version: 1.0.1
   latest version: 1.0.1

Up to date!

Plugins:
  - snowflake: 1.0.0
  - postgres: 1.0.1
```

### Expected Behavior

It not to say `Up to date!` when the 1.0.1 patch of Core is available. 

not sure how it should behave when there's a patch for an adapter but not core (would that ever happen?)

### Environment

```markdown
- OS: MacOS
- Python:
- dbt: 1.0.0
```

### What database are you using dbt with?

snowflake

**Comment by jtcohen6** [comment]
I think this was resolved in https://github.com/dbt-labs/dbt-core/pull/4434 (i.e. in v1.0.1). There was a bug in v1.0.0 code such that it was still checking PyPi for the latest available version of a package named `dbt`, rather than `dbt-core`.

---

_That said_, the fixed code in v1.0.1 is still only going to report "Your version of dbt is out of date!" for `dbt-core`. It won't check whether there's a newer version of specific plugins. So, for instance, if/when we release `dbt-snowflake==1.0.1`, you'd still see:
```
(dbt-prod) joel@Joel-Labes GitHub % dbt --version                              
installed version: 1.0.1
   latest version: 1.0.1

Up to date!

Plugins:
  - snowflake: 1.0.0
  - postgres: 1.0.1
```

https://github.com/dbt-labs/dbt-core/pull/4565 adds messaging around whether the installed version of an adapter plugin is compatible with the installed version of `dbt-core`. We could also look into adding checks for each installed plugin, to see if they have a newer compatible version available—at the teensy cost of a bit more semver logic, and a few additional requests to the PyPi API.

For now, I think I'm going to close this issue as resolved. If you think it's important to get plugin-specific "up to date" / "out of date" checks, could I ask you to comment over in #4438 / #4565?
