### ISSUE TITLE
[CT-70] [Feature] Public API returns task or task.manifest

### ISSUE THREAD

**Issue by ismailsimsek** [dbt-labs/dbt-core#4593]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Is there public api to return `task` or `task.manifest.`  which is useful to integrate db to external applications like airflow

Currently `handle_and_check` is not returning `task`, if it was that would work too. 

having manifest.nodes makes it possible to create Airflow dag with granular tasks( a task per model) with correct dependencies.

example:

1. run dbt parse
2. retrieve manifest 
3. create airflow DAG tasks per `manifest.node` with correct dependencies (using `manifest.node.depends_on`)

this makes it possible to run some custom checks before running model
for-example running tests on all source dependencies and then running the model. 

related #2013

### Who will this benefit?

Anyone using dbt with Airflow

**Comment by gshank** [comment]
The dbt 'parse' command with the '--write-manifest' option will write out the manifest.json file, which is the official interface for that information. From the manifest.json you could get the node and depends_on information.

Since we do provide an official source of this information, I'm going to close this ticket, but if you feel that this doesn't address your needs, please update with additional information.

**Comment by ismailsimsek** [comment]
@gshank what are the advantages of json file over public api/(direct python integration)?
