### ISSUE TITLE
[CT-74] [Feature] dbt should parse only selected nodes (so that models can run concurrently if their parent model happen to be excluded)

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#4597]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

As far as I can tell, if someone were to execute `dbt run --select tags:a`:
1. At the start of the dbt invocation, dbt parses all the files in the project and constructs the manifest of every object (`--select` does not do anything here).
2. The manifest contains each model's dependencies (which model to run before others) - this establishes the DAG.
3. dbt looks at all models in the manifest and throws out those not in our selection.
4. dbt runs the models in the selection - the order of which was determined in (2).

This means that, for a project with 4 threads and the following 3 models:

```sql
-- my_model_1.sql
{{ config(tags = 'a') }}
select  * from some_table

-- my_model_2.sql
{{ config(tags = 'b') }}
select * from {{ ref('my_model_1') }}

-- my_model_3.sql
{{ config(tags = 'a') }}
select * from {{ ref('my_model_2') }}
```

dbt will always run the models one by one (effectively single threaded) even if `my_model_2` was excluded from the selection:

![image](https://user-images.githubusercontent.com/8496748/150314643-910e703c-2192-466a-987c-fa5fb4906c22.png)

----

Should dbt be able to run `my_model_1` and `my_model_3` concurrently if `my_model_2` is excluded (essentially we have to take `--select` into account during parse time)? 

I think the status quo makes sense in situations where say `my_model_2` was a "view" - this means that table `my_model_1` completes, then `my_model_3` updates selecting from the view `my_model_2` which now has the latest updates to `my_model_1`.

There may be some other scenarios where a user may no longer want `my_model_2` (as a "table") to be updated somehow (at which point they could turn it into a `source`? Or perhaps they want `my_model_2` to be updated in some other `dbt run` job instead.

Should we allow users to have agency of having the DAG be built up of only resources in the selection? Thought I'd put this here for discussion. :) 

### Describe alternatives you've considered

NA

### Are you interested in contributing this feature?

Yes

**Comment by jtcohen6** [comment]
(Note to colleagues: I tagged this one for `Execution`, despite the word "parse" in the issue title, because it's actually a question about graph behavior / queuing when selecting a subset of nodes. Put another way: Should we skip [creating transitive edges when removing unselected nodes](https://github.com/dbt-labs/dbt-core/blob/3032594b26aaafaf1003db513645660d0e7c89dc/core/dbt/graph/graph.py#L83-L112)?)

**Comment by ChenyuLInx** [comment]
@jeremyyeo Thanks for opening this! Sorry for getting back to it late! I am trying to understand this more. 
Sounds like the materialization of `my_model_2` matters a lot here. If it is a table, then we can run `my_model_1` and `my_model_3` in parallel. But if it is a view, then we will actually have to have the transitive edges between `my_model_1` and `my_model_3` since the result of a view depends on the original table? I guess that's why the original transitive edge is added. 
I think it makes sense from a technical point to not create that transition edge if an unselected node is a table. How often of a use case do you expect that to be? Given that the `my_model_3` in this case is running on potentially staled data in this selection.
Let me know if I missed anything!

**Comment by jtcohen6** [comment]
I think DAG validity is very very important for end users of dbt—both as perception and reality. To @ChenyuLInx's point, we'd need to introspect the materializations of the middle model (table vs. view vs. ???) to understand whether we can safely run the third model concurrently with the first. For the time being, I think our safest bet is to _always_ run them in order, even at the cost of slightly slower runs.

This does have interesting overlap with the conversations we're having around more complex scheduling / DAG traversal...

If a user really wants to, they can take matters into their own hands, and kick off two concurrent executions — `dbt run -s my_model_1` and `dbt run -s my_model_3` — with all the risk that it entails.
