### ISSUE TITLE
[CT-75] [Feature] Per-query retry strategy for all adapters (currently available only for BigQuery)

### ISSUE THREAD

**Issue by jvenezia** [dbt-labs/dbt-core#4598]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Currently only the BigQuery adapter has a retry option on the query-level: https://docs.getdbt.com/reference/warehouse-profiles/bigquery-profile#retries

This would be very useful to have in other adapter. 
I am particularly interested in Redshift but I think it could be useful to have globally implemented (not specific for an adapter) in dbt.

### Describe alternatives you've considered

Isolate the models that needs retries and use our own retry methods (Airflow or custom...).

### Who will this benefit?

All dbt users, especially with large code bases with many concurrent runs which I believe increases the change to have unexpected errors (`could not open relation with OID 123...`).

### Are you interested in contributing this feature?

I can't unfortunately.

**Comment by nathaniel-may** [comment]
Hi, @jvenezia! Thanks for the feature request. The BigQuery adapter has the best support for retries because BigQuery provides it via their API and we just pass along the configured value. Today, the [Spark](https://github.com/dbt-labs/dbt-spark/pull/194) and [Snowflake](https://github.com/dbt-labs/dbt-snowflake/pull/6) adapters each have much more rudimentary adapter-side implementations so something similar is likely possible for the remaining adapters as well.

For Redshift specifically, there is already another open issue: #3303. Please feel free to join the conversation over there. In the interest of keeping the conversation streamlined I'm closing this issue as a duplicate.
