### ISSUE TITLE
[CT-80] [Bug] post-hook macro generates SQL with incorrect source table

### ISSUE THREAD

**Issue by tekumara** [dbt-labs/dbt-core#4606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

_lineitem.sql_:
```
{{ config ( materialized='incremental',
   post_hook=[insert_synclog()]
    ) }}
....    
```

_insert_synclog.sql_:
```
{% macro insert_synclog() -%}

SELECT ...
FROM {{ source('upstream', 'extractlog') }}

{% endmacro %}
```

Instead of using the source, the macro uses `this`, ie the post hook macro generates this SQL statement:

```
SELECT ...
FROM mydb.lineitem
```

### Expected Behavior

The macro post hook generates the SQL:
```
SELECT ...
FROM upstream.extractlog
```

### Environment

```markdown
- OS:
- Python:
- dbt: 1.0.1
```

### What database are you using dbt with?

snowflake

**Comment by tekumara** [comment]
Looks like the same issue as https://github.com/dbt-labs/dbt-core/issues/3985.


And the current solution is to use a substitution in the post hook:

```
{{ config ( materialized='incremental',
   post_hook=["{{ insert_synclog() }} "]
    ) }}
```

**Comment by emmyoop** [comment]
Awesome that you found the duplicate #3985 @tekumara.   I'm going to close this as a duplicate.  Feel free to reopen it if you have issues with the proposed solution.

**Comment by jtcohen6** [comment]
Just going to call out (as I think I did on #3985 too) that the nested-curly syntax is pretty gnarly, and definitely not intuitive.

I'm not convinced this is the right answer, but I keep coming back to thinking that we should re-render certain configs (such as post hooks) at compilation/runtime. In order to do that, though, we'd need to extract the unrendered config value at parse time, via something like static analysis/extraction.
