### ISSUE TITLE
[CT-139] [Bug] Database Error: Failed to Connect

### ISSUE THREAD

**Issue by faithlierheimer** [dbt-labs/dbt-core#4662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="699" alt="Screen Shot 2022-02-02 at 9 53 23 AM" src="https://user-images.githubusercontent.com/54042545/152200898-dc7b561b-c6d0-4120-b17d-946684c84058.png">

When I try to run dbt locally, I receive this vague error that is difficult to debug. dbt seems to be receiving the information that it expects based on the profiles.yml and dbt_project.yml being read as valid. It errors out at the connection and says it finds an error, but the only error it gives is "Runtime Error/Database Error/failed to connect." 

This is confusing and frustrating because the profile that I have provided dbt is identical to the profile I provided to dbt cloud, but for some reason dbt will not run locally with the exact same credentials. The error message is vague and I am not sure what else to do and need help. I have also attached my profile information with the sensitive parts blacked out. 

<img width="476" alt="Screen Shot 2022-02-02 at 9 50 17 AM" src="https://user-images.githubusercontent.com/54042545/152201411-c0f18439-580b-4a49-8262-f72db67fe16d.png">

### Expected Behavior

I expect a more detailed error when I try to run dbt locally--what about the connection failed? Is the token invalid? is the SQL endpoint invalid? Is the host wrong? Something other than 'failed to connect' and 'check your credentials'. My credentials are identical to dbt cloud, and dbt cloud works fine. 

### Steps To Reproduce

1. in the dbt repository, run `source ./dbt-env/bin/activate` in the terminal
2. in the top-level folder (dbt), run 'dbt run' in the terminal. 
3. receive the error pictured belo
<img width="1096" alt="Screen Shot 2022-02-02 at 10 06 27 AM" src="https://user-images.githubusercontent.com/54042545/152202154-753eece4-f27e-4873-b831-a7bd505461e3.png">
<img width="1096" alt="Screen Shot 2022-02-02 at 10 06 27 AM" src="https://user-images.githubusercontent.com/54042545/152202365-da2b4a6d-d5ba-41ae-8085-416dbc1ea5ce.png">
w

### Environment

```markdown
- OS:Big Sur 11.6
- Python: 3.9.7
- dbt:1.0.1
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

using databricks plugin 1.0.0

**Comment by jtcohen6** [comment]
@faithlierheimer Thanks for opening this detailed bug report!

The connection that dbt uses to each database is defined in the adapter plugin for that database. That's also where the logic needs to live for more detailed error information, in the event that the connection fails. As such, I'm going to close this issue, since `dbt-databricks` (not `dbt-core`) would be the right spot for a related code change. (This repository can be a good place to discuss general-purpose approaches that we might recommend for each adapter plugin to follow / implement themselves, e.g. https://github.com/dbt-labs/dbt-core/issues/3828.)

If your aim is to get help debugging the specific local connection, I'd encourage you to post [on StackOverflow](https://stackoverflow.com/questions/tagged/dbt), or in the #db-spark-databricks channel in [the dbt Community Slack](https://www.getdbt.com/community/).

If you have a specific request for a code change in `dbt-databricks`, such as more error message details / error chaining from dependencies, I'd encourage you to re-open a similar issue over there: https://github.com/databricks/dbt-databricks/issues/new/choose

**Comment by Crimsonabyss** [comment]
I had the same issue and this is how I fixed it:
https://stackoverflow.com/questions/72291367/can-not-connect-dbt-cloud-or-dbt-core-to-databricks
