### ISSUE TITLE
[CT-153] [Feature] Expose the meta field as a query parameter for Metadata API calls

### ISSUE THREAD

**Issue by BrJan** [dbt-labs/dbt-core#4663]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Enable the meta data field to be queryable for the following API calls -
https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-api/metadata/schema/metadata-schema-sources
https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-api/metadata/schema/metadata-schema-models

### Who will this benefit?

This'll help dbt user who leverage the Metadata API.

Requested by Loft.

**Comment by jtcohen6** [comment]
Thanks @BrJan!

This one is for the Metadata team at dbt Labs (cc @barryaron). My understanding is that `meta` is available as a field for metrics, but not yet for other node types.

I will note that there's a _related_ Core issue we need to resolve, to ensure that all `meta` fields are consistently represented in the node's `meta` dictionary in `manifest.json`: https://github.com/dbt-labs/dbt-core/issues/4459. This is an outcome of `meta` being configurable in many more places (since v0.21), and wanting to consolidate all `meta` values into a single dictionary, for ease of downstream parsing. Otherwise, downstream metadata consumers (both `dbt-docs` + Metadata API) will need to check the values in both `node.meta` and `node.config.meta`. We're planning that fix for a future v1.0 patch release, targeting v1.0.3 in March.
