### ISSUE TITLE
[CT-154] [Feature] DBT project cutter

### ISSUE THREAD

**Issue by cove9988** [dbt-labs/dbt-core#4667]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

## DBT project cutter
Shall we develop a command-line utility that creates a project from project templates adopting DBT solution? The project initialization contains readme with the best practices and development guide, its required project folder structure, sample files in model, macro and data and test folders etc... It also can build required virtual environment or docker as a project needs

## Background
My company starts to adopt DBT for data pipeline from sources into data warehouse. However, different project teams have different understanding and approach to manage their project branches, which cause headache and conflict when merge into master repository and deploy to production.

I have developed some scripts for dbt project initialization (DBT project cutter). If there is a beneficial for our community. I would like to initial a project for it.

## sample model file
./model/example.sql
```sql
-- --------------------------------------------------------------------------------------------------------------------------------------------------
-- VERSIONS  DATE          WHO                      DESCRIPTION
-- 1.00      {{ date }}    {{ creator }}            Initial
-- --------------------------------------------------------------------------------------------------------------------------------------------------
-- DO NOT USE objects directly, 
--    USE source() call to reference external defined in the source.yml
--    USE ref() call to reference other dbt models.
-- DO NOT include DDL code such as CREATE or DROP VIEW in object file
-- DO NOT include any semicolon “;” in the file, or the script will fail
-- DO NOT have “Grant” permissions statements 
-- Highly repeating code or reusable code can be turned into loops and macros, to speed up future development and increase the readability of the code. 

{% snapshot {{ file_name }} %}

{{
    config(
      target_schema=generate_schema_name('curated_source'),
      unique_key='business_key',
      pre_hook=before_begin("{{ delta_load_job_control_start('" ~ this.identifier ~ "') }}"),
      distributed_by='business_key',
      post_hook="ANALYZE {{ this }}", 
      strategy='timestamp',
      updated_at='update_time',
      invalidate_hard_deletes=True
    )
}}

{% if execute %}

SELECT 
-- your columns here
FROM {{ source('{{ source_schema }}','{{ file_name }}') }} alias

{% endif %}

{% endsnapshot %}
```

### Who will this benefit?

DBT project developer

### Are you interested in contributing this feature?

Yes

**Comment by cove9988** [comment]
A different project type, source connector, can have its own template which can predefined/user altered into configuration file. Furthermore, we can build a check-validation bot based on the best practice and user rule definitions which will be triggered when user submit a PR.

**Comment by jtcohen6** [comment]
@cove9988 Thanks for opening, and sorry for the delay getting back to you.

We had something like this a long time ago for consulting projects: https://github.com/dbt-labs/dbt-init

I do think the right place for this issue, like all "dbt source code generation," is in packages and plugins external to `dbt-core`. (E.g. [`codegen` package](https://hub.getdbt.com/dbt-labs/codegen/latest/), [`dbt-generator` tool](https://github.com/tuanchris/dbt-generator).) `dbt init` is an exception to this rule, since it is built right into `dbt-core`, but I want to keep its intended use case narrow in scope: someone's _very first_ experience using dbt, right after installing it on their machine. If an organization wants to customize that experience for its newest dbt developers, to provide org-specific context and guidance—power to them!

I saw you opened a discussion too (https://github.com/dbt-labs/dbt-core/discussions/4666), and I think that's the right place for something like this going forward. I'm going to close the issue to keep the thread centralized over there.
