### ISSUE TITLE
[CT-156] [Bug] dbt build --full-refresh is not running a full-refresh seed 

### ISSUE THREAD

**Issue by senickel** [dbt-labs/dbt-core#4669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I change a column name in an existing seed and I run `dbt build -s my_model --full-refresh` I get the error 
```
000904 (42000): SQL compilation error: error line 82 at position 11
invalid identifier 'NEW_COLUMN_NAME'
```

If I run a `dbt seed --full-refresh` beforehand the `dbt build` command from above works.

### Expected Behavior

I would expect that there is no necessity for running `dbt seed --full-refresh` as it is outlined in the [documentation](https://docs.getdbt.com/reference/commands/build):  "build will use the same value for all selected resource types (e.g. both models and seeds will be full refreshed)." 

### Steps To Reproduce

1. use seeds in your model and build it all from scratch
2. change the column name of the seed (and where you reference it in your model)
3. run `dbt -s your_model --full-refresh`
4

### Relevant log output

```shell
000904 (42000): SQL compilation error: error line 82 at position 11
invalid identifier 'NEW_COLUMN_NAME'
```
```


### Environment

```markdown
- OS:Ubuntu 20.04
- Python: 3.9.9
- dbt: 1.0.1
```

### What database are you using dbt with?

snowflake

**Comment by leahwicz** [comment]
Hi @senickel! Thanks for opening up an issue! 

I see what's going on here. When you change the existing seed's column name, you are correct that you need to run `seed` again to pull in that change. The problem is that running `dbt -s your_model --full-refresh` does not run `seed` (like you is seeing happen). 

The reason `seed` is not run with this specific command is that `--full-refresh` runs differently than you are expecting. This is a [better description here](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#how-do-i-rebuild-an-incremental-model) explaining it, but that flag is for when incremental models need a full rebuild but that doesn't mean any of the upstream dependencies of it is also rebuilt. You are just selecting that specific node to perform the refresh on. 

To also have `seed` run in this scenario, you can do a couple things:
* Remove the selection entirely: `dbt build --full-refresh`
   * This will refresh every node so that might be overkill for you scenario
* Select the model and all it's upstream dependencies: `dbt build -s +my_model --full-refresh`
   * This would be good if you are looking to change multiple upstream dependencies instead of just a single seed.
* Select the model and the seed: `dbt build -s my_model my_seed --full-refresh`
   * This is very specific and targeted to the given seed and model but will do the minimal amount of work needed if that is all you will ever do.

Does this make sense?
