### ISSUE TITLE
[CT-166] [Bug] accepted_values test causing  OSError: File name too long

### ISSUE THREAD

**Issue by treeforest456** [dbt-labs/dbt-core#4684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have 12 accepted values defined in the `accepted_values` test list. When running this, it gives this OSError
```
OSError: [Errno 36] File name too long: '/home/********/project/project-name/target/test.folder.source_accepted_values_very_long_accepted_values_strings.123456789.html'
```

### Expected Behavior

Maybe a better way to generate test file names? Or maybe document somewhere that there could be a limit of number of accepted values defined in the list?

### Environment

```markdown
- OS: macOS Big Sur, version 11.5.2
- Python: 3.9.5
- dbt: 1.0.0
```

### What database are you using dbt with?

snowflake

**Comment by nathaniel-may** [comment]
Hi, @treeforest456! Thanks for the report, and I'm sorry to hear you're having issues running tests. We have run into issues with the way we internally uniquely identify test nodes before and it seems the file path that is too long for your file system is caused in part by the unique identifier being too large.

[I left a comment](https://github.com/dbt-labs/dbt-core/issues/3348#issuecomment-1031840405) on a previous issue to propose a long-term fix, and I wanted to point you to [a proposed short-term fix in this ticket](https://github.com/dbt-labs/dbt-core/issues/3626#issuecomment-886694083) which is identified as a good first issue for a community PR, and I believe would solve your issue as well.

Unfortunately, I cannot think of any workarounds for your particular issue that do not involve a code change to dbt.

Since this ticket specifically calls out the inability to write test results because of the filepath length, I do not believe this issue is a duplicate and will leave it open until resolved.
