### ISSUE TITLE
[CT-174] [Bug] Table names and not escaped when using dbt seed

### ISSUE THREAD

**Issue by lmmentel** [dbt-labs/dbt-core#4694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am aware that it is not good practice, however I have a table name `Group` for which I was to upload seed data from a csv file. When I run

```bash
dbt seed
```

I get 

```bash
10:05:44  2 of 5 ERROR loading seed file DEV_synthetic.Group.............................. [ERROR in 1.75s]
```

and 

```bash
10:05:52  Completed with 1 error and 0 warnings:
10:05:52  
10:05:52  Database Error in seed Group (seeds/Group.csv)
10:05:52    001003 (42000): SQL compilation error:
10:05:52    syntax error line 1 at position 37 unexpected '.'.
```

I haven't found a way of checking the SQL that gets put together but I suspect that the `Group` table name is problematic.

### Expected Behavior

Seeding works even when tables have names that are reserved keywords or throws a more informative error.

### Steps To Reproduce

1. create a file `Group.csv` and put in the `seeds` folder
2. run `dbt seed`

### Environment

```markdown
- OS: linux mint 20.3
- Python: 3.9.9
- dbt: 1.0.1


dbt-core                   1.0.1     With dbt, data analysts and engineers can build analytics the way engineers ...
dbt-extractor              0.4.0     
dbt-postgres               1.0.1     The postgres adpter plugin for dbt (data build tool)
dbt-redshift               1.0.0     The Redshift adapter plugin for dbt
dbt-snowflake              1.0.0     The Snowflake adapter plugin for dbt
```
```


### What database are you using dbt with?

snowflake

### Additional Context

_No response_

**Comment by jtcohen6** [comment]
@lmmentel Thanks for opening the issue!

This has everything to do with the fact that you're using Snowflake. [On Snowflake, we disable quoting by default for database/schema/relation identifiers](https://github.com/dbt-labs/dbt-snowflake/blob/ffbb05391a0b2fda478004c1cb67fb6d71b1d41b/dbt/adapters/snowflake/relation.py#L5-L9), because quoted identifiers are case-sensitive and, this everything _much much_ harder. Check out docs on this: https://docs.getdbt.com/reference/project-configs/quoting

If you have any way to do it, I _highly_ recommend naming that table something else that avoids special characters and reserved words. If you absolutely must use `Group`, then you'll need to override the project-level quoting config for `identifier`:
```yml
quoting:
  database: false
  schema: false
  identifier: true # quote all view/table names when creating them, and when checking for their existence
```
In order to make that work on Snowflake, you'll probably also need to start uppercasing all identifiers, `ref()` arguments, and model (file) names. That juice just isn't, in my view, worth the squeeze.

**Comment by lmmentel** [comment]
Thanks a lot for the info @jtcohen6! Great that dbt has a mechanism for addressing the quoting issue but I think it'll follow your recommendation and try to get the table renamed.
