### ISSUE TITLE
[CT-219] [Feature] Add mechanism to get relation columns for multiple relations at a time

### ISSUE THREAD

**Issue by jnatkins** [dbt-labs/dbt-core#4713]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Currently, dbt has an adapter macro called `get_columns_in_relation`. This macro also gets used in some places where adapters might get many relations all at once (for example in `dbt_utils.union_relations`). The result is that if this is an inefficiently executed query, it can drag out compilation times for models that may call this function in rapid successful for large numbers of relations. 

In particular, in the Redshift adapter, the `get_columns_in_relation` implementation queries the information schema directly, and in the case of `union_relations`, this results in one query against the information schema per relation being unioned, which is very inefficient. It would be much more efficient to query the information schema once for all of the relations, and just store that in a dict that can be processed by the macro in the dbt process.

The suggestion of this feature is to introduce a `get_columns_in_relations` macro, which would take in a list of relations, and get columns in bulk to reduce overall compilation time.

### Who will this benefit?

This would definitely speed up compilation of Redshift macros that get multiple relation details at once. I'd have to dig into some of the other adapter implementations and look at other macro's usage of `get_columns_in_relation` to really understand the broader impact of this improvement.

**Comment by jtcohen6** [comment]
Thanks for opening, @jnatkins!

The approach would indeed need to vary here by adapter, since some get column information from a centralized `information_schema`, while others run a separate `describe` command for each table (e.g. [Spark](https://github.com/dbt-labs/dbt-spark/blob/63ebe042419a0feb5939c2eb1c010e7e52e8c802/dbt/include/spark/macros/adapters.sql#L139), although that information might be cached!). Even the performance of the information schema-based approach may vary depending on whether the tables live in the same database + schema, or across different ones.

Still, the worst-case (and default) approach here ought to be one where the adapter implements `get_many_relation_columns` as multiple sequential calls to `get_columns_in_relation`, i.e. the status quo ante:

```sql
{% macro default__get_many_relation_columns(relations) %}
  {% set rel_array = [] %}
  {% for rel in relations %}
    {% set columns = adapter.get_columns_in_relation(rel) %}
    {% do rel_array.append({'relation': rel, 'columns': columns) %}
  {% endfor %}
  {{ return(rel_array) }}
{% endmacro %}
```

@gshank Only because we were just looking at and talking about this: one of the "internal" methods that we use to power tests (`TableComparison`) today is indeed [`get_many_table_columns`](https://github.com/dbt-labs/dbt-core/blob/c112050455e1f7b984c5c0d42a57a90a0d4d7053/test/integration/base.py#L648-L709). There are a few notes, in the implementation, that suggest it's optimized for cases that come up in our integration tests (dedicated sandbox schemas), and may not represent the best all-around approach for general use.
