### ISSUE TITLE
[CT-226] relationships tests pickup tag from target table

### ISSUE THREAD

**Issue by caoilte** [dbt-labs/dbt-core#4720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Table B has a "relationships" test dependency on Table A.

If I run the schema tests for Table A (or at least a tests for a tag that includes A and not B), this relationship gets tested as well. This is confusing and unexpected.

### Expected Behavior

I would only expect the relationship to be tested when schema tests for table B are run

### Environment

```markdown
- OS: 20.04
- Python: 3.8.6
- dbt: 1.0.0
```

### What database are you using dbt with?

bigquery

**Comment by ChenyuLInx** [comment]
Hey @caoilte, thanks for opening this issue, and sorry it took a hot minute for us to get back! 
Can you elaborate a bit on why you think the relationship tests shouldn't be run in this case? The current behavior would be able to catch changes in model A that breaks model B when a relationship test is defined.

**Comment by caoilte** [comment]
Hi Chenyu. No problem. 
It was surprising because at the time I hadn't yet created model B (via dbt run). Therefore the test failed not because the relationship was invalid but because models created by the run action don't correspond with models tested by the test action. I would expect these tasks to run over a consistent set of models (ie the models created via run to be the same as the models tested via test).

A consistent dbt run / test would require either,
- a relationship to only be tested by a tag selection if both models in the relationship have the tag applied (my preferred solution)
- dbt run creates all models required indirectly via schema tests (seems counter-intuitive to me but would at least make dbt run consistent with dbt test)

**Comment by jtcohen6** [comment]
@caoilte There are good reasons to want either approach, so dbt does make this behavior configurable. The name for this feature is indirect selection ([docs](https://docs.getdbt.com/reference/node-selection/test-selection-examples#indirect-selection)). It was "cautious" by default for a few versions, but we decided to restore "eager" behavior as the default in v1.0.

Eager selection (default) will include all tests that touch any of your selected models:
```
dbt test --select model_a --indirect-selection=eager
```
By contrast, cautious indirect selection:
```
dbt test --select model_a --indirect-selection=cautious
```
This does _not_ include the relationships test, because we're being "cautious" with indirect selection. The relationships test has another parent (`model_b`) that isn't selected.

**Comment by caoilte** [comment]
Thanks @jtcohen6 switching to cautious gives us the desired behaviour. Thanks for explaining.
