### ISSUE TITLE
[CT-230] DBT seed converts empty strings to nulls

### ISSUE THREAD

**Issue by snagapuri-mdsol** [dbt-labs/dbt-core#4725]
### Describe the bug
DBT seed process converts 
- ,"",
- ,,
- ,NULL,

all above cases to NULLs

I would say atleast quoted empty strings should be allowed to be as blank as its being explicit enough to be used as blank: ,"",

### Steps to reproduce
Add any csv seed file with data like below:
column1,column2,column3
NULL,"",

All the above three columns produce NULLs in database table

### Expected results
NULL,,NULL
Atleast second column in the above example can be left alone to be blank in order to have an option in seed process to add blanks in database tables

### Actual results
NULL,NULL,NULL

### System information

**Which database are you using dbt with?**
- snowflake

**The output of `dbt --version`:**
```
installed version: 1.0.1
   latest version: 1.0.1

Up to date!

Plugins:
  - snowflake: 1.0.0
```

**Comment by ChenyuLInx** [comment]
@snagapuri-mdsol  thanks for opening this! We are still going to stick to the behavior for empty strings in CSVs. Since it is implemented in python standard CSV reader, and it seems to be standard outside python.
To achieve the specific result you want, you can opt for a "placeholder" empty string value (e.g. `EMPTY`), coupled with a staging model that wraps around the seed.
