### ISSUE TITLE
[CT-254] dbt-core - Snapshot - macro dbt_macro__create_schema takes not more than 1 argument(s)

### ISSUE THREAD

**Issue by rlshuhart** [dbt-labs/dbt-core#4742]
https://github.com/dbt-labs/dbt-core/blob/3ad61d5d810aab8bf7bf7bc38f62d02348839c80/core/dbt/include/global_project/macros/materializations/snapshots/snapshot.sql#L9-L11

Hi I've raise this same issue in dbt-sqlserver, but the issue might actually lie here after further investigation. I'm running into the issue, "macro 'dbt_macro__create_schema' takes not more than 1 argument(s)", when attempting to do a simple snapshot. When I delete lines 9-11 in the above all goes well.

Please see additional details on dbt-sqlserver issue at https://github.com/dbt-msft/dbt-sqlserver/issues/208

**Comment by jtcohen6** [comment]
@rlshuhart Thanks for opening, you're totally right! We need to make that `create_schema` call take a single `Relation` argument, rather than `database` + `schema`. This was a breaking change a long time ago... all the way back in v0.17 (https://github.com/dbt-labs/dbt-core/pull/2411).

It's worth checking to see if we actually need this `create_schema` call at all. I have a sneaking suspicion that the snapshot _may_ already be properly accounted for by this logic:
https://github.com/dbt-labs/dbt-core/blob/5e0a7659174a9277e2013390f8615acc97464d40/core/dbt/task/run.py#L437-L439

**Comment by jtcohen6** [comment]
I've concluded these lines are totally unneeded. After a bit of digging through the `git blame`, I see that the origin of the `create_schema` in the snapshot (then archive) materialization was in: https://github.com/dbt-labs/dbt-core/pull/625

At the time, Drew noted that:

> There might be a smarter way to do this -- we could set the node `schema` to the value of `target_schema`, then this will happen automatically through the `node_runner` before_run flow.

This is in fact what we do:

https://github.com/dbt-labs/dbt-core/blob/204d53516a08a619ebea69b68aa8138dd1814f54/core/dbt/parser/snapshots.py#L38-L40

And have been doing since https://github.com/dbt-labs/dbt-core/pull/1478 ([here specifically](https://github.com/dbt-labs/dbt-core/pull/1478/files#diff-bf38b489542759bef40924131b226b9d91c54303f3b545719a3c99f600b5b093R14-R24)). This is picked up accordingly by the `before_run` method in the `snapshot` task (inherited from the method in the `run` task shown above).

Worth noting that this piece still isn't perfect, if you're defining `target_schema` in a `.yml` file instead of `snapshots/*.sql`: https://github.com/dbt-labs/dbt-core/issues/4000
