### ISSUE TITLE
[CT-268] [Feature] Partial compilation (--select support for dbt compile)

### ISSUE THREAD

**Issue by alexrosenfeld10** [dbt-labs/dbt-core#4766]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

When refactoring macros that are used in many sources around a project, the sources will often fail compilation during / after the macro changes. It's really helpful to be able to compile things and see the output, but having models fail compilation gets in the way of doing so. Here's an example:

I have a model named `augmented_public__groups.sql`, which has broken macro calls in it (intentionally here, for the sake of this example, hence `foo`). I have another called `augmented_public__users.sql` that compiles. Here’s what happens:
```
❯ dbt compile --select augmented_public__users
01:47:21  Running with dbt=1.0.3
01:47:21  Encountered an error:
Compilation Error in model augmented_public__groups (models/reporting/augmented/augmented_public__groups.sql)
  macro 'dbt_macro__ll_aug_view' takes no keyword argument 'foo'
  
  > in macro ll_aug_view (macros/util/generators.sql)
  > called by model augmented_public__groups (models/reporting/augmented/augmented_public__groups.sql)
```

There's already well-formed syntax around the `--select` and `--selectors` flags, this issue proposes to use the same functionality in the `dbt compile` command. I don't know tons about the internals of how dbt works, but I'd imagine it'd be fairly hard to run graph operations on a non-compiling project. Here's my completely naive and annoyingly high-level hand-wavey suggestion:

1. If the `--select` flag is present in the dbt compile flag, change all compilation errors to warnings
2. Limp along during compilation - if something fails to compile, keep compiling and actually write the target dir. Write `compilation failed` or something obvious that we can observe in the next step if a model did in fact fail.
3. When finished, try to trace the graph for the users selection. If we found the failure in step 3 somewhere along the path, then exit with a compilation error. If it can be fully traced, awesome, output success, with the warnings of "these failed to compile but weren't on your selection path".

### Describe alternatives you've considered

The workaround to this is [disabling](https://docs.getdbt.com/reference/resource-configs/enabled) the models that are known to fail compilation. However in a project with many models that can get tedious. 

### Who will this benefit?

Any user of dbt that is trying to narrow down and debug compilation issues. Most typically happens when refactoring macros, in my experience.

### Are you interested in contributing this feature?

Maybe, I'd imagine this would be a pretty complex feature to work on and I know very little about dbt's internals. I love writing code, though!

### Anything else?

link to [community slack convo](https://getdbt.slack.com/archives/CBSQTAPLG/p1645573947811849)

**Comment by gshank** [comment]
I can see why this proposed functionality would be an attractive idea to someone trying to debug macros. But it really isn't possible to do what you request considering the way that dbt works. In order to compile a model, we must be able to execute the macros that it calls. That's the reason that compilation is not done at what we call parse time -- everything is not in place to be appropriately called until after all parsing is done and the DAG constructed. I'm sure there are a few models in a few circumstances that could be kinda sorta compiled even if their macros fail, but we can't determine that programmatically.

We are looking at how to make macro debugging easier; that's definitely on the roadmap. But we're not sure exactly what it will look like yet.
