### ISSUE TITLE
[CT-269] Add more performance regression tests

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#4768]
### Describe the Feature

The first version of performance regression tests only include `dbt parse` over one project with 2000 model files. For performance regression tests to be more generally useful we need to cover more test projects and more dbt commands.

@jtcohen6 has suggested the following list of commands:
- `dbt --no-partial-parse parse`: "full" parse
- `dbt --partial-parse parse`: partial parse with no file changes, requires preserving partial_parse.msgpack from step 1
- `dbt compile --exclude fqn:*`: includes graph compilation, in order to catch regressions like https://github.com/dbt-labs/dbt-core/issues/4012 / https://github.com/dbt-labs/dbt-core/issues/4135
- `dbt build --exclude fqn:*`: includes graph compilation with extra test edges (same as above)
- `dbt compile --select node_0`: includes graph compilation + adapter cache construction, in order to catch regressions like https://github.com/dbt-labs/dbt-core/issues/4569

In order to add these commands, the following work must be done:
- [ ] Create a sample project that stresses each of the above commands.
- [ ] Add a warehouse to the sampling and modeling github actions.
- [ ] Change the Rust runner to only run one project-command pair
- [ ] Map projects to commands outside the runner source code. e.g. move command definitions to a file inside each project source code, or have one config file that maps projects to commands.
- [ ] Change the modeling part of the release Github Action to model each of these in parallel GHA containers.
- [ ] Change the sampling Github Action to sample each of these in parallel GHA containers.
- [ ] Test that the runner correctly matches samples to models for the correct project-command pairings

**Comment by kwigley** [comment]
2 quick thoughts!

> Add a warehouse to the sampling and modeling github actions.

We can probably get away with using a postgres instance running in the github actions runner! Any reason not to do this?

> Create a sample project that stresses each of the above commands.

I think the current project with the additional change shown below will stress the commands listed in the issue, but additional project of different shapes will definitely be helpful.

For the current project, we should update the project generator code to use `ref(...)` for relationship tests. So, instead of:
https://github.com/dbt-labs/dbt-core/blob/8f50eee330ea34dd6aaba40993a01a380373fa32/performance/projects/01_2000_simple_models/models/path_0/node_0.yml#L7-L9
it should look something like
```yaml
 - relationships: 
     field: id 
     to: ref('node_0')
```
I'd expect to see a significant perf hit with this change, especially when selecting a small subset of nodes (the `dbt compile --select node_0` example).

**Comment by jtcohen6** [comment]
@kwigley Agree with both points! I think this is well within our reach, starting with the same project we have today, and the (many) other actions we have that leverage Postgres.

The change to the `relationships` test is needed in any case. It's straight-up wrong right now.

While we only have the one project, with multiple commands, how much of the complexity in the issue TODOs can we avoid? We'd still want to store separate results for each command, and compare each to its respective baseline.
