### ISSUE TITLE
[CT-273] [Bug] modifying snapshot files with multiple snapshots causes error (partial parsing)

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#4771]
If you modify a snapshot file with multiple snapshot blocks, and then do 'dbt run', you see the error "dbt found two resources with the name "date_orders_snapshot".  Running with "--no-partial-parse" will re-parse the entire project and then you can run again.

The partial parsing code does not handle multiple snapshot blocks.

**Comment by jtcohen6** [comment]
Nice find! Could this also:
- Fix the same bug for macros: https://github.com/dbt-labs/dbt-core/issues/4233
- Happen for `docs` blocks? The bugs we've heard about have been more around, a `docs` block being missed, than accidentally added twice

**Comment by waterworthd-cim** [comment]
I've just run into this - I added a second snapshot to a project, then had to build with `--no-partial-parse` multiple times, first with my own (dev) account, then I had to modify add `--no-partial-parse` to my CI and daily build jobs, finally I had to manually run `dbt build --source dbt-power-user --no-partial-parse` in the vscode terminal in order to unblock the dbt power use add-on (every power user command failed until I did this)
