### ISSUE TITLE
[CT-340] [Feature] Prevent dbt from installing on Python 3.10

### ISSUE THREAD

**Issue by jaypeedevlin** [dbt-labs/dbt-core#4845]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Lots of folks have issues running dbt on Python 3.10, because dbt _will_ install, but _won't_ work (see slack examples [1](https://getdbt.slack.com/archives/CBSQTAPLG/p1646843167432599), [2](https://getdbt.slack.com/archives/CBSQTAPLG/p1646696986280099), [3](https://getdbt.slack.com/archives/CBSQTAPLG/p1645565109361139?thread_ts=1645565065.138539&cid=CBSQTAPLG), [4](https://getdbt.slack.com/archives/CBSQTAPLG/p1645471971178299), all within the last couple of weeks)

Until https://github.com/dbt-labs/dbt-core/issues/4562 is complete, it would be nice to do what's done in setup.py for early versions for 3.10 also:

```python
if sys.version_info < (3, 7, 2):
    print("Error: dbt does not support this version of Python.")
    print("Please upgrade to Python 3.7.2 or higher.")
    sys.exit(1)
```

### Describe alternatives you've considered

Not doing anything :)

### Who will this benefit?

Folks trying to install dbt and getting frustrated, me from answering the same question over again in the slack!

### Are you interested in contributing this feature?

Absolutely, I'd throw in a quick PR!

**Comment by ChenyuLInx** [comment]
@jaypeedevlin Thank you so much for opening this and answering questions for the community! This would be great! I feel like we can put another check other there checking the minor version is less than 10. And add similar print to tell people to install python3.9. Let me know when you have the PR and we can push it along and get into the next patch release.

This part is more of a note for later on, but we have tests running for different python versions defined at [here](https://github.com/dbt-labs/dbt-core/blob/main/.github/workflows/main.yml#L71). We should probably make the version check and tests running reading from a same place if it is a easy lift.

**Comment by jtcohen6** [comment]
Definitely supportive of this change as a temporary measure. Depending on how heavy a lift #4562 turns out to be, we should either:
- Backport py10 compatibility to `1.0.latest`, for inclusion in v1.0.x (py10 compatible!)
- _Not_ backport py10 compatibility, and instead backport this preventative measure, so that v1.0.x is forever and very clearly _not_ py10 compatible

I think we'll want to add this check to both the `sys.version_info` logic (checked when dbt initializes, if already installed), and the `python_requires` check further down (checked during installation (I think)):

https://github.com/dbt-labs/dbt-core/blob/3b86243f04bdb4226b53bf23f40777c1f00e2b2b/core/setup.py#L86

**Comment by cwegener** [comment]
@jaypeedevlin If such a feature was implemented, how would this impact the upcoming release of Ubuntu 22.04 that is due in 5 weeks from today's date? Will it mean that Ubuntu 22.04 will not be supported by dbt?

Note: I have been using dbt with Python 3.10 for a while without any issues. So, I am very puzzled by this move in general.

**Comment by jaypeedevlin** [comment]
@cwegener I'm not certain, but I think some of the logging changes in 1.0 were what caused the incompatibility, so if you're using an earlier version you may not be running into any conflicts.

In any case, as cited above many folks are running into this issue with fresh installs.

Regarding Ubuntu compatibility, I don't use Ubuntu (nor do I work for dbt Labs) but I don't see any reason why the fact that an upcoming version comes with Python 3.10.x preinstalled means that dbt is unsupported. IMO it just means that while Python 3.10.x is the default that users on that Ubuntu version will need to use an earlier Python version to install dbt.

**Comment by cwegener** [comment]
Hi @jaypeedevlin
Thanks for providing the clarification.
Regarding python 3.10 incompatibilities, the problem is that dbt-core uses an abandoned logging library (logbook), which does not run on Python 3.10 without modifications. The modifications to logbook are pretty straight forward. @MartinNowak has provided a patch in one of the many Python 3.10 issues (#4537)

Regarding using Python 3.9 on Ubuntu 22.04 - I fear that this would be a MAJOR frustration for users of dbt-core. Compiling the Python interpreter and its standard library from source by hand and managing that "from source" installation in parallel with the distribution-provided Python 3.10 is  something that I would not wish on my biggest enemies.

**Comment by jaypeedevlin** [comment]
Maybe your thoughts might be better suited to https://github.com/dbt-labs/dbt-core/issues/4562 ?

**Comment by jaypeedevlin** [comment]
Closing as https://github.com/dbt-labs/dbt-core/issues/4562 makes this redundant
