### ISSUE TITLE
[CT-394] [BUG] Console Log doesn't show model for Database Error

### ISSUE THREAD

**Issue by spuders** [dbt-labs/dbt-core#4894]
### Is there an existing issue for this?

- [x]  I have searched the existing issues

### Current Behaviour

When dbt run results in an database error at the end of the log information in console there is no information regarding the failing model. You have to scroll through the complete logging information to see which model fails.

```
20:14:54  
20:14:54  Finished running 1 view model in 0.33s.
20:14:54  
20:14:54  Completed with 1 error and 0 warnings:
20:14:54  
20:14:54  ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Falsche Syntax in der Nähe des as-Schlüsselworts. (156) (SQLMoreResults)')
20:14:54  
20:14:54  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Expected Behaviour

As it was in previous versions. With concrete information like Database Error in model stg_orders (models/staging/stg_orders.sql)

```
20:14:54  
20:14:54  Finished running 1 view model in 0.33s.
20:14:54  
20:14:54  Completed with 1 error and 0 warnings:
20:14:54  Database Error in model error (models/playground/error.sql)
20:14:54  ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Falsche Syntax in der Nähe des as-Schlüsselworts. (156) (SQLMoreResults)')
20:14:54  
20:14:54  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Steps to reproduce

Run simple model with an SQL Error 

`SELECT AS ERROR`

This should result in an database error and an information which model failed.

### What database are you using dbt with?

SQL Server

### Additional context

I upgraded from dbt version 0.19.2 to 1.0.3. Since that I have this behaviour

**Comment by iknox-fa** [comment]
Hi @spuders thanks for the bug report!  I'll look into it this afternoon.

**Comment by stu-k** [comment]
@spuders Thanks again for submitting the issue! Apologies for the long response time.
I wasn't able to determine whether this issue is coming from this repository, or the [the SQLServer adapter repo](https://github.com/dbt-msft/dbt-sqlserver), so we'll have to do a little more digging on this one.

There is [a known issue](https://github.com/dbt-msft/dbt-sqlserver/issues/139) in the SQL Server Adapter codebase that may be the cause of this issue. Though if the issue lies within `dbt-core`, it likely has to do with [the way errors are being printed](https://github.com/dbt-labs/dbt-core/blob/080dd41876aaf5d348f75db402b2efbb074be4a2/core/dbt/task/printer.py#L78).

If any other community members or `dbt-sqlserver` adapter users have experienced this or similar issues, we would appreciate your input!
