### ISSUE TITLE
[CT-404] [Bug] Docs not loading due to Cannot read properties of undefined (reading 'adapter_type')

### ISSUE THREAD

**Issue by saraleon1** [dbt-labs/dbt-core#4923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

dbt docs site is stuck on 'loading'. The JS console shows the following error:

```
index.html:73 TypeError: Cannot read properties of undefined (reading 'adapter_type')
    at index.html:67:78969
    at index.html:73:95583
    at index.html:73:95721
    at c.$digest (index.html:73:100890)
    at c.$apply (index.html:73:103069)
    at index.html:73:66456
    at A (index.html:73:69360)
    at XMLHttpRequest.b.onload (index.html:73:68723) 'Possibly unhandled rejection: {}'
```

### Expected Behavior

dbt docs site works as expected

### Environment

```markdown
- OS: N/A - dbt Cloud IDE
- Python: N/A - dbt Cloud IDE
- dbt: 0.21.1
```

### What database are you using dbt with?

snowflake

### Additional Context

Note that this is happening in the Cloud IDE, but not in runs. Because of this, I am unable to get to the manifest.json file to double-check what value is entered for 'adapter_type' in the metadata.

**Comment by jaypeedevlin** [comment]
Chiming in because I ran into a similar error on 0.20.0 which you can read about here https://github.com/dbt-labs/dbt-docs/issues/207

The bug that was causing the exception to be raised was fixed, so likely yours is different, but I did have some malformed yaml that was contributing (in my case I had defined relationships test to a node that didn't exist), so as a workaround it might be worth checking for weirdness in your yaml files.

**Comment by jtcohen6** [comment]
@saraleon1 and I managed to do a bit more investigation, and we found that the `manifest.json` file is missing! More precisely: It's just a big old `None`. Our hunch is that it's due to the size of the file, preventing it from loading properly.

It would be great if `dbt-docs` could raise a more informative error when _everything_ is `None` (not just the sub-object that `adapter_type` rides in on). For the meantime, I'm going to close this issue.
