### ISSUE TITLE
[CT-405] [Feature] Expose Jinja function to read seed files as an alternative to run_query

### ISSUE THREAD

**Issue by tomasfarias** [dbt-labs/dbt-core#4924]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

In the spirit of keeping things DRY, we seek to abstract static data from our queries. If the data is a small list or dictionary, we can just use a `{% set %}` at the top of the query. However, once the data gets larger and used by multiple queries, we start noticing a lot of repeated `{% set %}` statements that produce a lot of boiler plate code.

Having the possibility of reading the data from a seed file at compile time would allow us one more level of abstraction: having the static data as a seed file, and then loading it as an `agate.Table` wherever it's needed, e.g.:

```sql
{% set table = read_seed('seed_my_seed_model') %}

{% for row in table %}
-- Do something with rows.
```

Moreover, this way we eliminate errors from copying and pasting static values that are re-used in multiple queries.

Finally, having a single seed file means that in the event the data has to change we can update only one file, instead of each individual query file.

### Describe alternatives you've considered

I've come across the following pattern several times:

```sql
{%- set query -%}
  SELECT * FROM {{ ref('seed_my_seed_model') }}
{%- endset -%}

{%- set table = run_query(query) -%}

{%- for row in table -%}
-- Do something with rows
```

While this works, the pattern is making unnecessary database calls as seed files are static that change infrequently (as the [dbt docs](https://docs.getdbt.com/docs/building-a-dbt-project/seeds/) describe them).

Moreover, given that seed files are version controlled, everyone in my team has access to them locally, and doesn't need to call the database to access the data.

Finally, this pattern also requires the seed file to already be present in the database, which may not be the case if the seed file is new, or adds an additional `dbt seed` step.

### Who will this benefit?

Any teams that needs to inject static data into their queries, and that static data has gotten too large to copy around every time, leading to significant amounts of duplicated data and boilerplate code.

### Are you interested in contributing this feature?

Yes, of course. I'd like some guidance on where to write this.

### Anything else?

This could be extended to simply supporting any custom Python function as a custom Jinja filter, however, as per #4571, I understand there is a security concern about doing this. For this reason, I have opted to open a feature request for a single filter, in the spirit of #1894. Security concerns are minimized further by limiting the data that can be loaded to only existing seed files (instead of any csv file).

**Comment by nathaniel-may** [comment]
Hi @tomasfarias, thanks for your detailed request and the willingness to contribute! I think you have a good intuition about the appropriate solution shifting as your static data gets larger. For a small number of values, you might consider defining a [jinja macro](https://docs.getdbt.com/docs/building-a-dbt-project/jinja-macros#macros) that returns the static values, and then calling that macro in each of your files to reduce duplication.

You rightfully call out that,
> ... once the data gets larger and used by multiple queries

this pattern stops making quite as much sense. I think this is because if you have dozens of rows of data, you probably want to be treating it like data and using sql joins instead of using it to template the sql queries. To use your example code, the following...

```
{%- set query -%}
  SELECT * FROM {{ ref('seed_my_seed_model') }}
{%- endset -%}

{%- set table = run_query(query) -%}

{%- for row in table -%}
-- Do something with rows
```

could become something like

```
with other_model as (
  select * from {{ ref('another_model') }}
),

seed as (
  select * from {{ ref('seed_my_seed_model') }}
)

select

  other_model.column,
  seed.outcome

from other_model
join seed
  on other_model.column = seed.if_condition
```

Because this query gets issued to your warehouse, the seed data isn't being transferred over the network each time it is referenced and the larger seed data is being processed in your warehouse which is better suited to that task.

Does this sound like it could work for your project?

Special thanks to @jtcohen6 for the example sql and for discussing the solution space with me.

**Comment by tomasfarias** [comment]
Hey @nathaniel-may. Thanks for the quick and detailed response.

> For a small number of values, you might consider defining a [jinja macro](https://docs.getdbt.com/docs/building-a-dbt-project/jinja-macros#macros) that returns the static values, and then calling that macro in each of your files to reduce duplication.

The main motivation behind the issue was that we have a set of seed files maintained by non-technical folks. Although teaching them how to maintain a jinja macro is more than possible, they are more used to CSV files as they can easily export them from Excel spreadsheets.

> I think this is because if you have dozens of rows of data, you probably want to be treating it like data and using sql joins instead of using it to template the sql queries.

Just to describe our use case more in detail: we have some CSV files that are updated to perform many-to-one mappings.

Imagine the following CSV which maps several job titles to a single id (data is made up, purely for illustration purposes):

```
| id | job               |
| -- | ----------------- |
| 1  | software engineer |
| 1  | data engineer     |
| 2  | product manager   |
| 2  | product owner     |
```

When provided with this CSV, we need to construct a CTE for each ID:

```sql
{# Imagine we have a table object already loaded somehow #}

{# It may be more efficient to use a dictionary or using some group by method, this is just a quick example #}
{% set unique_ids = set((row[0] for row in table.rows)) %}

{% for unique_id in unique_ids %}

    {% set jobs = [row[1] for row in table.rows if row[0] == unique_id] %}

    with job_category_{{ unique_id }} as (
        select job, * from {{ ref('another_model') }}
        where job in ({{ jobs | join(',') }})
    ),
{% endfor %}

{# We now have 2 CTEs created, one for each of the two unique job IDs #}
```

> and the larger seed data is being processed in your warehouse which is better suited to that task.

We could refactor the CTEs with a `JOIN`, it's just that since the data is known at compile time, it would save us a `dbt seed` run in our CI/CD pipeline. I understand I may be prematurely optimizing, though, or that our use case may be too specific (we have a particularly beefy CI/CD pipeline).

**Comment by nathaniel-may** [comment]
@tomasfarias, thanks for the additional context. This helps a lot.

First, while I certainly appreciate your desire to keep a zippy CI/CD pipeline, if adding an additional seed to your project negatively impacts performance, I would encourage you to log a bug ticket with us because it should be a near negligible difference.

Seeds are generally used for data which never changes or changes very infrequently ([docs](https://docs.getdbt.com/docs/building-a-dbt-project/seeds)). Since this is data being maintained by another team, you might consider treating it as a source instead. I know there are some ways to do this on most warehouses with Google sheets.

I would like to continue to help find a pattern that works well for your team in this ticket. However, to clearly address the original ask we aren't planning to support the ability to do file IO in jinja templating because of all the additional complications it brings, and because it would be considered an anti-pattern for the majority of projects.

**Comment by tomasfarias** [comment]
Understandable, @nathaniel-may thanks for your replies so far. I would like to make one more final plea to allow folks to implement custom Jinja filters, but I understand the arguments in https://github.com/dbt-labs/dbt-core/issues/4571. I guess this is one we'll just have to fork and implement it ourselves.

I have no more comments, so I'm closing this issue. Again, thanks for the replies and amazing work in dbt 🎉
