### ISSUE TITLE
[CT-408] [Feature] Database Agnostic error handling

### ISSUE THREAD

**Issue by McKnight-42** [dbt-labs/dbt-core#4926]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Per https://github.com/dbt-labs/dbt-core/pull/4858#discussion_r826331310 the way we are catching database errors needs to be handled in a way that leverages each databases level of concern for the error or to catch them, and turn them into dbt specific errors and run those against tests

### Describe alternatives you've considered

currently catching and lowering error to be read out same way across databases.

### Who will this benefit?

potential for all uses to benefit as errors could be written very clearly across all databases.

**Comment by jtcohen6** [comment]
@McKnight-42 The error message we're catching here is specific to the test added in #4858, and it's actually handled in a database-agnostic way there. We'll find out when we convert the test cases to use the new `pytest`-based framework, and set them up to be inherited and run (with _zero_ code changes) in each of our plugins. Then, we can delete the copy-pasted code that lives in the plugins currently.

I think this can be closed, since the main work is already reflected in https://github.com/dbt-labs/dbt-core/issues/4882
