### ISSUE TITLE
[CT-413] Update Mashumaro to 3.0

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#4940]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Tech debt:
Updated Mashumaro to 3.0.  It has some breaking changes so the dependabot PR isn't going to cut it.

See dependabot PR
https://github.com/dbt-labs/dbt-core/pull/4705

**Comment by nathaniel-may** [comment]
estimation:
- lots of test failing on dependabot PR, but many of them are imports. might need to change our stubs
- some unknowns here but we don't expect it to be too complicated
- estimation: 2

**Comment by gshank** [comment]
I took a look at this and it's worse than I expected. I think there's a bug in using to_msgpack -- it complains about "unexpected keyword argument" "dialect" which is a parameter that's been sprinkled around but I'm guessing not totally consistently.  It's also really hard to debug because the error occurs in the generated to_dict code.  mashumaro has very few tests of to_msgpack. 

We also need to generate new third-party-stubs (using stubgen) because the code has been reorganized into different directories. On top of that there were lots of mypy complaints, particularly for incompatibilities with the hologram "from_dict" and "to_dict' methods.  I've forgotten if we ever use those hologram methods (possibly for generating the json schemas?) but fixing it might require rearranging hologram so there aren't incompatibilities. Last time I fixed it by lying about the parameters in the mashumaro stubs and it's possible that would work again, but a quick attempt at doing that didn't work (probably because the new signatures are different in ways that won't allow that).

So I think we need to raise the estimation to something closer to a 5.

**Comment by Fatal1ty** [comment]
> I took a look at this and it's worse than I expected. I think there's a bug in using to_msgpack -- it complains about "unexpected keyword argument" "dialect" which is a parameter that's been sprinkled around but I'm guessing not totally consistently. It's also really hard to debug because the error occurs in the generated to_dict code. mashumaro has very few tests of to_msgpack.

Hey. You might have missed it but this issue was [here](https://github.com/Fatal1ty/mashumaro/issues/76) in 3.0.3.
