### ISSUE TITLE
[CT-424] Dbt list json output should include the final target name of the model

### ISSUE THREAD

**Issue by whisperstream** [dbt-labs/dbt-core#4955]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I execute `dbt list -m my_model --output-json > some.json`, file `some.json` should ideally contain the fully qualified target name of the model.  In my dbt project I make heavy use of of the `generate..x..name()` set of schemas to alter the final target name based on the environment.

I depend on the output from `dbt list` in my CICD processes and recently discovered that it doesn't capture this information in the output - which I feel it should.

### Describe alternatives you've considered

I'm working around it right now, by also having to read in the manifiest and parsing that.

### Who will this benefit?

Everyone - having the final target (a critical value) as processed by macros would be valuable to a wide audience.

### Are you interested in contributing this feature?

Not at this time

**Comment by jtcohen6** [comment]
Thanks for opening @whisperstream! I remember this being open as an issue some time ago: https://github.com/dbt-labs/dbt-core/issues/2643

Since https://github.com/dbt-labs/dbt-core/pull/2837, we _do_ add the fully qualified `relation_name` for all "relational" nodes (ones that point to / create database objects)—but only at compile time, after loading the adapter:

https://github.com/dbt-labs/dbt-core/blob/81118d904a876276d8a890eb207e1e2a813c344a/core/dbt/compilation.py#L197-L203

https://github.com/dbt-labs/dbt-core/blob/81118d904a876276d8a890eb207e1e2a813c344a/core/dbt/compilation.py#L380

Why? Because we need to know the adapter's specific rules for creating relation names. Some adapters are `schema.table` only, some use ` `` ` instead of `""` as their quote characters, etc.

In order to include this in the output of `dbt ls`, the information has to be available at the end of parsing, without requiring the additional compilation step (i.e. `dbt compile`). Is that possible? Someone from the Core - Language team would have to weigh in
