### ISSUE TITLE
[CT-457] [Bug] Project list is not sorted alphabetically in the dbt Cloud UI

### ISSUE THREAD

**Issue by james-stover-moe** [dbt-labs/dbt-core#4994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The project list in a dbt Cloud account is not sorted alphabetically. Current sort order appears to be based on when the project was created.

### Expected Behavior

The project list should be sorted alphabetically or have an option to sort in ascending or descending order.

### Steps To Reproduce

1. Navigate to cloud.getdbt.com
2. Select an account from the account list
3. Select and observe the project list

### Environment

```markdown
- OS: Windows 10 version 20H2 (build 19042.1586)
- Browser: Chrome 99.0.4844.51
- dbt: Cloud v1.1.45.206
```

### What database are you using dbt with?

snowflake

**Comment by jtcohen6** [comment]
@james-stover-moe Thanks for opening the issue! I totally hear you on the ask for a way to sort, or a more intuitive sort order. I know this same request has come in from a number of users and customers, and it's on the minds of the teams working to build dbt Cloud.

Could I ask you to send this feedback to support, via the chat window inside the application, or by email to support@dbtlabs.com? They handle all bug reports and requests for functionality that is specific to dbt Cloud.

In the meantime, I'm going to close this issue, because the change for it will need to take place in a codebase external to `dbt-core`.
