### ISSUE TITLE
[CT-468] [Feature] ref() should be treated as model parent in generic test arguments

### ISSUE THREAD

**Issue by jarno-r** [dbt-labs/dbt-core#5006]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

A generic test can have an argument that is a reference to another table. For example:

````yaml
models:
  - name: my_model
    tests:
      - is_equal:
          compare_to: ref('other_model')
````

`dbt build --select +my_model` should also include `other_model` in the DAG.

Not including `other_model` as a parent may also cause build failures due to `other_model` being build after `my_model` when running `dbt build --select my_model other_model`.

### Describe alternatives you've considered

A ref() could be used in my_model.sql in a dummy set statement:
````
{% set _ = ref('outer_model') %}
````
This requires having the reference in two places and does not work with seeds.

### Who will this benefit?

Anyone who wishes to use generic tests that refer to other models. These are particularly useful in unit testing macros.

**Comment by jtcohen6** [comment]
@jarno-r Thanks for opening!

This is a complex edge case, and one that's come up many times before. We went on an epic journey related to this exact question last year: https://github.com/dbt-labs/dbt-core/issues/2874, https://github.com/dbt-labs/dbt-core/issues/2891, https://github.com/dbt-labs/dbt-core/issues/4082

Two things are at play here:
- Technically, `other_model` is not a _parent_ node of `my_model`, but they are both parents of a common child node (the `is_equal` test). So `other_model` is not included by `+my_model`
- The `is_equal` test _is_ selected by `+my_model`, as it would be `my_model`, because tests are selected _indirectly_ and _eagerly_ by default. That is, when you say "build my model," that also means "run any tests that depend on my model."

You have two valid options:

1. Use the `@` operator instead of the `+` operator, i.e. `dbt build --select @my_model`. This means: Build this model, its parents, its children, and _other parents of its children_. https://docs.getdbt.com/reference/node-selection/graph-operators#the-at-operator
2. Switch "indirect selection" for tests from "eager" to "cautious." Eager means, run any tests with at least one selected parent. "Cautious" means, _don't_ run any test with at least one _unselected_ parent. https://docs.getdbt.com/reference/node-selection/test-selection-examples#indirect-selection

This is a complex problem, and we found it impossible to define a default behavior that accounts for every scenario. That's where configuration comes in. At it is, I feel pretty happy with where we've landed on this one, so I'm going to close this issue.
