### ISSUE TITLE
[CT-598] [Feature] Add support for new full refresh value for `on_schema_change` 

### ISSUE THREAD

**Issue by azhard** [dbt-labs/dbt-core#5210]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Currently when a new column gets added to an incremental model the functionality to fill that column is quite limited. Specifically "old" rows will never get updated with the new column as mentioned in the docs:
```
Note: None of the on_schema_change behaviors backfill values in old records for newly added columns. If you need to populate those values, we recommend running manual updates, or triggering a --full-refresh.
```

The goal here would be to add a new potential value for `on_schema_change` that either:
- detects that there is a new column and constructs an `UPDATE` statement to update all rows for the model
- automatically triggers a full refresh for the model when an additive schema change is deteced

### Describe alternatives you've considered

As mentioned in the dbt docs: manually updating the model or running --full-refresh for the model.

### Who will this benefit?

Any dbt user who leverages incremental models that undergo additive schema changes.

### Are you interested in contributing this feature?

Open to contributing, would just like a nudge on what implementation makes the most sense.

**Comment by jtcohen6** [comment]
Hey @azhard, thanks for opening! I agree this would be impactful. We've already got an issue open for it (https://github.com/dbt-labs/dbt-core/issues/4473), so I'm going to close this one as a duplicate.

The work involved here is a bit tricky, in terms of plumbing the logic through these conditional paths without duplicating a bunch of code unnecessarily. I'd like to wait on tackling this until after our attempt to streamline the logic in the `incremental` materialization (#5089), by consolidating more of the logic in `dbt-core` and easing the duplication that exists in adapter plugins (+ users' own projects) today. At that point, if you'd be interested in chipping in, we'd definitely welcome your help.

One meta comment I'll leave before closing. You offered two paths, and I feel pretty strongly that this is the right one:

> automatically triggers a full refresh for the model when an additive schema change is deteced

Otherwise, we get into tricky territory around how to perform the update. Should users configure default backfill values? (At that point, I'd rather they just run the `update` statement themselves.) Run the model query against all historical data, to update just that column? (How is that different from `--full-refresh`, really?)
