### ISSUE TITLE
[CT-649] [Feature] Prettify duration message at the end of execution

### ISSUE THREAD

**Issue by SOVALINUX** [dbt-labs/dbt-core#5253]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Hi colleagues,
Would like to suggest more human-readable logging for end of execution dbt commands
Now we log only time in seconds, but it's not very convenient to convert it in your head every time you need to understand how long it was
For example:
```
Finished running 15 tests, 1 hook in 410.20s.
```
I would suggest to write it in the following way:
```
Finished running 15 tests, 1 hook in 6 min 51s (410.20s).
```
Saving pure seconds for those cases who might be parsing the duration from logs using RegExp

### Who will this benefit?

Those who execute pipelines longer than few minutes

### Are you interested in contributing this feature?

I think my team can do it

**Comment by jtcohen6** [comment]
@SOVALINUX Makes sense to me! We do something similar for `bytes_processed` on `dbt-bigquery` [here](https://github.com/dbt-labs/dbt-bigquery/blob/8aaa6ab6da182aa8e831f631feb12af5ec76d9ce/dbt/adapters/bigquery/connections.py#L245-L253). The underlying data is still recorded as an integer (number of bytes, number of seconds), but then we convert the value for inclusion in the human-friendly message.

The relevant message is in a event named `HookFinished`:

https://github.com/dbt-labs/dbt-core/blob/0d8e061a3d8d726bb10ff767d8f276439cc472b2/core/dbt/task/run.py#L394-L405

https://github.com/dbt-labs/dbt-core/blob/0d8e061a3d8d726bb10ff767d8f276439cc472b2/core/dbt/events/types.py#L1500-L1507

I'm going to mark this a `good first issue`. It sounds like it's a change your team may be interested in contributing?

---

**Tech debt:** I'll be honest, this event feels far from perfect:
- `HookFinished` doesn't feel like the right name, versus `RunResultsLine` or similar. (I'm not sure if or how we could make this change in a backwards-compatible manner, though)
- I'd much rather pass in a structured dictionary of node counts, and then render the human-friendly `stat_line` for the event's message
- We should also be storing `execution_time` as a float, rather than `execution` as a string

Those are beyond the scope of the specific change you're proposing. For what you're after, I think it would be reasonable to:
- Format `execution`, as a string, with hours/minutes/seconds (`1 hr 6 min 51s`)
- Add `execution_time` (float, representing seconds) as a dataclass attribute that gets passed into `HookFinished`, and included in its structured (JSON) output, even if it isn't templated into the human-friendly `message`

**Comment by SOVALINUX** [comment]
Hi
Will take a look, thanks! It's not the first priority for my obviously, but sooner or later we can make it :)
Thanks for your inputs!
