### ISSUE TITLE
[CT-659] [Feature] Add a better name for flags.WHICH

### ISSUE THREAD

**Issue by SOVALINUX** [dbt-labs/dbt-core#5262]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

We have different dbt commands (run, test, compile, docs, etc.) and refer them as "commands"
However the variable in the context storing this information called "flags.WHICH", what is clear for developer community, but might be confusing for users
Suggestion is to have another flag: flags.EXECUTED_COMMAND or flags.COMMAND to store the same as flags.WHICH
Deprecate flags.WHICH and potentially remove it in dbt 2.0

### Describe alternatives you've considered

I even made a PR thinking that flags.WHICH doesn't exist :)

### Who will this benefit?

everyone who're doing hooks and unit testing

### Are you interested in contributing this feature?

I think I can

### Anything else?

This feature is a spin-off from https://github.com/dbt-labs/dbt-core/issues/5251

**Comment by jtcohen6** [comment]
@SOVALINUX Thanks for opening! Let's definitely pick a new name for this, one that makes more sense to end users and metadata consumers :)

Tagging this as both Language + Execution because:
- it relates to the tightly coupled config at dbt initiatlization that we've been discussing
- it has implications for dbt project code and metadata interfaces
- I think the choice of the word `"which"` isn't actually ours — it's `argparse`'s built-in word for identifying which subparser (=subcommand) is being used ([reading here](https://stackoverflow.com/questions/8250010/argparse-identify-which-subparser-was-used)) — does that sound right? It also makes me think this is something that would (or should) come up naturally if/when we take up work that moves us away from `argparse`, toward a better CLI interface.

### Backwards compatibility considerations
1. `flags` module, which is exposed to [the Jinja context](https://docs.getdbt.com/reference/dbt-jinja-functions/flags) for end users writing project code. This should be relatively easy: `flags.WHICH` could just redirect to the new name.
2. Metadata consumers: structured logging events that include `args`, i.e. [`MainReportArgs`](https://github.com/dbt-labs/dbt-core/blob/e50678c91424142aa1a4995ee1d358dac6a6fdf8/core/dbt/events/types.py#L133), and artifacts that include `args`, i.e. `run_results.json` ([as documented](https://docs.getdbt.com/reference/artifacts/run-results-json#top-level-keys)). I think this would be trickier, without lots of duplication.
