### ISSUE TITLE
[CT-670] [Feature] Standardize result statuses 

### ISSUE THREAD

**Issue by amychen1776** [dbt-labs/dbt-core#5276]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Today to use the results node selectors for tests vs models, you have to remember that for models, you should use `result:error` and for tests: you can use `result:fail`. 

While there is a clear difference between a runtime error (SQL failed during execution) and failed assumptions (data does not meet expectations), the way we have named the differences feels pedantic and requires more mental leaps than necessary. I understand that a test could fail or error out but right now, it's not like we support `result:error` for tests so I think it would be better to align on one agreed-upon declaration of "something went wrong, let's rerun the things that didn't pass the initial run". 

<img width="970" alt="image" src="https://user-images.githubusercontent.com/46451573/169402877-92a26255-7056-4653-a1c8-5ba72dfba1bc.png">

### Describe alternatives you've considered

Because the goal is to point to a failure or error and there is a clear distinct between what is an error and a fail for tests, I think we should agree on an synonym so it's higher level (to signal this failure) or just go with `fail` and call it a day

### Who will this benefit?

Anyone trying to grasp an understanding of all of the different node selectors

### Are you interested in contributing this feature?

yes

**Comment by jtcohen6** [comment]
@amychen1776 Thanks for opening!

### Goal

We should align on 5 types of statuses, and then pick good names for each one:
1. **Success:** Everything ran as expected. Model/snapshot/source succeeded when building, and data in tests / source freshness meets expectations. (Do these need to be two different ones, `success` and `pass`? I don't think so personally, but I'm open to disagreement.)
2. **Warning:** Data does not meet expectations, but the user has opted to be warned for this test / at this threshold.
3. **Data quality error / failure / stale:** Data does not meet expectations, beyond an acceptable threshold, or for a higher-priority test.
4. **Runtime error:** SQL encountered an error while running. Syntax error, the table is missing, the `merge` was aborted halfway through.
5. **Skipped:** Didn't get run. Today, this can only be because an upstream DAG resource encountered status 3 or 4. In the future, could this also happen because the model doesn't _need_ re-running (e.g. materialized view)?

The fuzziest distinction today is definitely between 3 + 4. In the case of models/seeds/snapshots + tests, `error` means 4; in the case of _source freshness_, `error` means 3, whereas `runtime error` means 4. Let's fix it.

### Implementation

All of these statuses are defined [here](https://github.com/dbt-labs/dbt-core/blob/e50678c91424142aa1a4995ee1d358dac6a6fdf8/core/dbt/contracts/results.py#L71-L100).

This is most closely related to `Execution`. The relevant stakeholders are really our metadata consumers:
1. consumers of `run_results.json`
2. consumers of structured logging
3. `result:` selector method
4. people who use [`Results`](https://docs.getdbt.com/reference/dbt-jinja-functions/on-run-end-context#results) Jinja object, i.e. within post-hooks

I think it might be easy enough for us to offer backwards compatibility for the rename in 3+4. Doing so for 1+2 would be a bit more difficult.

> I think it would be better to align on one agreed-upon declaration of "something went wrong, let's rerun the things that didn't pass the initial run

I also think it's totally reasonable for us to provide, within the `result:` selector method in particular, some catch-all selection method for "did not succeed," whether because of runtime errors or failure to meet data quality expectations. (Should that include `warn` statuses as well?)

### Open questions

- Do those 5 statuses make sense? Are those the right conceptual categories?
- Can we come up with clear one-word names for each one, that apply across resource types and are sufficiently distinct from one another?

**Comment by mirosval** [comment]
As far as I can tell there is one category of failures that is probably folded into (4.) which are SQL errors not related to the model, but to the connection to the DB (Auth fails, Connection pool exhausted, Timeouts, etc.).

I don't know if it should be a separate category but its worth talking about it.
