### ISSUE TITLE
[CT-671] [Bug] Failing singular test with two dependent models a&b doesn't block a downstream model c unless it selects from both a&b

### ISSUE THREAD

**Issue by jaypeedevlin** [dbt-labs/dbt-core#5277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Singular `test_ab` selects from `model_a` and `model_b`.
- `model_c` selects from `model_a` only
- when running `dbt build -s a+ b+`, `test_ab` doesn't run before `model_c`

### Expected Behavior

A singular test with multiple dependencies should run before any models downstream of those dependencies.

### Steps To Reproduce

```sql
-- models/model_a.sql
select 1 as foo
```

```sql
-- models/model_b.sql
select 1 as foo
```

```sql
-- tests/test_ab.sql
select 1 as foo
-- {{ ref('model_a') }}
-- {{ ref('model_b') }}
```

```sql
-- models/model_c.sql
select 1 as foo
-- {{ ref('model_a') }}
```

```
$ dbt build -s a+ b+
03:44:55  Running with dbt=1.1.0
03:44:56  Found 3 models, 1 test, 0 snapshots, 0 analyses, 0 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
03:44:56  
03:45:04  Concurrency: 8 threads (target='dev')
03:45:04  
03:45:04  1 of 4 START view model schema.model_a ............................. [RUN]
03:45:04  2 of 4 START view model schema.model_b ............................. [RUN]
03:45:08  1 of 4 OK created view model schema.model_a ........................ [SUCCESS 1 in 3.52s]
03:45:08  3 of 4 START view model schema.model_c ............................. [RUN]
03:45:10  2 of 4 OK created view model schema.model_b ........................ [SUCCESS 1 in 5.22s]
03:45:10  4 of 4 START test test_ab ...................................................... [RUN]
03:45:11  3 of 4 OK created view models schema.model_c ........................ [SUCCESS 1 in 3.17s]
03:45:12  4 of 4 FAIL 1 test_ab .......................................................... [FAIL 1 in 2.35s]
03:45:12  
03:45:12  Finished running 3 view models, 1 test in 15.79s.
03:45:12  
03:45:12  Completed with 1 error and 0 warnings:
03:45:12  
03:45:12  Failure in test test_ab (tests/test_ab.sql)
03:45:12    Got 1 result, configured to fail if != 0
03:45:12  
03:45:12    compiled SQL at target/compiled/project_name/tests/test_ab.sql
03:45:12  
03:45:12  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
```

Either dropping `test_ab`s dependency on `model_b` or adding a dependency from `model_c` to `model_b` causes the test to block `model_c` as expected.

### Environment

```markdown
- OS: MacOS 12.3.1
- Python: 3.8.10
- dbt: 1.1.0
```

### What database are you using dbt with?

snowflake

### Additional Context

Reproduced from someone I was helping in [this slack thread](https://getdbt.slack.com/archives/C50NEBJGG/p1652987147658199)

**Comment by danielefrigo** [comment]
I just found the same issue with generic tests (tried both standard referential integrity test and a custom one)

**Comment by giovanni-girelli-sdg** [comment]
Same issue, dbt-bigquery 1.1.0.

**Comment by jtcohen6** [comment]
Relevant spot in our code:

https://github.com/dbt-labs/dbt-core/blob/e50678c91424142aa1a4995ee1d358dac6a6fdf8/core/dbt/compilation.py#L468-L472

In the reproduction case, `test_ab` depends on `{'model.testy.model_a', 'model.testy.model_b'}`, but `model_c` depends on `{'model.testy.model_a'}` only, so the former is not a subset of the latter. (Thanks for the really clear one @jaypeedevlin, as always!)

Why is that logic there to begin with? There's a risk of cycle if `model_a` &rarr; `model_b` &rarr; `model_c`, and all of them have interdependent `relationships` tests defined. There's a fairly clear reproduction case for that behavior outlined in [this test case](https://github.com/dbt-labs/dbt-core/blob/e50678c91424142aa1a4995ee1d358dac6a6fdf8/test/integration/069_build_tests/test_build.py#L108-L142).

Worth more digging and thinking, since this has come up for multiple folks!

**Comment by jtcohen6** [comment]
Agreed that our goal here should be rewriting the logic to:
- support the use case / reproduction case outlined in this issue
- without causing a cycle in the test case linked above (interdependent tests)

If finding the right logic to do that proves too difficult, we have to make a more straightforward trade-off between the two use cases identified.

**Comment by ChenyuLInx** [comment]
Thank you all for the info and for digging into the codebase!!! I drafted out a change that should complete the full request. Still need to add tests and evaluated the computation cost a bit. But feel free to take a look and give it a test run to see if it makes sense.

**Comment by ChenyuLInx** [comment]
After some more digging and testing, I think that it is might be best to keep the current behavior but maybe add a way to specify this type of dependency explicitly.

Here's the reason(I think I have the right logic but this is kind of tricky so please correct me if I got something wrong):
For the interdependent test case @jtcohen6 mentioned above, there are some ways of adding not too much computation cost while making sure it works. But if we change the situation to be the following, there's `m2`, `m3` all ref `m1`, and relational test `t1` tests `m1-m2`, `t2` tests `m1-m3`. When we do build, none of the two red dependencies are going to be generated with the current implementation. And adding either one of them is fine since it doesn't generate a cycle in the DAG. Only when both red edges are added, we have a cycle in the DAG.

So if we want to make this situation work, we have some options:
- check the cycle for every edge and skip if a cycle is detected
- add all of the edges and realize that there's a cycle in the end. 
- keep the current condition(not adding them) and let the user specify which edge should be added.

Option 1 is super computationally expensive, and which edge we have in the end depends on whether we run into m2 or m3 first.
Option 2 will make the interdependent test case fail.
So I think the current condition plus the ability to let users specify which edge to add would be our best option. I am not sure if there's a good/ergonomic way to do it now @jtcohen6  

@jaypeedevlin I understand that in your case `test_ab` is checking something that might affect `model_c`, but in other cases where `test_ab` checking things only related to `model_b`, `model_c` probably doesn't have to be skipped. And IMO defining that explicitly by the user might be better than leaving it for dbt to figure out atm.
<img width="880" alt="Screen Shot 2022-06-09 at 1 28 54 PM" src="https://user-images.githubusercontent.com/17092660/172938510-246923f8-48a2-45d9-a904-2dc034077588.png">

**Comment by jtcohen6** [comment]
@jaypeedevlin If you're able to share, actually curious to hear your real original use case for this. We've tried coming up with a practical real-world example where we're testing two upstream models (e.g. `orders` + `customers`), _and_ want a downstream model selecting from `customers` to skip if there's a failure in the test between them. It feels much more likely that the downstream model for which that test is relevant would select from both.

In terms of practical next steps:
- @ChenyuLInx Thank you for the diagram, I'm convinced! Having this behavior by default, while giving users the option to explicitly specify the extra `--depends on` if they want to skip on test failures, feels like the right compromise. (Is it much more ergonomic to say `--depends on: {{ ref('test_ab') }}` instead of `--depends on: {{ ref('model_b') }}`, i.e. I depend directly on the upstream test, versus I depend on all the upstream models that _are being tested._)
- Let's update the docs here: https://docs.getdbt.com/reference/commands/build. There's already mention of: "In the case of a test with multiple parents, where one parent depends on the other..." We should add a clarification for: "In the case of a test with multiple parents, a downstream model that selects from only _one_ of those parents will..."

**Comment by jaypeedevlin** [comment]
@jtcohen6 this was not actually my use case, I just wrote it up on behalf of [Kevin on slack](https://getdbt.slack.com/archives/C50NEBJGG/p1652987147658199) who was experiencing the unexpected (to him) behavior that seemed unintuitive to me.

I agree that the downstream model selecting from both seems more common, FWIW.

**Comment by kmarq** [comment]
> @jtcohen6 this was not actually my use case, I just wrote it up on behalf of [Kevin on slack](https://getdbt.slack.com/archives/C50NEBJGG/p1652987147658199) who was experiencing the unexpected (to him) behavior that seemed unintuitive to me.
> 
> I agree that the downstream model selecting from both seems more common, FWIW.

Kevin here. So in this case what we have is that model a is the result of applying CDC records (I/U/D) onto a table from an external source. Model b is an aggregated view of the original source table from the other system. So test a_b is looking to validate that the changes applied to model a based on the CDC records match back to what the source sent as a validation file. We've had issues where the source has had manual changes applied that broke the CDC process, so this is an attempt at catching those issues before downstream items (model c) get run. 

Hope that helps clarify.

**Comment by ChenyuLInx** [comment]
@kmarq  Hey Kevin, thanks for the really clear use case description, it makes total sense! 

As the example in the diagram above in my previous comments shows, adding the logic that's desirable in your situation might cause problems in other situations. So we would prefer that user specify that dependency vs dbt inferring it. 
Do you feel like what Jerco mentioned method above: adding `--depends on: {{ ref('model_b') }}` to model c is a good solution for you?

**Comment by kmarq** [comment]
> @kmarq Hey Kevin, thanks for the really clear use case description, it makes total sense!
> 
> As the example in the diagram above in my previous comments shows, adding the logic that's desirable in your situation might cause problems in other situations. So we would prefer that user specify that dependency vs dbt inferring it. Do you feel like what Jerco mentioned method above: adding `--depends on: {{ ref('model_b') }}` to model c is a good solution for you?

This seems like a reasonable workaround to me given the above complexity. I've implemented that when it was suggested and it continues to work as expected.

**Comment by culpgrant** [comment]
I have a similar issue/unexpected behavior. I have a DAG of `model_a` -> `model_b` -> `model_c`, each of them is tagged with `my_tag`. I have a custom singular dbt test that `ref` `model_a` and a calendar dim model `model_calendar`. `model_calendar` is not tagged with `my_tag`.

When I run the command `dbt build --select tag:my_tag` it runs `model_a` then the custom singular dbt test. But if the custom singular dbt test fails it continues to process downstream models. The only way I can get `dbt build` to PASS is if I remove the `ref('model_calendar')` in the custom test. 

I almost need what is above but to force downstream models to depend on a test passing.

**Comment by jeremyyeo** [comment]
![image](https://github.com/user-attachments/assets/794318b9-45ea-4549-9e2d-3dc092a37e70)

Put a `--depends_on: {{ ref('dim_calendar') }}` in your model b.

![image](https://github.com/user-attachments/assets/a67eab62-608a-43dd-8cd5-da4f2cb5c21e)
