### ISSUE TITLE
[CT-701] Store test pass and failures using —store-failures flag

### ISSUE THREAD

**Issue by brittianwarner** [dbt-labs/dbt-core#5313]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

As a dbt user, I would like to store all tests including passes and failures.  As part of a DQ reporting initiative, we want to be able to see percentage of successful tests compared to failures.  We know we could possible customize the output to do this but am wondering if this can be built into the `--store-failures` flag and possibly a field in the created table for status (pass vs failure).  

### Describe alternatives you've considered

Create a service that reads dbt output to store test results.

### Who will this benefit?

Anyone reporting on data quality in a regulated environment.

### Are you interested in contributing this feature?

Yes the best I can. 

### Anything else?

This is more for individuals who have a requirement to report on DQ metrics.  It seems like most of the functionality is in place, however it is not clear on whether we can store successful tests along with failures.  Please, advise if I am missing something.

**Comment by brittianwarner** [comment]
Ref: https://github.com/dbt-labs/dbt-snowflake/issues/164

**Comment by hiattp** [comment]
@dlawrences ^

**Comment by dlawrences** [comment]
Hey @jtcohen6 

The approach we've taken for now is the following:

- reimplement any test we use (both generic tests of dbt and tests in other packages) to return all records in a model passing the test, as well as all records in the model failing it at the same time (alongside the model data, we are also sticking some metadata columns that we would use for further handling e.g. `__dbt_passed_test`, `__dbt_test_name`, `__dbt_test_model`, `__dbt_test_facet` - the latter being the aspect of the model being tested)
- override default dbt macro https://github.com/dbt-labs/dbt-core/blob/1cfc0851ca1e8da654acb2cdaf866536461e137b/core/dbt/include/global_project/macros/materializations/tests/helpers.sql#L1-L3 to call a custom macro instead of directly wrapping the `compiled_test_sql` into a subquery for reporting purposes; the custom macro does the following overall:

```jinja2
{% macro
    create or replace temporary table {{ a_target_table_for_the_results_of_the_current_test_in_the_current_execution }}
    {{ main_sql }};

    insert into {{ central_table_for_persisting_tests }}
    select {{ columns_transformations_to_conform_test_results }}
    from {{ a_target_table_for_the_results_of_the_current_test_in_the_current_execution }};

    select
      {{ fail_calc }} as failures,
      {{ fail_calc }} {{ warn_if }} as should_warn,
      {{ fail_calc }} {{ error_if }} as should_error
      from (
        select *
        from {{ a_target_table_for_the_results_of_the_current_test_in_the_current_execution }}
        where __dbt_test_passed = false
        {{ "limit " ~ limit if limit != none }}
      ) dbt_internal_test
{% endmacro %}
```
- the custom macro manages to execute only once the `compiled_test_sql` (referenced above as `main_sql`) of the test which is something we explicitly wanted

While working on this, we felt that a potential override in https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/tests/test.sql would have been slightly better since we would want to synchronise the work that dbt is doing in https://github.com/dbt-labs/dbt-core/blob/1cfc0851ca1e8da654acb2cdaf866536461e137b/core/dbt/include/global_project/macros/materializations/tests/test.sql#L5-L33 with the overall changes, however the issue we've faced is that `get_test_sql` is too aggressive in expecting only failures to be reported out of the `main_sql`, so we need to work around that.

Is there any possibility to expose some configuration that can be passed down to `get_test_sql` and expected out of the general test reporting to:
- allow, on configuration, `get_test_sql` to accept the test reporting both passing records and failing records
- request that a test reports the result of records using some `{{ metadata_column }}` that is configured ahead of time or defaulted to some standard one

If this was the case, then the override may be limited to only ensuring that tests report all that data back, and then handling the persistence of failing/passing/both type of records in the test materialization.
