### ISSUE TITLE
[CT-711] [Draft] Add Structured Logs to Materializations

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#5325]
### Motivation
Today, run_results.json is a static artifact written at the end of a run which contains a summary of the objects that `dbt run` created and updated along with an incomplete view of the sql from each materialization. This information should be more granular and be visible during a run. Structured logging is a formal interface for programmatically consuming metadata about a dbt run, and is where this more granular information will be streamed to outside consumers.

### Context
The materialization macro and the adapter functions it calls are natural places to put these log lines. However, many adapters override materialiations directly (i.e. snowflake, bigquery, spark), and others override key adapter functions such as `adapter.execute` (i.e. bigquery) which would require these and future adapter maintainers to remember to copy our log lines exactly the same. Requiring adapter maintainers to take direct action to maintain the reliability of the structured logging interface is something we'd like to avoid, which is why this ticket puts these logs lines before and after the call to execute in statement.sql ([source](https://github.com/dbt-labs/dbt-core/blob/7f953a6d48a4db254b17fd3929d267e4b6069228/core/dbt/include/global_project/macros/etc/statement.sql#L10)). Since statement.sql is not a Python file, structured logging must be accessible to jinja and today it is not.

### Implementation
- [ ] Create a new function in the jinja context `log_event` like `log` ([source](https://github.com/dbt-labs/dbt-core/blob/75f3e8cb749c7b52d226844394ecb34c1e0070a4/core/dbt/context/base.py#L576-L593)) so that instead of taking a string msg, it takes a string `event_name` and a list of values of type `List[Any]`. This will fire an event with the same name as the string passed with the parameters in the list. (Using `Event.__subclasses__()`, and the splat operator for lists (i.e. `*[foo, bar]`) may help here). Mypy will not be able to catch any type mismatches here since the event constructors aren't passed concrete values till runtime. Since these log lines will run with every materialization, tests should catch any issues with these log lines.
- [ ] Update [SQLQueryStatus](https://github.com/dbt-labs/dbt-core/blob/7f953a6d48a4db254b17fd3929d267e4b6069228/core/dbt/adapters/sql/connections.py#L73-L75) to take in the full `adapter_response` object, and node name. Today we stringify the adapter reponse first making it much harder to consume. Special attention will have to be paid to serialization since each warehouse will be putting different values into their own responses. Using examples from today's warehouses for inputs to serialization tests is a good idea. The name of the currently running node is accessible via the "jinja god context" (TODO: link example of how to access the jinja god context) (TODO: `adapter.execute` is called in other places too. We should add log lines there too. Link exact lines here.)

**Comment by jtcohen6** [comment]
> Requiring adapter maintainers to take direct action to maintain the reliability of the structured logging interface is something we'd like to avoid

Agree in principle. I'm on the fence about sticking this [in the `statement` macro](https://github.com/dbt-labs/dbt-core/blob/189c06dbb16f572d17337a1973aa6768d9abe8cf/core/dbt/include/global_project/macros/etc/statement.sql#L10), vs. just expanding the [`SQLQuery` event fired in `add_query`](https://github.com/dbt-labs/dbt-core/blob/189c06dbb16f572d17337a1973aa6768d9abe8cf/core/dbt/adapters/sql/connections.py#L66). This would indeed require some work in [`dbt-bigquery`'s custom `execute`](https://github.com/dbt-labs/dbt-bigquery/blob/1b85fc50287ac9afd81fd92e715dffa5f0757379/dbt/adapters/bigquery/connections.py#L424), which doesn't feel great, but... almost all adapters out in the world inherit from the "SQL" adapter.

Definitely curious to hear Gerda's thoughts on how to factor this code. Also tagging @dataders for visibility / fruit for thought: To what extent must we shy away from high-impact logging, or other important metadata, living in the adapter?

> TODO: adapter.execute is called in other places too. We should add log lines there too. Link exact lines here.

The important ones I can find:
- [`run_hooks`](https://github.com/dbt-labs/dbt-core/blob/189c06dbb16f572d17337a1973aa6768d9abe8cf/core/dbt/task/run.py#L355) in the `run` task (as in, `on-run-start`/`on-run-end` hooks)
- [`SqlExecuteRunner`](https://github.com/dbt-labs/dbt-core/blob/189c06dbb16f572d17337a1973aa6768d9abe8cf/core/dbt/task/sql.py#L78-L80), used by [`dbt.lib.execute_sql`](https://github.com/dbt-labs/dbt-core/blob/189c06dbb16f572d17337a1973aa6768d9abe8cf/core/dbt/lib.py#L109-L113)

We use it in our functional test utilities as well, [here](https://github.com/dbt-labs/dbt-core/blob/189c06dbb16f572d17337a1973aa6768d9abe8cf/core/dbt/tests/util.py#L332) and [here](https://github.com/dbt-labs/dbt-core/blob/189c06dbb16f572d17337a1973aa6768d9abe8cf/core/dbt/tests/util.py#L388)

### Logging relation info as soon as it's built

_This was another thing we discussed earlier today, related to this effort but possibly its own ticket_

Let's add structured logging about the _relations_ produced by the materialization, as soon as it finishes building them ([here](https://github.com/dbt-labs/dbt-core/blob/189c06dbb16f572d17337a1973aa6768d9abe8cf/core/dbt/task/run.py#L269-L275)). Materializations already return the set of relations it creates/updates, for the purposes of updating dbt's cache. Why not share the wealth with programmatic consumers of dbt metadata?

(Will serializing Relation objects be an absolute nightmare? Relation objects can be reimplemented by adapter, of course, though they all inherit from [`BaseRelation`](https://github.com/dbt-labs/dbt-core/blob/189c06dbb16f572d17337a1973aa6768d9abe8cf/core/dbt/adapters/base/relation.py#L26), which _should_ be serializable. Even so, we may not want _all_ the object attributes included in the logging event—probably just a subset.)

For now, the only really valuable information included on the relation object is database location (`database.schema.identifier`) and relation type (view, table, etc). However, I could see doing two things to make this _very_ valuable, for which this logging lays necessary groundwork:
- Additional fields like `columns` (with data types) and table statistics (maybe even column-level stats, too) — a.k.a. the same basic contract as [`CatalogInfo`](https://github.com/dbt-labs/dbt-core/blob/189c06dbb16f572d17337a1973aa6768d9abe8cf/core/dbt/contracts/results.py#L431)
- Steps at the end of each materialization that `describe` the just-built relation, to populate those fields, which will then be logged out once the materialization completes

Put it all together, and we'll be able to provide realer-time access to [catalog info](https://docs.getdbt.com/reference/artifacts/catalog-json), rather than trying to grab it all in one big memory-intensive batch during `docs generate`.

**Comment by jtcohen6** [comment]
I've come around on this, given the way that we've implemented Python on some adapters. The `statement` macro has become the "gateway" for both SQL + Python code, and it will call either `adapter.execute` or `adapter.submit_python_job` (on some adapters). Rather than require logging in both of those methods, trusting adapter maintainers to implement it for us, we should have that logging in one place — `statement`.

We'd still want to handle cases where:
- We hook into adapter.execute directly today (linked above). It's theoretically possible to call `adapter.execute` directly from the Jinja context, bypassing the `statement` / `run_query` situation — though it's not something we document.
- It's theoretically possible for an end user to override the `statement` / `run_query` macro... though I think a LOT of things would break :)

**Comment by ChenyuLInx** [comment]
In python model we currently added [a decorator ](https://github.com/dbt-labs/dbt-core/blob/1d1f915438ac69fb1c7f13d1027ac5725046cbec/core/dbt/adapters/base/impl.py#L1279)to log things.

**Comment by jtcohen6** [comment]
Assigning myself to reopen as two separate issues, and then close this one

**Comment by jtcohen6** [comment]
Closing in favor of #6731, #6732, #6733
