### ISSUE TITLE
[CT-719] Add Grants to Postgres Materializations

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-core#5329]
blocked by: #5263

Once the above work is merged, there are some tweaks that need to be made in the Postgres adapter to fully expose the feature:
    - [ ] for incremental, seed, and snapshot materializations call apply_grants(..., revoke=True)
    - [ ] otherwise (i.e. view/table materializations) call apply_grants(..., revoke=False) for a performance improvement

**Comment by jtcohen6** [comment]
- `get_grant_sql`: https://www.postgresql.org/docs/current/sql-grant.html (let's take this formulation as our default)
- `get_revoke_sql`: https://www.postgresql.org/docs/current/sql-revoke.html (let's take this formulation as our default)
- `get_show_grants_sql`: https://www.postgresql.org/docs/current/infoschema-table-privileges.html or https://www.postgresql.org/docs/current/infoschema-role-table-grants.html (I'm more inclined to use `show grants` as the default, since that's supported by more databases)
