### ISSUE TITLE
[CT-737] [Bug] Wonky pluralization when duplicate docs are found

### ISSUE THREAD

**Issue by pdebelak** [dbt-labs/dbt-core#5352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The error message for duplicate docs is:

```
dbt found two docss with the name "whatever".
```

### Expected Behavior

The error message would be:

```
dbt found two docs with the name "whatever".
```

### Steps To Reproduce

1. Create multiple `{% docs whatever %}` blocks with the same name.
2. Run `dbt parse`.
3. See the weird pluralization in the output.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### What database are you using dbt with?

redshift

### Additional Context

I believe the `pluralize` method of `NodeType.Documentation` would need to be updated to change this.

**Comment by jtcohen6** [comment]
@pdebelak Nice catch!

> I believe the `pluralize` method of `NodeType.Documentation` would need to be updated to change this.

You're spot on :) Would you like to contribute the fix for this?

https://github.com/dbt-labs/dbt-core/blob/72b6a80b07b3acc9aa64ae65c5d82191dbb1aa11/core/dbt/node_types.py#L57-L61

Is the plural of `docs`, `docs`? Should it be `docs blocks` (per [our docs](https://docs.getdbt.com/docs/building-a-dbt-project/documentation#using-docs-blocks))? I could go either way.
