### ISSUE TITLE
[CT-747] [Bug] Problem with Chinese Character

### ISSUE THREAD

**Issue by 1c7** [dbt-labs/dbt-core#5371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/1804755/173558719-44bb3ddf-ffcf-40bf-bd91-0b9227e09dfc.png">

> 'latin-1' codec can't encode character '\u65e0' in position 557: Body ('无') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

### Expected Behavior

Everything works fine. `dbt run` generate no error at all.

### Steps To Reproduce

1. write a SQL contain Chinese Character
Example: 
```sql
{ { config(materialized = 'view') } } 

with batch2022Spring as (
  SELECT id
  from mp_production.apply_applications
  WHERE deleted_at IS NULL
    AND batch_id = 7
    AND status = 'submitted'
),

final as (
  select *
  from apply_answers
  WHERE notEmpty(value_string)
    AND value_string NOT IN ['无', '没', '没有', '暂无', '/', '-', 'none']
    AND question_key NOT IN ['video_url', 'company_has_investment', 'company_url']
    AND application_id IN batch2022Spring
)

select *
from final
```

2. execute `dbt run`

### Relevant log output

```shell
10:20:05  Running with dbt=1.1.0
10:20:05  Found 1 model, 0 tests, 0 snapshots, 0 analyses, 186 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
10:20:05
10:20:06  Concurrency: 1 threads (target='dev')
10:20:06
10:20:06  1 of 1 START view model mp_production_dbt_playground.batch_2022_Spring ......... [RUN]
10:20:06  1 of 1 ERROR creating view model mp_production_dbt_playground.batch_2022_Spring  [ERROR in 0.23s]
10:20:06
10:20:06  Finished running 1 view model in 1.09s.
10:20:06
10:20:06  Completed with 1 error and 0 warnings:
10:20:06
10:20:06  Runtime Error in model batch_2022_Spring (models/example/batch_2022_Spring.sql)
10:20:06    'latin-1' codec can't encode character '\u65e0' in position 557: Body ('无') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
10:20:06
10:20:06  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Environment

```markdown
- OS: macOS Monterey (12.3.1)
- Python: 3.9.13
- dbt: 1.1.0
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

ClickHouse

**Comment by jtcohen6** [comment]
@1c7 I think this is likely a bug in ClickHouse, or potentially [`dbt-clickhouse`](https://github.com/ClickHouse/dbt-clickhouse), rather than one in `dbt-core`.

For example, I ran your same model via `dbt-postgres`, with some slight modifications for PostgreSQL, and to mock the data inputs. When I `dbt run`, I can see dbt running this SQL (in `target/run/` or `logs/dbt.log`):
```sql
  create view "jerco"."dbt_jcohen"."my_model__dbt_tmp" as (
     

with batch2022Spring as (
  SELECT id
  from (
    select 1 as id, null as deleted_at, 7 as batch_id, 'submitted' as status
  ) apply_applications
  WHERE deleted_at IS NULL
    AND batch_id = 7
    AND status = 'submitted'
),

final as (
  select *
  from (
    select 'not 无' as value_string, 'some_question' as question_key, 1 as application_id
  ) apply_answers
  WHERE nullif(value_string, '') is not null
    AND value_string NOT IN ('无', '没', '没有', '暂无', '/', '-', 'none')
    AND question_key NOT IN ('video_url', 'company_has_investment', 'company_url')
    AND application_id IN (select id from batch2022Spring)
)

select *
from final
  );
```
That is, it hasn't done anything to modify or re-encode the Chinese characters. dbt sends that query off to Postgres, and Postgres successfully creates the view.
```
11:48:09  1 of 1 START view model dbt_jcohen.my_model .................................... [RUN]
11:48:09  1 of 1 OK created view model dbt_jcohen.my_model ............................... [CREATE VIEW in 0.11s]
```
```
jerco=# select * from dbt_jcohen.my_model;
 value_string | question_key  | application_id
--------------+---------------+----------------
 not 无       | some_question |              1
(1 row)
```

I'm guessing that this is an issue with the character encoding supported by ClickHouse, or (more likely) the [`clickhouse-connect` library](https://github.com/ClickHouse/clickhouse-connect) which `dbt-clickhouse` uses to submit its queries. I'd encourage you to reopen this issue over in the [`dbt-clickhouse`](https://github.com/ClickHouse/dbt-clickhouse) repo.

**Comment by 1c7** [comment]
@[jtcohen6](https://github.com/jtcohen6) Thank you!
