### ISSUE TITLE
[CT-774] [Feature] custom logger name

### ISSUE THREAD

**Issue by jefferyng33106** [dbt-labs/dbt-core#5407]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Hi, I am wondering whether it's possible to have a feature to define the logger name as environment variable

For example,

```
export DBT__LOGGING_TASK_NAME=airflow.task
```

then when do the logger initialization like getLogger
```
logger_name = conf.get("logging", "task_name")

logger = logging.getLogger(logger_name)
```

So that we can collect the logs by the given logger

### Who will this benefit?

All the DBT users

### Are you interested in contributing this feature?

me or my colleague will be happy to help

**Comment by jtcohen6** [comment]
From group conversation:
- Let's definitely rename the loggers to be prefixed `dbt_` instead of `default_`
- Open question as to whether we want to condone end users modifying the logger with Python wrapper when importing `dbt-core` as a library/module (not a thing that's yet officially supported today), given the increasing importance of structured logging as a `dbt-core` metadata interface
- **Strong opposition** to supporting this as a flag / environment variable that dynamically renames the logger at runtime
