### ISSUE TITLE
[CT-801] [Feature] The model argument to generic tests should always be a relation

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-core#5435]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Me:
> Hi Jeremy just want to run something by you - it would seem like the [get_where_subquery](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/tests/where_subquery.sql) macro can return either a relation object or a str object, is that correct? A project I'm working with has overridden that macro to add some filtering for generic tests, but it's then causing an issue where the model argument to generic tests is no longer a relation type but is just a string. Would it be better if the get_where_subquery macro was designed to just alter the string representation of the relation, rather than replacing the relation with a string object altogether?

Jeremy:
> You're totally right, that is exactly what happens [...] This feels like a really good idea! Would just require a modification to [BaseRelation.render](https://github.com/dbt-labs/dbt-core/blob/60e491b3c178ee8112dbe1311bcc69e5c778ccfa/core/dbt/adapters/base/relation.py#L176-L178), I think. Trying to think of how it might go wrong, but it's passing most mental checks...

Me:
> It's causing an issue with https://github.com/elementary-data/dbt-data-reliability for example, which attempts a [{%- set model_relation = dbt.load_relation(model) %}](https://github.com/elementary-data/dbt-data-reliability/blob/master/macros/edr/tests/test_table_anomalies.sql#L21) on the model argument to the test. That model argument becomes a string type depending on what get_where_subquery does.

This feature encompasses a couple of things which I'd love to see:
* The response from `get_where_subquery` is not passed directly as the model argument to generic tests, but is set as the string representation of the relation object which is passed to generic tests (non breaking change unless someone relies on the argument being a string type not a relation, but I highly doubt this considering that the argument can be either a relation or a string type today)
* An attribute on the relation object which always represents its location in the database. This would be unaffected by the result of `get_where_subquery`.

### Who will this benefit?

Anyone who writes custom generic tests that would like to either ignore the response of the `get_where_subquery` macro, or rely on access to the relation object (which is what the Elementary package does).

**Comment by NiallRees** [comment]
Adding this to the top of the `get_where_subquery` works as a temporary fix:
```
  {% if model | selectattr("package_name", "equalto", "elementary") %}
  {% do return(model) %}
  {% endif %}
```

**Comment by jtcohen6** [comment]
@NiallRees Thanks for opening!

I think the most desirable outcome here manages to accomplish two outcomes:
1. The `{{ model }}` argument to generic tests is always a `Relation`, regardless of the config set — so that authors of generic tests can comfortably pass it into macros like `get_columns_in_relation`
2. Every generic test can support the `where` config, without needing to make any changes to the generic test definition — because, if `where` config is specified

I'm honestly not sure if there's a way to make that possible, but that's what feels desirable to me!

Maybe that looks like a new `Relation` method/property to accept a subquery/filter, which then updates the output of `Relation.render()`, while still preserving the `Relation` object itself — while still giving users a way to render the relation's database location, without the subquery / filter. (In the worst case, they'd still have direct access to all attributes and methods of the `Relation`, including `database.schema.identifier`.)

I don't think this is something we're going to be able to prioritize on our end—but I think the code for it is _relatively_ self-contained, the test cases are highly straightforward, and the biggest risk is the potential blast radius of mucking with `BaseRelation` (and object used _everywhere_). Maybe a new subclass, just for tests...? Probably a bad idea :)
