### ISSUE TITLE
[CT-813] [Feature] Improve resource-path nomenclature to allow basic regex patterns

### ISSUE THREAD

**Issue by adamcunnington-mlg** [dbt-labs/dbt-core#5442]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

It would be really cool if the resource-path was more sophisticated. Currently, a resource-path can be a project name or a model name, and you can nest model names underneath sub-directories. I have a really robust folder structure and want to use this to power functionality, dynamically.

An example of what I want to be able to do is automatically grant permissions to x group where x is a sub-directory. I propose positional capturing groups from a basic regex flavour.

I think this example is fairly self-explanatory of what I want to be able to do:
```
models:
  my-project:
    some-parent-dir.some-child-dir.(.+).(.+).sql:
        post_hook: GRANT SOME_PERMISSION TO foo-$1-users@company.com ON $2
```

The GRANT SQL is pseudo code but what I am trying to do here is dynamically grant some access to the table/view created by a model where the directory containing the sql file is the first captured group (some value that resolves to a valid group name when $1 is substituted) and where the second captured group is the name of the created table/view itself (probably a better way of doing this).

There's a lot of room for design compromise here though so mostly looking to spark a discussion around making resource-paths more flexible. The docs already implies that if you don't want something to apply to all children, your only option is to go for an explicit path which is a shame when for example, you have 1 exception to a rule that would otherwise be ubiquitous - or the use case I showed above (dynamic information). 

### Describe alternatives you've considered

Maintaining a copy and paste of same information. Undermines DRY (as well as general maintainability).

### Who will this benefit?

Everyone who wants to use a more advanced syntax for resource-path, without negatively affecting anyone that does not.

### Are you interested in contributing this feature?

Perhaps - but is a question of design first

**Comment by jtcohen6** [comment]
@adamcunnington-mlg Hmm! I think there's another way of achieving your particular use case. I'm also hesitant to add regex support to further complexify an already implicitly tricky behavior in dbt, being config inheritance.

There is a way to do this, leveraging the `model` context variable, which returns the manifest node for the model being materialized. We have some docs on this (unfortunately quite sparse): https://docs.getdbt.com/reference/dbt-jinja-functions/model

The node object returned by `model` includes the `fqn` ("fully qualified name") of the model, which maps exactly to the model's relative file path. You use the FQN when specifying config in `dbt_project.yml`. So, here goes:

```sql
{% macro grant_some_permission_macro() %}

  {% set fqn = model.fqn %}
  /*{# e.g. ['my_project', 'some_parent_dir', 'some_child_dir', 'part_a', 'part_b', 'some_model'] #}*/

  {% set first, second = fqn[3:5] %}
  
  GRANT SOME_PERMISSION TO foo-{{ first }}-users@company.com ON {{ second }}

{% endmacro %}
```

Try it out:

```yml
models:
  my_project:
    some_parent_dir:
      some_child_dir:
        post-hook: "{{ grant_some_permission_macro() }}"
```
```
models/
|____some_parent_dir/
| |____some_child_dir/
| | |____part_a/
| | | |____part_b/
| | | | |____some_model.sql
```
```
18:31:12.541569 [debug] [Thread-1  ]: On model.my_project.some_model: /* {"app": "dbt", "dbt_version": "1.3.0b2", "profile_name": "garage-postgres", "target_name": "dev", "node_id": "model.my_project.some_model"} */

        /**/
  
  
  GRANT SOME_PERMISSION TO foo-part_a-users@company.com ON part_b
```

Unfortunately, this is only possible for post-hooks. Other configs set at the project level are rendered at parse time, rather than having their rendering time delayed until execution time, and the parse-time rendering context doesn't support custom macros or node-specific properties.

I'm going to close this issue, as I think there's a valid workaround for the specific use case requested, and I don't foresee us adding regex support to the FQN-based config specification in `dbt_project.yml`.

**Comment by adamcunnington-mlg** [comment]
Fair call and tanks for the example workaround using model.

**Comment by oakromulo** [comment]
@jtcohen6

> _"I'm also hesitant to add regex support to further complexify an already implicitly tricky behavior in dbt, being config inheritance."_

would it also be the case even if only glob-like wildcard patterns were allowed instead of full (and slow) regex support? it'd be really nice to be able to e.g. apply specific configs to all models on a given path ending with a given (static) suffix

**Comment by oakromulo** [comment]
@jtcohen6

> _"I'm also hesitant to add regex support to further complexity an already implicitly tricky behavior in dbt, being config inheritance."_

what would you say if only some basic glob-like wildcard patterns were allowed instead of full (and slow) regex support? it'd enable multiple use cases such as applying specific configs to models ending with some pre-defined (static) suffix

another way to put it: the basic-pattern-matching would be analogous to [SQL LIKE](https://www.w3resource.com/PostgreSQL/postgresql-like-operator.php) operator, usually an order of magnitude faster than its [SIMILAR TO](https://www.w3resource.com/PostgreSQL/postgresql-similar-operator.php) counterpart w/ regex support

in terms of config inheritance these could still follow the pattern that the "most specific config always holds precedence" and its scope could remain limited to `dbt_project.yml` with direct resource-paths taking precedence over the proposed basic-pattern-matched ones

the most tricky part would be to establish precedence if a given subset of models gets matched by multiple overlapping pattern-based resource-paths but there could be some workarounds w/o introducing a lot of complexity:

- throw a warning of "truly unpredictable behavior" whenever conflicting configs are getting scoped for the same model via pattern matching

- throw a hard error (just as with circular dependencies) and introduce a `resource-priority` integer config that can be used to resolve precedence in case of conflicts 

- decide based on the yml file order e.g. pick first or last (might be a bad idea as it could introduce version-specific parser-related side-effects)

- introduce additional but still simple rules:
  - broadness: patterns that apply to the least number of overlapping resources receive higher precedence
  - length + A-z order: patterns with most characters (generally more specific) take precedence as primary criterion and A-z is used as secondary
