### ISSUE TITLE
[CT-816] [Bug] Incremental materialization - cast column when changing column type

### ISSUE THREAD

**Issue by Olaktal** [dbt-labs/dbt-core#5445]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Hello,

DWH type: Redshift

In the incremental materialization, when [altering column type](https://github.com/dbt-labs/dbt-core/blob/35005285064f55f6482719fc2d272c0f0dbb7bde/core/dbt/include/global_project/macros/adapters/columns.sql#L52) , no cast is made.

In our model, a column type has changed from `varchar` to `timestamp` resulting in an error because we are trying to insert varchar into a timestamp column. A cast to the destination column type will solve this issue and in general, I don't see any problem in converting values systematically in the destination column type, what do you think?

### Describe alternatives you've considered

Modifications:
```
    update {{ relation }} set {{ adapter.quote(tmp_column) }} = {{ adapter.quote(column_name) }}::{{ new_column_type }};
```

`::` operator is postgres database specific so the modification should be made in the postgres adapter

### Who will this benefit?

dbt + postgres users

### Are you interested in contributing this feature?

I can try to make the modification if you are ok with my proposal
I signed the CLA.

**Comment by dbeatty10** [comment]
@Olaktal Thanks for opening!

Is this a new bug in dbt-core? In other words, is this an error, flaw, failure or fault in our software?

Looking into this a bit (but without testing it myself), this looks like a bug to me. It would affect Redshift 

Let's take a quick look at a few adapters to confirm or deny:
- [Snowflake](https://github.com/dbt-labs/dbt-snowflake/blob/v1.2.0/dbt/include/snowflake/macros/adapters.sql#L179-L183) and [Spark](https://github.com/dbt-labs/dbt-spark/blob/v1.2.0/dbt/include/spark/macros/adapters.sql#L265) have direct syntax for altering the data type of a column so it's implementation is very straightforward and doesn't even need a cast.
- [BigQuery](https://github.com/dbt-labs/dbt-bigquery/blob/v1.2.0/dbt/include/bigquery/macros/adapters.sql#L182) requires re-writing the entire table to change the column type, and it uses a cast.
- [The default](https://github.com/dbt-labs/dbt-core/blob/v1.2.0/core/dbt/include/global_project/macros/adapters/columns.sql#L52) implementation inherited by Postgres, Redshift, and other database adapters doesn't contain a cast, as you pointed out.

Here would be my suggested implementation (currently un-tested), which looks a lot like your suggestion, but should work across more databases by using the standard SQL `cast()` syntax:

```sql
    update {{ relation }} set {{ adapter.quote(tmp_column) }} = cast({{ adapter.quote(column_name) }} as {{ new_column_type }});
```

As you noted, the suggested line of code would go right [here](https://github.com/dbt-labs/dbt-core/blob/v1.2.0/core/dbt/include/global_project/macros/adapters/columns.sql#L52).

## Instructions for implementation
- [ ] Validate the failure case locally using Redshift and/or Postgres
    1. Create two seeds files with identical column names, but different data types (timestamps, then strings)
    1. Create one incremental model that loads from the first seed and run it
    1. Update the incremental model to load from the second seed and run it
- [ ] Create a functional test that fails for this use case (to prevent a regression in the future)
- [ ] Implement the change suggested above

## Future ideas
I looked for a cross-database `cast()` macro, but the closest I could find was [`safe_cast()`](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros#safe_cast)

Feature request: Add a default `cast()` cross-database macro that Postgres and Redshift could optionally override with the `::` syntax. 

## Notes for adapter maintainers

There are three main ways to implement the `alter_column_type` macro:
1. If available, use the database's built-in DDL function for changing a column's data type.
2. Use a SQL query to select the table data, cast the relevant column, and overwrite the table.
3. Add a new column with the desired type (using a temporary name), backfill values from the old column into the new (casting along the way!), drop the old column, and rename from the temporary column name to the old column name.

Here's a decision tree for implementing the `alter_column_type` macro:
1. Does your database have a direct method to update the data type of a column (similar to Snowflake and Spark)?
    - If so, use it (method 1 above).
2. Is adding or dropping a column an "expensive" operation that requires a full table scan (similar to BigQuery)?
    - Overwrite the table (method 2 above).
3. None of the above (like Postgres and Redshift)?
    - Do nothing to use the default implementation (method 3 above).

**Comment by jtcohen6** [comment]
@dbeatty10 I think you're right on the money! A `cast()` here should do the trick, and it's fair that a user would expect this to work.

One thing I did want to call out:

> Does your database have a direct method to update the data type of a column (similar to Snowflake and Spark)? If so, use it (method 1 above).

Snowflake's built-in `alter table alter type` does _not_ support changing a column's data type to another data type. From [Snowflake docs](https://docs.snowflake.com/en/sql-reference/sql/alter-table-column.html):

> Change a column [data type](https://docs.snowflake.com/en/sql-reference/data-types.html) to a different type (e.g. STRING to NUMBER).

In this case, the "hard refresh" of the column (default approach) _would_ work, but the [Snowflake-specific approach](https://github.com/dbt-labs/dbt-snowflake/blob/340c3faaa43cff425c92161e4918beb171f1196f/dbt/include/snowflake/macros/adapters.sql#L187-L191) would _not_ work.

Maybe dbt _should_ opt into the "hard refresh" version if [`on_schema_change`](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#default-behavior) is set to "sync all columns" (including data type changes)? (I think that's the context for [calling the `alter_column_type` macro](https://github.com/dbt-labs/dbt-core/blob/4d6208be6464a48a078dd8000ae6c29d8d7a42ce/core/dbt/include/global_project/macros/materializations/models/incremental/on_schema_change.sql#L79-L85) in this issue.)

A balanced approach we could consider taking: `snowflake__alter_column_type` uses built-in `alter table alter column` IFF the old + new types are compatible (aliases, or just increasing length/precision), and then opts for the "hard refresh" default otherwise.

**Comment by dbeatty10** [comment]
@jtcohen6  Thanks for expanding the context and correcting the key details!

Logically, the balanced approach makes sense (but I'm guessing would be a bit tricky in implementation).

The suggestion to opt into the "hard refresh" version if [on_schema_change](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#default-behavior) is set to "sync all columns" sounds a lot more straight-forward in terms of implementation.

### Ancillary commentary
Regardless of the approach chosen, I'd expect the `dbt run/build` to fail if the old data type can't be `cast()` to the new data type. Does that sound right?

This could be "solved" by exposing an option to use [`safe_cast()`](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros#safe_cast) instead. If we go that route, we'd want to user to opt-in to that configuration since it would fill in `null` values whenever the cast didn't work. There are some databases that don't support `safe_cast()`, and those would just fail no matter what.
