### ISSUE TITLE
[CT-818] [Bug] Comments at end of model definition can break compilation and/or runs

### ISSUE THREAD

**Issue by daweimau** [dbt-labs/dbt-core#5449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This issue is very similar to an [old bug](https://github.com/dbt-labs/dbt-core/issues/1018).

The below model definition cannot compile, and instead throws:

```sql
{{ config(materialized='incremental') }}
select
  1 as id 
-- comment about incremental config with example here:  
-- {{
-- config(
--     materialized = 'incremental',
--     unique_key = 'id',
--     merge_update_columns = [],
-- )
-- }}
```

Result:
```
Server error: Compilation Error in rpc request (from remote system)
expected token ',', got '='
line 11
-- materialized = 'incremental',
```

Changing to block comments:
```sql
{{ config(materialized='incremental') }}
select
  1 as id 

/*
comment about incremental config with example here:  
{{
config(
    materialized = 'incremental',
    unique_key = 'id',
    merge_update_columns = [],
)
}}
*/
```

Result:

* Compiles fine, runs fine in preview
* `dbt run mymodel` - FIRST RUN - Fine
* `dbt run mymodel` - subsequent runs - Failure with error:

```
Database Error in model tmp (models/indebted/stage_a/tmp.sql)
  001003 (42000): SQL compilation error:
  syntax error line 12 at position 9 unexpected 'not'.
  syntax error line 12 at position 21 unexpected 'then'.
  compiled SQL at target/run/DataStandardisation/models/indebted/stage_a/tmp.sql
```

Removing the comments cures all errors. Not **every** comment raises these errors. It seems the comment is really getting parsed to some extent.

### Expected Behavior

Regardless of their content and placement, comments should not cause compile or run errors

### Steps To Reproduce

Create models with the above definitions, and attempt to run compile them, then run them in `dbt run`.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### What database are you using dbt with?

snowflake

**Comment by jtcohen6** [comment]
@daweimau Thanks for opening! I think the issue here is that there's a distinction between _Jinja comments_ and _SQL comments_. Even though you've added SQL comments (`--` or `/* */`) to your `config()` macro call, it's not commented out from Jinja's perspective. So your observation here is right on:

> It seems the comment is really getting parsed to some extent.

The right resolution here, going all the way back to #458, is to use [Jinja comments](https://docs.getdbt.com/docs/building-a-dbt-project/jinja-macros#jinja:~:text=Comments%20%7B%23%20...%20%23%7D%3A%20Jinja%20comments%20are%20used%20to%20prevent%20the%20text%20within%20the%20comment%20from%20compiling) instead:

```sql
{{ config(materialized='incremental') }}
select
  1 as id 

{#
comment about incremental config with example here:  
{{
config(
    materialized = 'incremental',
    unique_key = 'id',
    merge_update_columns = [],
)
}}
#}
```
(To accommodate the syntax highlighting in most text editors, you may want to double up and use `/* {#` and `#} */`.)

Explanations two particular errors you've been seeing:
1. The presence of `--` inside the Jinja macro `config()` is not recognized as valid syntax
2. When `merge_update_columns = []`, the `update` set is totally empty. (Perhaps dbt should skip the `update` clause entirely—I'd welcome this as a new issue, probably an `enhancement`.)
```sql
merge into <my_model> as DBT_INTERNAL_DEST
        using <tmp_version> as DBT_INTERNAL_SOURCE
        on 
                DBT_INTERNAL_SOURCE.id = DBT_INTERNAL_DEST.id

    when matched then update set
        
    

    when not matched then insert
        ("ID")
    values
        ("ID")
;
```

I'm going to close this issue in the meantime.
