### ISSUE TITLE
[CT-839] Unable to override exising macro

### ISSUE THREAD

**Issue by topofstack** [dbt-labs/dbt-core#5467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not sure if it's a bug or not. I need to override incremental model's behaviour, so i've added an override for  `incremental_upsert` macro by creating a file with a name `incremental_upsert.sql` in dbt's `macro` dir. The file contains the following code.
```
{% macro incremental_upsert(tmp_relation, target_relation, unique_key=none, statement_name="main") %}
    {%- set dest_columns = adapter.get_columns_in_relation(target_relation) -%}
    {%- set dest_cols_csv = dest_columns | map(attribute='quoted') | join(', ') -%}

    RAISE division_by_zero;  -- just a stub to see if it actually works
{%- endmacro %}
```
When models are executed, I see that number of macros is incremented by one, but all the models are executed as usual, without any effect.

I followed this https://github.com/dbt-labs/dbt-core/issues/3020 to get the idea.

### Environment

```markdown
- OS: MacOS 11.6.4
- Python: 2.7.16
- dbt: 1.1.1
```

### What database are you using dbt with?

postgres

**Comment by jtcohen6** [comment]
@topofstack Thanks for opening!

> I followed this https://github.com/dbt-labs/dbt-core/issues/3020 to get the idea.

Since the conversation in that issue (~18 months ago), we refactored the code in the [`incremental` materialization](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/models/incremental/incremental.sql), and removed the `incremental_upsert` macro since it is no longer used (https://github.com/dbt-labs/dbt-core/pull/4154, https://github.com/dbt-labs/dbt-core/pull/4154/commits/99b40732713c1fe5b184a8e8c38c149cef8c7eb6).

I think the macro you'd now want to override is called `get_delete_insert_merge_sql`, and the code for it is here:

https://github.com/dbt-labs/dbt-core/blob/e03d35a9fc606f5b1fc7e94c0bc04dbe88f558cf/core/dbt/include/global_project/macros/materializations/models/incremental/merge.sql#L55-L86
