### ISSUE TITLE
[CT-841] [Bug] `dbt init .` creates logs at the root directory, then asks for target directory

### ISSUE THREAD

**Issue by clrcrl** [dbt-labs/dbt-core#5471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. Run `dbt init .`
2. **Expected result**: I'm not actually sure! I was just testing this out to see what it did, I guess I expected it to create my project in the current directory (i.e. create `./models` and `./tests` etc.
3. **Actual result**: dbt creates a `./logs` directory, and then gives you a message about needing to have a different project name
```
Creating dbt configuration folder at /home/vscode/.dbt
. is not a valid project name.
Enter a name for your project (letters, digits, underscore): jaffle_shop
```
5. Once I entered `jaffle_shop` it created everything in the `./jaffle_shop` subdirectory, but yeah it left behind a file in `./logs`
```
$ ls logs/
dbt.log
```
<img width="382" alt="Screen Shot 2022-07-13 at 8 34 24 pm" src="https://user-images.githubusercontent.com/20294432/178892422-424ca7bb-0da4-47d5-9ed0-b8f88e75812e.png">

Anyway such a minor bug, but thought I would do my duty to report it, and it should be a pretty good first issue!

### Environment

```markdown
$ dbt debug
03:37:49  Running with dbt=1.1.1
dbt version: 1.1.1
python version: 3.9.13
python path: /usr/local/python/bin/python3
os info: Linux-5.4.0-1074-azure-x86_64-with-glibc2.3
```

**Comment by jtcohen6** [comment]
@clrcrl Thanks for opening :)

The logs that show up in the original root directory's `logs/dbt.log` include the log events that dbt fires [while being initialized from the CLI](https://github.com/dbt-labs/dbt-core/blob/f988f76fccc1878aaf8d8631c05be3e9104b3b9a/core/dbt/main.py#L221-L234):

```
$ cat logs/dbt.log


============================== 2022-07-14 08:45:58.288946 | 37340441-8058-4fb0-b879-627a5bdfcc09 ==============================
08:45:58.288951 [info ] [MainThread]: Running with dbt=1.1.0
08:45:58.289155 [debug] [MainThread]: running dbt with arguments {'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': False, 'partial_parse': True, 'static_parser': True, 'profiles_dir': '/Users/jerco/.dbt', 'send_anonymous_usage_stats': False, 'event_buffer_size': 100000, 'quiet': False, 'no_print': False, 'skip_profile_setup': False, 'which': 'init', 'indirect_selection': 'eager'}
08:45:58.289225 [debug] [MainThread]: Tracking: do not track
```

Specifically, I think it's this line that's causing the new "event" logger to pick `logs/dbt.log` as its default relative path, if unsupplied with other config:
https://github.com/dbt-labs/dbt-core/blob/f988f76fccc1878aaf8d8631c05be3e9104b3b9a/core/dbt/main.py#L228

We'd need some way to disable that logging for the `init` task, or find a way to batch it in memory, until we know where we actually want our `logs` directory to go (based on user input). I tried removing that `"logs"` default, just to see what would happen, and very quickly ran into errors. I think this might be a bit trickier than a `good_first_issue`, unfortunately.

We have gotten the request before for `init` to create its files in the current working directory (https://github.com/dbt-labs/dbt-core/issues/3024), rather than a new directory — but that's how `init` has been working for a long time, it allows us to coordinate project/profile naming across directory + `dbt_project.yml` + `profiles.yml`, and it seems to work for most of what it's needed to do.

**Comment by iknox-fa** [comment]
This was estimate with the intent of disabling logging for the init command.
