### ISSUE TITLE
[CT-843] [Feature] Adapter-specific starter projects

### ISSUE THREAD

**Issue by panasenco** [dbt-labs/dbt-core#5473]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

When `dbt init` runs, it should use an adapter-specific starter project rather than the generic starter project if an adapter-specific one is available.

Specifically, the `init` task will first search the path `dbt.current_adapter.include.starter_project.PACKAGE_PATH` and if that doesn't exist then fall back to the default `dbt.include.starter_project.PACKAGE_PATH`.

### Describe alternatives you've considered

Using [cookiecutter](https://github.com/boromir674/cookiecutter-python-package) or a similar tool instead of `dbt init`. However, that seems overkill since the change required to `dbt init` is very small.

### Who will this benefit?

This will create a more seamless experience for folks getting started with dbt as they can get started with examples and documentation that help them understand the particular adapter they're working with. This will be especially useful for more adapters to non-standard databases.

### Are you interested in contributing this feature?

I'll do it if the adapter I'm working on starts gaining traction

**Comment by jtcohen6** [comment]
@panasenco Thanks for opening!

I mostly buy what you're saying. We do aim to make the starter project as generic as possible, so that it can run on all dbt adapters—but the question raised here isn't really one of compatibility, as much as customizability.

I'm also very slightly concerned by the risk of drift, between updates we make to our starter project, and an adapter-specific version. But it's only a very slight concern. We don't update our starter project very often, and at the point where an adapter maintainer is implementing a custom one, they understand that they're taking on that code as surface area to maintain going forward.

> Specifically, the init task will first search the path `dbt.current_adapter.include.starter_project.PACKAGE_PATH` and if that doesn't exist then fall back to the default `dbt.include.starter_project.PACKAGE_PATH`.

I think this makes sense as an implementation mechanism. We'd need to ensure that the `starter_project` is not lumped in with the rest of the `include/` directory, in terms of the macros that the adapter is expecting to load up for all projects. So having these live side-by-side, e.g. `include/snowflake` and `include/starter_project`, feels like it should work with the existing pattern.

I'm going to mark this one as `help_wanted` (slightly trickier than `good_first_issue`), and welcome a contribution if you or another adapter maintainer feels up for it! It sounds like you've already done a bit of digging through the codebase. I think it would just require an update here:

https://github.com/dbt-labs/dbt-core/blob/71223dc2531b83e0c41dc59b211516c80d6425fe/core/dbt/task/init.py#L33

Perhaps using logic to iterate through adapter directories, similar to what we have here:

https://github.com/dbt-labs/dbt-core/blob/71223dc2531b83e0c41dc59b211516c80d6425fe/core/dbt/version.py#L209-L235
