### ISSUE TITLE
[CT-859] [Feature] hooks in target folder

### ISSUE THREAD

**Issue by johannes-becker-otto** [dbt-labs/dbt-core#5490]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

I am using some rather complex run-operations and hooks and was wondering if their actions could become a part of the target folder.

This seems to me relatively straight forward for the hooks (sorry if that is a wrong assumption) and I would suggest subfolders similar to the schema.yml folder found in
target/run/project_name/.../schema.yml/unique_TABLE_NAME_COLUMN_NAME.sql

Maybe
target/run/project_name/.../pre_hooks/TABLE_NAME_pre_hook.sql

I am not sure about the run-operation

All the best
Hannes

**Comment by lostmygithubaccount** [comment]
Hi @johannes-becker-otto, thanks for opening this! It seems like an oversight, so I'll reclassify to a bug. If you're interested in contributing this yourself, we can likely give some guidance, otherwise we'll throw it on the backlog to address.

**Comment by jtcohen6** [comment]
Models/snapshots/etc do this using the `write` method:
https://github.com/dbt-labs/dbt-core/blob/a3b018fd3b0c789c976e0e189788471edef8acb1/core/dbt/context/providers.py#L770-L776

Called within the "main" statement of materializations:
https://github.com/dbt-labs/dbt-core/blob/a3b018fd3b0c789c976e0e189788471edef8acb1/core/dbt/include/global_project/macros/etc/statement.sql#L8-L11

I think it could make sense to "write" the compiled SQL executed by `on-run-*` hooks, which are called within the `run` task (and child tasks), and do get "compiled" in a way similar to how models are compiled.|

Writing pre- and post-hooks would be slightly trickier, since they're called from within materializations. It's been a longstanding need for materializations to actually write their full content — _every query they run_ — rather than just the "main" statement. This is a problem for multi-step materializations as well (e.g. incremental).

In the meantime, dbt does log every query it runs, and that log message should include some information about the thread / model it's running for.

**Comment by johannes-becker-otto** [comment]
Hi,
was on holidays :) so delayed reply.
I'm afraid my dbt-core skills + time restrictions won't allow me to look at it myself.
"In the meantime, dbt does log every query it runs, and that log message should include some information about the thread / model it's running for." - I'll try to search through the log file to see what it's telling me.
Cheers
Hannes
