### ISSUE TITLE
[CT-886] [Feature] Add create schema to dbt compile?

### ISSUE THREAD

**Issue by moreaupascal56** [dbt-labs/dbt-core#5513]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Hello team, 

Maybe a dumb question or a wrong process on my side🤔 
My usual process is to run: 
- `dbt compile`
-  Then: `dbt run`

But when a new target schema (not existing on the data warehouse) needs to be created on snowflake for example, dbt compile will fail because it does not exist, this implies to either: 
- create the schema manually on the data warehouse
- start with dbt run instead of dbt compile to create the schema with this line [https://github.com/dbt-labs/dbt-core/blob/2548ba99369a38fa8c15050e00e4c5f7152d27d6/core/dbt/task/run.py#L442](https://github.com/dbt-labs/dbt-core/blob/2548ba99369a38fa8c15050e00e4c5f7152d27d6/core/dbt/task/run.py#L442). 

I was wondering if a `before_run` step in dbt compile would make sense to create the schema as well. 

Thanks and have a great day :) 

### Are you interested in contributing this feature?

yes

**Comment by jtcohen6** [comment]
@moreaupascal56 Thanks for opening! I'm inclined to preserve the existing behavior, which is that `dbt compile` _does_ run introspective queries as needed to compile model SQL, but not create any new objects in the data warehouse.

I think this issue is motivated by a failure during the `dbt compile` step when the new schema does not exist. In the general case, this should not happen—`compile` should not fail when run in a new schema for the first time.

I think `dbt compile` _will_ fail if:
- a model, analysis, or other resource requires an introspective query in order to template its compiled SQL
- that introspective query depends on `{{ target.schema }}` or another referenced resource in the project — which hasn't yet been built, because it's a `dbt compile` step!

For example:
```sql
-- analysis/something.sql
{% set introspective_sql %}
-- this will fail if the schema does not yet exist
show objects in schema {{ target.schema }}
{% endset %}

{% set results = run_query(introspective_sql) %}

select 1 as id

```

This will cause `dbt compile` to fail if the schema does not yet exist, and then succeed after. Do you see, in your error message, a specific model/analysis/other that is encountering the error?

---

> My usual process is to run:
> 
> `dbt compile`
> Then: `dbt run`

Is there a specific reason why you're running `compile` ahead of `run`? When I hear folks say this, it's often due to a common misconception about what `dbt compile` does. It's not for parsing the project and constructing the internal representation, including any parse-time checks (that's `dbt parse`). `compile` is also not a needed prerequisite for `run`—rather, `run` includes a "compile" step for each model (at the right spot in the DAG), and `compile` does 95% of what `run` does. The only thing `compile` _doesn't_ do, which `run` does, is materialize the results of a model's compiled SQL as a table/view/etc in the database.

So, in practice, there's no real workflow reason to run `dbt compile` before `dbt run` — compilation is included as part of the `run` step, and crucially compilation occurs in DAG order in `run`, so that resources needed for downstream SQL compilation will already exist by the time they're needed to compile that SQL.

**Comment by moreaupascal56** [comment]
hi 👋  thanks for the detailed response, yes that's exactly the case the team is running compile before run just because it is a fastest way to check if there is issue on the code, I agree that compile is not necessary at all and get the philosophy of the command, I'm closing the issue :) 
Thanks and have a great day!
