### ISSUE TITLE
[CT-897] [Feature] Add Jinja function which returns all dbt variables

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-core#5523]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Add a function which returns all the currently set variables. Use case is for the dbt_artifacts package's https://github.com/brooklyn-data/dbt_artifacts/blob/main/models/fct_dbt__invocations.sql model.

**Comment by jtcohen6** [comment]
@NiallRees Thanks for opening!

This one is a touch trickier, because var scoping is frankly confusing:
- Vars used in `profiles.yml` + `dbt_project.yml` can only be CLI vars (passed via `--vars`)
- Vars defined in `dbt_project.yml` can be scoped globally, or to specific projects (including installed packages)

I think the goal here is to:
- Return the set of `cli_vars` — these always "win"
- Return the dictionary representation of `vars` defined in `dbt_project.yml`, a.k.a. [`VarProvider.to_dict()`](https://github.com/dbt-labs/dbt-core/blob/94a7cfa58df3df5d3b07b619c0510fead9195700/core/dbt/config/project.py#L513-L514), which would also nest vars according to their scope (global vs. project-specific)

One question: Is this actually needed for parity with existing JSON artifacts? I don't think we include `vars` in those, except for `args.vars` in `run_results.json`, which _only_ includes the vars set on the CLI (`--vars)`.

I do get how this would be desirable to include in metadata, in one form or another. Even if we had just the `cli_vars`, and the version of the code in the original run (e.g. git commit), it would be possible to recalculate all values of all vars... but that sounds like a lot of work, when dbt could just make this information more accessible.

Speaking of CLI args - I'll jump over to https://github.com/dbt-labs/dbt-core/issues/5524

**Comment by jtcohen6** [comment]
Concrete ask here: Make [this code](https://github.com/brooklyn-data/dbt_artifacts/blob/4c1d79f03baa4636a42f67d7fa72608e88bcb396/macros/upload_invocations.sql#L54-L62) in the `dbt_artifacts` package less kludgey. I don't think this is strictly needed for parity with JSON artifacts, though, and it's the trickiest of the three issues.
