### ISSUE TITLE
[CT-990] [Feature] Define set of tests that are executed on models/columns that meet condition

### ISSUE THREAD

**Issue by filipjelenkovicFO** [dbt-labs/dbt-core#5612]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I would like to have an option to define set of tests that are executed on models that meet condition. This way if I would like to add another test I can do that in one place and not go over hundred of columns and add it. 
Also when you run "dbt test" those test whould be aplied to all models/columns. 

### Describe alternatives you've considered

Currently I can manually manage set of tests but it requires great effort in managing them.

### Who will this benefit?

For example apply/run all unique and not_null tests on all columns that are tagged as "primary". I might want to add test "greater then zero" test on those columns.
Also all models downstream of ModelA should have tests for recent data (my custom test).

There are certain tests that are added to models/columns of similar type/meaning/semantic. This will help in those situations

**Comment by jtcohen6** [comment]
@filipjelenkovicFO Thanks for opening the issue! I know this is one that's come up for many many folks, searching for a more ergonomic way to apply tests to many many models at once. Some recent Slack threads [here](https://getdbt.slack.com/archives/C2JRRQDTL/p1649955100718789) + [here](https://getdbt.slack.com/archives/C2JRRQDTL/p1656443943301399)

I think the use cases here are totally legitimate. The question is all around how we'd want to model this in dbt's internals, to expose and enable the right user experience.

Here are some possibilities I can imagine, starting linear and getting increasingly far out:

## Explicit configuration
At simplest, make it possible to add tests in `dbt_project.yml`, like other configuration (even though tests aren't really like other configs):
```yml
models:
  subdirectory:
    # every model in this subdirectory has a column called 'id', with unique + not_null tests
    # if any model *doesn't* have a column called 'id', the tests will still run (and fail)
    +columns:
      - name: id
        tests:
          - unique
          - not_null
```

A better approach, and heavier lift, would be to start treating all tests—or generic tests, specifically—as _actual_ properties of models, rather than separate nodes (what they are today). Then, we'd make it possible to configure/add tests from `dbt_project.yml`, or via `{{ config() }}` blocks within models, which could use macros to define "rule-sets."

## Implicit derivation

Make it possible to define rule sets: "if this {property}, then that {generic test}." Those rules would be defined  ... somewhere ... such that dbt would infer or derive the creation of tests based on another model property. Imagine: Whenever dbt finds a model with a column tagged `primary_key`, you've defined a rule such that it should create `unique` + `not_null` tests on that column. Then, you have the full power and expressibility of the `tags` config, _and_ a single place to define your "if this then that" rules.

We'd need a place to put these rules, front-and-center, so that it isn't hidden magic which just takes effect at runtime. I hesitate to say `dbt_project.yml`, because so much already goes there, but that is the front page of most dbt projects. It is sort of interesting to think about putting these within the definition / configuration of each generic test, but that also really risks hiding the magic away.

Another form of implicit derivation, which you mention: If model A has `unique` + `not_null` tests defined on column `id`, any models downstream of model A which also include a column named `id` should also include those tests. Should they actually _run_ those tests? Or just consider the column "tested"? Doing this in a smart way would, I think, require dbt to have a sense of column-level lineage between models, which it frankly doesn't have today. Lots and lots of conversation about this topic: #2995

## Other ways to define project resources

In dbt today, if you want to code up one function that produces multiple project resources, that requires code generation. Lots of folks have done this, with scripts and helpers written in Python, targeting dbt code (yaml + Jinja-SQL) as their "compilation target."

It's totally possible to do this by reading in dbt project data (yaml files) or metadata (`manifest.json`), identifying all columns tagged `primary_key`, annotating that data with `tests: [unique, not_null]`, and then writing back the yaml as project data. But it requires quite a bit of work, and it's not very fun.

What if (_huge_ what if) we could support alternative modes of defining dbt project resources? So in addition to standard `.sql` + `.yml` + `.md` (+ now `.py`) files, in the familiar structure, where dbt will parse all those file contents into a set of Python objects that make up your project's internal representation — what if it were also possible to create project resources _directly_ as those contracted Python objects? You might then be responsible for providing more properties, defining explicit DAG relationships, and all the rest that dbt usually takes care of behind-the-scenes — but, you'd also have the ability to interact programmatically with dbt's manifest (internal project representation), just like it does.

Inspired by some pseudo-code from @lostmygithubaccount, when we were talking about this issue the other day:
```python
models = dbt.Manifest.models()
for model in models:
   for column in model:
      if column(column):
          new_test = dbt.Test(
              test_name = "unique",
              model = model.name,
              column_name = column.name
          )
          dbt.Manifest.tests().add(new_test)
```
Love it? Hate it?

We're not sure if this sort of "dbt Python SDK" would be all that interesting to the average end user — but it could make a lot of sense for developers of packages and integrations, who will want to interact programmatically with dbt _project contents_. We already know many folks today who want to interact programmatically with dbt's runtime (tasks, hooks, logging, etc).

---

I don't see us making immediate progress on this one. We will continue making stepwise progress toward better defining dbt's internal constructs, so that we _could_ imagine exposing them via a Python API.

In the meantime, this need is one that should stay on our minds. I'm going to convert this into a discussion; let's keep the conversation flowing over there.
