### ISSUE TITLE
[CT-999] [Bug] In 1.2.0 implictly imported `exit` being used instead of `sys.exit`

### ISSUE THREAD

**Issue by varun-dc** [dbt-labs/dbt-core#5621]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In https://github.com/dbt-labs/dbt-core/commit/d257d0b44c8118328a98caac5cb916eed4c3506c, this new bit of code was added,
```
+        available_adapters = list(_get_adapter_plugin_names())
+        if not len(available_adapters):
+            print("No adapters available. Go to https://docs.getdbt.com/docs/available-adapters")
+            exit(1)
```
The `exit(1)` in its current form seems like the wrong thing to do, as per the Python docs,
> The [site](https://docs.python.org/2/library/site.html#module-site) module (which is imported automatically during startup, except if the [-S](https://docs.python.org/2/using/cmdline.html#id2) command-line option is given) adds several constants to the built-in namespace. They are useful for the interactive interpreter shell and should not be used in programs.

Since `exit` is provided by the implicitly imported `site`, and docs suggest,
> should not be used in programs

### Expected Behavior

The better thing to do is, `import sys` and `sys.exit(1)`

### Steps To Reproduce

The easiest way to see this fail is with `python -S` and then `>>> exit(1)`, this will fail with,
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'exit' is not defined
```

### Environment

```markdown
- OS: any
- Python: 3+
- dbt: 1.2.0
```

### Additional Context

I'm a bit unsure about how the branching and release process work for dbt-core.
The [change](https://github.com/dbt-labs/dbt-core/commit/d257d0b44c8118328a98caac5cb916eed4c3506c) is only in the `1.2.latest` branch, not in `main`.

Will this change get cherry picked onto `main`? Right now 1.2.0 suffers from this issue only

**Comment by jtcohen6** [comment]
@varun-dc Thanks for opening!

If I follow you, it sounds like we should simply be swapping out `exit(1)` for:
```python
import sys
sys.exit(1)
```
Which makes sense to me!

To be clear, this code does also live on [the `main` branch](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/task/init.py#L302-L305) of `dbt-core` as well:

https://github.com/dbt-labs/dbt-core/blob/eb72dbf32aa96394d599c28db439e0b2c6fcc135/core/dbt/task/init.py#L302-L305

We'd want to merge the fix into `main` first, and then backport it to `1.2.latest` for inclusion in a v1.2.x patch release.

Is this a change you'd be interested in contributing this week? Otherwise, someone from our side can swing around to it, to incorporate in a patch sooner rather than later.

**Comment by varun-dc** [comment]
I'll push up a PR for this
