### ISSUE TITLE
[CT-1046] [Feature] Allow Overrides on Metrics

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/dbt-core#5661]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As seen in [this documentation](https://docs.getdbt.com/reference/resource-properties/overrides), the `source` resource supports an `overrides` functionality where the definition can be overridden. This is helpful in package development as it allows customers to override sources that don't perfectly match what their reality looks like.

This functionality should also exist for metrics so that packages which have metrics defined can be overwritten if the definition that the user wants doesn't match that of the package developer.  

### Describe alternatives you've considered

- Not supporting this functionality. 
- Focusing on enabling/disabling metrics and telling users to disable metrics that don't match their definition and then create new ones.

### Who will this benefit?

Anyone using packages that contain metric definitions.

### Are you interested in contributing this feature?

Yes

### Anything else?

I believe this can be closely tied to #5422

**Comment by jtcohen6** [comment]
@callum-mcdata Thanks for opening! I'm not conceptually opposed to this. I agree that it will be valuable for packages to define metrics, and users may want to override one or few specific fields. 

I know Joe had opened #4157 a few months ago, talking about `overrides` for models, and I still think it's a reasonable idea. My answer now is the same as my answer then:

> The way we've implemented `overrides` is quite complex under the hood, especially for partial parsing.

@gshank Does this still sound right to you? My sense was that `overrides` as a pattern introduces a _lot_ of technical complexity behind the scenes.

---

In the spirit of better support for multi-project namespacing (now its own discussion: https://github.com/dbt-labs/dbt-core/discussions/5244), I've also imagined calling this `package_name` instead of `overrides`. The idea is, if you're defining properties for a metric in `my_sweet_project` like:
```yml
version: 2
metrics:
  - name: some_metric
    package_name: cool_installed_package
    description: My slightly different description, with everything else the same
```
That's equivalent to "overriding" the definition of `some_metric` from the `cool_installed_package` package. Only the root project would be able to do this sort of overriding / redefining of objects defined in other packages.

---

In the meantime, I do see https://github.com/dbt-labs/dbt-core/issues/5422 as another way to get at this same outcome, using a pattern that's both better understood and more widely used. You'd need to disable the `some_metric` definition coming from the package, and re-enable it yourself in your own project (including all its properties). Less ergonomic, but still possible.

**Comment by ataft** [comment]
Has there been any more thought around this? I'm interested in the ability to override models, metrics, columns, etc. Basically, I want to create a master project template that has general docs, models, metrics, etc., but each specific project will likely override various parts. I see that the semantic label was recently applied, and I think this concept would be very powerful for creating re-usable master projects that limit redundancy.
