### ISSUE TITLE
[CT-1052] [dbt-util] add cast_string_to_date as cross-db macro

### ISSUE THREAD

**Issue by algol68** [dbt-labs/dbt-core#5675]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

create macro for generic conversion of string-to-date objects. when trying to backport dbt-metrics macro to use w/oracle I run into quite a few cast calls that are non-workable in more conventional databases

### Describe alternatives you've considered

custom macro just for my use

### Who will this benefit?

non-base-covered db users who want to use dbt product

### Are you interested in contributing this feature?

got code ready to go ;-)

### Anything else?

see pull request in dbt-utils project. trying to follow proper process this time around ;-)
https://github.com/dbt-labs/dbt-utils/pull/640

**Comment by dbeatty10** [comment]
Thanks for making this suggestion @algol68!

That's cool that you are back-porting dbt-metrics to work with the Oracle database adapter 🤩

In an ideal future state, dbt-metrics could "just work" across adapters without any back-porting needed if we get the requisite abstractions within dbt-core (and implemented in adapters like Oracle). Although we'd be unlikely to introduce a new abstraction to accommodate just a single database, I'm guessing there will many useful abstractions that we'll want to add to unlock cross-database packages like dbt-metrics.

## `to_date` macro

For your _specific_ use-case of constructing a `date` from a `string`, I'd suggest a macro named just `to_date` instead.

Although I'm not aware of a `TO_DATE` function being in the SQL standard, it looks like many databases implement that function or something similar:
- [Oracle `TO_DATE`](https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions183.htm)
- [Snowflake `TO_DATE`](https://docs.snowflake.com/en/sql-reference/functions/to_date.html)
- [Redshift `TO_DATE`](https://docs.aws.amazon.com/redshift/latest/dg/r_TO_DATE_function.html)
- [Databricks `TO_DATE`](https://docs.databricks.com/spark/latest/spark-sql/language-manual/functions/to_date.html)
- [BigQuery `PARSE_DATE`](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#parse_date)
- etc

A naive (and untested!) implementation looks like this:
```sql
{% macro default__to_date(expression, format) %}
  {%- if format -%}
    to_date({{ expression }}, {{ format }})
  {%- else -%}
    to_date({{ expression }})
  {%- endif -%}
{% endmacro %}

{% macro bigquery__to_date(expression, format) %}
    parse_date({{ format }}, {{ expression }})
{% endmacro %}

{#-/* Won't be needed if it is the same as the default implementation */#}
{% macro oracle__to_date(expression, format) %}
    ...
{% endmacro %}
```

The big caveat for cross-database implementations is that I don't know if the databases can be expected to follow the same string format syntax or not 😅.

A small implementation idea is to consider wrapping references to the `format` parameter with the [string_literal](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros#string_literal) macro in order to add vendor-specific string literal quoting (rather than assuming that a single quote `'` is used for string literals). I left this out of the example implementation above for simplicity, but it would be nice for a real implementation.

For inclusion within dbt-core, a pull request would also require adding integration test cases here:
https://github.com/dbt-labs/dbt-core/tree/v1.2.1/tests/adapter/dbt/tests/adapter/utils

## `cast` macro
For covering the _general_ case (which is a bit tangential to this issue), we would probably want an implementations of a `cast` macro like this (which is pseudo code):
```sql
{% macro default__cast(expression, data_type) %}
    cast({{ expression }} as {{ data_type }})
{% endmacro %}

{% macro oracle__cast(expression, data_type) %}
    ...
{% endmacro %}
```

Since the valid data types vary per database, we'd probably want to hook into the type abstractions provided via the [Column class](https://docs.getdbt.com/reference/dbt-classes#column):
https://github.com/dbt-labs/dbt-bigquery/blob/defb70e5311ae79620b9caf7567e45b26ffd5f56/dbt/adapters/bigquery/column.py#L11-L19
