### ISSUE TITLE
[CT-1064] [Bug] Dbt incremental: unique_key with null values generates duplicates row

### ISSUE THREAD

**Issue by AndresSalvatierra** [dbt-labs/dbt-core#5691]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm using dbt(v1.1.2) with Redshift. This is scheduled from Airflow. I have an incremental model with two unique_key (type, name). When I run the model for day 1 it presents null values for **type** but for **name** it does not.  The generated table looks like this:

type | name | count_values
NULL onion 5
fruit apple 10

When I run the model for day 2, it presents again null values for **type** but not for **name**, this generates again another row in the final table and does not append to the existing one.

type | name | count_values
NULL onion 5
fruit apple 10
NULL onion 7

### Expected Behavior

What I expect to happen is:

type | name | count_values
NULL onion 12
fruit apple 10

### Steps To Reproduce

SQL Incremental Model:
select 
type,
name,
count(*) as count_values
from another_table
where date >= '{ds}' and
group by type, name

### Environment

```markdown
- Python:3.10
- dbt: 1.1.2
- Airflow: 2.3.2
```

### Which database adapter are you using with dbt?

redshift

**Comment by jtcohen6** [comment]
@AndresSalvatierra Thanks for opening!

In cases where multiple columns are needed to uniquely identify a record (= `unique_key` is a list), **none of those columns can be null.** The equality check for upserts / merges doesn't have handling for null values built in—nor do I think it should, since this obfuscates more logic in an already difficult-to-debug place (materialization logic, rather than transformation logic).

If there's any risk of one or more columns being null, you're better off creating a single surrogate (hash) key. The [`dbt_utils.surrogate_key`](https://github.com/dbt-labs/dbt-utils#surrogate_key-source) macro handles null values, and will return the same hashed result for the same null input(s).

It looks like we don't do a good job of documenting this today: https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#defining-a-uniqueness-constraint-optional

I'm going to close this issue as a `wontfix`, and open a new issue in https://github.com/dbt-labs/docs.getdbt.com to update that documentation.

**Comment by AndresSalvatierra** [comment]
Hi Jeremy!
Thank you for your quick response! 
I solved my problem using `dbt_utils.surrogate_key`, thank you very much!
