### ISSUE TITLE
[CT-1224] [Bug] type_string - Spark

### ISSUE THREAD

**Issue by pixie79** [dbt-labs/dbt-core#5899]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When using the dbt-glue adapter with calogica/dbt-expectations macro for testing column types it would appear that type_string is trying to CAST to TEXT instead of STRING. 
This causes the tests to fail

### Expected Behavior

type_string should return STRING for casting.

### Steps To Reproduce

11:42:15        from (
11:42:15          with relation_columns as (
11:42:15    
11:42:15            
11:42:15            select
11:42:15                cast('GL_HEADER_KEY' as TEXT) as relation_column,
11:42:15    ------------------------------------^^^
11:42:15                cast('STRING' as TEXT) as relation_column_type
11:42:15            union all

### Environment

```markdown
- OS: OSX
- Python: 3.9.13

Core:
  - installed: 1.2.1
  - latest:    1.2.1 - Up to date!

Plugins:
  - postgres: 1.2.1 - Up to date!
  - spark:    1.2.0 - Up to date!

Packages - 
packages:
  - package: dbt-labs/spark_utils
    version: [">=0.3.0"]
  - package: dbt-labs/dbt_utils
    version: [">=0.9.2"]
  - package: calogica/dbt_expectations
    version: [">=0.6.1", "<0.7.0"]
  - package: calogica/dbt_date
    version: [ ">=0.6.0", "<0.7.0" ]
  - package: dbt-labs/dbt_external_tables
    version: [">=0.8.0"]
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Issue first raised with dbt-expectations who have pointed me in your direction.
https://github.com/calogica/dbt-expectations/issues/196

The following macro has fixed the issue for now.
```
{% macro spark__type_string() -%}
    STRING
{%- endmacro %}
```

**Comment by jtcohen6** [comment]
Hey @pixie79 — thanks for opening, and glad you were able to find a functional workaround.

I'm not able to reproduce this using `dbt-core` + `dbt-spark` v1.2:

```sql
-- models/my_model.sql
select cast('a_string' as {{ type_string() }}) as my_col
```
```
$ dbt run
```
```sql
-- target/run/test/models/my_model.sql
create or replace view dbt_jcohen.my_model
  
  as
    select cast('a_string' as string) as my_col
```

Do you have other dbt packages installed (in `packages.yml`)? Or custom reimplementations of any other macros in your own project that might be relevant?

### Explanation

Here's where the `type_string()` macro is defined in `dbt-core`:

https://github.com/dbt-labs/dbt-core/blob/b089a471b7121d02105f3bbca3046be12276d92d/core/dbt/include/global_project/macros/utils/data_types.sql#L1-L13

In the general case, this does return `TEXT`, because the default `Column` class in `dbt-core` translates `STRING` &rarr; `TEXT` (`STRING` isn't supported in PostgreSQL):
https://github.com/dbt-labs/dbt-core/blob/b089a471b7121d02105f3bbca3046be12276d92d/core/dbt/adapters/base/column.py#L10-L16
https://github.com/dbt-labs/dbt-core/blob/b089a471b7121d02105f3bbca3046be12276d92d/core/dbt/adapters/base/column.py#L23-L25

**However,** in `dbt-spark` we don't do _any_ type translation — we just return the exact data type that's been passed in. The relevant code is [here](https://github.com/dbt-labs/dbt-spark/blob/f32f9fd723c3879e007c5d87df3c61fa79f2ac77/dbt/adapters/spark/column.py#L21-L23):
```python
    @classmethod
    def translate_type(cls, dtype: str) -> str:
        return 
```
So if `"string"` is what's passed in, `"string"` is also what you should be seeing on the other side — and what I see when I run this locally.
