### ISSUE TITLE
[CT-1251] [Bug] `adapter.get_columns_in_relation` (Redshift) Fails With Uppercase Schema Name

### ISSUE THREAD

**Issue by mrkaye97** [dbt-labs/dbt-core#5941]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Using `adapter.get_columns_in_relation` fails to get columns (and returns an empty list instead of an error) if the schema name has upper case characters.

### Expected Behavior

Basically the title -- it should correctly return the columns in the relation.

### Steps To Reproduce

Leaving a minimal repro below:

I've created two models: `test_src` and `test`. 

`test_src.sql`:

```sql
{{ config(materialized="view") }}

SELECT 'foo' AS x, 'bar' AS y
```

`test.sql`

```sql
{% set cols = adapter.get_columns_in_relation(ref('test_src')) %}

SELECT 
    ({% for col in cols %}
    "{{col.column}}"
        {% if not loop.last %}
        ||
        {% endif %}
    {% endfor %}) AS foobar
FROM {{ ref('test_src') }}
```

I ran `dbt build` on these two models with two schema names (ran from inside an existing `dbt` project with a `--select` flag):
1. `test_uppercase`
2. `test_Uppercase`

See log output below

### Relevant log output

```shell
(base) matt@Matt-Kayes-MBP repro % dbt build --select +test --target test
15:43:11  Running with dbt=1.1.1
15:43:11  Unable to do partial parsing because profile has changed
15:43:14  Found 57 models, 326 tests, 0 snapshots, 0 analyses, 670 macros, 0 operations, 0 seed files, 11 sources, 0 exposures, 0 metrics
15:43:14  
15:43:17  Concurrency: 8 threads (target='test')
15:43:17  
15:43:17  1 of 2 START view model test_uppercase.test_src ................................ [RUN]
15:43:19  1 of 2 OK created view model test_uppercase.test_src ........................... [CREATE VIEW in 1.60s]
15:43:19  2 of 2 START table model test_uppercase.test ................................... [RUN]
15:43:22  2 of 2 OK created table model test_uppercase.test .............................. [SELECT in 2.96s]
15:43:22  
15:43:22  Finished running 1 view model, 1 table model in 8.06s.
15:43:22  
15:43:22  Completed successfully
15:43:22  
15:43:22  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
(base) matt@Matt-Kayes-MBP repro % dbt build --select +test --target test
15:43:37  Running with dbt=1.1.1
15:43:37  Unable to do partial parsing because profile has changed
15:43:41  Found 57 models, 326 tests, 0 snapshots, 0 analyses, 670 macros, 0 operations, 0 seed files, 11 sources, 0 exposures, 0 metrics
15:43:41  
15:43:44  Concurrency: 8 threads (target='test')
15:43:44  
15:43:44  1 of 2 START view model test_Uppercase.test_src ................................ [RUN]
15:43:46  1 of 2 OK created view model test_Uppercase.test_src ........................... [CREATE VIEW in 2.05s]
15:43:46  2 of 2 START table model test_Uppercase.test ................................... [RUN]
15:43:47  2 of 2 ERROR creating table model test_Uppercase.test .......................... [ERROR in 1.48s]
15:43:48  
15:43:48  Finished running 1 view model, 1 table model in 6.82s.
15:43:48  
15:43:48  Completed with 1 error and 0 warnings:
15:43:48  
15:43:48  Database Error in model test (models/marts/test.sql)
15:43:48    syntax error at or near ")"
15:43:48    LINE 13:     () AS foobar
15:43:48                  ^
15:43:48    compiled SQL at target/run/repro/models/marts/test.sql
15:43:48  
15:43:48  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
```

### Environment

```markdown
- OS: MacOS 12.4
- Python: 3.9.5
- dbt: 1.1.1
- dbt-redshift plugin: 1.1.0
```

### Which database adapter are you using with dbt?

redshift

### Additional Context

https://getdbt.slack.com/archives/CBSQTAPLG/p1663863376695159

I think the issue is related to [enabling case sensitivity](https://docs.aws.amazon.com/redshift/latest/dg/r_enable_case_sensitive_identifier.html) in Redshift, but it seems to me that `get_columns_in_relation` should be robust to any individual Redshift cluster's settings.

**Comment by Fleid** [comment]
Hey @lowaperture, sorry for the delay.
I can reproduce the behavior.

To me this is a [collation](https://aws.amazon.com/about-aws/whats-new/2021/06/amazon-redshift-now-supports-case-insensitive-collation-with-column-level-overrides/) issue, not a identifier case sensitivity one.

Here the [macro](https://github.com/dbt-labs/dbt-redshift/blob/2c3f7829a293e1f588ace5098a00d4b80d4a342a/dbt/include/redshift/macros/adapters.sql#L102-L218) is trying to populate a column list using a compiled query that looks like:

```SQL
select
  ordinal_position,
  table_schema,
  column_name,
  data_type,
  character_maximum_length,
  numeric_precision,
  numeric_scale

from information_schema."columns"
where table_name = 'test_src' and table_schema = 'test_uppercase'
```
Whether `test_Uppercase` resolve against `test_uppercase` is a collation setting. By default Redshift is case_sensitive, meaning it won't resolve. I'd say that's an expected behavior here. So I'll retag this as enhancement.

I can hear the argument that the macro should check [enable_case_sensitive_identifier](https://docs.aws.amazon.com/redshift/latest/dg/r_enable_case_sensitive_identifier.html) and alter its behavior depending on it (compiled query):

```SQL
...
where table_name = 'test_src' 
   and 
  (
    (current_setting('enable_case_sensitive_identifier') = 'off' and lower(table_schema) = lower('test_Uppercase'))
    or
    (current_setting('enable_case_sensitive_identifier') = 'on' and table_schema = 'test_Uppercase')
  )
```

But then we need to rethink that across the board, every time we read the schema from `pg_namespace`, `pg_tables`, `information_schema`... So basically writing a macro to implement the logic above once, and wrap every invocation of the schema with it. And we may need that macro for more than schemas? What about the other object names?

This needs a bit more thinking, and I'm not sure I see an urgency for now. Happy to hear other opinions though ;)
