### ISSUE TITLE
[CT-1265] Implement 'protobuf' log_format options and create tests comparing proto and json logs

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#5955]
Using the initial code changes in #5954/#5662, create a log_format option "protobuf".  Create logs in proto format, convert to event classes, and verify that content is equal when round-tripped.

**Comment by peterallenwebb** [comment]
After reviewing the protobuf branch and doing some research, my suggestion is to use the canonical protobuf<->JSON mapping which is part of the proto3 specification. It is supported by the python implementation. 

The log output would consist of exactly one JSON object per log line, corresponding to one event fired by dbt-core.

The log consumer parse the JSON messages directly or convert back to proto objects on their side using the message definitions we maintain. Converting back to proto objects would require inspecting the JSON far enough to figure out the message type, but that seems reasonable to me. This would mean we have two JSON logging formats, but that also seems reasonable under the circumstances.

**Comment by peterallenwebb** [comment]
It would not be difficult to implement a binary log. Since there isn't much downside to supporting one, I'll prepare a changeset for that.

My first thought was to use JSON because my experience is that it is unusual to use binary logging in a cloud production environment, so I'm a bit skeptical we will use it in practice. Binary logs won't be human readable, nor machine readable without specialized code. As a result, the logs will be opaque to Datadog or other monitoring and analysis systems, which I suspect would be a dealbreaker for production operations.

The advantages would be:
1. A more compact network and storage format (uncertain overall benefit after compression)
2. Much faster for specialized log processing code to deserialize

**Comment by peterallenwebb** [comment]
Working with the rest of the team, I've completed this spike by opening a PR for a protobuf log mode prototype (https://github.com/dbt-labs/dbt-core/pull/6138). We will not merge the PR in its current state, but have identified several areas needed for further work which will be split into separate issues. I'll include a list of those below after I have opened them.
