### ISSUE TITLE
[CT-1275] [Bug] Model config var incorrectly evaluated in dbt Cloud multi-step job

### ISSUE THREAD

**Issue by jaysobel** [dbt-labs/dbt-core#5970]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Snowflake, Azure, dbt Cloud.

A large model was configured to scope a maximum set of days in a full refresh or incremental run.

```
{{
  config(
    materialized = 'incremental'
    , unique_key = 'unique_key'
    , full_refresh = true if flags.FULL_REFRESH and var('large_model_incremental_days', 999) != 999 else false
  )
}}
```

 A dbt Cloud job with two steps and the following commands was run:

`dbt build -s large_model --full-refresh --full-refresh --vars '{"large_model_incremental_days": 122}'`
`dbt build -s large_model --vars '{"large_model_incremental_days": 122}'`

### Expected Behavior

The expected behavior was a full refresh of the first 122 days in the model, followed by an incremental merge of the next 122 days. The actual behavior was two full refreshes in a row. As if the `flags.FULL_REFRESH`, or the output of the whole config logic, was not re-evaluated, with the changed flag.

Afterwards, a separate job was run with a single step exact copy of the previous commands second step, except for `build` changed to `run`.

`dbt run -s large_model --vars '{"large_model_incremental_days": 122}'`

In this separate job, the model ran incrementally, as expected.

### Steps To Reproduce

1. Create an incremental model with an incremental config similar to the one above. 
2. Run commands similar to the above ones within a single dbt Cloud job
3. After they finish, run a second job with a single command 

```my_model.sql
{{
  config(
    materialized = 'incremental'
    , unique_key = 'unique_key'
    , full_refresh = true if flags.FULL_REFRESH and var('incremental_values', 999) != 999 else false
  )
}}

with generated_series as (
  {{ dbt_utils.generate_series(upper_bound=1000) }}
)

, range as (
  select 
    {% if is_incremental() %}
        max(unique_key) as start_at
    {% else %}
        0 as start_at
    {% endif %}

    , start_at + {{ var('incremental_values', 10) }} as end_at

  {% if is_incremental() %}
    from {{ this }}
  {% endif %}
)

select generated_number::int as unique_key
from generated_series
where generated_number::int between (select r1.start_at+1 from range r1) and (select r2.end_at from range r2)
```

First dbt Cloud job, two commands
`dbt run -s my_model --full-refresh --vars '{"incremental_values": 10}'`
`dbt run -s my_model --vars '{"incremental_values": 10}'`

Observe two full refreshes in a row, leaving the table with still just 10 rows.
```
1 of 2 OK created incremental model CORE.my_model .................... [SUCCESS 1 in 1s]
2 of 2 OK created incremental model CORE.my_model .................... [SUCCESS 1 in 1s]
```

Second dbt Cloud job, one command (same as second from above)
`dbt run -s my_model --vars '{"incremental_values": 10}'`

Observe the incremental update as expected, leaving the table with 20 rows.
```
1 of 1 OK created incremental model CORE.my_model .................... [SUCCESS 10 in 1s]
```

Side note: if the `incremental_values` var was 1, how would you distinguish incremental updates from full refreshes in the logs?

### Environment

```markdown
- OS: (dbt Cloud)
- Python: 3.10.4
- dbt: 1.2.0
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

Var-involved configs are something we would like to use to do dbt runs with an _optional_ full-refresh once per week. We use the config below. It's important for us to understand if there are ways in which dbt Cloud can mishandle vars in configs.

```
 {{
  config(
    materialized = 'incremental'
    , unique_key = 'unique_key'
    , full_refresh = true if var('weekly_full_refresh_job', false) == true else none
  )
}}
```

https://getdbt.slack.com/archives/C2JRRQDTL/p1662663354438099
+ comment in discourse
https://discourse.getdbt.com/t/how-to-prevent-accidental-full-refreshes-for-a-model/1008

**Comment by jtcohen6** [comment]
Thanks @jaysobel!

Configs are resolved at **parse time**, and partial parsing is enabled by default. Meaning, subsequent steps reuse the parsed representation of the project from the first step, even if the `flags` change between them.

This is called out as a caveat in the docs on `flags` (https://docs.getdbt.com/reference/dbt-jinja-functions/flags):

> **Note:** It is not recommended to use flags as an input to parse-time **configurations**, properties, or dependencies (ref + source). Flags are likely to change in every invocation of dbt, and their parsed values will become stale (and yield incorrect results) in subsequent invocations that have partial parsing enabled. For more details, see [the docs on parsing](https://docs.getdbt.com/reference/parsing).

Other approaches that should achieve the desired result:
- Set different values of `--vars` between the first and step job steps. This will trigger dbt to do a full re-parse.
- Rather than adding this conditional behavior within the `full_refresh` config, define a custom version of the `should_full_refresh` macro, so that it checks the additional variables of interest. This macro is resolved at **runtime** ([within the materialization](https://github.com/dbt-labs/dbt-core/blob/0e60fc1078cd337859ac78ce74a06e5b8bc2e431/core/dbt/include/global_project/macros/materializations/models/incremental/incremental.sql#L14)) instead of **parse time,** so its logic will be recalculated in each job step.
https://github.com/dbt-labs/dbt-core/blob/8442fb66a591c4f5353f8baaaaf62f846c5f5171/core/dbt/include/global_project/macros/materializations/configs.sql#L6-L12

```sql
{% macro should_full_refresh() %}
  {% set config_full_refresh = config.get('full_refresh') %}
  {% if config_full_refresh is none %}
    {% set config_full_refresh = flags.FULL_REFRESH %}
  {% endif %}
  {% if var('some_other_condition') != expected_value %}
    {{ return(False) }}
  {% endif %}
  {% do return(config_full_refresh) %}
{% endmacro %}
```

I'm going to close this for now, as a documented limitation, but I'm happy to continue the conversation about potential workarounds

**Comment by jaysobel** [comment]
Thanks for the instantaneous and thorough answer. Joel also advised me to override the core macro. 

I'll read up on parse-time vs run-time.
