### ISSUE TITLE
[CT-1359] [Feature] Create option to raise severity of unused configuration path warning

### ISSUE THREAD

**Issue by katieclaiborne** [dbt-labs/dbt-core#6080]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I would like to be able to configure this warning as an error, so that we catch misspellings before they're merged.

### Are you interested in contributing this feature?

Yes!

**Comment by jtcohen6** [comment]
Thanks for opening the issue @katieclaiborne, and for the awesome work in the hackathon!

We had a good conversation about this as a team earlier today. We'd like to solve this with something more general-purpose, whereby we provide users with more granular control over the `--warn-error` configuration. Today, it's a simple boolean ("all or nothing") switch to flip. We should also support users passing in the specific warning/exception classes that they want to treat as exceptions, rather than warnings. That way, we don't need a standalone config for every single warning/exception class.

I'll open a new issue to reflect that work.

**Comment by katieclaiborne** [comment]
Thanks, Jeremy!
