### ISSUE TITLE
[CT-1377] [Feature] Add functionality to use separate files for project variables

### ISSUE THREAD

**Issue by nolan-jardine** [dbt-labs/dbt-core#6110]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The `dbt_project.yml` file gets very long and tough to maintain when there are a lot of different variables declared for different purposes. On top of that, it's tough to look through the history of `dbt_project.yml` when it has so many changes for many different cases. It would be nice to be able to have separate variable files that can be split out for certain use cases and maintained separately.

### Describe alternatives you've considered

Adding everything into `dbt_project.yml`.

### Who will this benefit?

Anybody that uses variables extensively, or would like more organization to `dbt_project.yml`.

My use case that prompted this was that I want to set up a mapping to maintain BigQuery policy tags all in one place/variable to make it more maintainable and readable when the policy tags are referenced. It would be a fairly large mapping and `dbt_project.yml` is already getting quite large for our team.

**Comment by nolan-jardine** [comment]
Closing because I found this issue after opening, and I think it covers what I was suggesting:
https://github.com/dbt-labs/dbt-core/issues/4938

**Comment by jtcohen6** [comment]
@nolan-jardine I really agree with the thrust of your issue! We should have a separate place to define variables for use in dbt projects. The question is whether those variables should:
- support any kind of env-based Jinja compilation
- be consolidated with "global" variables (env vars / CLI flags / "user config" in `profiles.yml`)

Glad you found #4938, I agree that's the right place to keep the ideas centralized. I just converted it to a discussion (#6170) so that it's easier to find, share, and weigh in on.
