### ISSUE TITLE
[CT-1409] [Bug] when there's a variable being called in a jinja block that is not defined in dbt_project.yml, there's an compile error

### ISSUE THREAD

**Issue by bossnunta** [dbt-labs/dbt-core#6145]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Not 100% sure what about this code block causes the error. Possible there's a variable being called inside a jinja block
https://www.loom.com/share/eb8a9d3b57e24e588c5fa8b96e9d13cf

### Expected Behavior

We shouldn't show any error here (?) -- see Loom for more info

### Steps To Reproduce

1. Start with an existing project in the Cloud IDE
2. Choose any existing sql data model
3. add this block of code
```
{% if var('random_var_name') != [] %}
,
{{ var('random_var_name') | join (", ")}}

{% endif %}
```
4. Save file
5. Notice the error state from RPC
6. If you go into dbt_project.yml and define random_var_name, then the error goes away

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by jtcohen6** [comment]
After a little digging, there's more history here:
- https://github.com/dbt-labs/dbt-core/issues/3320
- https://github.com/dbt-labs/dbt-core/pull/1429
- https://github.com/dbt-labs/dbt-core/issues/434

Big idea: At parse time, a missing var actually returns `None` (to avoid raising errors due to missing vars in disabled models). That works fine sometimes, but not if the variable is expected to support `__iter__` type operations. Hence, `'NoneType' object is not iterable`.

Going to re-label this one as a spike, to understand what's possible here as far as better UX.

**Comment by jatkins23** [comment]
Wanted to follow up that this is still not resolved if its possible to reopen
