### ISSUE TITLE
[CT-1434] [Feature] Skip applying grants based on target

### ISSUE THREAD

**Issue by davcamer** [dbt-labs/dbt-core#6164]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When using different targets during development, there might not be the same need or ability to alter permissions on the produced models. For example, the first 'dev' target might only be accessible to me, as I am working out the model structure. And I might not be able to change permissions, in order to enforce that it stays only accessible to me.

This was also recently discussed in this Discourse thread, although I could not find a resulting issue or discussion: https://discourse.getdbt.com/t/using-grants-in-a-target-specific-way/4981/9

Other relevant discussions might include the usage grant issue:
https://github.com/dbt-labs/dbt-core/issues/6063

And the schema definition discussion:
https://github.com/dbt-labs/dbt-core/discussions/5781

I think this is a narrower piece of functionality, which would still be useful on its own. Grants are a layer orthogonal to the models that have different requirements for different targets, even when the models themselves will graduate from target to target untouched.

### Describe alternatives you've considered

[minhajpasha](https://discourse.getdbt.com/u/minhajpasha) in the discourse thread worked out an approach to do this within model .sql files:
```
{% if target.name == 'dev' %}
    {{ config(grants = {'roles/bigquery.dataViewer': ['user:someone@yourcompany.com']}) }}

{% elif target.name == 'uat' %}
    {{ config(grants = {'roles/bigquery.dataViewer': ['user:sometwo@yourcompany.com']}) }}

{% elif target.name == 'prod' %}
    {{ config(grants = {'roles/bigquery.dataViewer': ['user:somethree@yourcompany.com']}) }}
{% endif %}
```

[joellabes](https://discourse.getdbt.com/u/joellabes) suggested overriding the global project's macros. I've tried this locally, and the simplest pinch point I found was this:
```
{% macro apply_grants(relation, grant_config, should_revoke) %}
    {% if target.name == 'dev' %}
        {#-- Ignoring grant application --#}
    {% else %}
        {#-- Standard implementation from dbt core --#}
        {{ return(adapter.dispatch("apply_grants", "dbt")(relation, grant_config, should_revoke)) }}
    {% endif %}
{% endmacro %}
```

I think the best place to specify this, would be in the target definitions in the profile files:
```
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      ...
      apply_grants: no
```

Default to yes to retain the existing behavior.

### Who will this benefit?

This benefits teams taking advantage of declarative grants, who are also stepping through multiple targets, and the targets have different permissions imposed by the environment. 

### Are you interested in contributing this feature?

I'm not sure. A pointer to which part of the code handles it would help.

**Comment by jtcohen6** [comment]
@davcamer Thanks for opening, and providing the thoughtful write-up!

The closest recent issue (and the one that came out of the linked discourse post) was https://github.com/dbt-labs/dbt-core/issues/6017. In that issue, I showed how you could write per-`target` logic into the `grants` config. That makes sense when you need actually different grant recipients in different runtime environments, and want to write conditional logic that inspects `target` / `env_var` / etc.

While I understand that this is env-specific behavior, and connection profiles are one place to put env-specific logic, I'm skeptical about adding `apply_grants` as an evergreen config within every `profiles.yml` entry.

So that leaves us with a few potential patterns:
1. Use conditional Jinja expressions when defining `grants` as a config, as in #6017. This lets you enable/disable `grants` at a per-model level. This will actually change the value of the configuration stored on the model.
2. Override the `apply_grants` macro (in exactly the way you show). This gives you the most control: a project-wide on/off switch, but also the ability for custom conditional logic that, e.g., applies grants for model relations landing in some schemas and not others. This doesn't change the value of the configuration stored on the model, it just optionally ignores that configuration at runtime.
- We have a notion of ["global" configs](https://docs.getdbt.com/reference/global-configs), which may change based on the env/runtime/command and are independent of actual project code. The upside (and downside) of this approach is that the config lives outside of version control — it's a CLI flag, env var, or "user config" setting in `profiles.yml`.

I lean toward options 1 + 2 (especially 2)! The macro override feels pretty ergonomic to me.

If we hear many more folks asking for this capability — a universal on/off switch — we might pursue option 3, and add a global `APPLY_GRANTS` config (`--apply-grants`, `--no-apply-grants`, `DBT_APPLY_GRANTS=1|0`).

I'm going to close the issue for now, but happy to hear from more folks who'd want this capability built-in.
