### ISSUE TITLE
[CT-1445] "Encountered an error: expected dict, got "

### ISSUE THREAD

**Issue by kostasgaridis** [dbt-labs/dbt-core#6176]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Hi all! Upgraded to 1.3.0, using Homebrew. When running dbt compile to test if all is ok, I get the following - really weird - error:
```
Encountered an error:
expected dict, got
```
<img width="239" alt="Screenshot 2022-10-28 at 19 27 31" src="https://user-images.githubusercontent.com/94909994/198687979-d3a7e2c3-5b80-4113-888e-6ecdec081748.png">

Yes, with the last sentence unfinished. Check the screenshot in this message as well. 

Relevant brew commands:
```
brew update
brew upgrade dbt-bigquery
```

Output from `dbt debug` (sans possibly sensitive information denoted by XXX):

```
16:23:37  Running with dbt=1.3.0
dbt version: 1.3.0
python version: 3.9.15
python path: /usr/local/Cellar/dbt-bigquery/1.3.0/libexec/bin/python
os info: macOS-12.6-x86_64-i386-64bit
Using profiles.yml file at /Users/kostas/.dbt/profiles.yml
Using dbt_project.yml file at /Users/kostas/repos/bi-roi-dbt/dbt_project.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]

Required dependencies:
 - git [OK found]

Connection:
  method: oauth
  database: XXX-bi-dm-dev
  schema: roi
  location: US
  priority: interactive
  timeout_seconds: 300
  maximum_bytes_billed: None
  execution_project: XXX-bi-dm-dev
  job_retry_deadline_seconds: None
  job_retries: 1
  job_creation_timeout_seconds: None
  job_execution_timeout_seconds: 300
  gcs_bucket: None
  Connection test: [OK connection ok]
```

### Expected Behavior

I was expecting `dbt compile` in 1.3.0 (dbt-bigquery) to compile a model, as was the case with 1.2.0 I tried just before upgrading. 

### Steps To Reproduce

- Upgrade to 1.3.0 using brew
- Run `dbt compile`

### Environment

```markdown
- OS: MacOsX
- Python: >3.9
- dbt: 1.3.0
```

### Which database adapter are you using with dbt?

bigquery

**Comment by lostmygithubaccount** [comment]
community slack thread: https://getdbt.slack.com/archives/CBSQTAPLG/p1666974608072329

**Comment by jtcohen6** [comment]
@kostasgaridis Could you include the contents of the debug-level logs (either from `logs/dbt.log`, or by rerunning `dbt --debug compile`)? That _might_ give us a hint into which file dbt is trying to read when it encounters this error.

**Comment by kostasgaridis** [comment]
> @kostasgaridis Could you include the contents of the debug-level logs (either from `logs/dbt.log`, or by rerunning `dbt --debug compile`)? That _might_ give us a hint into which file dbt is trying to read when it encounters this error.

Here's the log output. It's rather long and it seems that the whole query I have shows up in there for some reason as unformatted text. This is not the case when I run the same model with dbt core 1.2.2.

[dbt-log.txt](https://github.com/dbt-labs/dbt-core/files/9918027/dbt-log.txt)

**Comment by jtcohen6** [comment]
Ok! Based on the logs you sent over, it seems like dbt encounters this error while:
- parsing through models
- _without_ first logging that `static parser failed`

```
[0m15:58:22.251155 [debug] [MainThread]: 1699: static parser successfully parsed roi_extra/p0_v3_backup.sql
[0m15:58:22.253442 [debug] [MainThread]: 1603: static parser failed on roi_extra/curve_data_1.sql
[0m15:58:22.260794 [debug] [MainThread]: 1602: parser fallback to jinja rendering on roi_extra/curve_data_1.sql
[0m15:58:22.261860 [debug] [MainThread]: 1699: static parser successfully parsed roi_extra/p1_v3_backup.sql
[0m15:58:22.263946 [debug] [MainThread]: 1699: static parser successfully parsed roi_extra/p2_v3_backup.sql
[0m15:58:22.266120 [debug] [MainThread]: 1699: static parser successfully parsed roi_extra/p0_v2_backup.sql
[0m15:58:22.268366 [debug] [MainThread]: 1699: static parser successfully parsed roi_extra/p2_v4_backup.sql
[0m15:58:22.270811 [debug] [MainThread]: 1699: static parser successfully parsed roi_extra/p3_v2_backup.sql
[0m15:58:22.272938 [debug] [MainThread]: 1699: static parser successfully parsed roi_extra/p1_v4_backup.sql
[0m15:58:22.274529 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10fe200d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1100ec580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1100ec550>]}
[0m15:58:22.274747 [debug] [MainThread]: Flushing usage events
[0m15:58:22.854055 [error] [MainThread]: Encountered an error:
expected dict, got 

```
I'm guessing here, but I think it might mean that `py_extract_from_source` is failing to return a dictionary here. (That method comes from [`dbt-extractor`](https://github.com/dbt-labs/dbt-extractor), a.k.a. our static parser/analyzer for dbt-Jinja written in Rust.)
https://github.com/dbt-labs/dbt-core/blob/39c5c42215b4d6751e9644324040a1c716742224/core/dbt/parser/models.py#L379-L383
Specifically, that `_shift_sources` method expects to receive a dictionary, rather than... `None`?
https://github.com/dbt-labs/dbt-core/blob/39c5c42215b4d6751e9644324040a1c716742224/core/dbt/parser/models.py#L475

Again, I'm guessing here, not totally positive. You might be able to confirm that the static parser is the culprit by disabling it ([docs](https://docs.getdbt.com/reference/global-configs#static-parser)), e.g.
```
dbt --no-static-parser parse
```
That would still leave us to figure out exactly which file is tripping up the static parser, and then fixing the logic within `dbt-extractor`. To do that, we might need you to run an interactive debugger (or access to your project files, so one of us can try).
