### ISSUE TITLE
[CT-1487] [Feature] Allow DBT Models to Reference Created Temporary Tables prior to final result set & materialization.

### ISSUE THREAD

**Issue by KeeonTabrizi** [dbt-labs/dbt-core#6234]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

This feature request is to support using temporary tables (within a single session) instead of CTE references in the execution of a single DBT model. 

**To be clear as I've seen this confusion, this is not a request to materialize a temporary object - rather utilize a temporary object in the materialization itself**.

I believe it would require a model specific over-ride to limit execution to within 1 thread / session (vs. the global thread default in `dbt_project.yml`. Additionally, the compilation / execution order would first require the execution of the temporary objects followed by the remaining query (which could actually include a CTE). For the examples below I will assume a Snowflake DB.

Currently, DBT can compile a model below:

`dbt_model.sql`
```sql
{{ config(
    alias="your_table",
    materialized="table"
) }}

WITH my_data AS (
      SELECT ...
      FROM {{ ref('my_other_dbt_model') }}
)

SELECT ...
FROM my_data
````

The `run` target may look something like

```sql
CREATE OR REPLACE db.schema.your_table AS (
WITH my_data AS (
      SELECT ...
      FROM db.schema.my_other_dbt_model'
)

SELECT ...
FROM my_data

);
```

A simple version of this query that would utilize a tempory table could look as follows:

`dbt_model_temp_table.sql`
```sql
{{ config(
    alias="your_table",
    materialized="table"
) }}

CREATE TEMPORARY TABLE my_data AS
      SELECT ...
      FROM {{ ref('my_other_dbt_model') }}
;

SELECT ...
FROM my_data
````

The `run` target will currently generate **invalid** SQL as follows:

```sql
CREATE OR REPLACE db.schema.your_table AS (
CREATE OR REPLACE my_data
      SELECT ...
      FROM db.schema.my_other_dbt_model'
;

SELECT ...
FROM my_data

);
```

The compiled version should first execute any create statements and then wrap the final query which generates the result set to materialize:

```sql
CREATE TEMPORARY TABLE my_data as
      SELECT ...
      FROM db.schema.my_other_dbt_model'
;

CREATE OR REPLACE db.schema.your_table AS ( --what DBT would materialize
  SELECT ...
  FROM my_data
);
```

What I believe is needed is an additional config argument into the model to indicate temporary tables are used which would force a single session/thread for the model execution as well as re-order the execution of the model (first executing the temporary objects in the session, and finally generating the results for DBT to materialize).

### Describe alternatives you've considered

Converting everything to CTEs or creating individual upstream models is the only option. However, I feel strongly enough in the development / iteration cycles around complex queries/transformation where temporary tables are used that having the option to directly materialize those queries through DBT models will be a win for developers.

### Who will this benefit?

This will benefit anyone developing complex queries as well as those already using temporary tables which can improve debugging / speed of query development as results can remain available to an open session.

It allows a developer to move a query > model > production quicker and provides that option versus being forced to convert a query into CTEs and/or break up a query into component models with dependencies. 

While, this may be theoretically better data engineering practice it shouldn't be forced by the lack of support for temporary tables.

See this comment which also describes some of the benefit: https://github.com/dbt-labs/dbt-core/issues/2725#issuecomment-1161001928

### Are you interested in contributing this feature?

Happy to ideate

### Anything else?

Tangential but not directly related issues & PRS:

- https://github.com/dbt-labs/dbt-core/issues/2725
- https://github.com/dbt-labs/dbt-core/pull/1409
- https://github.com/dbt-labs/dbt-core/issues/946

**Comment by dbeatty10** [comment]
@KeeonTabrizi thanks for a thorough write-up and links to tangential issues and PRs!

We are always interested to discuss opportunities to improve debugging / speed of query development.

Question:
- is this feature request primarily intended for use during iterative development? Or is it intended for deployment to production as well?

**Comment by dbeatty10** [comment]
Gotcha @KeeonTabrizi

What are you trying to optimize for in the iterative development cycle?
1. Having all the logic you are currently working on within the same file
1. Re-use within multiple downstream models
1. Persisting a large data set to save time of re-materializing it during each dev re-build/re-run cycle
1. Not persisting certain data sets beyond the end of a build (presumably to save storage costs)
1. Something else?

## Options
As you're probably well-versed, there's a variety of options for developing dbt models including:
- table materialization (permanent or transient)
- ephemeral materialization
- view materialization
- explicit CTE within one of the above

Let's explore what each of those are optimized for:

|    |                                                                                                                             | **table** | **ephemeral** | **view** | **explicit CTE** |
|----|-----------------------------------------------------------------------------------------------------------------------------|-----------|---------------|----------|------------------|
| A) | Having all the logic you are currently working on within the same file                                                      | ❌         | ❌             | ❌        | ✅                |
| B) | Re-use within multiple downstream models                                                                                      | ✅         | ✅             | ✅        | ❌                |
| C) | Persisting a large data set to save time of re-materializing it during each dev re-build/re-run cycle | ✅         | ❌             | ❌        | 💡                |
| D) | Not persisting certain data sets beyond the end of a build (presumably to save storage costs)                    | 💡         | ✅             | ✅        | ✅                |

We can see in the chart above that A) and B) are _generally_ opposites, as are C) and D). 'Tis the nature of trade-offs!

### Table materialization
Optimized for B) and C)

💡 But we can unlock D) by mimicking the way [Snowflake temporary tables](https://docs.snowflake.com/en/user-guide/tables-temp-transient.html#temporary-tables) behave in practice!

You'd just add `drop table if exists` statements as [`on-run-end`](https://docs.getdbt.com/reference/project-configs/on-run-start-on-run-end) hooks if you don't want the table to stick around beyond a full `dbt run/build`.

The lifespan of these "temp" tables would limited to a dbt "session" (spanning Snowflake connections) rather than just a single Snowflake connection session.

### Ephemeral and view materializations
Optimized for B) and D)

### Explicit CTE
Optimized for A) and D).

💡 Although they are not optimized for C), adding a `limit X` during development can reduce the size of the data set and speed up cycle times.

## Example

### "Temp" tables within a dbt "session"

`my_data.sql`

```sql
{{ config(
    materialized="table"
) }}

select ...
from {{ ref('my_other_dbt_model') }}
```

`your_table.sql`

```sql
{{ config(
    materialized="table"
) }}

select ...
from {{ ref('my_data') }}
```

`dbt_project.yml`
```
...
# on-run-end:
#   - "drop table if exists {{ ref('my_data') }};"
```

☝️ Uncomment above once you want it to act like a "temp" table in production. Leaving it commented will allow it to persist across sessions during development.

### Usage

Rebuilding just the downstream table (leaving the "temp" table as-is):
```shell
dbt build -s your_table
```

Rebuilding both the "temp" table and its downstream consumer:
```shell
dbt build -s my_data your_table
```

**Comment by dbeatty10** [comment]
Although _not at all_ what we would recommend, the thing you described is actually possible via [pre-hooks](https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook).

In your original description, you already explained how this doesn't work as-is:
`your_table.sql`
```sql
{{ config(
    materialized="table"
) }}

CREATE TEMPORARY TABLE my_data AS
      SELECT ...
      FROM {{ ref('my_other_dbt_model') }}
;

SELECT ...
FROM my_data
```

But if you just add a `pre_hook` configuration and shuffle the order of content slightly as seen below, it will work.

> ⚠️ Note: We'd consider using pre-hooks in this way an anti-pattern and **not** what we'd recommend!⚠️
> 
> Instead, we'd recommend putting that `select`ion logic in a CTE, `view`, `ephemeral`, or `table` materialization instead. If you need to drop tables to save storage costs, then we'd recommend using an `on-run-hook` as described in the [example above](https://github.com/dbt-labs/dbt-core/issues/6234#issuecomment-1320766483).

`your_table.sql`
```sql
-- ⚠️ Using pre-hooks in this way is an anti-pattern! ⚠️
{{ config(
    materialized="table",
    pre_hook="

CREATE TEMPORARY TABLE my_data AS
      SELECT ...
      FROM {{ ref('my_other_dbt_model') }}"
) }}

SELECT ...
-- depends_on: {{ ref('my_other_dbt_model') }}
FROM my_data
```

See [here](https://docs.getdbt.com/reference/dbt-jinja-functions/ref#forcing-dependencies) for an explanation why the dependency might need to be forced via `-- depends_on: {{ ref('my_other_dbt_model') }}`

### Smaller data sets
For scenarios with a lot of trial & error iteration on a large data set, we’d recommend limiting the data like [this](https://docs.getdbt.com/guides/legacy/best-practices#limit-the-data-processed-when-in-development) or with a `limit` clause or using Snowflake’s [tablesample](https://docs.snowflake.com/en/sql-reference/constructs/sample.html) functionality. Then you can rip it out once you're done iterating (or leave it in for future developers within a `target.name == '...'` filter).

### Hot data sets
But what about the goal of keeping a data set hot/available so you can iterate on a transformation query quickly?

A regular `table` materialization is the exemplary way to persist the result of a transformation within a dbt session or across dbt sessions.

But let's consider using a `pre_hook` to define a temp table instead. In this case, the data will disappear in between iterations and it will be re-built every time you run dbt. If the temp table takes a non-trivial amount of time to build, then the time losses will add up over many iterations. With the `table` materialization however, it would only incur a one-time cost until you re-run that particular upstream node. So using inline temp tables in a dbt model for the purpose of rapid development really has me scratching my head. 🤔

The only explanation I can think of:
- Maybe you are doing all your development cycles using temp tables _outside_ of dbt and then copy-pasting it into a dbt project once you are done? And then you're trying to make the minimum number of changes to the SQL after pasting?

**Comment by dongchris** [comment]
Would love this feature as well! :)

**Comment by jtcohen6** [comment]
@dongchris @KeeonTabrizi I think @dbeatty10 did a nice job above laying out the rationale for why dbt both _cannot_ and _does not_ support this, for reasons of technical limitation (how dbt manages database connections) and best practice (code & workflow in dev should closely mirror the code that will be actually be running in prod).

In the meantime, if you really want this support, I'd recommend you try out Doug's suggestion above, where you pass your "CTE" into a `pre-hook` that creates it as a temp table. You could even macro-tize this logic, with `create if not exists`, so as to reuse it across your models, and avoid rebuilding if it already exists in your current session. Again, we won't be adding this into `dbt-core` natively, for all the reasons Doug articulated in his comments above.

**Comment by dongchris** [comment]
Thanks @jtcohen6 for the explanation. If we use the pre hook way, what if there are actual prehooks running, would having it in the config this way override existing ones?
