### ISSUE TITLE
[CT-1510] Decouple `Target` from `Project`

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#6257]
In order to work with `Project`s we require a `Target`.  Currently `Target`s only exist in the `Profile`.  This coupling makes it difficult to do useful things with just `Project`s so this ticket encompasses the work to de-couple the two.

**Comment by jtcohen6** [comment]
Should we retitle this issue, **"Decouple `Target` from `Project`"**? That feels more tractable, and would resolve the confusion in my comment above.

`{{ target }}` is only supported in a subset of `Project` configuration — namely, the project-level configuration of `models`, `seeds`, `snapshots`, ...

It's _not_ supported in the rendering context for `packages-install-path` or `clean-paths`. So we **should** be able to support `deps` and `clean` without a `Profile`, and thereby remove the need for the dummy `UnsetProfile` that we're using currently.

The way we do this conditional rendering is pretty funky today: use the `TargetContext` if we have a profile, otherwise `BaseContext` if we don't.
https://github.com/dbt-labs/dbt-core/blob/ccb4fa26cd682812f15d2fd50b37a8c422e092f8/core/dbt/config/renderer.py#L97-L114

**Comment by iknox-fa** [comment]
Closing due to a lack of concrete value in completing the work.
