### ISSUE TITLE
[CT-1536] [Bug] Upstream Table level tests trigger downstream relationship tests

### ISSUE THREAD

**Issue by FridayPush** [dbt-labs/dbt-core#6290]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Given a model dependency: A-> B-> C
Where C has a relationship test back to A on a column.

Running `dbt test --select A`

Triggers not only tests on A, but also the Relationship test on C. I primarily hit this in development environments when working in a schema that hasn't had a full run done previously. Where a source test of `dbt test --select source*` pulls in and fails for models that do not exist downstream. 

Other users have commented about this recently in slack: https://getdbt.slack.com/archives/C01UM2N7814/p1668777441491409

> Hi people, I have a quick question regarding tests. I have a dimension table and a fact table, the fact table schema has a relationship test referencing the pk on the dimension table. The problem comes when I run the dimension table tests, the actual relationship is tested on the fact table though the relationship test is defined under the fact table. Has anyone come across this? Am I missing something? (edited) 

Also consider the behavior from models that have sources which perform hard deletes where a downstream model no longer has referential integrity until it's rerun. Running a source test before all models have been rerun fails as the relationships are also brought in.

### Expected Behavior

Selecting a model for tests should not trigger tests that the model is used in, unless the "owning" model is also selected by the criteria. 
eg `dbt test --select A+` vs `--select A` where the latter should not run downstream tests.

### Steps To Reproduce

1. Create two models where the second depends on the first
2. Add a relationship test from the second model to the first on a column
3. Run tests on the first model, observe the relationship test is triggered. 

### Environment

```markdown
- OS: MacOS
- Python: 3.8
- dbt: Both latest, and 1.2.1
```

### Which database adapter are you using with dbt?

redshift

**Comment by jtcohen6** [comment]
@clausherther said it well - thank you!

We've considered changing this behavior in the past — actually, we did, and then we changed it back, because using "cautious" selection as the default was more confusing to folks. We've settled on making the behavior configurable, and (hopefully) well documented! Now, it's almost a rite of passage :)

Definitely open to thoughts on how we could make this clearer within the product itself. Should we include log messages whenever a multi-parent test has been selected, on the basis of only one parent? Provide a fuller description (or link to docs) in `dbt test --help`?

Going to close this issue in the meantime, but very happy to keep ^that discussion going
