### ISSUE TITLE
[CT-1559] [Feature] Include all refs and sources in compiled Python model code

### ISSUE THREAD

**Issue by chamini2** [dbt-labs/dbt-core#6328]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

dbt Python models parse the Python model file and include in the compiled code only the **found** `ref` and `source` calls.

For example, the model

```py
def model(dbt, fal):
    from utils.get_bool import get_some

    dbt.config(materialized="table")

    bike_data = dbt.source("bike", "bike_duration")
    print(bike_data)

    df = get_some(dbt)

    df["my_bool"] = True
    return df
```

Will be compiled to

```py
def model(dbt, fal):
    from utils.get_bool import get_some

    dbt.config(materialized="table")

    bike_data = dbt.source("bike", "bike_duration")
    print(bike_data)

    df = get_some(dbt)

    df["my_bool"] = True
    return df


# This part is user provided model code
# you will need to copy the next section to run the code
# COMMAND ----------
# this part is dbt logic for get ref work, do not modify

def ref(*args,dbt_load_df_function):
    refs = {}
    key = ".".join(args)
    return dbt_load_df_function(refs[key])


def source(*args, dbt_load_df_function):
    sources = {"bike.bike_duration": "xxx.yyy.bike_duration"}
    key = ".".join(args)
    return dbt_load_df_function(sources[key])


config_dict = {}


class config:
    def __init__(self, *args, **kwargs):
        pass

    @staticmethod
    def get(key, default=None):
        return config_dict.get(key, default)

class this:
    """dbt.this() or dbt.this.identifier"""
    database = 'xxx'
    schema = 'yyy'
    identifier = 'ns____ns__simple_test_model_c'
    def __repr__(self):
        return 'xxx.yyy.ns____ns__simple_test_model_c'


class dbtObj:
    def __init__(self, load_df_function) -> None:
        self.source = lambda *args: source(*args, dbt_load_df_function=load_df_function)
        self.ref = lambda *args: ref(*args, dbt_load_df_function=load_df_function)
        self.config = config
        self.this = this()
        self.is_incremental = False

# COMMAND ----------
```

Specifically, 

```py
def ref(*args,dbt_load_df_function):
    refs = {}
    key = ".".join(args)
    return dbt_load_df_function(refs[key])


def source(*args, dbt_load_df_function):
    sources = {"bike.bike_duration": "xxx.yyy.bike_duration"}
    key = ".".join(args)
    return dbt_load_df_function(sources[key])
```

But as we passed `dbt` into the `get_some`, the idea could be to do

```
def get_some(dbt):
  df = dbt.ref('other_bike')
  return df.describe()
```

And it would fail with a `KeyError`.

```
...
    return dbt.ref('other_bike')
  File "<string>", line 55, in <lambda>
  File "<string>", line 23, in ref
KeyError: 'other_bike'
```

### Describe alternatives you've considered

Doing all `dbt.*` operations in the main python model file and not passing the `dbt` object to any imported function.

### Who will this benefit?

Users expecting Python objects to work independent of context: it is weird to different behavior just for passing the variable down.

### Are you interested in contributing this feature?

Yes!

### Anything else?

My idea would be to include in the `refs` object in the compiled code ALL of the models and the same for `sources`. Still parsing to make sure you have referenced valid refs and sources.

**Comment by chamini2** [comment]
> If that get_some is defined in another file, I feel like maybe we need to think of something similar to ephemeral model for code reuse.

It is in another file, yes.

> My main concern with including All of the models and sources is that for a big project it would be a giant dictionary.

I am wondering if this concern is that the compiling process will take long for dbt or if it's about running the Python code taking too long to read the whole dictionary?

**Comment by jtcohen6** [comment]
@chamini2 Thanks for opening, and sorry that it's taken me forever to get back to you!

I share @ChenyuLInx's hesitation about including the full set of resolved `refs` and `sources` in the every compiled Python model. Even / especially if the goal is to enable some shenanigans akin to [`{{ graph }}`](https://docs.getdbt.com/reference/dbt-jinja-functions/graph) in the dbt-Jinja context. That's a one-way door that we've intentionally chosen not to walk through (yet). Someday, we may decide that the benefits (use cases) outweigh the costs in complexity.

Before we even get there, though, I think there's another problem: dbt needs to be able to know the upstream references of a model, at parse time, in order to properly infer dependencies and construct the DAG. At present, the way we parse Python models is using static analysis (Python `ast`); we can reasonable capture all instances of `dbt.ref()` in that model's file, then resolve the reference and add the DAG edge accordingly. I don't think we'd be able to do this for functions defined in _different_ files, without either:
- Actually executing the Python code — an anti-pattern, both for security reasons, and because we want a very clear separation of "control plane" versus "data plane" code. (We can capture `ref` calls embedded in Jinja macros because we actually execute that Jinja code "locally," within the `dbt-core` application.)
- Statically analyzing every `.py` file, extracting all calls to all functions (including `dbt.ref`), and assembling a tree of which models depend on which `refs` (directly or indirectly). This feels _possible_, though also much trickier to implement, and liable to lots of little edge cases.

Would we need to do something like this anyway, to unlock a future where dbt natively supports UDFs? (https://github.com/dbt-labs/dbt-core/discussions/5741) I don't think so; at least, it wouldn't be strictly necessary. If `udf` were a first-class node type, we could track the `ref` on the UDF node, which could then "carry" that upstream edge to any downstream models calling it. No need for additional passthrough logic powered by trickier AST acrobatics.

**Comment by chamini2** [comment]
> At present, the way we parse Python models is using static analysis (Python ast); we can reasonable capture all instances of dbt.ref() in that model's file, then resolve the reference and add the DAG edge accordingly. I don't think we'd be able to do this for functions defined in different files

You are completely right, I forgot about the DAG building for a second there. I understand that it is not really viable to analyze any file where the `dbt` object is being passed to. Maybe if we use something like `dill` which does this sort of analysis and brings the whole context with it (when `dill.settings["recurse"] = True`), maybe that makes AST analysis easier?

**Comment by daveworth** [comment]
Is there some alternative solution where we could decorate our python models with the `ref`s/`source`s we expect and dbt will respect those in addition to any explicit references done by the static analysis?

I ask because the `_ = dbt.ref("some_model")` is causing some significant memory issues in our production pipelines as it loads all of that underlying data into memory in the dataframe before proceeding.
