### ISSUE TITLE
[CT-1560] 070_incremental_schema_tests

### ISSUE THREAD

**Issue by VersusFacit** [dbt-labs/dbt-core#6331]

**Comment by colin-rogers-dbt** [comment]
Looks like we didn't include porting the adapter implementations of the integration tests as part of the above PR. See [BQ test](https://github.com/dbt-labs/dbt-bigquery/tree/main/tests/integration/incremental_schema_tests) 

This would have made it easier to catch/debug https://github.com/dbt-labs/dbt-core/issues/6485

**Comment by VersusFacit** [comment]
How do we determine when one needs to be ported? At the time, I believe I actually did check on this one with some team members and was found not to need a port--although memory may serve me wrong.

Let's certainly avoid that in future conversions.

**Comment by colin-rogers-dbt** [comment]
So taking a look at this again it's pretty understandable to not see this since it didn't directly inherit from these and we have so many tests.  Arguably it's a separate test conversion see: https://github.com/dbt-labs/dbt-bigquery/blob/52de0f0b5350b755303968bf5abc577df8847962/tests/integration/incremental_schema_tests/test_incremental_schema.py#L4-L5
