### ISSUE TITLE
[CT-1565] [Feature] Add dbt benchmark command

### ISSUE THREAD

**Issue by WillAyd** [dbt-labs/dbt-core#6337]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I propose adding a `dbt benchmark` command that accepts two revision arguments. Assuming your dbt is version controlled within git, the benchmark tool should be able to compile the models as shown within each revision, run an EXPLAIN command on each of those models and then compare the results across revisions. If there is a performance change that exceeds a particular thresshold, the user should be notified

### Describe alternatives you've considered

I looked at dbt parse but I think that is more about the performance of dbt itself, not necessarily a tool for the end user to validate their model performance

### Who will this benefit?

Any user interested in optimizing analytics performance

### Are you interested in contributing this feature?

Possibly

### Anything else?

My inspiration for this comes from tools in the Python space like asv:

https://asv.readthedocs.io/en/stable/index.html

Pandas uses this to physically run benchmarks at every revision so we can detect unforeseen regressions automatically:

https://asv-runner.github.io/asv-collection/pandas/

**Comment by dbeatty10** [comment]
Thanks for submitting this compelling feature idea @WillAyd -- love the idea of improving the "airspeed velocity of an unladen dbt model" similar to `asv` !

I didn't know about `asv` before, and enjoyed getting to read about it. During my research, even ran into [this](https://github.com/pandas-dev/pandas/issues/29165) -- "Hey, I know @WillAyd !" 😎 

### Probably best outside of dbt-core
Similar to how `asv` is external to scipy, pandas, etc, I'm guessing we'd want some tool external to dbt rather than within dbt-core itself.

Some reasons it would be better outside of the dbt-core:
- dbt-core is git-agnostic when it comes to the projects it runs -- it just cares about a bunch of files (however they got there!)
- an external tool can take advantage of pre-existing dbt packages that measure actual execution times (like [`dbt_artifacts`](https://hub.getdbt.com/brooklyn-data/dbt_artifacts/latest/), more info [here](https://discourse.getdbt.com/t/analyzing-fishtowns-dbt-project-performance-with-artifacts/2214))
- more innovation could be possible outside core, including different tools attempting benchmarking in different ways or being optimized for a particular data platform
- we want dbt-core itself to be as unladen as possible to maximize _its_ airspeed :)

Am I overlooking some key reasons why it should be within dbt-core rather than an external tool?

### How might it work?

Let's start by assuming that installing and configuring the [`dbt_artifacts`](https://hub.getdbt.com/brooklyn-data/dbt_artifacts/latest/) package is required for each dbt project to profile.

Then any time that dbt executes, the `dbt_artifacts` package will add the execution timing to the database -- I think that would handle what `asv quickstart` and `asv run` do.

Then you'd just need something to mimic what `asv publish` and `asv preview` do -- namely using that timing data from the database and producing a static website out of it. I didn't dig into the `asv` code, but you might be able to re-use portions of their code.

Or since it's already in your database... just use your BI tool of choice!

An example chart from [here](https://discourse.getdbt.com/t/analyzing-fishtowns-dbt-project-performance-with-artifacts/2214#h-1-monitoring-project-run-time-over-time-12) of overall project build times:

![image](https://user-images.githubusercontent.com/44704949/208554587-39f2ae0c-a937-428d-a282-31ea74cea508.png)

An example chart from [here](https://discourse.getdbt.com/t/analyzing-fishtowns-dbt-project-performance-with-artifacts/2214#h-2-identifying-bottlenecks-13) of all the models in a single run:

![image](https://user-images.githubusercontent.com/44704949/208553779-18a78227-f761-4e2f-b5e4-6d283d702f67.png)

([Sounds like these vizes](https://discourse.getdbt.com/t/analyzing-fishtowns-dbt-project-performance-with-artifacts/2214/8) were built using Looker.)

How does the above align overall with the spirit of your proposal?

**Comment by dbeatty10** [comment]
Sounds good @WillAyd 👍 Will close to signal our intent.

I'm glad you proposed this, and hopefully our discussion is useful to others searching for something similar.
