### ISSUE TITLE
[CT-1733] [Bug] Macro lookup between packages

### ISSUE THREAD

**Issue by elongl** [dbt-labs/dbt-core#6491]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Specifying `my_macro()` without package scoping (`my_package.my_macro()`) can result in calling an external package even though `my_macro()` is defined in my own package (project).

As far as I can tell, this seems to only happen in the compilation step rather than in runtime, though not sure.
Here's [what I think happens in more details and context](https://github.com/calogica/dbt-expectations/issues/230#issuecomment-1366518509) to the actual problem that occurred.

### Expected Behavior

I'd expect doing `my_macro()` to first look up in my own project, then dbt, and only then (if at all), at 3rd party packages.

### Steps To Reproduce

Install two non-dependent packages with the same macro name.

**Comment by jtcohen6** [comment]
@elongl Which version of dbt were you using when you saw the unexpected resolution order, as described in https://github.com/calogica/dbt-expectations/issues/230#issuecomment-1366518509?

It looks like the macros were being called within custom generic tests, which do use a slightly different macro rendering context at parse time. I'm asking about the version because, we included a change in v1.3 (https://github.com/dbt-labs/dbt-core/pull/5907) that fixed an issue when a macro in a generic test was being called as `{{ dbt.type_timestamp() }}` instead of just `{{ type_timestamp() }}` (https://github.com/dbt-labs/dbt-core/issues/5720).

In any event, I would expect calling `{{ my_macro() }}` to prefer your own package version, wherever it's being called, rather than the version defined in a package. If you can provide a simplified reproduction case, that would be much appreciated!
