### ISSUE TITLE
[CT-1735] [Bug] generate_schema_name macro not applied if in a package.

### ISSUE THREAD

**Issue by akerone** [dbt-labs/dbt-core#6492]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Created a `generate_schema_name` macro in a project that is then imported into the main one as a package using `dbt deps`. The default naming behavior still applies when running the project.

### Expected Behavior

The overriden schema naming behavior should be applied when running the project.

The alternative, which is writing the same macro in each and every dbt project, is against the DRY principle.

### Steps To Reproduce

1. Create a new dbt project `project_a`
2. Under `macros/`, create a new file named `get_custom_schema.sql` with the following content:
```
{% macro generate_schema_name(custom_schema_name, node) -%}
    {%- if custom_schema_name is not none -%}

        {{ custom_schema_name | trim }}

    {%- else -%}

        {{ default_schema | trim }}

    {%- endif -%}
{%- endmacro %}
```
3. Create a new dbt project `project_b`
4. Add a `packages.yml` file to `project_b`, importing `project_a`
5. Configure any of the example models in `project_b` to have a custom schema.
6. Run `dbt deps` followed by `dbt build` on `project_b`

The modified model will be created in a schema following the  <target_schema>_<custom_schema> nomenclature.

### Environment

```markdown
ghcr.io/dbt-labs/dbt-bigquery:1.3.0
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thanks for opening this issue @akerone !

### Zooming in
In the situation you described, each dbt project that imports `project_a` would need to add a custom macro like the following in order to use its custom definition of [`generate_schema_name`](https://docs.getdbt.com/docs/build/custom-schemas#how-does-dbt-generate-a-models-schema-name):

```sql
{% macro generate_schema_name(custom_schema_name, node) -%}
    {{ project_a.generate_schema_name(custom_schema_name, node) }}
{%- endmacro %}
```
Could you give that a shot and see if it works for you?

### Zooming out

The same instructions apply for packages that re-define [`generate_database_name`](https://docs.getdbt.com/docs/build/custom-databases#generate_database_name) or [built-in macros](https://docs.getdbt.com/reference/dbt-jinja-functions/builtins) like [`ref`](https://docs.getdbt.com/reference/dbt-jinja-functions/ref) or [`source`](https://docs.getdbt.com/reference/dbt-jinja-functions/source).

This isn't quite as DRY as merely installing the desired package, but it does safeguard from the ambiguous case if two different installed packages each provide a definition of `generate_schema_name`.

If you are creating new dbt projects on a frequent basis that should install and use `generate_schema_name` from `project_a`, then creating and using your own custom [Copier](https://copier.readthedocs.io/en/stable/) or [cookiecutter](https://cookiecutter.readthedocs.io/en/stable/) template is one option to consider.

**Comment by akerone** [comment]
So, if I understood correctly, built-in macros need to be overwritten within the project itself and there's no other option. Is that right?

I understand the dangers of 2 packages overwriting the same macro, but that can happen anyway with non-built-in macros. How is the issue addressed in that case?

P.S.: We already have a template project with the package.yml and a basic directory structure for our projects, but for some reason this makes me feel that tingle in the back of the neck when something is not quite DRY enough 😅

**Comment by jtcohen6** [comment]
This is also a place where `dispatch` can help, because all "global project" macros (including `generate_schema_name`) are dispatched into the `"dbt"` namespace.

Check out the docs here: https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch#overriding-global-macros

**Comment by akerone** [comment]
@jtcohen6 Thanks a lot, that was truly insightful. We'll still have to add some code, but the dispatch route sits way better with me than the copy-pasted macro.

We'll give it a try, thanks!

**Comment by jtcohen6** [comment]
Sounds good! Going to close this one out
