### ISSUE TITLE
[CT-1738] [Bug] dbt snapshot does not drop __dbt_tmp table if post-hook fails

### ISSUE THREAD

**Issue by RobbertDM** [dbt-labs/dbt-core#6498]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If you make a valid snapshot with an invalid posthook, the snapshot's `__dbt_tmp` table will still exist.
Correcting the invalid posthook to a valid one will still result in failure, since dbt will try to create that `__dbt_tmp` table again, which already exists.

### Expected Behavior

A correct snapshot configuration with a correct post-hook should always be able to run.

### Steps To Reproduce

1) Make a valid snapshot with a valid post-hook
2) Make any syntax error in the `post_hook`
3) Run `dbt snapshot`
4) Correct the syntax error from step 2
5) Run `dbt snapshot` and see it fail

Here's my snapshot code:
```
{% snapshot my_snapshot %} 


{{
    config(
      target_database='iceberg',
      target_schema='dbt_robbert_snapshots',
      unique_key='id',

      strategy='check',
      check_cols='all',
      invalidate_hard_deletes=True,

      post_hook="alter table {{this}} execute optimize"
    )
}}

select * from {{ ref('table_to_be_snapshotted') }}

{% endsnapshot %}
```

### Relevant log output

```shell
14:47:15  Running with dbt=1.3.1
14:47:15  Found 15 models, 25 tests, 1 snapshot, 0 analyses, 528 macros, 0 operations, 4 seed files, 7 sources, 0 exposures, 0 metrics
14:47:15  
14:47:16  Concurrency: 2 threads (target='dev')
14:47:16  
14:47:17  1 of 1 START snapshot dbt_robbert_snapshots.my_snapshot ........................ [RUN]
14:47:18  1 of 1 ERROR snapshotting dbt_robbert_snapshots.my_snapshot ......... [ERROR in 1.49s]
14:47:18  
14:47:18  Finished running 1 snapshot in 0 hours 0 minutes and 3.22 seconds (3.22s).
14:47:18  
14:47:18  Completed with 1 error and 0 warnings:
14:47:18  
14:47:18  Database Error in snapshot my_snapshot (snapshots/my_snapshot.sql)
14:47:18    TrinoUserError(type=USER_ERROR, name=TABLE_ALREADY_EXISTS, message="line 1:1: Destination table 'iceberg.dbt_robbert_snapshots.my_snapshot__dbt_tmp' already exists", query_id=20230102_144718_01344_szyby)
14:47:18  
14:47:18  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Environment

```markdown
- OS: Ubuntu 22.04
- Python: 3.10.6
- dbt: 1.3.1
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

db adapter = trino

**Comment by RobbertDM** [comment]
This might be a minimum viable snapshot (you still need to fill in a target db and schema:

```
{% snapshot testing_dbt_snapshot_bug %}

{{
    config(
      target_database='iceberg',
      target_schema='dbt_robbert_snapshots',
      unique_key='id',
      strategy='check',
      check_cols='all',
      post_hook=""
    )
}}

select 0 as id 

{% endsnapshot %}
```

**Comment by RobbertDM** [comment]
I also checked the `post_hook` config with normal models and with incremental loading, and those both work. They execute the `drop table blabla__dbt_tmp` before executing the post_hook.

**Comment by dbeatty10** [comment]
Thanks for reporting this @RobbertDM !

It looks to me like [dbt-trino](https://github.com/starburstdata/dbt-trino) is using the underlying default logic below which runs the "inside_transaction" post hooks before dropping that `__dbt_tmp ` temporary object via [`post_snapshot`](https://github.com/starburstdata/dbt-trino/blob/c3c43dc37c842f079a674361d3c5e18a8f6e6d15/dbt/include/trino/macros/materializations/snapshot.sql#L8-L11):
https://github.com/dbt-labs/dbt-core/blob/9ecb6e50e4b1c7f1ac99143a5a2cce4e545a9ac3/core/dbt/include/global_project/macros/materializations/snapshots/snapshot.sql#L87-L95

@jtcohen6 do you know if it is an option to move the call to `post_snapshot` to be before the first call to `run_hooks`? (I'm guessing not, but do not know precisely why -- see below for a guess.)

The ordering of the commit prior to `post_snapshot` looks like it was originally set [here](https://github.com/dbt-labs/dbt-core/blob/7d490d4886daab2c16c2a1d517f86a27a8f5dac9/core/dbt/include/global_project/macros/materializations/archive/archive.sql#L250-L254) (within [#1478](https://github.com/dbt-labs/dbt-core/pull/1478/files#diff-7eb6fc83ea4a71746d2786197db598cd2d30b95b147bb3ec53d65640c70d71a1R250-R254)) which pre-dates post hooks.

Maybe the commit is prior to `post_snapshot` because DDL (like a DROP TABLE statement) often causes an implicit commit? And we want the `inside_transaction` post hooks to be within the same transaction as the bulk of the snapshot logic?

**Comment by RobbertDM** [comment]
Not sure what's so different (why incremental does not have this problem but snapshots do)
Compare with incremental: 
https://github.com/dbt-labs/dbt-core/blob/9ecb6e50e4b1c7f1ac99143a5a2cce4e545a9ac3/core/dbt/include/global_project/macros/materializations/models/incremental/incremental.sql#L79-L88

**Comment by dbeatty10** [comment]
@RobbertDM dbt-trino has its own definition of the `incremental` materialization that overrides the default one, so it will use the following instead of the code you linked:

[starburstdata/dbt-trino/dbt/include/trino/macros/materializations/incremental.sql#L98-L100](https://github.com/starburstdata/dbt-trino/blob/c3c43dc37c842f079a674361d3c5e18a8f6e6d15/dbt/include/trino/macros/materializations/incremental.sql#L98-L100)
```sql
  {% do drop_relation_if_exists(tmp_relation) %}

  {{ run_hooks(post_hooks) }}
```

Is the tmp relation truly dropped when you have a bad post-hook with an incremental materialization? Or is preserved in between executions until a good post-hook clears it out?

It does appear to drop the tmp relation also at the beginning of the incremental materialization, which might enable re-runs  whereas snapshots were not able:

[starburstdata/dbt-trino/dbt/include/trino/macros/materializations/incremental.sql#L43-L46](https://github.com/starburstdata/dbt-trino/blob/c3c43dc37c842f079a674361d3c5e18a8f6e6d15/dbt/include/trino/macros/materializations/incremental.sql#L43-L46)
```sql
  -- drop the temp relation if it exists already in the database
  {{ drop_relation_if_exists(preexisting_tmp_relation) }}

  {{ run_hooks(pre_hooks) }}
```

**Comment by RobbertDM** [comment]
For incremental, the `_tmp` one really gets deleted before the post-hook executes (at least that's what the query history of our database shows):

Query_id | Query text | user | create date | CPU time | elapsed time
--- | --- | --- | --- |--- |--- 
20230106_104719_00707_3kc63 | select fail | robbert | 1/6/2023, 11:47:19 AM | 0.00s | 0.00s
20230106_104719_00706_3kc63 | drop view if exists iceberg.dbt_robbert.incremental_model__dbt_tmp | robbert | 1/6/2023, 11:47:19 AM | 0.00s | 0.08s
```

**Comment by dbeatty10** [comment]
This bug can be reproduced with dbt-bigquery snapshots as well (and I'm guessing dbt-spark although I didn't actually test it). It might also affect some incremental strategies for some adapters, but I didn't find a reproduction case for it.

### Potential solution
I suspect the solution for this may be as simple as doing this:

```sql
  {% if staging_table is defined %}
      {% do post_snapshot(staging_table) %}
  {% endif %}

  {{ adapter.commit() }}
```

instead of this:

```sql
  {{ adapter.commit() }}

  {% if staging_table is defined %}
      {% do post_snapshot(staging_table) %}
  {% endif %}
```

If that is the case, then the same solution should be applied to dbt-spark [here](https://github.com/dbt-labs/dbt-spark/blob/8c84b80d60754155f9252baed92c99038bd4e9f4/dbt/include/spark/macros/materializations/snapshot.sql#L174-L178).

It should also be applied to the incremental materialization in core [here](https://github.com/dbt-labs/dbt-core/blob/9ecb6e50e4b1c7f1ac99143a5a2cce4e545a9ac3/core/dbt/include/global_project/macros/materializations/models/incremental/incremental.sql#L79-L88).

### Acceptance criteria
1. a functional test is added to dbt-core and inherited by all adapters, including dbt-bigquery (and fails initially)
    - the test could check that the relevant `__dbt_tmp` relation doesn't exist
2. the fix is added to dbt-core
3. repeat 1) and 2) for incremental materializations also
