### ISSUE TITLE
[CT-1784] [Feature] dbt build command should also install dependencies

### ISSUE THREAD

**Issue by mickaelandrieu** [dbt-labs/dbt-core#6570]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I'm a happy user of dbt and Airbyte.
As I used dbt through Airbyte to trigger dbt transformations, I have 2 commands to execute:

- dbt deps
- dbt build

I think this should be dbt build __only__ as a "build" is intended to manage all operations in order to execute ... a build.

What I suggest:

- (subject to discussion, risky ?) Add ``dbt deps`` as a first step of the ``dbt build`` command
- or add an optional argument to trigger the installation of the dependencies i.e `dbt build --with-deps`

### Describe alternatives you've considered

As for now, the alternative is to chain `dbt deps` and `dbt build` operations.

When these tasks are in isolation  (i.e dockerized), you **must** configure a folder to keep the dependencies installed outside of the containers.

Painful, ugly, but it works:

```
packages-install-path: "../dbt_packages"
```

![Airbyte](https://user-images.githubusercontent.com/1247388/211765819-cf186cc9-b5e4-478f-b381-a8bc9c1affdd.JPG)

### Who will this benefit?

Everyone that needs dependencies and eager to automatize the execution of its dbt operations

### Are you interested in contributing this feature?

Yes

**Comment by dbeatty10** [comment]
Glad to hear from you @mickaelandrieu !

It sounds like you are experiencing two separate problems that have `dbt deps` in common:
1. you'd like to run just a single command instead of two
1. getting `dbt deps` + `dbt_packages` to work in Docker was arduous

Searching past reported issues, we have two relevant tickets that are still open:
1. https://github.com/dbt-labs/dbt-core/issues/4557
1. https://github.com/dbt-labs/dbt-core/issues/4784

### Run just a single command instead of two
Your feature request plus in addition to that first pre-existing issue inspired us to open a new feature request yesterday:
- https://github.com/dbt-labs/dbt-core/issues/6643

The thing you are asking for wouldn't be fully unlocked until "phase 3" described there, but the first two phases would enable it. The work described in #6643 isn't something our team has capacity to pick up right now, but we'd be very open to supporting a motivated community contributor who would want to start by tackling phase 1.

### Easing `dbt deps` in Docker
It seems like you have a unique solution to the Docker problem. Would you mind sharing your solution over in https://github.com/dbt-labs/dbt-core/issues/4784?

### Next steps
I'm going to close your issue in deference to https://github.com/dbt-labs/dbt-core/issues/6643 and https://github.com/dbt-labs/dbt-core/issues/4784. We would welcome continued discussion with you within each of those. Please know that you instigated the creation of that first ticket -- thank you for sharing your experience and proposal!
