### ISSUE TITLE
[CT-1801] [Feature] Allow for multiple schemas to be configured in model configurations

### ISSUE THREAD

**Issue by duncan771** [dbt-labs/dbt-core#6582]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

It would be great to have the option to identify multiple schemas you would like a model to go to. For example, you can use `{{ config( schema='schema_name') }}` in any model to dictate where it will be built. 

The issue I've ran into is when trying to think through permissions for multiple schemas/datasets. It's not uncommon to have multiple datasets that need access to the same reporting models. However, it may not always be the best option to hand out permissions to both datasets to the other teams, and creating a third dataset for both makes things more complicated since you may not have a ton of overlap outside of a few models.

Take financial reports for instance. We may not want a sales team to have access to all of the finance reports, but they would need to have access to their compensation reports - which would also be useful for the finance team.

I'm suggesting adding the ability for the input to the config "macro" above to be an array of strings instead of a single string. This would then create the materialization in both datasets: `{{ config( schema=['schema1', 'schema2']) }}`

### Describe alternatives you've considered

I'm not sure if there would be a simpler way of implementing this, but maybe there another config option called "other schema(s)" we could create that allows the code base to not change for the initial `schema` field but also enables this new feature. 

I'm not sure of the difficulty of adding a new schema, or adding in a set of schemas as a list. The above option could be a solution if making it a list is more difficult and it could limit the amount of schemas to just two. I don't think this is the ideal solution, but it could allow for more functionality without what could be a much more difficult ask.

### Who will this benefit?

I think any team could benefit from this. Big and small companies alike have data that overlaps between multiple teams and handling permissions on a model-by-model basis via your warehouse is just unrealistic. This would allow you to have granularity at the model level, but you could still keep your permissions set by business domain, data domain, or whatever other structure you've decided on.

I think the use case mentioned above with finance reporting and where that overlaps with various teams (sales, customer support, marketing, etc.) is very common. I think generally there are models that can and do fit into multiple datasets no matter how you slice them. This will allow for the decision of how to handle those cases much easier by allowing you to have those models in both datasets.

### Are you interested in contributing this feature?

Potentially. I spent some time trying to dig into how the model config code works but have ran into some trouble trying to track down the specific files and code blocks.

### Anything else?

I don't think this is an uncommon thing to want. Just doing a quick search in the Slack channel had a couple of people who've asked for something similar.

**Comment by dbeatty10** [comment]
Thanks for opening @duncan771 !

If I'm understanding correctly, the aim of your feature proposal is related to precision access to shared data sets. Your particular data access is granted at the schema level and schemas are created based on domains like finance, sales, customer support, marketing, etc. The goal is to provide shared access to certain models within a domain-specific schema. Does that sound right?

Up to this point, dbt has held the philosophy of "one model one data set" rather than allowing a single model to create multiple data sets, and we see no change to that philosophy in the near term. So we're not keen to configure multiple target schemas within a single dbt model as you proposed.

However, this sounds like a job for the [grants](https://docs.getdbt.com/reference/resource-configs/grants) configuration. The grants config is the canonical dbt feature to configure precision access like this. Have you looked at it at all?

The principal/user/group details will vary depending on your data platform, but here's an example configuration:

```yaml
models:
  - name: example_shared_model
    config:
      grants:
        select: ['finance', 'sales', 'customer_support', 'marketing']
```

or within the `example_shared_model` model itself:
```sql
{{ config(grants={'select': ['finance', 'sales', 'customer_support', 'marketing']}) }}
```

An alternative is to manage data set permissions outside of dbt, but it sounds like your intent is to try that permission management inside dbt.
