### ISSUE TITLE
[CT-1846] Refactor `dbt init` to use click more directly.

### ISSUE THREAD

**Issue by iknox-fa** [dbt-labs/dbt-core#6646]
### Describe the feature

During BLG for #5548, it was noted that because `dbt init` is an interactive command line process and because it already uses some of the internals of Click such as `click.prompt` and `click.confirm`, it might make sense to refactor the entire thing into a single `click.command` which could be imported and attached directly to the cli.

This ticket encompasses the work to do just that.

**Comment by jtcohen6** [comment]
Agree 100% with the thrust of this proposal. Main audience for `dbt init` are users just getting started on the CLI.

Let's also preserve a programmatic entry point into `dbt init` that _just_ returns the starter project files, in case we (eventually) want to start using it in the dbt Cloud IDE, instead of the legacy/current behavior (cloning from the [`dbt-starter-project`](https://github.com/dbt-labs/dbt-starter-project) repo). That's sorta possible today via `dbt init <projectname> --skip-profile-setup`.

**Comment by iknox-fa** [comment]
Per BLG 1/23/23 -- We're estimating this today, however we'd like to have some further conversations around what should be in a task vs in a click command vs possibly not even a direct part of dbt.
