### ISSUE TITLE
[CT-1899] [Bug] `exceptions.warn` does not actually give model WARN status

### ISSUE THREAD

**Issue by rlh1994** [dbt-labs/dbt-core#6721]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When using `exceptions.warn` in either a model, or a macro called by a model, in both cases the warning message is written to the log but the model itself runs as a SUCCESS (counts as a PASS in the summary). 

### Expected Behavior

When a model, or a macro called within a model, raises a warning via `exceptions.warn` this should log the message as it currently does, but also complete the model with a WARN status.

### Steps To Reproduce

1. Create a new project with a valid profile
2. Create a macro called `raise_a_warning.sql`
    ```jinja2
      {% macro raise_a_warning() %}
      {% if execute %}
          {% do exceptions.warn("Alert, alert, warning warning!") %}
      {% endif %}
      {% endmacro %}
    ```
3. Create a model called `warn_test.sql` (adjust the dummy table query as needed for your warehouse)
    ```jinja2
      {{ raise_a_warning() }}
      {% if execute %}
          {% do exceptions.warn("Warning, warning, alert, alert!") %}
      {% endif %}
      
      select 1 as x
    ```
4. Call `dbt run` - observe warning messages but model registers as SUCCESS/PASS
5. Call `dbt --warn-error run` - model now errors as expected

### Relevant log output

```shell
09:18:01  Running with dbt=1.3.2
09:18:01  Found 1 model, 0 tests, 0 snapshots, 0 analyses, 304 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
09:18:01  
09:18:03  Concurrency: 1 threads (target='dev')
09:18:03  
09:18:03  1 of 1 START sql view model dbt_ryan.warn_test ................................. [RUN]
09:18:03  Alert, alert, warning warning!
09:18:03  Warning, warning, alert, alert!
09:18:03  1 of 1 OK created sql view model dbt_ryan.warn_test ............................ [SUCCESS 1 in 0.79s]
09:18:03  
09:18:03  Finished running 1 view model in 0 hours 0 minutes and 2.28 seconds (2.28s).
09:18:03  
09:18:03  Completed successfully
09:18:03  
09:18:03  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

### Environment

```markdown
- OS: Mac OS
- Python: 3.9.13
- dbt: 1.32
```

### Additional Context

Exceptions docs: https://docs.getdbt.com/reference/dbt-jinja-functions/exceptions

**Comment by jtcohen6** [comment]
Thanks for opening @rlh1994! I'm not convinced that this is the expected behavior, since the warning message raised does not actually stop the model from proceeding to build (either successfully or unsuccessfully).

I do see it as expected behavior that `{{ exceptions.warn() }}` yields a `WARN`-level event, which appears in logs and can be observed/parsed/reacted to accordingly, including by means of `--warn-error`.

Currently, model result statuses can be only `Success`, `Error`, or `Skipped`:
https://github.com/dbt-labs/dbt-core/blob/cbb9117ab997289062cd5bacaf4cfd4466ab9b1e/core/dbt/contracts/results.py#L91-L94

Whereas [tests and source freshness checks can indeed return `Warn` as a result status](https://github.com/dbt-labs/dbt-core/blob/cbb9117ab997289062cd5bacaf4cfd4466ab9b1e/core/dbt/contracts/results.py#L97-L110).

There's an issue from last year proposing a more thorough review of result statuses: https://github.com/dbt-labs/dbt-core/issues/5276. If we're going to change this, I would want it to be part of a more-holistic review, rather than adding `Warn` to the set of possible model result statuses in a vacuum.
