### ISSUE TITLE
[CT-1924] Support 'contract' config outside model yaml file

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#6756]
In the [first cut of dbt constraints](https://github.com/dbt-labs/dbt-core/pull/6271), `constraints_enabled` (= “this model is contracted and should be treated as such”, to be renamed to `contract`) can only be set in model yaml files, alongside the columns attribute to enable parse-time validation. 

We should either: 
1. Resolve some tech debt around parsing (#6511) to enable setting this config elsewhere ((dbt_project.yml, yaml file, within .sql file) or,
2. Remove the at parse-time validation, failure will happen at runtime

Relevant discussions: 
* https://github.com/dbt-labs/dbt-core/pull/6271#discussion_r1069354422
* https://github.com/dbt-labs/dbt-core/issues/6511#issuecomment-1404853662

**Comment by jtcohen6** [comment]
Let's take https://github.com/dbt-labs/dbt-core/issues/6511 off the critical path, and take the "lazy" approach for now, by raising the error at runtime instead of parse time.

https://github.com/dbt-labs/dbt-core/pull/6986 is going to give us a neat place to raise this error at runtime:

https://github.com/dbt-labs/dbt-core/blob/5858095535985a48f208303064a9456727a59914/core/dbt/include/global_project/macros/adapters/columns.sql#L41-L47

If `col['data_type'] == ""`, let's raise a clear exception — rather than having it crop up as a harder-to-debug syntax error when we submit this query to the data platform:

```sql
cast(col_name as ),
```

Then, we should remove these validation checks:
https://github.com/dbt-labs/dbt-core/blob/5858095535985a48f208303064a9456727a59914/core/dbt/parser/base.py#L313-L324

https://github.com/dbt-labs/dbt-core/blob/5858095535985a48f208303064a9456727a59914/core/dbt/parser/schemas.py#L1015-L1025
