### ISSUE TITLE
[CT-2019] [Bug] Enabling tests after being disabled via a config block within the test file

### ISSUE THREAD

**Issue by gunthermeert** [dbt-labs/dbt-core#6843]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Enabling a test after it was disabled using a config block within the test file does not enable the test.

### Expected Behavior

Run the test after being enabled.

### Steps To Reproduce

1. Create a generic test file with a config block under tests/generic.

`{{ config(
  enabled=true
) }}`

![image](https://user-images.githubusercontent.com/89607565/216362897-e0049899-e7e3-4c8f-9c2a-cce5fb79e112.png)

2. Configure this generic test for a model in the models.yml

![image](https://user-images.githubusercontent.com/89607565/216363216-d65df593-0b7e-4d36-a6b1-d9673af21272.png)

3. Trigger the tests for the specific model
`dbt test --select models/staging/dh_shop/stg_dh_shop__customers.sql`

4. Verify that the test as run.
![image](https://user-images.githubusercontent.com/89607565/216363497-c6ba0fa7-6fe9-433e-94b8-6b8f978c98eb.png)

5. Disable the generic test by adjusting the config block within the test file.
`{{ config(
  enabled=false
) }}`

6. Rerun the test.
`dbt test --select models/staging/dh_shop/stg_dh_shop__customers.sql`

7. Verify that the test doesn't run.

8. Enable the generic test again by adjusting the config block within the test file.
`{{ config(
  enabled=true
) }}`

9. Rerun the test.

10. The test does not run.

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.10.6
- dbt: 1.3.0
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Hey @gunthermeert 👋 thanks for opening this!

I was able to reproduce this bug; see below for a quick workaround you can use in the meantime.

### Workaround
[Disable partial parsing](https://docs.getdbt.com/reference/global-configs#partial-parsing) (just one time!) whenever you re-enable your test:
```shell
dbt --no-partial-parse test --select models/staging/dh_shop/stg_dh_shop__customers.sql
```

### Reproduction of the bug

See below for the most simple example I could think of.

`dbt_project.yml`
```yaml
name: "my_dbt_project"
version: "1.0.0"
config-version: 2
profile: "my_profile"
```

`models/simple_model.sql`
```sql
select 1 as id
```

`models/schema.yml`
```yaml
version: 2

models:
  - name: simple_model
    tests:
      - simple_test
```

`tests/generic/simple_test.sql`
```sql
{% test simple_test(model) %}

    {{ config(enabled=true) }}

    select 1 as id
    where 1=0

{% endtest %}
```

Commands to reproduce the error and demonstrate the work-around:
```shell
dbt test --select simple_model
# disable the generic test within its macro config
dbt test --select simple_model
# re-enable the test
dbt test --select simple_model
# disable partial parsing (for just this test invocation)
dbt --no-partial-parse test --select simple_model
# subsequent runs can use partial parsing again
dbt test --select simple_model
```

### What's going on
Quoting from [these](https://docs.getdbt.com/reference/parsing#partial-parsing) docs:
> After parsing your project, dbt stores an internal project manifest in a file called `partial_parse.msgpack`. When partial parsing is enabled, dbt will use that internal manifest to determine which files have been changed (if any) since it last parsed the project. Then, it will _only_ parse the changed files, or files related to those changes.

Partial parsing will avoid re-parsing unchanged files between invocations.

In your case, when switching from `enabled=false` to `enabled=true`, it looks like dbt is not detecting the macro as having changed, and it is not re-parsing it. Instead, it is re-using a cached version within `partial_parse.msgpack` wherein `enabled=false`.

Solving this bug will involve detecting that the macro has changed and re-parsing this file upon the next invocation.

### How to selectively disable partial parsing in the meantime

You won't need to disable partial parsing for every invocation (and you probably don't want to). You _only_ need to disable partial parsing a single time whenever you re-enable that test macro.

There are several methods to [disable partial parsing](https://docs.getdbt.com/reference/global-configs#partial-parsing):

#### Environment variable
```shell
export DBT_PARTIAL_PARSE=false
```

#### Profile config
`profiles.yml`
```yaml
config:
  partial_parse: false
```

#### CLI flag
```shell
dbt --no-partial-parse run
```

To be clear, I view disabling partial parsing as just the short-term work-around until the bug is fixed.

**Comment by gunthermeert** [comment]
Hi @dbeatty10 👋,

Thank you for reviewing and providing a short-term work-around, this will do for now and is much appreciated.
Hopefully the bug get fixed soon.

Kind regards,
Gunther

**Comment by jtcohen6** [comment]
In summary: When a generic test definition (= macro) is modified, it seems we aren't appropriately re-parsing the specific generic test that's linked to that macro. Thanks @dbeatty10 for identifying root cause & providing the clear reproduction case!
