### ISSUE TITLE
[CT-2130] Respect `log.ini` config file if provided

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-core#6993]
> However, for CLI use a file config is more common and appropriate in my mind. The dictionary config is for calling directly within python. A --logging-config-file argument would probably meet all future logging needs. [file config docs](https://docs.python.org/3/library/logging.config.html#logging.config.fileConfig)

If an end user provides logging config in a `log.ini` configuration file, we should do our best to respect that file's configuration. I'd be curious to see how many other users / community members would be interested in the same.

_Original discussion in https://github.com/dbt-labs/dbt-core/issues/6639_

**Comment by DustinMoriarty** [comment]
Here is some background. The request is to allow a user to provide a standard [logging.config](https://docs.python.org/3/library/logging.config.html) file which bypasses all DBT logging configuration. For CLI use, the user would provide the logging configuration file path. The user defines the log levels, log formats, log destinations (e.g. stderr, stdout, file, etc) in that file using the existing python log configuration format. There would be no need to add any new parsing of the configuration file schema. DBT would simply expose the existing built in python logging configuration options provided by the built in logging library provided by the language.

As far as all the extra event metadata available with json logging is concerned, as long as that metadata is provided in the "extra" argument in any log statement (e.g. `log.info("Something happened", extra={"data": {}, "info": {}})`), then it can be picked up by any log formatter which wants to use it, including json structured log formatters like [python-json-logger](https://pypi.org/project/python-json-logger/).

**Comment by DustinMoriarty** [comment]
It looks like DBT uses [logbook](https://logbook.readthedocs.io/en/stable/) for logging rather than the standard library. I would take a hard look at if logbook is really a good fit. It looks like logbook adds a lot of complexity to solve problems which probably should not be handled within the application logger in the first place (sending emails, notifications, webhooks, raising tickets, etc.). These are all things which should be handled by log layers outside of the actual application (e.g. cloudwatch, ELK, splunk, etc.) and that DBT is not using anyway. I don't at first glace see a place in logback to provide a logging config, which in itself makes me question it's design since log config should be a runtime decision and never hard coded.  I would be curious what logbook feature is needed by DBT.


There must be a way that logbook exposes the logging config though.

**Comment by jtcohen6** [comment]
@DustinMoriarty We don't use `logbook` anymore, except in our "legacy" logging system (pre-1.0), which is still around to support a few quite old integrations that are still being deprecated.

For the new event/logging system, see:
- https://github.com/dbt-labs/dbt-core/tree/main/core/dbt/events
- https://docs.getdbt.com/reference/events-logging
