### ISSUE TITLE
[CT-2181] [Feature] Enable calling a model using `source` or a temporary relation in dbt metrics

### ISSUE THREAD

**Issue by iriscatter** [dbt-labs/dbt-core#7049]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently, dbt metrics only supports `ref` when calling a model that is within the DAG.

Besides this existing feature, we should also consider the capability of using `source` or creating a temporary relation to refer to any other model outside of the current repository(since we have many GIT repos that teams use to build models).

So the potential model reference example in dbt metrics can be:
```
{%- set target_relation = api.Relation.create(
    database = 'banking',
    schema = 'staging',
    identifier = 'account_info') -%}

metrics:
  - name: account_balance
    model: target_relation
    ....
```

OR
```
metrics:
  - name: account_balance
    model: source('a', 'b')
    ....
```

### Describe alternatives you've considered

Duplicate an external model by creating a view in the DAG first, and then refer to the view in dbt metric. However, this is neither flexible nor scalable.

### Who will this benefit?

Anyone who plans to use `dbt metric` in a cross-functional or cross-database environment.
This will also encourage more people to start using dbt metrics, given its more flexible settings.

### Are you interested in contributing this feature?

Yes if it is within my capabilities.

**Comment by Jstein77** [comment]
Hey @iriscatter 

I just joined dbt as a Developer Experience Advocate focused on the semantic layer and all things metrics. Thanks for opening this issue!

It sounds like you want to accomplish two things:
* The ability to reference a model in a different dbt project
* The ability to use sources for a metric

Let me try to address these two points separately.

### The ability to reference a model in a different dbt project
More likely than not this is something that we will try and support over the coming year, especially as dbt Cloud leans more into the multi-project world. You can read more about our plans for multi-project deployments here: [#6725 Multi-project deployments](https://github.com/dbt-labs/dbt-core/discussions/6725)

We most likely will not support this by creating a temporary relation with Jinja. One significant reason why this is an issue is that it breaks our DAG - the temporary relation isn’t a real node and so the metric is a floater, something we generally discourage in dbt projects as we’d have no idea of the correct sequence to run the metric query. 

### The ability to use sources for a metric
It sounds like this is an extension of the multi-project problem i.e trying to reference a table in another project but using sources. We have not supported using sources to define metrics in the past because our view is metrics are meant for mart level models that have been cleaned, transformed, and tested, not for raw data from the source. If I understand what you’re trying to use sources for correctly, then I think the work we’re doing on multi-project deployments will also address this use case. As I mentioned, keep an eye on [#6725 Multi-project deployments](https://github.com/dbt-labs/dbt-core/discussions/6725) for developments on this issue.

**Comment by dbeatty10** [comment]
Thanks for taking the time to write this up @iriscatter !

I'm going to close this as `wontfix` for the reasons @Jstein77 outlined, namely that we intend to enable the use case you described via https://github.com/dbt-labs/dbt-core/discussions/6725
