### ISSUE TITLE
[CT-2190] [Feature] Incremental delete and merge update

### ISSUE THREAD

**Issue by acurtis-evi** [dbt-labs/dbt-core#7057]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I would like to introduce a `delete_column` and an update to `merge_update_columns` as described below to the incremental merge materialization.  I have worked this out in this [website PR](https://github.com/dbt-labs/docs.getdbt.com/pull/2930) and this [dbt-core PR](https://github.com/dbt-labs/dbt-core/pull/7055).  

Introducing this will allow AWS DMS Op='D' to be respected when merging / reconstructing tables.  The merge_update_columns will allow cumulative models.

When selecting columns to merge (using the `merge` strategy), a computation consisting of the current and old value can be done using a dictionary to represent the column instead of naming it.  The freq column represents a computed merged column in the example below.

<File name='models/my_model.sql'>

```sql
{{
  config(
    materialized = 'incremental',
    unique_key = 'word',
    merge_update_columns = ['word',
        {
            'name': 'freq',
            'value': 'DBT_INTERNAL_SOURCE.freq+DBT_INTERNAL_DEST.freq'
         }],
    ...
  )
}}

select word, count(*) as freq FROM ... group by 1
```

</File>

The `merge` strategy supports deleting rows when the `delete_column` is specified.  This column is only needed during the incremental update of a table and should be represented as a boolean.

<File name='models/my_model.sql'>

```sql
{{
  config(
    materialized = 'incremental',
    unique_key = 'id',
    delete_column = 'is_deleted',
    ...
  )
}}

select
{% if is_incremental() %}
   case
    when DATA:Op=='D' then true
    else false
   end as is_deleted,
{% endif %}
   col1,
   col2,
   ...

```

### Describe alternatives you've considered

There doesn't seem to be a `good` alternative

### Who will this benefit?

Anyone who wishes to use delete functionality of merge and custom merges

### Are you interested in contributing this feature?

yes

**Comment by dbeatty10** [comment]
Thanks for taking the time to open this issue and the associated pull request @acurtis-evi !

We currently have four built-in incremental strategies (`append`, `delete+insert`, `merge`, `insert_overwrite`), and our intent is to keep them as "simple" as possible rather than adding more configuration options.

Simultaneously, we want to be able to support advanced users like yourself that want to define their own customizations! 🧠 

We've added some new functionality in https://github.com/dbt-labs/dbt-core/issues/5245 to empower users like you to override the behavior of existing incremental strategies or implement your own without a bunch of boilerplate, but we're behind on documenting it!

[Here](https://github.com/dbt-labs/docs.getdbt.com/issues/1761) is our issue to add this documentation, which may or may not already be clear enough for you to see how to implement your custom strategy. Eventually, this information will be added [here](https://docs.getdbt.com/docs/build/incremental-models#configuring-incremental-strategy).

I'm going to close this as `wontfix` since we want to keep the current `merge` strategy as simple as possible. But I hope our pending update to the documentation ends up being even more useful to you and others.
