### ISSUE TITLE
[CT-2279] [Feature] add adapter response message to terminal `LogTestResult`

### ISSUE THREAD

**Issue by bruno-szdl** [dbt-labs/dbt-core#7136]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Tests can be a real money drainer in BQ since the billing is based on bytes processed. We can configure lots of tests without knowing how much they are costing and have a surprise with the bill at the end of the month.

@aezomz added the adapter_response to tests in #6645, making it possible to better monitor bytes processed by tests.

I am proposing to also show the bytes_processed, through the adapter_response message, in the `LogTestResult` in the terminal, the same way as it is shown for models. In this way, developers can more quickly and easily monitor test costs, and detect if there is an unexpectedly expensive test being run.

So, instead of this
![CleanShot 2023-03-07 at 22 08 36@2x](https://user-images.githubusercontent.com/47795359/223593093-dedd244d-c693-4de7-bb9c-14ea67cee3f1.png)

We would have something like this
![CleanShot 2023-03-07 at 22 09 52@2x](https://user-images.githubusercontent.com/47795359/223593246-ba5faa8e-e54b-4fa2-ba97-5671dd2828ec.png)

As this is a change I think must be made in dbt-core, not in dbt-bigquery, I chose to include the full adapter response message, not only the bytes_processed, because other adapters don't have it.

### Describe alternatives you've considered

I modified the following files:
- `proto_types.py`
- `types.py`
- `test.py`

To include the adapter response message in the `LogTestResult`

### Who will this benefit?

Mainly for developers using dbt-bigquery.

### Are you interested in contributing this feature?

Yes, if this is considered a good issue I can open the PR.

**Comment by Fleid** [comment]
On principle, I'm 100% for it.

If we're to make that `help_wanted`, I need a sanity check from @jtcohen6 that how we're doing that for models is portable to tests.

**Comment by Fleid** [comment]
@emmyoop weren't you looking at logging recently? Just looking for a quick sanity check before marking that `help_wanted` and getting @bruno-szdl to take a pass at it. I don't want anybody losing their time here ;)

**Comment by jtcohen6** [comment]
Hmm. The equivalent to this for other commands is:
https://github.com/dbt-labs/dbt-core/blob/311a57a21e61955904202bdb469c2077202e9073/core/dbt/task/run.py#L186-L204

Specifically this line:
https://github.com/dbt-labs/dbt-core/blob/311a57a21e61955904202bdb469c2077202e9073/core/dbt/task/run.py#L192

Rather than including the full `adapter_response` in the log output, the adapter can choose what string gets passed into `result.message`! [Here in `dbt-bigquery` is where](https://github.com/dbt-labs/dbt-bigquery/blob/ea0833424c6445cff853e82ab9a5d563a55d3856/dbt/adapters/bigquery/connections.py#L516-L528) the logic for that is defined, including the rules about when/how to include `bytes_processed`.

I'd prefer to take a consistent approach here, if possible.
