### ISSUE TITLE
[CT-2290] `dbt debug` ignores configured “log-path”.

### ISSUE THREAD

**Issue by dbrtly** [dbt-labs/dbt-core#7150]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Logs always go to “logs/“ even if configured to “.logs”. 

### Expected Behavior

Logs should be in “.logs/“

### Steps To Reproduce

Use dbt init to create a new project.

Add explict config to dbt_project.yml 
```log-path: “.logs”```

Run `dbt debug`

look in project directory for log files. 
They are in “logs/“ not “.logs”. 

### Environment

```markdown
- OS: windows and macos
- Python: 3.10
- dbt: 1.4.4
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thanks for reaching out @dbrtly !

Could you try `log-path: ".logs"` or `log-path: '.logs'` or `log-path: .logs` instead of `log-path: “.logs”`?

It looks like the example you provided uses unicode characters U+201C and U+201D which didn't work for me, but the other variations did work when I tried them out.
