### ISSUE TITLE
[CT-2292] [Bug] HTTPSConnectionPool(host='hub.getdbt.com', port=443): Max retries exceeded with url: /api/v1/index.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by xmansch** [dbt-labs/dbt-core#7153]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

External connection exception occurred: HTTPSConnectionPool(host='hub.getdbt.com', port=443): Max retries exceeded with url: /api/v1/index.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)'))) 

### Expected Behavior

-

### Steps To Reproduce

det deps

### Environment

```markdown
- OS: Windows 10
- Python:3.11
- dbt:1.4.4
```

### Additional Context

No vpn

**Comment by dbeatty10** [comment]
Thanks for reporting this @xmansch !

Are you still having this problem? If so, could you share the contents of your `profiles.yml` file?

I was able to successfully execute `dbt deps` with the following file:

`packages.yml`
```yaml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0
```

**Comment by xmansch** [comment]
> 

No, error is
**External connection exception occurred: HTTPSConnectionPool(host='hub.getdbt.com', port=443): Max retries exceeded with url: /api/v1/index.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))        **

i set enviroment
set PYTHONWARNINGS=
but error is the same

**Comment by xmansch** [comment]
i make this test script

**import requests
import urllib3
urllib3.disable_warnings()
try:
    with requests.get("https://hub.getdbt.com", stream=True) as rsp:
        ip, port = rsp.raw._connection.sock.getpeername()
        print(ip, port)
except:
    print("!except!!")
    with requests.get("http://hub.getdbt.com", stream=True, verify=False) as rsp:
        ip, port = rsp.raw._connection.sock.getpeername()
        print(ip, port)

and i have

![image](https://user-images.githubusercontent.com/4114548/224475853-75227f36-4891-410b-aaea-f7a0d9ef0a0b.png)

**Comment by xmansch** [comment]
i resolve this issue , when install
pip install python-certifi-win32
thanks

**Comment by imsushantjain** [comment]
Faced the same issue with dbt 1.2.6, Windows 10 and python version 3.10.7.

1) Initially tried installing pip-system-certs, but that didn't work.

2) Installing python-certifi-win32 worked, cheers to @xmansch

**Comment by alison985** [comment]
I'm also seeing what @jordanperr just reported in entralliance/entr_runtime#82 When on the corporate VPN `dbt deps` doesn't work. If I disconnect from the VPN it works fine. I'm on an M1 Mac and running this within `docker run --platform=linux/amd64 python:3.10-bullseye /bin/bash`

**Comment by dbeatty10** [comment]
@alison985 [at least one](https://github.com/dbt-labs/dbt-core/issues/7427#issuecomment-1520194576) non-Windows user was able to resolve a `External connection exception occurred: HTTPSConnectionPool ... Max retries exceeded` issue by setting the [`REQUESTS_CA_BUNDLE`](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification) environment variable.

Would you be willing to give that a try?

(`CURL_CA_BUNDLE` may or may not also work.)

**Comment by dbeatty10** [comment]
@alison985 I'm not sure!

This thread on Stack Overflow had some interesting tidbits that may or may not be useful:
https://stackoverflow.com/a/57795811

You may need to ask help from your network admin on this one.

**Comment by moseleyi** [comment]
I get this when trying to install `dbt_utils`

```
External connection exception occurred: HTTPSConnectionPool(host='codeload.github.com', port=443): Read timed out. (read timeout=10.0)
```
![image](https://github.com/dbt-labs/dbt-core/assets/16131590/8131dd2d-5d97-4777-bcec-1cfcd68fc3da)

Anybody knows why it's happening?

**Comment by fpa-postgres** [comment]
Seeing same issue in RHEL 8, x86_64 GNU/Linux host. I tried installing 
pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org pip_system_certs

After that, warnings went away, but, getting connection issue on running dbt deps

dbt deps --profiles-dir ./profile --project-dir x/y/test

Any suggestions

Thanks
Vidhya

**Comment by fpa-postgres** [comment]
Seeing same issue in RHEL 8, x86_64 GNU/Linux host (connected to vpn). I tried installing
pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org pip_system_certs

After that, warnings went away, but, getting connection issue on running dbt deps

dbt deps --profiles-dir ./profile --project-dir x/y/test

Error - External connection exception occurred: HTTPSConnectionPool(host='hub.getdbt.com', port=443): Max retries exceeded with url: /api/v1/index.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe4a427aca0>, 'Connection to hub.getdbt.com timed out. (connect timeout=30)'))

Any suggestions

Thanks
Vidhya

**Comment by vidhyaguru** [comment]
Seeing same issue in RHEL 8, x86_64 GNU/Linux host (connected to vpn). I tried installing
pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org pip_system_certs

After that, warnings went away, but, getting connection issue on running dbt deps

dbt deps --profiles-dir ./profile --project-dir x/y/test

Error - External connection exception occurred: HTTPSConnectionPool(host='hub.getdbt.com', port=443): Max retries exceeded with url: /api/v1/index.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe4a427aca0>, 'Connection to hub.getdbt.com timed out. (connect timeout=30)'))

Any suggestions

Thanks
Vidhya

**Comment by dbeatty10** [comment]
Hi @vidhyaguru, this looks like an issue in your local environment rather than a bug in dbt-core. It's just a matter of figuring out what the missing piece is within your local environment.

[Here](https://github.com/dbt-labs/dbt-core/issues/8554#issuecomment-1715874918) is a write-up that includes a high-level explanation as well as as variety of approaches that have worked for others. In particular, it has a sample Python script for troubleshooting. Using this script removes `dbt` from the equation and allows you to focus on your local environment.

Let us know how it goes!

**Comment by vidhyaguru** [comment]
We are still having issue. It is working fine from local env (iterm from mac, with vpn). But getting timeout when run from a baremetal host with vpn. 

Error - External connection exception occurred: HTTPSConnectionPool(host='hub.getdbt.com', port=443): Max retries exceeded with url: /api/v1/index.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe4a427aca0>, 'Connection to hub.getdbt.com timed out. (connect timeout=30)'))

 Network team ruled out any firewall issues. Any suggestions we can try out ?

Thanks
Vidhya

**Comment by dbeatty10** [comment]
> getting timeout when run from a baremetal host with vpn.

My suggestion for next steps would be to add the Python script explained [here](https://github.com/dbt-labs/dbt-core/issues/8554#issuecomment-1715874918) to your baremetal host.

[At least one](https://github.com/dbt-labs/dbt-core/issues/7427#issuecomment-1520194576) corporate VPN user was able to resolve their networking issues by setting the [`REQUESTS_CA_BUNDLE`](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification) environment variable.

The write-up [here](https://github.com/dbt-labs/dbt-core/issues/7427#issuecomment-1520194576) really the best and most detailed troubleshooting options we know about. It should give you good launching off points for further research on your own.

**Comment by vidhyaguru** [comment]
Thank you for the suggestions. Yes, have been trying to get the test script working and enabled all possible options as in the post. No luck, yet ! 

python test.py
It didn't work

HTTPS_PROXY: None
REQUESTS_CA_BUNDLE: /lib/python3.9/site-packages/certifi/cacert.pem
CURL_CA_BUNDLE: /lib/python3.9/site-packages/certifi/cacert.pem
DEFAULT_CA_BUNDLE_PATH:/lib/python3.9/site-packages/certifi/cacert.pem

Thanks
Vidhya

**Comment by apolorei** [comment]
I am facing the same issue

**Comment by dbeatty10** [comment]
@apolorei and @rbritto-fanduel

If you are getting this error message, it is probably an issue in your local environment rather than a bug in dbt-core.
 
Check out https://github.com/dbt-labs/dbt-core/issues/8554#issuecomment-1715874918 for some context and troubleshooting steps.

**Comment by vidhyaguru** [comment]
has anything changed at amazon redirect setting ?
dbt deps - traceroute is showing IP 52.46.164.38 (amazon site) which is where we are getting connection timeout from linux host. 
it was working fine a month back

thanks
Vidhya

**Comment by dbeatty10** [comment]
@vidhyaguru I just checked and I was able to run `dbt deps`. If you're having trouble with a connection timeout, the best troubleshooting advice we have is catalogued [here](https://github.com/dbt-labs/dbt-core/issues/8554#issuecomment-1715874918).

**Comment by vidhyaguru** [comment]
Thanks, Yes, I am also able to run dbt deps from my mac (with vpn), its from specific linux BM hosts we are getting timing out. Tried all options in the catalog, will keep posted if we figure out more on specific env

**Comment by HichemELB** [comment]
Today, we are encountering the same error more frequently, 1 out of 10 jobs. We use dbt cloud, and nothing is self-hosted, even for development.

**Comment by dbeatty10** [comment]
Thanks for reporting this @HichemELB, we are investigating the issue currently.

**Comment by dbeatty10** [comment]
@HichemELB you can monitor the status here:
https://status.getdbt.com/incidents/0mb25gcntq9g

**Comment by HichemELB** [comment]
Thanks a lot @dbeatty10 🙏🏼

**Comment by mxie-r2r** [comment]
> I'm also seeing what @jordanperr just reported in [entralliance/entr_runtime#82](https://github.com/entralliance/entr_runtime/issues/82) When on the corporate VPN `dbt deps` doesn't work. If I disconnect from the VPN it works fine. I'm on an M1 Mac and running this within `docker run --platform=linux/amd64 python:3.10-bullseye /bin/bash`

This fixed my issue. I had Cloudflare WARP active. Disconnecting it allowed me to run it normally.

**Comment by srinichunduri** [comment]
pip install pip-system-certs has helped. It seems like a bug when using python 3.11.
