### ISSUE TITLE
[CT-2314] [Feature] Do we _have_ to call the boolean property `contract`?

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#7184]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

From reading https://github.com/dbt-labs/dbt-core/issues/6748, it looks like I'm about 3 weeks late to this party. But better now than in another 3 weeks! 

I haven't been following this closely, and when I saw `contract:` I assumed it was going to be the key of a dictionary containing all the rules of the contract, not a simple bool. 

Could I make a late breaking pitch for `has_contract`? 

### Describe alternatives you've considered

- I would also accept `is_contracted`, but I don't think I'll get as far on that one. 
- Or go back to the original naming scheme, but just change the noun (i.e. `contract_enabled` instead of `constraints_enabled`)

### Who will this benefit?

People who assume we follow [our style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md#:~:text=Booleans%20should%20be%20prefixed%20with%20is_%20or%20has_.) (yes I know this is the SQL style guide not the Python style guide, but it's going to be side-by-side with all the YAML that does follow this scheme)

### Are you interested in contributing this feature?

I could if it's the only way it'll get done, but I won't be the fastest way to get it done

**Comment by jtcohen6** [comment]
@joellabes Thanks for opening ❤️ 

> But better now than in another 3 weeks!

Very very true!

Options:
- `has_contract` — my qualm with this is that it feels more _descriptive_ than _proactive_, and choosing to contract a model is an intentional matter
- `contract_enabled` — I don't like the overlap with `enabled`
- `enforce_contract` or `contract_enforced` ?

**Comment by joellabes** [comment]
I like `enforce_contract`, I like `enforce_spec` even more!

**Comment by jtcohen6** [comment]
Good conversation with @gwenwindflower @callum-mcdata @MichelleArk in Slack: Could we envision supporting other nested fields / configurations in the future? For example, during community office hours, there was an ask to make "enforcing column order" configurable. I don't think we're going to do that in the first cut—for simplicity, and because I don't think deterministic column order is high-value, and finally because column order necessarily changes to handle schema evolution for incremental models—but still, we could imagine other related configurations existing in the future.

```yml
contract:
  enforced: true
  <more_things_in_future>: ...
```

I prefer `contract` here to `spec`, again because it feels more suggestive of the larger feature we're interested in building, even if it's not _everyone's_ idea of what "data contract" means.

**Comment by gwenwindflower** [comment]
i also like contract in terms of pointing to where this is all headed. data contracts do indeed mean many things to many people, but this is one of the most common meanings.

**Comment by joellabes** [comment]
Totally happy with 

```
contract:
  enforced: true
  <more_things_in_future>: ...
```
!
