### ISSUE TITLE
[CT-2319] Selection for versioned models

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-core#7199]
* `dbt run --select versioned_model` should run all versions of the model by default
* `dbt run --select versioned_model.v2` should run just the specific model
* potentially: syntax to select just the latest, or a specific model version.

**Comment by jtcohen6** [comment]
> syntax to select just the latest

How about:
```bash
$ dbt run --select version:latest
```

---

It should also be possible to select:
- Models that are not versioned (`version:none`?)
- Model versions that are _newer_ than the `latest` version (`version:prerelease`?), and _older_ than the `latest` version (`version:old`?). To do this, we'd need to know about how versions are _ordered_. Plain-old alphabetical sorting only works up to `10`; we'd talked about implementing this for numeric values, and also supporting it for SemVer.

It's conceivable that folks will want to change the default behavior in development—include latest versions, prerelease versions, and models that aren't versioned—i.e. exclude "old" model versions—which they could accomplish by defining a [default selector](https://docs.getdbt.com/reference/node-selection/yaml-selectors#default).

If we're able to come up with a syntax for these use cases sooner, we can pull it into the scope of this issue. Otherwise, it feels like a UX improvement that can come later.

---

> or a specific model version

Given that each model has its own versioning scheme, and we're not prioritizing ergonomics/functionality for "bump the version for entire subset of models at once" — I don't think it makes sense to support a syntax for, "Select every model whose `version` is `2`." If we did eventually want to do this, _maybe_ it would look like `dbt run --select version:2`, but I don't care to do it within the scope of this issue.

---

For future consideration (also out of scope for this issue):
- whether models with an upcoming `deprecation_date` should raise a warning whether selected
- whether models past their `deprecation_date` should be selected, unselected, or full-on disabled by default
