### ISSUE TITLE
[CT-2443] [Regression] `dbt snapshot` command uses target path, but does not have a CLI option to specify it.

### ISSUE THREAD

**Issue by dwreeves** [dbt-labs/dbt-core#7418]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

the `dbt snapshot` command does not have a `--target-path` option.

### Expected Behavior

Because the `dbt snapshot` command uses the target path as part of its runtime, I expected that you would also be able to specify it. This is also a regression from our end (we are upgrading from dbt 1.1 to 1.5), as we were using a custom target path to run everything out of.

### Steps To Reproduce

Attempt the command `dbt snapshot --target-path my/custom/path`.

### Environment

```markdown
- OS: OSX
- Python: 3.10
- dbt: 1.5 beta
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for trying out 1.5 and reporting this @dwreeves 🏅 

I suspect that the behavior you are seeing is because `@p.target_path` is missing from here:
https://github.com/dbt-labs/dbt-core/blob/1722079a43d1e3a94ffb73e66c8712ee0837e9fa/core/dbt/cli/main.py#L638-L655

I'm going to re-label this as a regression.

**Comment by dbeatty10** [comment]
Lol, I just noticed you already realized the fix and submitted https://github.com/dbt-labs/dbt-core/pull/7419 accordingly. Thanks for doing that @dwreeves!
