### ISSUE TITLE
[CT-2511] [Regression] source freshness not working in bigquery after upgrade to 1.5 

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#7489]
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

After upgrading dbt from 1.4.1 to 1.5.0, commands like `dbt source freshness --select source:mysql.schools` never finish.  

A command that takes a few seconds in 1.4.1 will now get stuck after "1 of 1 START freshness of mysql.schools ........................................ [RUN]"... and will hang there until I cancel the process

We use the image from ghcr.io/dbt-labs/dbt-bigquery

We have the freshness configured like this:
```
freshness:
  error_after:
    count: 1
    period: day
```

We see the same behavior for any source/model we try to select.

### Expected/Previous Behavior

below

### Steps To Reproduce

We've reverted to 1.4.1 to confirm it still works in that image (it does).

We've run source freshness commands with "--debug". The command still stalls out in the same way, but it shows that the query takes about 2 seconds:

```
00:42:20  On source.company.mysql.schools: /* {"app": "dbt", "dbt_version": "1.5.0", "profile_name": "default", "target_name": "prod_admin", "node_id": "source.company.mysql.schools"} */





      SELECT
        TIMESTAMP_TRUNC(TIMESTAMP_MILLIS(last_modified_time), DAY, 'UTC') as max_loaded_at,
        TIMESTAMP_TRUNC(current_timestamp(), DAY, 'UTC') as snapshotted_at
      FROM
        `project-name`.`mysql`.__TABLES__
      WHERE table_id = 'schools'



00:42:22  BigQuery adapter: https://console.cloud.google.com/bigquery?project=project-name&j=bq:US:123456&page=queryresults
00:42:22  Timing info for source.company.mysql.schools (execute): 00:42:20.666548 => 00:42:22.372497
```

When I run the command in the 1.4.1 image, I get the same output except it continues with the following (and then finishes as expected):
 
```
00:46:39.233407 [info ] [Thread-1 (]: 1 of 1 PASS freshness of mysql.schools ......................................... [PASS in 1.50s]
```

### Environment

```markdown
- OS:
- Python:
- dbt (working version): 1.4.1
- dbt (regression version): 1.5.0
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

This is not my report! `@dylan-qz` reported it on the forum: https://discourse.getdbt.com/t/source-freshness-not-working-in-bigquery-after-upgrade-to-1-5/8102

**Comment by dylanharper-qz** [comment]
Thank you Joel! I'm relatively new to dbt and hadn't realized I could come here.

**Comment by dbeatty10** [comment]
Thanks for reporting this @dylanharper-qz (and @joellabes!) 🙏 

I wasn't able to reproduce this with the simple example below. Could you try it out and see if it fails for you @dylanharper-qz?

### Reprex

`models/my_model.sql`
```sql
select cast('2023-01-01 00:00:00' as datetime) as _etl_loaded_at
```

`models/_sources.yml`
```yaml
version: 2

sources:
  - name: my_test
    schema: "{{ target.database }}"
    schema: "{{ target.schema }}"
    freshness:
      error_after:
        count: 365
        period: day
    loaded_at_field: _etl_loaded_at

    tables:
      - name: my_model
```

```shell
dbt source freshness --select source:my_dbt_project.my_test.my_model
```

I also tried with `count: 1`, and that behaved correctly as well.
`

**Comment by dylanharper-qz** [comment]
@dbeatty10 I was unable to get those snippets to run, what does the dbt_project.yml look like? I kept getting errors like "Unrecognized name: _etl_loaded_at at [3:11]" or "404 Not found: Table X.Y.Z was not found in location US".

But while trying, I realized that we have a custom collect_freshness macro that might be causing the problem.

This example reproduces the behavior described at the top of this ticket:

`models/mysql/_sources.yml`

```
version: 2

sources:
  - name: mysql
    schema: "mysql"
    freshness:
      error_after:
        count: 365
        period: day
    loaded_at_field: _etl_loaded_at

    tables:
      - name: schools
  ```
  
  `macros/collect_freshness.sql`
  
  ```
  {% macro collect_freshness(source, loaded_at_field, filter) %}
  {% call statement('collect_freshness', fetch_result=True, auto_begin=False) -%}
    {% set time_period = "DAY" %}

    SELECT
      TIMESTAMP_TRUNC(TIMESTAMP_MILLIS(last_modified_time), {{ time_period }}, 'UTC') as max_loaded_at,
      TIMESTAMP_TRUNC({{ current_timestamp() }}, {{ time_period }}, 'UTC') as snapshotted_at
    FROM
      `{{ source.database }}`.`{{ source.schema }}`.__TABLES__
    WHERE table_id = '{{ source.table }}'
    {% if filter %}
    AND {{ filter }}
    {% endif %}
  {% endcall %}
  {{ return(load_result('collect_freshness').table) }}
{% endmacro %}
```

`dbt_project.yml`

```
name: "qz"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# The configuration parameters below apply to all resources in a particular directory. These
# settings can be overridden by either config blocks or parameters files, depending on the setting.
models:
  mysql:
    +schema: mysql
 ```

**Comment by dbeatty10** [comment]
I left out one crucial detail for my reprex @dylanharper-qz: need to do a `dbt run` first!
```shell
dbt run
dbt source freshness --select source:my_dbt_project.my_test.my_model
```

Once I tried your custom override for `collect_freshness`, I was able to reproduce what you are seeing between 1.4 and 1.5.

Could you try making the following change to your custom override?
```diff
- {{ return(load_result('collect_freshness').table) }}
+ {{ return(load_result('collect_freshness')) }}
```

Once I made that small change, it worked for me in 1.5. However, that same tweak is not compatible with 1.4 -- you need to use different versions of the macro between 1.4 and 1.5. This is presumably due to the changes in https://github.com/dbt-labs/dbt-core/commit/17014bfad3e204279c94c6a0285f784fc10711eb.

We should add a note to the [migration guide for 1.5](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.5).

**Comment by dylanharper-qz** [comment]
I can confirm that this works. Thank you both for the support!  I inherited a project with a lot of customizations and am still trying to get up to speed, but seeing how responsive you all are is a fantastic feeling.

We are really excited to start trying the new Data Governance features, thanks again for unblocking us.

**Comment by dbeatty10** [comment]
Awesome @dylanharper-qz  🎉

Glad this is working for you now. We will be keen to hear your feedback on the new governance features.

https://github.com/dbt-labs/docs.getdbt.com/issues/3331 will resolve the necessary updates to our migration guide.

**Comment by philipbaer-amaze** [comment]
I have same issue when upgrading to 1.5, the source freshness stalls. I don't have a collect_freshness custom macro, but do have a package override. Looks like this

version: 2

sources:
  - name: fivetran_log
    overrides: fivetran_log

    freshness:
      warn_after:
        count: 72
        period: hour
      error_after:
        count: 96
        period: hour

    tables:
      - name: account_membership
        freshness: null # do not check freshness for this table 


---
Any advice? Thanks!

**Comment by dbeatty10** [comment]
@philipbaer-amaze To paraphrase [our discussion](https://getdbt.slack.com/archives/C03SAHKKG2Z/p1683135493290699?thread_ts=1683127164.993329&cid=C03SAHKKG2Z) in Slack, [this](https://github.com/dbt-labs/dbt-core/commit/17014bfad3e204279c94c6a0285f784fc10711eb) change broke anyone depending on [`collect_freshness` from dbt_fivetran_utils](https://github.com/fivetran/dbt_fivetran_utils/blob/f7567295c8f406946dfdbcdd761affad7d7bb535/macros/collect_freshness.sql#L6). In your case, the `fivetran_log` package.

To be clear, this breaking change was caused by dbt-core and not the Fivetran team. Sorry about this @fivetran-joemarkiewicz 😰

**Comment by jtcohen6** [comment]
Thanks for all the hard work to dig in & identify root cause here!

I'm going to reopen this issue, because we should really add our own backward compatibility. I think it could be as simple as checking what's returned by the `collect_freshness` macro before unpacking:

https://github.com/dbt-labs/dbt-core/blob/828d723512fced809c63e369a82c7eb570a74986/core/dbt/adapters/base/impl.py#L1115-L1117

We should definitely also update the migration guide to document the change (https://github.com/dbt-labs/docs.getdbt.com/issues/3331).
