### ISSUE TITLE
[CT-2543] Execution <> Adapters: Cloning from production

### ISSUE THREAD

**Issue by stu-k** [dbt-labs/dbt-core#7549]
## Description
One of the initiatives that the execution team is taking on in Q2 is [cloning from a production environment](https://github.com/dbt-labs/dbt-core/issues/7256). The work here is to core to enable core users to clone a schema using zero-copy clones if it is supported by the DWH, and views if is not.

Jeremy currently has a [draft PR](https://github.com/dbt-labs/dbt-core/pull/7258) up that touches the adapter zone of core.

Talk to @stu-k for additional details.

**Comment by ChenyuLInx** [comment]
There are 3 functions each adapter need to implement, they are
- can_clone_tables
- get_pointer_sql
- get_clone_table_sql
The default implementation(and one for snowflake) can be found in Jerco's PR linked above.

The work for adapter team would be figure out which functions each adapter need to implement and get them implemented.

**Comment by VersusFacit** [comment]
I've read through this, and I think the general strategy makes sense. Re: naming matters, I find state_relation to be a bit vague, especially in the Python runtime. With everything I understand currently, my best intuition is that it's a sister term of target_relation, and the like. Likewise, I find point her to be very odd, since we're not really pointing at a memory address. Instead, I believe we're referencing an existing relation, and we should thusly name is.

However, I feel like something far more descriptive would be stateful_relation or really anything that captures the essence that the relation referenced is the state being employed indirectly.

I believe Matt is going to do a more thorough check on the code with how it relates to the adapters, but I like the general design. We're very fortunate that this isn't something DBMSs have felt the need to differentiate in (yet).

**Comment by jtcohen6** [comment]
@aranke @McKnight-42 Shall we open separate issues to track the implementations / testing in each of:
- [ ] dbt-snowflake (I see there's a WIP PR: https://github.com/dbt-labs/dbt-snowflake/pull/664)
- [ ] dbt-redshift
- [ ] dbt-bigquery
- [ ] dbt-spark & dbt-databricks (I believe only the Databricks Runtime supports [`shallow clone`](https://docs.databricks.com/sql/language-manual/delta-clone.html), and only with Delta tables)

**Comment by jtcohen6** [comment]
Merged into all the adapters!
