### ISSUE TITLE
[CT-2552] Pin protobuf to greater than 4.0

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-core#7565]
Some users were seeing an error: ImportError: cannot import name 'builder' from 'google.protobuf.internal'. The generated types_pb2.py file was built with protobuf 4 and requires protobuf 4 in order to import "builder".

**Comment by pangtongs** [comment]
Hello, is this issue resolved, or Am I doing anything wrong here? I cannot install dbt due to unable to import name 'builder'

pip install dbt-core==1.8.2
pip install dbt-bigquery==1.8.1

already ran successfully without any message.

<img width="680" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/6629520/a9a7c3cf-ea93-4b25-b372-b6c7207aa252">
