### ISSUE TITLE
[CT-2575] [Bug] selectors.yaml not matching CLI -–select behavior

### ISSUE THREAD

**Issue by HybridNeos** [dbt-labs/dbt-core#7616]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have six tables with a tag of *view* given my dbt_project.yml. One of those table I added a tag *test* in the file config. If I use the CLI to run `dbt list --select 'tag:test,tag:view'` it returns just the one table. However, when making a selectors.yaml file and passing in the same CLI style selector, it returns all six instead of the one. This also happens with the CLI method or full yaml method for selectors.yaml.

### Expected Behavior

Returns the one model with tags of *test* and *view*

### Steps To Reproduce

1. Using dbt-core 1.4.4 or 1.5.0
2. Have a model directory with tags set by dbt_project.yml and one set in config directly in model. Create a selector.yml entry with desired selector logic.
3. Run `dbt list --select **alias**`

### Relevant log output

```shell
See picture attached
```

### Environment

```markdown
- OS: RHEL Linux 7.9
- Python: 3.8.16
- dbt: 1.4.4 or 1.5.0
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

![dbt_selectors_error](https://github.com/dbt-labs/dbt-core/assets/19171735/bd701a03-a184-4210-9dfb-2041f41297af)

**Comment by dbeatty10** [comment]
Thanks for reaching out @HybridNeos !

CLI style selectors in `selectors.yml` [don't support](https://docs.getdbt.com/reference/node-selection/yaml-selectors#cli-style) intersection, union, or exclude:

<img width="450" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/bbd90ab3-a3fa-4812-9e77-c0312231c38a">

But the full YAML worked for me when I tried out your example.

Could you try out example below and see if it works for you?

Note `--selector` rather than `--select` when using `selectors.yml`. Also note `value: test` instead of `value: wc`.

### Example

`selectors.yml`
```yaml
selectors:
  - name: views
    definition:
      intersection:
        - method: tag
          value: test
        - method: tag
          value: view
```

```shell
dbt list --selector views
```

**Comment by dbeatty10** [comment]
Glad that everything now works for you @HybridNeos  👍
