### ISSUE TITLE
[ADAP-565] Seed direct dependencies of delta models (from state diff)

### ISSUE THREAD

**Issue by dbrtly** [dbt-labs/dbt-core#7666]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

My boss asked me to investigate if this workflow is possible:

```
delta_nodes = Slim CI changed nodes

sseds = []
for dbt_model in delta_nodes:
    model_deps = get_direct_deps(dbt_model) # how??

for seed in seeds:
   create_seed_in_test_env(seed)

dbt -x run —select delta_nodes

```

i’m curious whether this is a solved problem. 

### Describe alternatives you've considered

Run thw whole project on every change 

### Who will this benefit?

Cli users who use slim ci

### Are you interested in contributing this feature?

I suspect this one is too hard for me

**Comment by dbrtly** [comment]
Thinking about it more, I expect that you're gonna tell me to use a paid subscription to dbt cloud to access the Metadata API. That seems like it's in your best interests. Is that right?

**Comment by dbeatty10** [comment]
I'd empower you with knowledge about the Metadata API if that were the best way to solve the problem, but I'm not sure if that's the case here or not. I wasn't fully understanding some key details in your original, so that's why I asked for clarification.

For feature requests like this, we just try to understand the problem you're trying to solve and then determine if it's in the scope of dbt-core or not. Sometimes the request is already possible in dbt-core. Other times it's out of scope. And plenty often we accept the idea and give guidance on how we'd want to see it implemented.

**Comment by dbrtly** [comment]
I found the deferrals feature. 
It looks very similar to what I'm looking for.
