### ISSUE TITLE
[CT-2615] [Bug] Proper Jinja results in a compiler error due to dbt-core's own macro parsing

### ISSUE THREAD

**Issue by wircho** [dbt-labs/dbt-core#7746]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The following code is perfectly correct Jinja. Yet it results in a compilation error if it appears within a macro file (place it at the end of a macro file, or at the end of a macro's code):
```jinja
{{ [{'a': {}}, '{% b'] }}
```
This is the compilation error that occurs when running `dbt parse`.
```bash
16:39:59  Encountered an error:
Compilation Error
  unexpected EOF, expected string, got "'] }}"
```
For contrast, these two examples below do **not** produce a compilation error:
```jinja
{{ [{'a': {} }, '{% b'] }}
```
```jinja
{{ [{'a': {}}, 'b'] }}
```

### Expected Behavior

Writing a macro that contains the Jinja tag `{{ [{'a': {}}, '{% b'] }}` should not result in a dbt compilation error when running `dbt parse`.

### Steps To Reproduce

1. In any dbt 1.5.1 project.
2. Add a new macro (at the end of an existing macro file, or in a new file):
  ```jinja
  {% macro my_macro() %}
    {{ [{'a': {}}, '{% b'] }}
  {% endmacro %}
  ```
3. Run `dbt parse`

### Relevant log output

```shell
16:39:59  Encountered an error:
Compilation Error
  unexpected EOF, expected string, got "'] }}"
```

### Environment

```markdown
- OS: macOS Ventura 13.3.1
- Python: 3.9.10
- dbt: 1.5.1
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

I believe I have found the source of this issue. The `handle_expr` function below, used by dbt's macro parsing (for manifest generation) makes an assumption that _only strings within macros can get in the way of finding the closing `}}`_. However, my example is evidence that perfectly good Jinja can also get in the way.

https://github.com/dbt-labs/dbt-core/blob/45d614533f0c7de81e20488c75c707262c9312e1/core/dbt/clients/_jinja_blocks.py#L153-L177

As a result of this assumption, the block is assumed to end at the first `}}`, and the subsequent `{%` (which is a harmless string) is assumed to be the beginning of a new block.

A robust solution to this is not straightforward. _Parsing_ is a hard problem. Perhaps the best way to go is to somehow leverage the `jinja2` package for _all_ parsing, rather than trying to perform parsing in house.

**Comment by dbeatty10** [comment]
Thanks for reporting this @wircho.

I was able to reproduce this using the steps you described.

Is there a workaround that worked consistently for you?

**Comment by wircho** [comment]
Thanks for the reply @dbeatty10. The workaround is essentially to prevent the code `}}` from appearing in your macros (other than to close tags or within strings).

In every scenario I can think of, one can simply separate these curly brackets with a space: `} }`

I would say this is indeed a workaround that works consistently 🙂

**Comment by dbeatty10** [comment]
@wircho Thanks again for reporting this and providing nice examples of what will trigger this error and what doesn't.

You did a nice job of showing that to trigger this, the conditions have to be _juuuust_ right (er, I should say "just wrong" 😅). These conditions are rare enough that you might be the first to run into it.

As you already figured out, the root cause is that the dbt parsing logic for macros assumes that _only_ strings within macros can prevent being able to find the closing `}}`. However, there is non-string Jinja that can contain non-closing `}}` as well. One example is a double-nested Jinja dictionary (like in your elegant example reprinted below), and there might be others as well.

```sql
{% macro my_macro() %}
  {{ [{'a': {}}, '{% b'] }}
{% endmacro %}
```

Until we can prioritize a solution, I agree with your work around of separating any relevant `}}` with a space instead: `} }`.
