### ISSUE TITLE
[CT-2620] [Feature] Run single dbt model without full parse

### ISSUE THREAD

**Issue by jlaneve** [dbt-labs/dbt-core#7751]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When running `dbt run --model my_model`, before anything's actually executed, dbt does a full project parse. This can be frustrating, because as your project grows larger, it adds more overhead. This was previously brought up, and after the following response from dbt there was no further discussion (the issue was marked stale):

> I think this issue is a really good candidate and I'd be excited to ship something that addresses this use case

https://github.com/dbt-labs/dbt-core/issues/2257

### Anything else?

Might be related to:
- https://github.com/dbt-labs/dbt-core/issues/2257
- https://github.com/dbt-labs/dbt-core/issues/4597
- https://github.com/dbt-labs/dbt-core/issues/2681

**Comment by jtcohen6** [comment]
@jlaneve Thanks for opening - I appreciate that it's frustrating to wait for dbt to do a lot, when it feels like you're only asking it to do a little.

Before dbt can enter "runtime," it needs a thorough understanding of the objects in your project. It needs to have constructed a DAG (from inferring dependencies), to have determined which models are enabled/disabled, and to have resolved all other configurations as well (in order to support `config:`-based selection). That means fully parsing your project.

We've done a lot of work over the past few years to speed up parsing, and to support ["partial" parsing](https://docs.getdbt.com/reference/global-configs/parsing#partial-parsing) in subsequent invocations—so if you've only changed one model file, dbt only needs to re-parse (update its understanding) of that one model.

At the same time: I agree that dbt parsing still isn't as fast as it should be, or as we ultimately want it to be. We will keep making incremental improvements (v1.6 will include a potential ~10% speedup: https://github.com/dbt-labs/dbt-core/pull/7451).

In the meantime, a couple of questions:
- How large is your project these days? Which steps are slowest? You can run `dbt parse` and examine `target/perf_info.json` to see a detailed breakdown. I recommend doing it for both a "full" parse (`--no-partial-parse) and a "partial" one (default, `--partial-parse`).
- As the number of models in your project increases, are there are also more people/teams collaborating on the same codebase? Do you see any opportunities for splitting up your project into multiple, with well-defined interfaces between each domain/team? It's not a pattern that will make sense for everyone, but it's something we're hearing about a _lot_, and have made it a principal focus for our team this year: #6725
- Finally: The more real-world projects we can see, the better we can determine where the real-world bottlenecks are. If you'd be willing to share an (anonymized) version of your project with us, we can at least take a look.
