### ISSUE TITLE
[CT-2627] [Bug] --warn-error-options doesn't support configuration of turning test warnings into failures

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-core#7761]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I [wrote about using the warn-error-options](https://www.linkedin.com/posts/joel-labes_dbt-analyticsengineering-cicd-activity-7068772846071656448-Pzrp) functionality on LI, and @epapineau asked to work with me to implement it in the internal analytics project. 

After we got it working, we realised we might have to exclude tests with a warn severity as well as "nothing to do", and went poking around in `types.py` where we found [LogTestResult](https://github.com/dbt-labs/dbt-core/blob/7a06d354aa90dce0e2f5196c0dd49a115d7ff621/core/dbt/events/types.py#L1511-L1536) (we assume that's the right one!)

Because it extends `DynamicLevel` instead of `WarnLevel`, nothing happened when we included it in the dictionary of include/excludes. However, `dbt build --warn-error` _would_ create an error from a warn-level test (or freshness check etc). 

`dbt test --warn-error-options {"include": "all"}` and `dbt test --warn-error` should be identical, right? 

This happens to be convenient bug for us, because we didn't want to include them anyway and were trying to add them to the exclude-list, but a bug nonetheless. 

### Expected Behavior

`dbt test --warn-error-options {"include": "all"}` and `dbt test --warn-error` to be identical

### Steps To Reproduce

Make a singular test: 
```
{{ config(warn_if = '>0', error_if ="> 10") }}

select 1 as issue
```

Run `dbt --warn-error-options '{"include":"all"}' test -s single_line`
and `dbt --warn-error test -s single_line `

### Relevant log output

```shell
(dbt-prod) joel@Joel-Labes joel-sandbox % dbt --warn-error-options '{"include":"all"}' test -s single_line
...
02:00:19  Finished running 1 test in 0 hours 0 minutes and 5.12 seconds (5.12s).
02:00:19  
02:00:19  Completed with 1 warning:
02:00:19  
02:00:19  Warning in test single_line (tests/single_line.sql)
02:00:19  Got 1 result, configured to warn if >0
02:00:19  
02:00:19  Done. PASS=0 WARN=1 ERROR=0 SKIP=0 TOTAL=1


(dbt-prod) joel@Joel-Labes joel-sandbox % dbt --warn-error test -s single_line 
...
02:00:40  Finished running 1 test in 0 hours 0 minutes and 5.06 seconds (5.06s).
02:00:40  
02:00:40  Completed with 1 error and 0 warnings:
02:00:40  
02:00:40  Failure in test single_line (tests/single_line.sql)
02:00:40    Got 1 result, configured to fail if >0
02:00:40  
02:00:40  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Environment

```markdown
- OS: Mac
- Python: 3.8.10
- dbt: 1.5.0
```

**Comment by dbeatty10** [comment]
Thanks for discovering and raising this @joellabes and @epapineau 🤩

I was able to reproduce what you reported ✅ 

### Root cause
I suspect it might be the difference between the logic in the [test task](https://github.com/dbt-labs/dbt-core/blob/2d237828ae2a94f39e3ce8e4680a84ac22b6ead4/core/dbt/task/test.py#L159C1-L166) and [warn_or_error](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/events/functions.py#L235-L244).

### Potential solution

Not the most elegant solution (and completely untested!), but updating this:
https://github.com/dbt-labs/dbt-core/blob/2d237828ae2a94f39e3ce8e4680a84ac22b6ead4/core/dbt/task/test.py#L160

to this _might_ do the trick 🤷:
```python
        if get_flags().WARN_ERROR or get_flags().WARN_ERROR_OPTIONS.includes(type(event).__name__):
```

**Comment by jtcohen6** [comment]
Hmm! Failures in tests and source freshness checks are a bit different from our other warnings-to-exceptions, because dbt handles "error" results gracefully, rather than interrupting its entire process.

As a way for users to configure `--warn-error-options`, `LogTestResult` does seem like the most sensible option here. To Doug's point, we might want to update line 160 to something like:
```python
        if get_flags().WARN_ERROR or get_flags().WARN_ERROR_OPTIONS.includes("LogTestResult"):
```

[That event](https://github.com/dbt-labs/dbt-core/blob/6f51de4cb5ed91125772ceae69acb1c22c00e834/core/dbt/events/types.py#L1524) has a "dynamic" log level, which is set conditionally based on the `status` returned by the `TestStatus`, using the `status_to_level` method. That's another (alternative? additional?) place where we should be elevating the log level from `warn` to `error`. But I'm not sure it makes sense to _actually raise an exception_ there.

https://github.com/dbt-labs/dbt-core/blob/6f51de4cb5ed91125772ceae69acb1c22c00e834/core/dbt/events/types.py#L1551-L1563

**Comment by joellabes** [comment]
Regardless of the answer ☝️, just want to also flag for the sake of completeness that source freshness tests have the same dynamic capabilities, so I expect are covered by the same issue where `--warn-error` doesn't have the same result as `--warn-error-options {"include": "all"}`

**Comment by dbeatty10** [comment]
We are not prioritizing this ourselves right now, but labeling as a `good_first_issue` in case a community member wants to contribute to this.

See implementation hint [here](https://github.com/dbt-labs/dbt-core/issues/7761#issuecomment-1587806609).

**Comment by jx2lee** [comment]
@dbeatty10 could i take this issue?
I've been looking for issue labeled `good_first_issue`, it's so much fun. 🤩

**Comment by dbeatty10** [comment]
That would be awesome @jx2lee 👍
