### ISSUE TITLE
[CT-2631] [Bug] dbt databricks sql ssl error

### ISSUE THREAD

**Issue by amirjalali1** [dbt-labs/dbt-core#7772]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt was unable to connect to the specified database.
The database returned the following error:

  >Runtime Error
  Database Error
    Error during request to server: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:992)

### Expected Behavior

connection should be successfull

### Steps To Reproduce

steps:
1- pip install dbt-databricks
2- dbt init dbtpro
3- dbt debug

### Relevant log output

```shell
Error during request to server: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:992)
```

### Environment

```markdown
- OS: macos
- Python: 3.11
- dbt: dbt-databricks 1.5.2
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @amirjalali1 !

First off, I'm guessing this isn't a bug in dbt and it's something related to your networking instead -- but I could be wrong.

It might also be useful to review the thread in https://github.com/dbt-labs/dbt-core/issues/4909: a user there [reported](https://github.com/dbt-labs/dbt-core/issues/4909#issuecomment-1077859701) that they got this error when they were inside a corporate network with an internal proxy certificate authority (CA) in the certificate chain. You may want to contact your network administrator and see if there's something they can do to help.

At least one user getting a similar error was able to resolve it by setting the `REQUESTS_CA_BUNDLE` environment variable (or `CURL_CA_BUNDLE`) as described in https://github.com/dbt-labs/dbt-core/issues/7427

Side note: I don't think the error message is related to https://github.com/dbt-labs/dbt-core/issues/7153 since that one only appears to affect Windows users.

Could you try the network-related troubleshooting above and let us know if you still think it's a bug on the dbt side of things rather than a network-related issue?

**Comment by amirjalali1** [comment]
You are right on that @dbeatty10 it is not a dbt bug and the workaround for me was the following two commands

    pip install certify 

    /Applications/Python\ 3.11/Install\ Certificates.command
