### ISSUE TITLE
[CT-2667] Review Test Coverage of New Metrics

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-core#7821]
During initial implementation of our new Metric objects, we were moving quickly and did not add as much testing as is needed to fully verify functionality and prevent regressions. Let's use this issue to do that.

**Comment by QMalcolm** [comment]
The coverage of metrics is looking pretty good. This is mostly due to the fact that metrics node already existed, and thus many tests existed. We even enabled some tests that were previously `@pytest.mark.skip`-ed. Currently we have 19 active tests and 2 skipped under `/tests/functional/metrics`. We have another 17 tests which test the interactions of metrics with other nodes. However, there are some low hanging improvements we can make.

- Enable [test_expression_metric](https://github.com/dbt-labs/dbt-core/blob/867534c1f49a3daccd6aae83dd32772173479f9d/tests/functional/metrics/test_metric_helper_functions.py#L20) (and rename to `test_derived_metric`)
- Enable [test_metric_deferral](https://github.com/dbt-labs/dbt-core/blob/867534c1f49a3daccd6aae83dd32772173479f9d/tests/functional/metrics/test_metric_deferral.py#L63)
- Add more tests to [test_semantic_layer_nodes_satisfy_protocols.py](https://github.com/dbt-labs/dbt-core/blob/main/tests/unit/test_semantic_layer_nodes_satisfy_protocols.py) for more sub protocols of Metric protocol
  - `MetricTimeWindow`
  - I thought there would be more we weren't testing, but nope, just the one

**Comment by QMalcolm** [comment]
I've created #8134, #8135, and #8136 as follow on issues attached to the [SemanticLayer 1.7 Epic](https://github.com/dbt-labs/dbt-core/issues/8125)
