### ISSUE TITLE
[CT-2691] Populate MetricNode `depends_on`

### ISSUE THREAD

**Issue by QMalcolm** [dbt-labs/dbt-core#7854]

**Comment by jtcohen6** [comment]
@QMalcolm Am I right in thinking that this would require dbt to traverse `metric` &rarr; `measure` &rarr; `semantic_model`, so that we can record SemMod unique IDs in the metric's `depends_on.nodes`?

I think this would be a prerequisite for DAG relationships to work:
- `dbt list -s my_semantic_model+` to include metrics
- DAG visualization in `dbt-docs` (https://github.com/dbt-labs/dbt-docs/issues/431)

**Comment by QMalcolm** [comment]
I chatted with @jtcohen6 earlier. There are three-ish places that metrics need to source the nodes for it's `depends_on` attribute

1. `Metric.type_params.input_metrics` for `RATIO` and `DERIVED` type metrics
2. `Metric.type_params.measure` for `SIMPLE` and `CUMULATIVE` type metrics
3.  From filters
  a. `Metric.filter`
  b. `Metric.type_params.measure.filter`
  c. `Metric.type_params.input_metrics[x].filter`

The work for 1 and 2 exist currently on #8015.

Number 3 is a bit harder though. This is because
A. The spec for filters actually isn't finalized yet. The MetricFlow team is working on support for dunders
B. Which semantic model a dimension comes from in a filter is determined at query time (because a dimension can exist on multiple semantic models and the optimal join path is calculated).

Thus this issue is just to resolve 1 & 2, whereas 3 will be pushed off and become a separate core ticket/issue
