### ISSUE TITLE
[CT-2754] [Bug] <inconsistent behavior when compiling macros>

### ISSUE THREAD

**Issue by noam-co** [dbt-labs/dbt-core#7974]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am running a complex flow that is using a deduplication macro.
I am checking whether a `minus` operation is making sense and really reduces all identifiers from 2 tables.
```
with cte as (
    select distinct id_col from table_a
    minus 
    select distinct id_col from table_b)
select count(*) from table_b where id_col in (select * from cte)
```
This query is returning a list of values while I would expect it to have 0 output.

When I ran the code from the compiled macro instead of `table_b`, I did get 0 output. The macro is consistently compiled to the same code. Hence, I suspect that the issue is in the macro compilation error.

Macro's details:
the macro has only 1 left join int_ended_subs_account_for_merge.account_id IS not NULL, and regexp_replace (which is not used for filtering).

Is this a common and known issue? 

### Expected Behavior

return 0  when 
```
with cte as (
      select distinct id_col from table_a
      minus 
      select distinct id_col from table_b)
select count(*) from table_b where id_col in (select * from cte)
```

### Steps To Reproduce

I need to generate data, hard to reproduce.

### Environment

```markdown
- OS: MacOS Ventura 13.2.1
- Python: 3.9.13
- dbt: dbt-core version = "1.5.1"
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thank you for reaching out @noam-co !

It sounds like you are using your own custom deduplication macro (rather than using one from a dbt package like [dbt_utils.deduplicate](https://github.com/dbt-labs/dbt-utils#deduplicate-source)). It also sounds like you are seeing more rows than you expected rather than seeing an error raised by dbt.

If so, what makes you suspect this is a bug in dbt-core rather than a bug in the deduplication logic that you are using in your macro?
