### ISSUE TITLE
[CT-2777] [Bug] `--warn-error-options` not working as expected with `"exclude":["NoNodesForSelectionCriteria"]` 

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-core#8011]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

This doesn't work as expected:
```shell
dbt --warn-error-options '{"include": "all", "exclude":["NoNodesForSelectionCriteria"]}' run --select nonexistent
echo $?
```

But these both do:

```shell
dbt --warn-error-options '{"include": "all", "exclude":["NoNodesForSelectionCriteria", "NothingToDo"]}' run --select nonexistent
echo $?
```

```shell
dbt --warn-error-options '{"include": "all", "exclude":["NothingToDo", "NoNodesForSelectionCriteria"]}' run --select nonexistent
echo $?
```

### Expected Behavior

Expected this to be `0` (instead of `2`) when excluding "NoNodesForSelectionCriteria":
```shell
echo $?
```

### Steps To Reproduce

Run the commands above with any dbt-core>=1.4 that does not have a model named `nonexistent`.

### Environment

```markdown
- OS:
- Python:
- dbt: 1.5.0
```

**Comment by jtcohen6** [comment]
Ultimately the thing at play here is that both `NoNodesForSelectionCriteria` and `NothingToDo` are warn-level, and both are logged in the case where:
- at least one selection criterion is invalid / does not select any nodes
- there are no selected nodes

Should these just be combined into a single event? (Putting aside that the removal of an event is probably a breaking change to the logging interface.)

Well, it is possible to have only `NoNodesForSelectionCriteria` without `NothingToDo`, as in the case of:

```
dbt --warn-error-options '{"include": "all", "exclude":["NoNodesForSelectionCriteria"]}' run --select extant_model nonexistent_model
echo $?
```
= 0
```
dbt --warn-error-options '{"include": "all", "exclude":["NothingToDo"]}' run --select extant_model nonexistent_model
echo $?
```
= 2

`nonexistent_model` does raise `NoNodesForSelectionCriteria`, but because we're also selecting `extant_model`, we do have SomethingToDo
