### ISSUE TITLE
[CT-2800] [Feature] New exit code for successful tests with failing checks

### ISSUE THREAD

**Issue by jennykwan** [dbt-labs/dbt-core#8045]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I'd like the CLI commands `dbt test` and `dbt build` to return a new exit code (3?) when the test command completes successfully but with failing checks.

The rationale is for orchestration platforms such as Airflow which can be configured to retry in the face of transient errors. If checks fail, they will continue to fail unless the models themselves are re-run. In my case, I want check failure to not retry, but to still skip downstream Airflow tasks.

### Describe alternatives you've considered

1. Parsing CLI command `stdout`. This is much more difficult.
2. Parsing the output JSON. Easier, though Airflow limitations which require Xcom make this awkward in Airflow.
3. Using something like `dbt_artifacts` to record check runs and their results in something like a DB, and examining that in a subsequent orchestration task. This feels heavyweight (though in my case, we'll probably end up doing this also).

### Who will this benefit?

Users of automated orchestration platforms.

### Are you interested in contributing this feature?

Yes. Point me at it!

**Comment by jtcohen6** [comment]
Hey @jennykwan! The main way we distinguish between these two cases today is via the test result's `status` field:
- "fail" = this test found failing rows
- "error" = this test encountered an error while running

https://github.com/dbt-labs/dbt-core/blob/5d28e4744e8713fca923c25fbb5a4ef2e83b613a/core/dbt/contracts/results.py#L101-L107

Right now, the three [exit code options](https://docs.getdbt.com/reference/exit-codes) are:
- `0` = the invocation completed & succeeded
- `1` = the invocation completed & failed, because at least one node failed/errored (but the failure/error was handled gracefully)
- `2` = the invocation did not complete (due to an error that could not be handled gracefully)

I'm hesitant to add a new CLI exit code for anything more granular than "the entire invocation did/didn't succeeded." What would you expect to happen in a case where an invocation ran two tests, one that found failing records, and one that encountered an error while running? If the former takes priority, it would be `3` (your proposal); if the latter takes priority, it would be `1` (status quo).

Instead, I'd encourage you to do one of the following:
- parse [structured (JSON-formatted) logs](https://docs.getdbt.com/reference/events-logging#structured-logging) from `dbt-core` while it's running — the [`NodeFinished`](https://github.com/dbt-labs/dbt-core/blob/5d28e4744e8713fca923c25fbb5a4ef2e83b613a/core/dbt/events/types.proto#L1718) event will include each test's `status` right after it finishes running, and [`LogTestResult`](https://github.com/dbt-labs/dbt-core/blob/5d28e4744e8713fca923c25fbb5a4ef2e83b613a/core/dbt/events/types.proto#L1583C9-L1583C22) event will be included in the summary at the end
- parse the results from [`run_results.json`](https://docs.getdbt.com/reference/artifacts/run-results-json) after the invocation completes — or using the `results` as a Python object, returned at the end of a [programmatic invocation](https://docs.getdbt.com/reference/programmatic-invocations#dbtrunnerresult)

I'm going to close this for now, but happy to hear your thoughts on any of the above!
