### ISSUE TITLE
[CT-2817] [Feature] Python Models - MS SQL Server

### ISSUE THREAD

**Issue by Sebowa** [dbt-labs/dbt-core#8075]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Implementation of Python models for Microsoft SQL Server.

### Describe alternatives you've considered

T-SQL but this was not fruitful as the process requires a variable number of passes over a dataset.

Currently attempting to stitch a macro together but it isn't clean nor is success guaranteed.

### Who will this benefit?

Anyone using Microsoft SQL Server looking to perform calculations that are more suited to Python than SQL.

### Are you interested in contributing this feature?

Yes. Not sure where to start.

**Comment by graciegoheen** [comment]
Hello! Thanks for opening :) this issue is actually better suited for the [dbt-sqlserver adapter repo](https://github.com/dbt-msft/dbt-sqlserver). Looks like I can't transfer an issue to a repo owned by another organization, so I would recommend the 'ole copy & paste method to move the issue over there.

We would love to see Microsoft SQL Server support for python models, but dbt is limited to the features available within the data platform itself - so Microsoft would need to first support this service before dbt-sqlserver could implement.
