### ISSUE TITLE
[Bug] `invocation_args_dict.which` contains the subcommand if it exists

### ISSUE THREAD

**Issue by matthieucan** [dbt-labs/dbt-core#8420]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running a dbt command which takes a sub-command, e.g. `dbt docs generate`, `invocation_args_dict.which` contains the sub-command.
In this example, the value will be `generate`, instead of `docs`.

### Expected Behavior

`invocation_args_dict.which == 'docs'` or `invocation_args_dict.which == 'docs.generate'`

### Steps To Reproduce

```shell
echo "-- {{ invocation_args_dict.which }}" >> models/some_model.sql
dbt docs generate
```

The catalog will display `-- generate` in the model.

It can also be reproduced by using `{{ debug() }}` anywhere.

### Environment

```markdown
- Python:3.10.12
- dbt:1.5.4
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment]
@matthieucan Thanks for opening!

Overall, `dbt-core`'s CLI has a very "flat" structure, without many nested commands — it's really just `docs generate`, `docs serve`, and `source freshness` — and there's no risk of ambiguity because `serve`, `generate`, and `freshness` are not top-level subcommands.

If I could snap my fingers, I agree that I'd slightly prefer `docs.generate` — although that would risk being a breaking change for anyone who's come to rely on it being `generate`. Given that consideration, and the fact that I don't see this as a blocker to any workflows in the meantime, I don't see us doing this in the near term.

**Comment by matthieucan** [comment]
Woops, I had missed your reply @jtcohen6. Thanks for the additional details, indeed if there's no risk of collision that works with me! 👍
