### ISSUE TITLE
[CT-3015] [Bug] DBT ls command doesn't accept log-path option

### ISSUE THREAD

**Issue by DanMawdsleyBA** [dbt-labs/dbt-core#8462]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

This links to https://github.com/astronomer/astronomer-cosmos/issues/411 which are fixing a permissions issues where in airflow having read only permissions. To get around this they have implemented a fix to write target and logs to a temporary directory however the `dbt ls` command does not accept either the log-path flag or equivalent environment variable.

### Expected Behavior

Allow `dbt ls` command to use the flag `--log-path` or DBT_LOG_PATH environment variable to set a log path.

### Steps To Reproduce

Run the below command:
`dbt ls --log-path path/to/logs`

### Relevant log output

```shell
dbt ls --log-path value
Usage: dbt ls [OPTIONS]
Try 'dbt ls -h' for help.

Error: No such option: --log-path Did you mean --target-path?
```

### Environment

```markdown
- OS: Windows 10
- Python: 3.10
- dbt: 1.5.5
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

Links to https://github.com/astronomer/astronomer-cosmos/issues/411 and may be a blocker to their fix

**Comment by jtcohen6** [comment]
@DanMawdsleyBA Try putting `--log-path` before the subcommand:
```
dbt --log-path path/to/logs ls
```

This is because `--log-path` is a "global" flag, registered on the `dbt` namespace, rather than each individual subcommand ([docs](https://docs.getdbt.com/reference/global-configs/about-global-configs)).

I agree this is confusing and hard to remember, hence my motivation for supporting these flags in both places:
- https://github.com/dbt-labs/dbt-core/issues/6497#issuecomment-1665363853

In the meantime, I'm going to close this specific issue as resolved
