### ISSUE TITLE
[CT-3035] [Bug] dbt doesn't detect the installed adapter plugins in development mode

### ISSUE THREAD

**Issue by aosingh** [dbt-labs/dbt-core#8504]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`dbt --version` doesn't detect the plugin. This happens only if I install an adapter in editable mode i.e. `make dev` or  `pip install -e .`

```bash
dbt --version
Core:
  - installed: 1.6.0
  - latest:    1.6.0 - Up to date!

Plugins:
```

Consequently, dbt commands in my test project fail saying type of adapter is not found.

```
15:37:41  Connection test skipped since no profile was found
15:37:41  1 check failed:
15:37:41  Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "dbt_test", target "dev" invalid: Runtime Error
    Could not find adapter type oracle!
```

if I build a whl file and install in the development environment, then this works fine
```bash
pip install dist/dbt_oracle-1.6.0-py3-none-any.whl 

```

```
dbt --version
dbt --version         
15:41:51  oracle adapter: Running in thin mode
Core:
  - installed: 1.6.1
  - latest:    1.6.1 - Up to date!

Plugins:
  - oracle: 1.6.0 - Ahead of latest version!


```

### Expected Behavior

dbt should detect all installed plugins in development mode i.e. either using `make dev` or `pip install -e .`

### Steps To Reproduce

1. git clone https://github.com/dbt-labs/dbt-snowflake.git
2. cd dbt-snowflake/
3. make dev
4. dbt --version

### Environment

```markdown
- OS: MacOS, Linux
- Python: 3.8, 3.9, 3.10
- dbt: 1.6.1
```

**Comment by dbeatty10** [comment]
Thanks for raising this @aosingh !

### Workaround
Here's a workaround:
👉 do the editable portion of the install **twice**\*

\* or at least separately from `dev-requirements.txt`

Could you give the following a shot and see if it works for you?

### Example

Assuming you have a `dbt_project.yml` file in your current working directory that is using a `profile` for dbt-snowflake, here's an example:

```shell
git clone https://github.com/dbt-labs/dbt-snowflake.git dbt-snowflake-main
(cd dbt-snowflake-main && git checkout main)
(cd dbt-snowflake-main && git branch)
```

```shell
python3 -m venv snowflake_editable_main
source snowflake_editable_main/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install -e dbt-snowflake-main -r dbt-snowflake-main/dev-requirements.txt
python3 -m pip install -e dbt-snowflake-main
source snowflake_editable_main/bin/activate
dbt --version
dbt debug
deactivate
```

:warning: Note that `pip install -e dbt-snowflake-main` is duplicated twice! The 2nd one is the key one in relation to the issue you are reporting. The 1st one is to avoid dependency conflicts with the way pip's dependency resolver works.

A minority of people also need to reactivate their environment after an install via pip, which is why `source snowflake_editable_main/bin/activate` is duplicated as well.

### More info

I don't know exactly why the editable portion of the install needs to be done separately from the non-editable portion. But we can see that analogous two-step installs is how the CI is being set up for these dbt adapters:
- [dbt-postgres](https://github.com/dbt-labs/dbt-core/blob/48d04e81417195393af5af1f78ef695f3398f193/tox.ini#L15-L16)
- [dbt-bigquery](https://github.com/dbt-labs/dbt-bigquery/blob/d7fb235a42780841c82ea5b01a647b3416070afe/tox.ini#L13-L14)
- [dbt-redshift](https://github.com/dbt-labs/dbt-redshift/blob/e5bfa3bc433f658daa23f669bf58c4dbbea9ab64/tox.ini#L13-L14)
- [dbt-snowflake](https://github.com/dbt-labs/dbt-snowflake/blob/8d5fca9d8d17b0e352590020c3c4c9bdbabf8643/tox.ini#L13-L14)
- [dbt-spark](https://github.com/dbt-labs/dbt-spark/blob/91f98879b9de863f9c6eb20fd0a752f7a859d5b3/tox.ini#L13-L14)

Also, I think the fact that `dbt --version` doesn't list editable plugins is a red herring here. But it would be nice if it did show up in the list!

### Next steps

In the meantime, I think we should update each of the `CONTRIBUTING.md` files accordingly (like [here](https://github.com/dbt-labs/dbt-snowflake/blob/e72e8f1fd569a40cd3ffabcdcd3968f3bd0d8acc/CONTRIBUTING.md?plain=1#L56)).

**Comment by aosingh** [comment]
Thanks @dbeatty10 

I tried installing it twice:

```
pip install -e .
pip install -e .
```

`dbt --version` still fails to detect the plugin

```
Core:
  - installed: 1.6.1
  - latest:    1.6.1 - Up to date!

Plugins:



```

**Comment by jtcohen6** [comment]
The reason this doesn't work: `dbt --version` doesn't _actually_ load & register adapters, in the way that "real" dbt commands do. Instead, we use `importlib` to tell us where the adapters _ought_ to be, based on where `dbt-core` is installed for the current Python environment:

https://github.com/dbt-labs/dbt-core/blob/7ae3de1fa011b231b397073bac7dadb67a56ed87/core/dbt/version.py#L218-L219

Then, we traverse through that file directory to find instances of `adapters/*/__version__.py`, and use that to report the versions of installed adapters.

The problem is that, in an editable install, the files are not colocated — they can be all over the place.

Normal install (in a virtual environment):
```
>>> import importlib.util
>>> importlib.util.find_spec("dbt.adapters").submodule_search_locations
['/Users/jerco/dev/scratch/testy/env/lib/python3.10/site-packages/dbt/adapters']
>>> importlib.util.find_spec("dbt.adapters.postgres").submodule_search_locations
['/Users/jerco/dev/scratch/testy/env/lib/python3.10/site-packages/dbt/adapters/postgres']
>>> importlib.util.find_spec("dbt.adapters.snowflake").submodule_search_locations
['/Users/jerco/dev/scratch/testy/env/lib/python3.10/site-packages/dbt/adapters/snowflake']
```

Editable install:
```
>>> import importlib.util
>>> importlib.util.find_spec("dbt.adapters").submodule_search_locations
['/Users/jerco/dev/product/dbt-core/core/dbt/adapters']
>>> importlib.util.find_spec("dbt.adapters.postgres").submodule_search_locations
['/Users/jerco/dev/product/dbt-core/plugins/postgres/dbt/adapters/postgres']
>>> importlib.util.find_spec("dbt.adapters.snowflake").submodule_search_locations
['/Users/jerco/dev/product/plugins/snowflake/dbt-snowflake/dbt/adapters/snowflake']
```

I don't think this is high priority for us to fix — the only folks who tend to do editable installs are developers / contributors to `dbt-core` or adapter plugins. I agree that an update to `CONTRIBUTING.md` in the meantime is a good idea.

**Comment by aosingh** [comment]
Thanks @jtcohen6 for the explanation. 

I raised this bug because plugin detection in editable mode worked before I started working on release v1.6.0. I maintain dbt-oracle and currently I am working on the release 1.6. It just takes multiple cycles for me to validate my changes against my test project. I have to build a whl file and install it every time in the virtual environment. 

Somehow, the following works after an editable install: 

```python
from dbt.version import get_version_information
print(get_version_information())
```

```
Core:
  - installed: 1.6.1
  - latest:    1.6.1 - Up to date!

Plugins:
  - oracle: 1.6.0 - Ahead of latest version!
```
