### ISSUE TITLE
[CT-3064] [Feature] Allow comments in jinja directives

### ISSUE THREAD

**Issue by RoyalTS** [dbt-labs/dbt-core#8528]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I find myself writing code like this:

```sql
  , {{
    dbt_utils.star(
      from=ref('fees'),
      except=[
        'immutable_fee_id',
        'date_local',
        'deliveries'
      ],
      relation_alias='f',
      quote_identifiers=False
    )
  }}
```

and find myself wanting to document why certain columns were excluded there. Alas, it does not appear possible to add comments inside jinja2 directives currently.

jinja2 apparently [allows for the presence of comments in directives if one declares what such comments should look like in the jinja2 Environment](https://stackoverflow.com/a/32917353). Would it be possible to e.g. add the standard Python comment string `#` to the environment dbt uses so we can use comments in directives?

**Comment by jtcohen6** [comment]
@RoyalTS This is a really cool idea!!

https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment

The place to turn this on inside dbt-core would be [here](https://github.com/dbt-labs/dbt-core/blob/7ae3de1fa011b231b397073bac7dadb67a56ed87/core/dbt/clients/jinja.py#L485-L487).

However, I haven't quite been able to get this working in local testing, even just using Jinja (not dbt):
```python
>>> import jinja2
>>> env = jinja2.Environment()
>>> env.parse("string")
Template(body=[Output(nodes=[TemplateData(data='string')])])
>>> env.parse("{% set some_value = 123 %} # comment")
Template(body=[Assign(target=Name(name='some_value', ctx='store'), node=Const(value=123)), Output(nodes=[TemplateData(data=' # comment')])])
>>> env.line_comment_prefix = "#"
>>> env.line_comment_prefix
'#'
>>> env.parse("{% set some_value = 123 %} # comment")
Template(body=[Assign(target=Name(name='some_value', ctx='store'), node=Const(value=123))])
>>> env.parse("{% set some_value = # comment \n 123 %}")
...
jinja2.exceptions.TemplateSyntaxError: unexpected char '#' at 20
```

Basically, while `line_comment_prefix` works for ignoring comments _after_ Jinja statements:
```sql
{% set some_value = 123 %} # this is a comment, Jinja will ignore it
{{ some_macro(...) }}.  # another comment
```
Jinja doesn't seem to support nesting comments _within_ statements:
```
{% set some_value = [
    1, # comment
    2, # comment
    3 # comment
] %}
{{ some_macro(
    arg1 = 'blue', #comment
    ...
) }}
```

So this is (I think) really just syntactic sugar on top of `{# #}`, rather than the more-compelling capability I was hoping it might be.

**Comment by RoyalTS** [comment]
Ah, such a shame! Thanks for looking into this though!

**Comment by jtcohen6** [comment]
Going to close - happy to reopen if someone finds that Jinja can support the thing we really want :)
