### ISSUE TITLE
[CT-3069] [Feature] Support S3 as dbt package source

### ISSUE THREAD

**Issue by kovaacs** [dbt-labs/dbt-core#8542]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We'd like to explore hosting dbt package tarballs on S3 instead of using local storage or HTTPS. Our build pipeline needs to access these tarballs on S3. However, configuring the HTTPS option isn't straightforward due to our strict network setup limitations.

### Describe alternatives you've considered

- Git: Each package must undergo a release approval process, meaning we can't simply grab the latest version; we need to use the most recent approved version. These approved packages are hosted on S3.

- HTTPS: While there is a method to access S3 objects via HTTPS, our internal configuration is highly restricted. We have S3 access configured, but HTTPS isn't set up due to these constraints.

- Local: Currently, our process involves downloading from S3 and treating the package as if it were local. However, this approach has proven to be cumbersome.

### Who will this benefit?

Organizations with a highly constrained setup that rely on S3 for their internal storage.

### Are you interested in contributing this feature?

Yes - I would only need some pointers

**Comment by pscanlon1** [comment]
I just used the athena connector to use s3 as the datasource, it was a little wonky to setup on AWS but once i figured out how to make tables for Athena from S3 it is pretty easy!

**Comment by jtcohen6** [comment]
@kovaacs To make sure I understand - you aren't able to use the existing `tarball` support for `dbt deps`:

https://docs.getdbt.com/docs/build/packages#internally-hosted-tarball-URL

Because [dbt is still requesting the contents over HTTPS](https://github.com/dbt-labs/dbt-core/blob/b39eeb328c9a245f21b54fb48f2761ad03d4d6ad/core/dbt/clients/system.py#L476), and you need to auth/request the contents via S3 natively instead. Is that right?

I don't think this is something we're likely to support within `dbt-core`. (If we set the precedent of supporting S3, there's no good reason to not also support GCS, Azure Blob, ... — and each would require the addition of heavyweight dependencies.)

Within your build pipeline, could you simply use a separate CLI tool / API call to copy down the files from S3 first? Then, dbt could reference those copied-down files as `local` packages.

---

@pscanlon1 I agree that many DWHs (and therefore dbt adapters) can already interact quite effectively with S3 as a data source! The ask in this issue is to access _dbt project/package source code_ from S3, rather than ingesting data into (e.g.) dbt `sources`.
