### ISSUE TITLE
[CT-3073] [Bug] semantic model doesn't work in the "plus" node selection

### ISSUE THREAD

**Issue by popcornylu** [dbt-labs/dbt-core#8546]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

```
dbt list -s 'stg_products+' 
```
does not include any metrics

### Expected Behavior

```
dbt list -s 'stg_products+' 
```
should include all metrics

### Steps To Reproduce

1. Clone the metric example project https://github.com/dbt-labs/jaffle-sl-template
2. The lineage graph is as follow
    ![image](https://github.com/dbt-labs/dbt-core/assets/860633/332e288c-41ad-4fb1-8b99-fada42b540a0)
3. Run `dbt list -s 'stg_products+'`, and no metrics are not in the list (error)
4. Run `dbt list -s 'metric:jaffle_shop.revenue+'` we can see four metrics (correct)

It seems the semantic models are not considered in the plus operator

### Relevant log output

```shell
$ dbt list -s 'stg_products+'
06:06:02  Running with dbt=1.6.1
06:06:02  Registered adapter: duckdb=1.6.0
06:06:02  Found 10 models, 6 seeds, 18 tests, 6 sources, 0 exposures, 14 metrics, 563 macros, 0 groups, 5 semantic models
jaffle_shop.marts.customers
jaffle_shop.marts.order_items
jaffle_shop.marts.orders
jaffle_shop.staging.stg_products
jaffle_shop.marts.accepted_values_customers_customer_type__new__returning
jaffle_shop.marts.not_null_customers_customer_id
jaffle_shop.marts.not_null_orders_order_id
jaffle_shop.staging.not_null_stg_products_product_id
jaffle_shop.marts.relationships_orders_customer_id__customer_id__ref_stg_customers_
jaffle_shop.marts.unique_customers_customer_id
jaffle_shop.marts.unique_orders_order_id
```

### Environment

```markdown
- OS:MacOS 13.2.1
- Python:3.10.11
- dbt: 1.6.1
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

duckdb

**Comment by jtcohen6** [comment]
@popcornylu Thanks for opening! Agree that this is a bug, and not the intended behavior.

I believe the basic problem here is that we're calling `add_node` here, instead of `link_node`:

https://github.com/dbt-labs/dbt-core/blob/7eedfcd2742fcf789200a4b829c8c2eb98369089/core/dbt/compilation.py#L186-L187

We only use `add_node` for `sources`. We use `link_node` for any nodes that can depend on other nodes, including `metrics`.

In addition to fixing the graph compilation, we also need to support semantic models within the output of `dbt list`. I started roughing in what a fix could look like: https://github.com/dbt-labs/dbt-core/commit/025d3dcfc681ac85ad2e5dee7529ccb4671a11d4

Using the changes in that commit:

```
$ dbt list -s stg_products+
09:46:37  Running with dbt=1.7.0-b2
09:46:37  Registered adapter: postgres=1.7.0-b2
09:46:37  Found 10 models, 6 seeds, 18 tests, 6 sources, 0 exposures, 14 metrics, 595 macros, 0 groups, 5 semantic models
metric:jaffle_shop.cumulative_revenue
metric:jaffle_shop.customers_with_orders
metric:jaffle_shop.food_orders
metric:jaffle_shop.food_revenue
metric:jaffle_shop.food_revenue_pct
metric:jaffle_shop.large_order
metric:jaffle_shop.median_revenue
metric:jaffle_shop.new_customer
metric:jaffle_shop.order_cost
metric:jaffle_shop.order_gross_profit
metric:jaffle_shop.order_total
metric:jaffle_shop.orders
metric:jaffle_shop.revenue
metric:jaffle_shop.revenue_growth_mom
jaffle_shop.marts.customers
jaffle_shop.marts.order_items
jaffle_shop.marts.orders
jaffle_shop.staging.stg_products
semantic_model:jaffle_shop.customers
semantic_model:jaffle_shop.order_item
semantic_model:jaffle_shop.orders
semantic_model:jaffle_shop.stg_products
jaffle_shop.marts.accepted_values_customers_customer_type__new__returning
jaffle_shop.marts.not_null_customers_customer_id
jaffle_shop.marts.not_null_orders_order_id
jaffle_shop.staging.not_null_stg_products_product_id
jaffle_shop.marts.relationships_orders_customer_id__customer_id__ref_stg_customers_
jaffle_shop.marts.unique_customers_customer_id
jaffle_shop.marts.unique_orders_order_id
jaffle_shop.staging.unique_stg_products_product_id
```

TODOs:
- Since semantic models can have the same name as models (e.g. `jaffle_shop.staging.stg_products`), we need a way to visually distinguish them in the default `list` output.
- We should also probably support a `semantic_model:{name}` selection syntax, similar to what we support for `source:`, `exposure:`, and `metric:`. I'd love to see us generalize this to just `{resource_type}:{fully_qualified_name}`, and then _every_ resource output by `dbt list` would include its resource type. I don't see why we couldn't do that!
