### ISSUE TITLE
[CT-3075] [Bug] private access property restricts exposure read

### ISSUE THREAD

**Issue by piotrs-ae** [dbt-labs/dbt-core#8550]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I set up groups and private access to my models. I then try to reference said models in an exposure and I get an error. There seems not to be any way to include exposure in the same group so it can have read access on the private models.

### Expected Behavior

Allow exposure to have a group property such that it can read from within the group with specified private access.

### Steps To Reproduce

1. dbt-snowflake adapter, dbt v1.6
2. Create a new group
3. Assign a model to said group and set access property to private
4. Create new exposure
5. Reference said model in exposure
6. Run dbt docs generate

### Environment

```markdown
- OS:
- Python:
- dbt: 1.6.0
```

### Which database adapter are you using with dbt?

snowflake

**Comment by jtcohen6** [comment]
@piotrs-ae Thanks for opening! I'm not going to call this a bug - it was an intentional choice!

If you're **exposing** a model outside dbt, it is (by definition) not private to a group of resources **within** dbt. If anything, that model might want to have `access: public` and [an enforced contract](https://docs.getdbt.com/docs/collaborate/govern/model-contracts).

Could you say more about your specific use case? What's motivating you to define a private model, and still feed it into an exposure?

See some of the related conversation in:
- https://github.com/dbt-labs/dbt-core/issues/8343
- https://github.com/dbt-labs/dbt-core/issues/7750

**Comment by jtcohen6** [comment]
Per https://github.com/dbt-labs/dbt-core/issues/7750#issuecomment-1730166771, this is now within the scope of https://github.com/dbt-labs/dbt-core/issues/7750, for consistency across node types. We still wouldn't recommend it :)
