### ISSUE TITLE
[CT-3125] [Bug] Exposure is green after model error

### ISSUE THREAD

**Issue by fdawans** [dbt-labs/dbt-core#8659]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After having skipped and/or errored models, the exposure is OK/green in Looker.

### Expected Behavior

I think that on top of source freshness and tests, exposures should also show an error if models are not able to be run as expected.

### Steps To Reproduce

- Add an exposure based on a model
- Run that model (with an error somewhere)
- Exposure is green/OK in Looker

### Environment

```markdown
- OS: MacOS Monterey
- Python: 3.7 (not sure?)
- dbt: 1.4
```

### Which database adapter are you using with dbt?

bigquery

**Comment by dbeatty10** [comment]
Thanks for reaching out @fdawans.

Is there something that you think dbt-core is doing wrong here?

e.g., is there anything that dbt-core can do to affect the green/OK you are seeing in Looker? The more details you can offer, the better.

**Comment by fdawans** [comment]
I don't know how I can help debug further.
I am not sure if it's a bug - maybe it's a missing feature.

From the documentation:
- The data freshness check fails if any sources feeding into the exposure are stale. > my sources are OK > no failure
- The data quality check fails if any dbt tests fail. > my tests are OK or skipped > no failure
https://docs.getdbt.com/docs/deploy/dashboard-status-tiles

**Comment by dbeatty10** [comment]
Ah, thanks for that link to the [Dashboard status tiles](https://docs.getdbt.com/docs/deploy/dashboard-status-tiles)!

This sounds like a feature request or bug report related to the dbt Cloud web interface, so it's not something we can address directly within dbt-core.

Sorry to redirect you to another place, but you'll need to send this to us by using the speech bubble (💬) in the dbt Cloud interface or at [support@getdbt.com](mailto:support@getdbt.com).

If you can provide a simple but detailed example (including example code for your source, exposure, and anything relevant in-between) that will help assess if it's a bug or a feature request.

In the meantime, I'm going to close this issue within the dbt-core repo since we can't address it here.
