### ISSUE TITLE
[CT-3169] [Bug] .yaml prefix not recognized for `packages.yml`

### ISSUE THREAD

**Issue by andy-clapson** [dbt-labs/dbt-core#8738]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If I create a valid `packages.yaml` in my project directory and run `dbt deps`, it fails to find any dependencies. If I change the file extension to be `.yml`, things work fine.

### Expected Behavior

I would expect `.yaml` and `.yml` to be interchangeable (and there seems to be an interface to handle both...? Maybe not used in some cases). If not, at least a warning pointing me to the issue.

### Steps To Reproduce

1. Create new project
2. Create/copy `packages.yaml` file
3. run `dbt deps` 

### Relevant log output

```shell
{"data": {"log_version": 3, "version": "=1.4.5"}, "info": {"category": "", "code": "A001", "extra": {}, "invocation_id": "f97fdb3c-61cf-49fb-b595-3dc00faaa631", "level": "info", "msg": "Running with dbt=1.4.5", "name": "MainReportVersion", "pid": 63990, "thread": "MainThread", "ts": "2023-09-28T15:46:04.254826Z"}}
{"data": {}, "info": {"category": "", "code": "M013", "extra": {}, "invocation_id": "f97fdb3c-61cf-49fb-b595-3dc00faaa631", "level": "info", "msg": "Warning: No packages were found in packages.yml", "name": "DepsNoPackagesFound", "pid": 63990, "thread": "MainThread", "ts": "2023-09-28T15:46:04.277178Z"}}
```

### Environment

```markdown
- OS: MacOS 12.7
- Python: 3.10
- dbt: 1.4.5
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
Thanks for reaching out @andy-clapson !

Totally reasonable to expect that `.yml` and `.yaml` would be interchangable (especially since the YAML folks [recommend the `.yaml` extension](https://yaml.org/faq.html)).

This is covered by https://github.com/dbt-labs/dbt-core/issues/5002, so I'm going to close this as a duplicate.

If anyone is interested in tackling this effort, there's some guidance here (that covers all of "profiles.yml", "dbt_project.yml", "selectors.yml", "packages.yml"): https://github.com/dbt-labs/dbt-core/issues/5002#issuecomment-1095183224

i.e., the end goal is that all of these would be interchangeable:

| | |
|-----------------|------------------|
| profiles.yml    | profiles.yaml    |
| dbt_project.yml | dbt_project.yaml |
| selectors.yml   | selectors.yaml   |
| packages.yml    | packages.yaml    |

**Comment by andy-clapson** [comment]
> Thanks for reaching out @andy-clapson !
> 
> Totally reasonable to expect that `.yml` and `.yaml` would be interchangable (especially since the YAML folks [recommend the `.yaml` extension](https://yaml.org/faq.html)).
> 
> This is covered by #5002, so I'm going to close this as a duplicate.
> 
> If anyone is interested in tackling this effort, there's some guidance here (that covers all of "profiles.yml", "dbt_project.yml", "selectors.yml", "packages.yml"): [#5002 (comment)](https://github.com/dbt-labs/dbt-core/issues/5002#issuecomment-1095183224)
> 
> i.e., the end goal is that all of these would be interchangeable:
> 	
> profiles.yml 	profiles.yaml
> dbt_project.yml 	dbt_project.yaml
> selectors.yml 	selectors.yaml
> packages.yml 	packages.yaml

ah! my searching failed me, but I did try and look for an existing issue - thanks!

**Comment by dbeatty10** [comment]
Sure thing @andy-clapson ! Thanks again for opening this issue 🏆

You nudged us to review #5002, and then we updated the issue title (for better searchability) and re-categorized it as a handy feature request.
