### ISSUE TITLE
[CT-3207] [Bug] Misleading error when dbt cli doesn't find the right target on the profile

### ISSUE THREAD

**Issue by sp35** [dbt-labs/dbt-core#8829]
### Is this a new bug in dbt-core?

- [ ] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm running `dbt build` using dbt cli on my local machine,  using the profile `my_profile`

```yml
# profiles.yml
my_profile:
  outputs:
    dev:
      ***
  target: prod

# dbt_project.yml
profile: 'my_profile'
```

Since the profile only defines the target `prod`, I'm expecting an error if dbt is trying to find the `target: dev`. However the error message that I'm seeing is:
```
The profile 'my_profile' does not have a target named 'prod'. The valid target names for this profile are:
   - dev
```

### Expected Behavior

The error message should instead be:

```
The profile 'my_profile' does not have a target named 'dev'. The valid target names for this profile are:
   - prod
```

### Steps To Reproduce

1. Create a profile with `target: prod`
2. Use the same profile in a dbt project
3. Invoke `dbt build` using dbt cli
4. See the error message in the log

### Environment

```markdown
- OS: macOS Monterey v12.4
- Python: 3.9.13
- dbt: 1.3.0
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

This might have been fixed in the later versions of dbt, I have only tried this on dbt 1.3.0

**Comment by dbeatty10** [comment]
Thanks for reaching out @sp35!

I gave this a look, and it looks like it is behaving correctly to me.

Suppose your project is using these two files:

`dbt_project.yml`
```
profile: 'my_profile'
```

`profiles.yml`
```yaml
my_profile:
  outputs:
    dev:
      ***
  target: prod
```

Then here's what is going on:
1. Your `dbt_project.yml` specifies to use a profile named `my_profile` within `profiles.yml`.
1. Within `my_profile` profile in your `profiles.yml`, `outputs` lists all the valid output targets
1. 👉 You only have one output target defined, and its name is `dev`
1. dbt will try using the default `target` for `my_profile` which is specified to be `prod`
1. 💥 But there is no `target` named `prod`! The only target you have defined is `dev`.

So that's why it gives you this error message:
```
The profile 'my_profile' does not have a target named 'prod'. The valid target names for this profile are:
   - dev
```

You can read more [here](https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml) and [here](https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles).

Since this is behaving as expected, I'm going to close this issue, but let me know if you need any further clarification.
