### ISSUE TITLE
[CT-3219] Add the current DB configured in dbt cloud

### ISSUE THREAD

**Issue by swapnil-bidgely** [dbt-labs/dbt-core#8850]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

On the UI, it would be great if we could have the current DB configured in settings shown in the develop screen, to avoid accidental runs of suppose a PROD_DB instead of DEV_DB. 

![dbt feature](https://github.com/dbt-labs/dbt-core/assets/95356530/0529e427-57d2-4a6b-86ab-f486cfd343f0)

Anywhere at the top of the screen or bottom like we have an indicator of `Ready` 

### Who will this benefit?

The end user developing will know where he is model is running.
because there is no indicator

**Comment by dbeatty10** [comment]
Thanks for sharing this feedback @swapnil-bidgely !

I'm going to close this here since it's not something that can be implemented in the dbt-core GitHub repo, but is something for our dbt Cloud web interface.

Could you submit this within the dbt Cloud interface so that this gets to the right team? Within the dbt Cloud interface, click the "Leave feedback" link:

<img width="350" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/853fee96-60be-4209-b621-5aed42535d5c">

</br>
</br>

Thanks again for taking the time to submit this suggestion, and sorry to need to redirect you!
