### ISSUE TITLE
[CT-3312] Allow declaring groups in dbt_project.yml

### ISSUE THREAD

**Issue by evgeniybobok** [dbt-labs/dbt-core#8983]
Currently, you can only [define new groups](https://docs.getdbt.com/docs/build/groups#declaring-a-group) in separate `.yml` files, not in the `dbt_project.yml`. This can lead to redundancy and confusion about where to create new groups. Additionally, you [can associate](https://docs.getdbt.com/docs/build/groups#adding-a-model-to-a-group) a model or folder with a group on a project level (e.g. in the `dbt_project.yml` file), but you can't actually declare the group itself there, which is [confusing](https://getdbt.slack.com/archives/CBSQTAPLG/p1695308192389719?thread_ts=1695299430.881839&cid=CBSQTAPLG).

I suggest allowing the declaration of new groups directly in the `dbt_project.yml` file. This way, all groups can be managed in one place, ensuring consistency for all project teams and members.

**Comment by dbeatty10** [comment]
Thanks for raising this idea @evgeniybobok !

### Overview

When it comes to `dbt_project.yml`, groups are similar to other resource types (like models).

e.g., models can be [_configured_](https://docs.getdbt.com/reference/configs-and-properties) within `dbt_project.yml`, but they can't be _defined_ there. We plan to keep it this way.

### Conventions for defining groups

To reduce confusion about where to create new groups, we suggest choosing a convention that works for your team.

Here are some options:
1. Single `_groups.yml` file in the root of the `models` directory
1. Single `_groups.yml` file in the root of a `groups` directory
1. Create your own convention!

Here's how option 2 would look like in practice:

Configure [`model-paths`](https://docs.getdbt.com/reference/project-configs/model-paths) within dbt_project.yml like this:

```yaml
model-paths: ["models", "groups"]
```

### Summary

I'm going to close this as "not planned" because we want to keep `dbt_project.yml` focused on configurations rather than introducing definitions.

But we'd definitely be interested to hear any feedback on any conventions you explore for where to define groups. Your experiences could help define [how we structure our dbt projects](https://docs.getdbt.com/guides/best-practices/how-we-structure/1-guide-overview) in the future 💡
