### ISSUE TITLE
[CT-3360] rerun from timeout

### ISSUE THREAD

**Issue by Melissa1047** [dbt-labs/dbt-core#9034]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The company I work for moved over to dbt Core v1.6 and we're pretty excited about it. We especially love that we can now rerun from failure. I'm curious is it possible to rerun from timeout?! This would be a game changer for us as we do have a run timeout set and occasionally have big models that make us exceed that.

### Describe alternatives you've considered

There are no alternative besides re-running the entire thing, which can take hours.

### Who will this benefit?

I think this can benefit anyone who uses dbt.

### Are you interested in contributing this feature?

N/A

### Anything else?

Can't wait to see if this becomes an option!

**Comment by dbeatty10** [comment]
Thanks for reaching out @Melissa1047 !

I'm assuming that  [`dbt retry`](https://docs.getdbt.com/reference/commands/retry) would work for timeouts too since they are a type of failure.

Wanna test it out and let us know if it doesn't work for timeouts the way you want or expect?

p.s. Out of curiosity, why not just raise the ceiling for timeouts? All other things being equal, wouldn't you expect it to just timeout two times in a row?

**Comment by Melissa1047** [comment]
> I'm assuming that [`dbt retry`](https://docs.getdbt.com/reference/commands/retry) would work for timeouts too since they are a type of failure.
This has happened in our production runs. If I were running it in my local, I could see using `dbt retry`. But, if I want a production run to start where it failed, I don't think this would work.

> p.s. Out of curiosity, why not just raise the ceiling for timeouts? All other things being equal, wouldn't you expect it to just timeout two times in a row?

So, the reason I have timeouts is because I was burned once with a recursive model running for over 8 hours (multiple days in a row). That has since been fixed, but I like keeping relatively conservative timeouts in place so we can see if something is taking longer to run than it should. What brought it up this time, was in a PR build.  We switched loaders, so we had to pick a new schema, etc. for over 30 models. So, all of the models coming in from the new loader have to run and do a full-refresh, I upped the timeout to be 4 hours, thinking surely it would complete in that time, but it didn't. But, now I don't want to run the entire thing again. I could remove the timeout entirely, but if I could re-run it from where it timed out, it sure would save us a lot.

**Comment by dbeatty10** [comment]
Totally understandable to be conservative after being burned ❤️

> But, if I want a production run to start where it failed, I don't think this would work.

Why wouldn't `dbt retry` work for restarting a failed production run from where it failed?

**Comment by Melissa1047** [comment]
> Totally understandable to be conservative after being burned ❤️
> 
> > But, if I want a production run to start where it failed, I don't think this would work.
> 
> Why wouldn't `dbt retry` work for restarting a failed production run from where it failed?

This is probably a lack of knowledge on my part. But, I have this job, for the Main Deploy. If it times out, how/where would I do `dbt retry`?

![image](https://github.com/dbt-labs/dbt-core/assets/105672569/c8171761-a92f-4cab-8cf2-3c1cf33946ee)

**Comment by dbeatty10** [comment]
I haven't tried it myself yet, but I think it would be like this (assuming you want a single retry):

## Execution settings
### Commands
```shell
dbt seed --select state:modified+ --full-refresh
dbt run-operation create_udf
dbt run --select state:modified+ --full-refresh --exclude tag:exclude_from_running
dbt retry
dbt test --select state:modified+ --exclude tag:exclude_from_running
```

### No-op when you're on the happy path

When you're on the happy path (which hopefully is most of the time), here's what the output would look like for the `dbt retry` command:

```
$ dbt run
...
19:10:49  Finished running 1 view model in 0 hours 0 minutes and 0.29 seconds (0.29s).
19:10:49  
19:10:49  Completed successfully
19:10:49  
19:10:49  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1

$ dbt retry
19:10:53  Running with dbt=1.6.7
19:10:53  Registered adapter: postgres=1.6.7
19:10:53  Found 1 model, 1 seed, 0 sources, 0 exposures, 0 metrics, 353 macros, 0 groups, 0 semantic models
19:10:53  
19:10:53  Nothing to do. Try checking your model configs and model specification args
```

Wanna try this out in a testing environment and see if it works?

**Comment by Melissa1047** [comment]
What you are suggesting would work, in theory. We would just have to manually go into the production job to add `dbt retry` to the run, after it times out, so it doesn't always just retry on it's own, even when we don't want it to. I was hoping for an option we could select like `rerun from failure` in the event we choose to want to run it again, but that it doesn't just do it on it's own.

**Comment by dbeatty10** [comment]
If you are really hoping for an option to select like `rerun from failure`, then you'd just need to submit this as a feature request within the dbt Cloud interface so that this gets to the right team. Click the "Leave feedback" link:

<img width="350" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/853fee96-60be-4209-b621-5aed42535d5c">

</br>
</br>

In the meantime, I think our intent is that you are safe to always include `dbt retry` within all your production runs because it will execute very quickly if there is nothing to do. It's a quick no-op when you're on the happy path. But when there is a failure, it will take the time to retry from that point forward.

Since it doesn't sound like there's an ask of dbt-core here, I'm going to close this in favor of you raising a feature request within the dbt Cloud interface. If I misunderstood, just let me know and we can re-consider re-opening this.

Thanks again for taking the time to submit this suggestion, and sorry to need to redirect you!

**Comment by jtcohen6** [comment]
Hey @dbeatty10 @Melissa1047 - this exists in dbt Cloud, check it out!

<img width="546" alt="Screenshot 2023-11-08 at 18 10 41" src="https://github.com/dbt-labs/dbt-core/assets/13897643/26b5b542-8da2-483e-8e62-ab0abd7db195">

https://docs.getdbt.com/docs/deploy/retry-jobs
https://docs.getdbt.com/dbt-cloud/api-v2#/operations/Retry%20a%20failed%20run%20for%20a%20job

**Comment by Melissa1047** [comment]
> Since it doesn't sound like there's an ask of dbt-core here, I'm going to close this in favor of you raising a feature request within the dbt Cloud interface. If I misunderstood, just let me know and we can re-consider re-opening this.

I appreciate your help and I will definitely still use your suggestion!

**Comment by Melissa1047** [comment]
> sts in dbt Cloud, check it out!

Yes! We love this feature, we were hoping there was a similar option, but that it would re-run from a timeout instead of an error. Which, I learned, is possible with code, just not a nice little button like above ;)

**Comment by dbeatty10** [comment]
I can't send you a direct link because it is a pop-up modal window.

But here's the steps to get there:

1. Log in to dbt Cloud

2. Click the "?" icon in the upper left hand side 
    <img width="63" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/afdb97cc-11b2-428e-b5ff-5b59e3e6e77e">

3. Click the "Leave feedback" link
    <img width="188" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/7f2ce9a0-ba9e-4055-988d-3cb559a3d96e">

4. Add your feedback, tick the checkbox (if you want), and click the "Send Feedback" button
    <img width="400" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/d958adf2-cb74-4551-aaae-0faa2cbf0cc8">
