### ISSUE TITLE
[CT-3368] [Regression] `warn-unpinned` is ignored (dbt deps, packages.yml)

### ISSUE THREAD

**Issue by seub** [dbt-labs/dbt-core#9050]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The [dbt documentation](https://docs.getdbt.com/docs/build/packages) specifies that if a package is added to package.yml with `warn-unpinned: false`, then the warning is suppressed.

It does not work: the warning still appears.

```yml
packages:
  - git: https://github.com/dbt-labs/dbt-utils.git
    warn-unpinned: false
```

```
The git package "https://github.com/dbt-labs/dbt-utils.git" is not pinned.
This can introduce breaking changes into your project without warning!
```
    

### Expected Behavior

Warning is suppressed

### Steps To Reproduce

Create packages.yml as above, run `dbt deps`

### Relevant log output

```shell
18:10:04  Installing https://github.com/dbt-labs/dbt-utils.git
18:10:07  WARNING: The git package "https://github.com/dbt-labs/dbt-utils.git" 
        is None.
        This can introduce breaking changes into your project without warning!

See https://docs.getdbt.com/docs/package-management#section-specifying-package-versions
```

### Environment

```markdown
- OS: MacOS Ventura
- Python: 3.9.10
- dbt: 1.7.1
```

**Comment by dbeatty10** [comment]
Thanks for reporting this @seub 🙏

### Root cause

This looks like a regression introduced in dbt 1.7.0 by https://github.com/dbt-labs/dbt-core/pull/6735.

The `package-lock.yml` that it creates is missing the `warn-unpinned: false` field.

### Reprex
I was able to reproduce the same thing as you with the following:

`packages.yml`
```yaml
packages:
  - git: https://github.com/dbt-labs/dbt-utils.git
    warn-unpinned: false
```

Then:
```shell
dbt deps
```

Then it creates a file like the following:

`package-lock.yml`
```yaml
packages:
- git: https://github.com/dbt-labs/dbt-utils.git
  revision: HEAD
sha1_hash: 15d074833b26c33d0ebabcfdac42b925eba0e019
```

### Workaround

But if I just change that `package-lock.yml` file by hand to add `warn-unpinned: false`, then it works:
```yaml
packages:
- git: https://github.com/dbt-labs/dbt-utils.git
  revision: HEAD
  warn-unpinned: false
sha1_hash: 15d074833b26c33d0ebabcfdac42b925eba0e019
```

### Acceptance criteria
- When `warn-unpinned` is set to `false`, its key/value pair persists within `package-lock.yml`
- When `warn-unpinned` is set to `false`, it doesn't give a `WARNING` message

**Comment by jtcohen6** [comment]
IMO - we should solve for this by _actually pinning_ the `git` package (with commit SHA) in the package "lock" file. That's the whole goal of "locking," to provide repeatable & predictable installs! You'll still get the "unpinned" warning when you run `dbt deps` for the first time, or `dbt deps --upgrade` to update the lock file.
