### ISSUE TITLE
[CT-3381] [Feature] Aliases for dbt-packages

### ISSUE THREAD

**Issue by alexandre-bernard** [dbt-labs/dbt-core#9073]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

In our project, we'd like to update all dbt-packages using [Renovate](https://www.mend.io/renovate/).
Renovate cannot be plugged directly to dbt hub, so I'm pluging it to Github.

In order to do this, I'm using a customManagers from Renovate.
The problem I'm facing is that the named of the package is not always the same as the name of the Github project (eg : dbt-labs/dbt_utils vs dbt-labs/dbt-utils      or     dbt-labs/codegen vs dbt-labs/dbt-codegen).

I'm aware that renaming the package or the repository is not an option.
Is it possible to add an alias for the package so we could use the Github project name instead of the package name ?

### Describe alternatives you've considered

In the packages.yml, I tried to install the packages with Git but as said in the docs, dbt deps cannot handle duplicate dependencies whit Git.

**Comment by dbeatty10** [comment]
Thanks for raising this idea @alexandre-bernard 💡 

### Question

> The problem I'm facing is that the name of the package is not always the same as the name of the Github project (eg : dbt-labs/dbt_utils vs dbt-labs/dbt-utils or dbt-labs/codegen vs dbt-labs/dbt-codegen).

Could you share more why the [dbt project name](https://github.com/dbt-labs/dbt-utils/blob/6ba7b660b1d1b4e3b41cb0cf6c3c0e4a70ae54e4/dbt_project.yml#L1) being different from the [GitHub repo name](https://github.com/dbt-labs/dbt-utils) is a problem?

### Option 1

For the alias, are you thinking a custom `name` similar to [this](https://docs.getdbt.com/docs/build/packages#internally-hosted-tarball-url)?
```yaml
packages:
  - tarball: https://codeload.github.com/dbt-labs/dbt-utils/tar.gz/0.9.6
    name: 'my_custom_package_name'
```

`analyses/my_thing.sql`
```sql
{{ dbt_utils.pretty_log_format("my log message") }}
```

Compile it and look at the output within the `target` directory:
```shell
dbt compile
```

### Option 2

Or are you wanting the macros to use the alias as well like this?

`analyses/my_thing.sql`
```sql
{{ my_custom_package_name.pretty_log_format("my log message") }}
```

**Comment by joshuajohananorthos** [comment]
I am not the original author but we would like this feature as well. Our use case is a little different.

We have built custom packages for certain datasets. Then we want to use the same dataset package, but pointed to different sources. We cannot import the same package twice into another project. We currently just split out the projects so that each one is only pulled in once. We were hoping to have larger project that encompassed all our data instead of multiple little packages. 

Most of our packages our local if that matters.

Example packages.yml
```yaml
packages:
  - local: ../modules/dataview_dataset
    name: dv_one
  - local: ../modules/dataview_dataset
    name: dv_two
  - local: ../modules/our_utils
```

In the project I would expect to use
```python
{{ dv_one.pretty_log_format("message")  }}
```
or
```sql
SELECT *
FROM {{ ref('dv_one', 'table') }}
```

**Comment by dbeatty10** [comment]
Thanks for adding your use-case @joshuajohananorthos !

Even if we did allow specifying a `name` alias when installing [local packages](https://docs.getdbt.com/docs/build/packages#local-packages), the `name` within `dbt_project.yml` still has to be unique for each package that you install. Otherwise, you'll get an error like this:

```
02:06:25  Encountered an error:
Compilation Error
  dbt found more than one package with the name "dataview_dataset" included in this project. Package names must be unique in a project. Please rename one of these packages.
```

Since we're not planning on relaxing the requirement that each imported package name need be unique, I'm going to close this as "not planned".
