### ISSUE TITLE
[CT-3414] [Bug] Error while generating snapshot after adding a column

### ISSUE THREAD

**Issue by karthikp8888** [dbt-labs/dbt-core#9135]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Adding a column in source data and regenerating snapshot resulted in below error: 

```
oracle adapter: Oracle error: ORA-00920: invalid relational operator
```

Above error is caused by below snippet of SQL generated by DBT. Two references to "TRUE" are causing the error:

```sql
 insertions as (

        select
            'insert' as dbt_change_type,
            source_data.*

        from insertions_source_data source_data
        left outer join snapshotted_data on snapshotted_data.dbt_unique_key = source_data.dbt_unique_key
        where snapshotted_data.dbt_unique_key is null
           or (
                snapshotted_data.dbt_unique_key is not null
            and (
                **(TRUE)**
            )
        )

    ),

 updates as (

        select
            'update' as dbt_change_type,
            source_data.*,
            snapshotted_data.dbt_scd_id

        from updates_source_data source_data
        join snapshotted_data on snapshotted_data.dbt_unique_key = source_data.dbt_unique_key
        where (
            **(TRUE)**
        )
    )
```

### Expected Behavior

Snapshot should have been regenerated with additional column

### Steps To Reproduce

- Issue can be reproduced using DBT core version 1.6.9 or  1.7.2
- Below is the model

```sql
{{ config(materialized='view') }}

with source_sq as (

    select * from test_schema.test_table
)

select *
from source_sq
```

- Below is snapshot

```sql
{% snapshot test1 %}

{{
    config(
      target_database='test',
      target_schema='test_schema',
      unique_key='guid',

      strategy='check',
      check_cols='all',
      on_schema_change='append_new_columns'
    )
}}


select * from {{ ref('test') }}

{% endsnapshot %}
```

- Run "dbt  run" followed by "dbt snapshot"
- Then run alter to add a column to test_schema.test_table
-  Run "dbt  run" followed by "dbt snapshot"
- Ora Error should occur
oracle adapter: Oracle error: ORA-00920: invalid relational operator

### Environment

```markdown
- OS:Windows
- Python:3.8
- dbt:1.6.9
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

Oracle

**Comment by dbeatty10** [comment]
Thanks for reporting this @karthikp8888 !

This looks like a bug in [dbt-oracle](https://github.com/oracle/dbt-oracle/issues/new/choose) rather than dbt-core.

It sounds like support for the `BOOLEAN` data type was just [added in Oracle 23c](https://www.oracle.com/database/23c/#boolean-data-type), so that could explain why you are seeing this error.

The fix would be adding a definition similar to [this](https://github.com/dbt-msft/dbt-sqlserver/blob/9546c40044c82c46cdd3383fc14448a0d28d405a/dbt/include/sqlserver/macros/materializations/snapshots/snapshot.sql#L17-L19) in dbt-oracle (which you can also verify by adding to your project):
```sql
{% macro oracle__get_true_sql() %}
  {{ return('1=1') }}
{% endmacro %}
```

Since the fix won't be in this repo, I'm going to close this bug report. Could you create a new bug report with [dbt-oracle](https://github.com/oracle/dbt-oracle/issues/new/choose) instead?
