### ISSUE TITLE
[CT-3514] [Feature] Use formatting for `package-lock.yml` that passes `yamlint` linting checks

### ISSUE THREAD

**Issue by nevdelap** [dbt-labs/dbt-core#9319]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`package-lock.yml` does not have a document separator and does not have correct indentation.

Run `ymllint --strict` on a newly created `package-lock.yml`.

```bash
> dbt deps
> cat package-lock.yml
packages:
- package: dbt-labs/audit_helper
  version: 0.9.0
- package: dbt-labs/codegen
  version: 0.12.1
- package: dbt-labs/dbt_utils
  version: 1.1.1
sha1_hash: 3cf6af6c0a4ee17cf53205ae383d515915b55f5f
> docker run --rm -v $(pwd):/data cytopia/yamllint:latest --strict /data/package-lock.yml
/data/package-lock.yml
  1:1       warning  missing document start "---"  (document-start)
  2:1       error    wrong indentation: expected at least 1  (indentation)

> echo $?
1
```

### Expected Behavior

That it be generated correctly formatted. For example here, when manually fixed it passes.

```bash
> cat package-lock.yml
---

packages:
  - package: dbt-labs/audit_helper
    version: 0.9.0
  - package: dbt-labs/codegen
    version: 0.12.1
  - package: dbt-labs/dbt_utils
    version: 1.1.1
sha1_hash: 3cf6af6c0a4ee17cf53205ae383d515915b55f5f
> docker run --rm -v $(pwd):/data cytopia/yamllint:latest --strict /data/package-lock.yml
> echo $?
0
```

### Steps To Reproduce

As above.

### Relevant log output

```shell
N/A
```

### Environment

```markdown
- OS: Linux
- Python: 3.11
- dbt: 1.7.4
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for noticing this and reaching out about it with a nice write-up @nevdelap ! 🤩 

This seems to only affect linting rather than the actual behavior of dbt, so I'm going to re-categorize this as a feature request.

I don't see a need for us to add the `---` part since we haven't typically included it in our style guide for other YAML documents like `dbt_project.yml`, etc. Do you see value in us adding the document start for `package-lock.yml`?

The workaround we'd recommend is to use the various [configuration options for `yamllint`](https://yamllint.readthedocs.io/en/stable/configuration.html) to either ignore `package-lock.yml` entirely or to relax the strictness.

In the meantime, I'm going to label it as a `good_first_issue` for a community member to tackle the indentation portion.

### Acceptance criteria
- after running `dbt deps`, `package-lock.yml` contains an indention level of 2 spaces and looks similar to below
- `yamllint --strict package-lock.yml --no-warnings` has an exit code of 0
  - use `echo $?` to see the exit code

  `package-lock.yml`
  
  ```yaml
  packages:
    - package: dbt-labs/audit_helper
      version: 0.9.0
  sha1_hash: 3cf6af6c0a4ee17cf53205ae383d515915b55f5f
  ```

**Comment by jx2lee** [comment]
can i take this issue?

**Comment by dbeatty10** [comment]
> can i take this issue?

Yup, sounds great @jx2lee 👍 Thanks for opening https://github.com/dbt-labs/dbt-core/pull/9341 🏆
