### ISSUE TITLE
[CT-3561] [Feature] Add graph variable to query-comment context

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-core#9392]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

dbt generic tests can't have a `meta` config key, but the models they depend on do. Consequently I'd like to be able to associate the `meta` of generic tests' dependent models to the test themselves in the query comment in https://github.com/get-select/dbt-snowflake-query-tags.

A use case for this is wanting to calculate the cost of the queries associated with a specific meta.owner key (including those dependent generic tests).

I can retrieve the list of upstream models for the generic test using the `node` variable, but I have no way of getting access to the meta for those models because the `graph` variable is not available in the query comment jinja context.

### Who will this benefit?

Query comment power users, users of https://github.com/get-select/dbt-snowflake-query-tags, users of https://github.com/get-select/dbt-snowflake-monitoring

### Are you interested in contributing this feature?

If it's an easy one, sure!

**Comment by dbeatty10** [comment]
Thanks for raising this idea @NiallRees !

The [context](https://github.com/dbt-labs/dbt-core/blob/0da5dfecbb45632d52ecdb07ad2c5b4726c246ca/core/dbt/context/manifest.py#L75) used for parsing the `query_header` is based off the `ManifestContext` and does not contain the `graph`.

It _might_ be possible to do something else, such as defer the construction of the query header macro generator and use a different context, but that code is pretty complex.

Due to the complexity involved, I'm going to close this as "not planned".
