### ISSUE TITLE
[Feature] Extend accidental feature (Snowflake) to other adapters (BQ, Postgres, etc)

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-core#9486]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

It looks like with `dbt show` we have an accidental feature on Snowflake - can we have this extended to other adapters?

```sql
-- models/foo.sql
select 1 id
```

Build our model:

```sh
$ dbt run -s foo
$ dbt --debug show --inline "foo"
...
01:30:25  On sql_operation.my_dbt_project.inline_query: /* {"app": "dbt", "dbt_version": "1.6.9", "profile_name": "all", "target_name": "sf", "node_id": "sql_operation.my_dbt_project.inline_query"} */
select *
    from (
        foo
    ) as model_limit_subq
    limit 5
...
01:30:28  Command end result
01:30:28  Previewing inline node:
| ID |
| -- |
|  1 |

01:30:28  Command `dbt show` succeeded at 14:30:28.275039 after 7.62 seconds
```

^ We can see that on Snowflake, show inline with the model name resulted in valid Snowflake SQL:

![image](https://github.com/dbt-labs/dbt-core/assets/8496748/9e958e8d-d5f6-4c7e-88d6-14db73357055)

Now - test this out on BQ:

```sh
$ dbt --debug show --inline "foo"
...
01:33:48  On sql_operation.my_dbt_project.inline_query: /* {"app": "dbt", "dbt_version": "1.6.9", "profile_name": "all", "target_name": "bq", "node_id": "sql_operation.my_dbt_project.inline_query"} */

  
    select *
    from (
        foo
    ) as model_limit_subq
    limit 5


01:33:50  BigQuery adapter: https://console.cloud.google.com/bigquery?project=cse-sandbox-319708&j=bq:US:3c440160-4ee9-4503-891a-c763c2a5a747&page=queryresults
01:33:50  BigQuery adapter: Retry attempt 1 of 1 after error: BadRequest('Syntax error: Expected keyword JOIN but got ")" at [7:5]; reason: invalidQuery, location: query, message: Syntax error: Expected keyword JOIN but got ")" at [7:5]')
```

Which is an invalid BQ syntax:

![image](https://github.com/dbt-labs/dbt-core/assets/8496748/16747510-0de3-4be9-b2f4-e2f895a52e72)

Similarly this syntax is also invalid for Postgres (and I guess Redshift).

### Describe alternatives you've considered

It's possible to override the adapter versions of the macro - for example (on BQ):

```sql
{% macro default__get_limit_subquery_sql(sql, limit) %}
    select *
    from (
        select * from {{ this.schema }}.{{ sql }}
    ) as model_limit_subq
    limit {{ limit }}
{% endmacro %}
```

Which would make the syntax work (`show --inline "<model name>"`) but potentially break it when the inline selection is something else... Maybe check if it's a single word or something.

### Who will this benefit?

Anyone who wants to highlight just name of the model and preview in the dbt Cloud IDE:

![2024-01-30 14 35 27](https://github.com/dbt-labs/dbt-core/assets/8496748/8f50d837-e009-4cbc-80fc-86214c009797)

^ BQ does not work cause invalid SQL generated.

![2024-01-30 14 36 53](https://github.com/dbt-labs/dbt-core/assets/8496748/8c9ba65b-bd71-43d3-8a30-cf35f3dd003e)

^ Snowflake - working good.

### Are you interested in contributing this feature?

No

### Anything else?

@wusanny discovered this accidental feature.

**Comment by dbeatty10** [comment]
Nice find @jeremyyeo 💡 !

Your videos show off nicely a cool feature of previewing within dbt Cloud that accidentally works in Snowflake, but could purposely work for other adapters as well.

I took a peek at the implementation in dbt-core + adapters:

### Interactive compile

Basically, [interactive compile](https://docs.getdbt.com/reference/commands/compile#interactive-compile) has two features:
1. Compile a specific node using `--select foo`
2. Compile an explicit Jinja+SQL query using `--inline some_sql_with_jinja_here`

Then each of these flags is available for `dbt show` also.

Your override of `default__get_limit_subquery_sql` would be invoked in the latter case, and I'm guessing it would break if you try a legit query like the following:

```shell
dbt show --inline "select 1 as id"
```

There's many different ways we could approach your feature request, here are a couple:

### Alternative proposal 1

To get the behavior you are going for, we could do the following in dbt Cloud:

If the selection is an exact match with a node name, then:
- utilize the `dbt show --select foo` syntax

Otherwise:
- utilize the `dbt show --inline some_sql_with_jinja_here` syntax

### Alternative proposal 2

Or we could try to bake it directly into the macro that `--inline` utilizes:

```sql
{% macro default__get_limit_subquery_sql(sql_or_node_name, limit) %}

    {% set sql = namespace(value=sql_or_node_name) %}

    {% for node in graph.nodes.values() %}
        {% if sql_or_node_name == node.name %}
            {% set sql.value = "select * from " ~ node.relation_name %}
        {% endif %}
    
    {% endfor %}

    select *
    from (
        {{ sql.value }}
    ) as model_limit_subq
    limit {{ limit }}
{% endmacro %}
```

### Trade-offs

It depends if it's more helpful to preview:
1. The logical state in the code base
1. The physical state in the database

For the alt proposal 2, the result has one key difference from doing a `dbt show --select foo`:
- `--inline` does a query on the current table that is materialized in the database, while `--select` reflects the most recent logic in `models/foo.sql` (even if it is different than what is within the database!).

For what it's worth, I'll often use `dbt show --inline` to get the physical state in the database during troubleshooting. i.e., do a couple snapshots or incremental models with different inputs and then examine the result afterwards. `dbt show --select` might be more useful during development of a non-incremental model.

**Comment by dbeatty10** [comment]
Here's how we an easily preview a dbt node (including any logical changes) by its name, unique_id, file path, or FQN:

```sql
dbt show --select models/my_model.sql
```

This issue wonders: what if we could show a dbt node (just what is actually materialized to the database) by its name, unique_id, file path, or FQN?

```sql
dbt show --inline models/my_model.sql
```

The latter would avoid needing to fully write out the entire SQL statement like:

```sql
dbt show --inline "select * from {{ ref('my_model') }}"
```

Here's the custom macros I played around with to accomplish this:

<details>
<summary>
Custom macros
</summary>

```sql
{% macro matches_node(id, node) -%}
    {% if id == node.name %}
        {% do return(True) %}
    {% elif id == node.unique_id %}
        {% do return(True) %}
    {% elif id == node.original_file_path %}
        {% do return(True) %}
    {% elif id == node.fqn | join(".") %}
        {% do return(True) %}
    {% endif %}

    {% do return(False) %}
{%- endmacro %}


{% macro default__get_limit_subquery_sql(sql_or_node_name, limit=none) %}

    {% set sql = namespace(value=sql_or_node_name) %}

    {% for node in graph.nodes.values() %}
        {% do log(node.unique_id ~ ", node:", info=false) %}
        {% do log(node | tojson(indent=2), info=false) %}
        {% if matches_node(sql_or_node_name, node) %}
            {% set sql.value = "select * from " ~ node.relation_name %}
        {% endif %}
    {% endfor %}

    select *
    from (
        {{ sql.value }}
    ) as model_limit_subq
    limit {{ limit }}
{% endmacro %}
```

</details>

**Comment by dbeatty10** [comment]
After chatting though this with @jtcohen6, what is observed in the Cloud IDE and CLI is accidental feature of Snowflake rather than dbt.

Closing this in favor of work the dbt Cloud IDE team is doing in relation to `limit`.
