### ISSUE TITLE
[Spike+][jinja if statement] [false positives] environment-aware logic in config should not cause resources to Always selected by state:modified

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9563]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Many folks want to have logic in their dbt project that _purposely_ differs by environment. 

For example, let's say I want to materialize a model as a view in `dev` but as a table in `prod`.

To accomplish this, I use a jinja if statement in my config block:
```
{{ config(
    materialized = "{{ 'table' if target.name == 'prod' else 'view' }}"
) }}

select *
from ...
```

When selecting `--select state:modified` and comparing my `dev` environment to a manifest from `prod`, this model will **ALWAYS** be marked as `modified`. This is because, the materialized config appears different - in `prod` it's `table`, in `dev` it's `view`. 

Instead, if I've changed nothing about this model, it shouldn't be marked as modified because the "if" statement/jinja logic hasn't changed. 

### Describe alternatives you've considered

A current work-around is to move _all_ environment-based logic to my `dbt_project.yml` file. 

If instead, I were to configure this model as so:
```
models:
  <path_to_my_model>:
    +materialized: "{{ 'table' if target.name == 'prod' else 'view' }}"
```
it would NOT be picked up when selecting `--select state:modified`. 

But this is cumbersome, unexpected, and can lead to an unnecessarily _massive_ `dbt_project.yml` file. 

### Who will this benefit?

Anyone who wants to use `state:modified` and has environment-based logic in their dbt project.

### Anything else?

Potential solution proposed here https://github.com/dbt-labs/dbt-core/issues/3680

This is relevant for all resources that can be configured, not just models.

**Comment by jtcohen6** [comment]
@graciegoheen How would you feel about recommending an in-between solution:
```yml
# models/path/to/my_model.yml
models:
  - name: my_model
    config:
      materialized: "{{ 'table' if target.name == 'prod' else 'view' }}"
```

Effectively, the same mechanism as in `dbt_project.yml`: we saved the raw Jinja text as `unrendered_config`, and compare the node's `unrendered_config` instead of the resolved config values. It does mean that, if someone edited the Jinja expression to be `"{{ 'table'        if target.name != 'prod' else 'view' }}"` — adding a bit of whitespace, no functional change — it would still be detected as a change by `state:modified`.

Reasons I like this approach:
- [usability] Avoids the problem of massive overloaded `dbt_project.yml`
- [feasibility] I believe it would be much easier for us to implement than statically analyzing + saving `{{ config() }}` arguments within model files

**Comment by graciegoheen** [comment]
@jtcohen6 can you help me understand the difference between:
```
models:
  - name: my_model
    config:
      materialized: "{{ 'table' if target.name == 'prod' else 'view' }}"
```
and
```
{{ config(
    materialized = "{{ 'table' if target.name == 'prod' else 'view' }}"
) }}

select *
from ...
```

Why can we save the raw Jinja text as `unrendered_config` in the first scenario but not the second?

**Comment by jtcohen6** [comment]
> Why can we save the raw Jinja text as `unrendered_config` in the first scenario but not the second?

It has to do with the way dbt uses Jinja for rendering + storing configs. In the first case, because it's a standalone Jinja expression in yaml, we can save `"{{ 'table' if target.name == 'prod' else 'view' }}"` as the unrendered config value associated with just the `materialized` key.

But in the second case, what the user actually provides ([no nested curlies](https://docs.getdbt.com/docs/building-a-dbt-project/dont-nest-your-curlies) except for pre/post-hook) is:
```sql
{{ config(
    materialized = ('table' if target.name == 'prod' else 'view')
) }}

select *
from ...
```
As I understand it, dbt resolves the entire `{{ config() }}` macro call, storing the fully resolved results (`'table'` or `'view'`). There is no intermediate step where we can store just `('table' if target.name == 'prod' else 'view')` as the unrendered config value of the `materialized` key. If we did want to do that, we'd need a static analysis/extraction step, as described in https://github.com/dbt-labs/dbt/issues/3680.

I'm definitely not saying it's impossible, just more difficult to implement. I think the conditional-Jinja-in-yaml case offers us a quicker win with lower lift.

**Comment by jtcohen6** [comment]
To support this pattern with `sources` (and probably other resource types), I believe we'd need to also do the work of treating `database` + `schema` + `identifier`/`alias` as configs, such that we can [save their unrendered values when configs are calculated](https://github.com/dbt-labs/dbt-core/blob/2411f93240a346961e6a965ad9cb5c766db275a0/core/dbt/parser/sources.py#L151-L154).

**Comment by michael-urrutia** [comment]
I ran into a similar issue recently where we had a macro for selecting the Snowflake warehouse size. Worth calling out that in an ideal world the logic could be encapsulated within a macro that is called within the project file. This is important to avoid redundancy and create more dry code, as well as handle complicated logic more elegantly. It is my understanding that macros cannot be currently referenced in the `dbt_project.yml` file today - issue [here](https://github.com/dbt-labs/dbt-snowflake/issues/103#issuecomment-1792775783). Although different, I think these issues are pretty coupled. Model configs should be able to be applied at the project or individual model level with identical behavior

**Comment by joellabes** [comment]
I'd be all-in on jinja-in-yaml if we also put [yaml-in-sql](https://github.com/dbt-labs/dbt-core/issues/7099) 😉

**Comment by MichelleArk** [comment]
Closed by: https://github.com/dbt-labs/dbt-core/pull/10487/files#diff-b14dff35dc9759591980bed526df1689bbe35b4a06e176d8af0880ae43afbb3a
