### ISSUE TITLE
failing unit test displayed in system logs, not at the node level

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9619]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

[Here’s a quick loom walking through the problem](https://www.loom.com/share/335a3ad0f3fd44828f4c6a232a5dfeee)

I can see the logs for a failing unit test in the system logs, but not at the node level

### Expected Behavior

- I should be able to view the failing unit test log message at the node level
- I should be able to view the failing data test log message at the node level

**Comment by gshank** [comment]
This works the same way as data tests.  Maybe it shouldn't, of course...   The NodeFinished logging event contains the RunResult (which contains the actual error text) but the "msg" is just "Finished running node [unit_test.my](http://unit_test.my/)_[dbt_unit_tests.my](http://dbt_unit_tests.my/)_model.test_my_model".  After that the logging events don't have node_info, and so won't be separated out into node specific logs.

**Comment by gshank** [comment]
This is actually the way it works for all erroring nodes, like models.  The errors are reported at the end from RunResultError (etc) events, and this is after all the other nodes have run. So I don't think we can just add node_info to the RunResult events, it might throw off other things.  At the end of each node execution, we clear out the node_info, for one thing, and the errors are reported long after. So this might not be something that can be fixed in core or in core alone.
