### ISSUE TITLE
[Feature] I want to override the schema/database my unit test temp tables are built into

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-core#9684]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Some folks have strict access requirements that prevent developers from creating tables in the schemas/databases used for their dbt models. 

This prevents them from creating a unit test for that type of model, because dbt attempts to build a temp table in that schema/database. 

We should provide the ability to override the schema/database used for the temp unit testing tables, so that folks can configure their unit test definitions to use a sandbox location (separate from their actual tables).

**Comment by dbeatty10** [comment]
@graciegoheen, @jtcohen6 and myself discussed this, and we'd rather if the instigating use-cases can be solved via an implementation detail rather than via a configurable option.
 
A couple options we discussed briefly:
1. Build the temporary objects in the same database + schema as the model being tested
1. Build the temporary objects in the [`target.database`](https://docs.getdbt.com/reference/dbt-jinja-functions/target) + [`target.schema`](https://docs.getdbt.com/reference/dbt-jinja-functions/target) from the [connection profile](https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles)

Two edge-cases we've seen in the wild to take into account:
1. The dbt process doesn't have permission to write to the schema for model being tested
    - for example, because there's a separate team that has responsibility for the DDL for the incremental model
1. The configured [`target.schema`](https://docs.getdbt.com/reference/dbt-jinja-functions/target) is a dummy that is always overridden within the project

**Comment by dbeatty10** [comment]
We're gonna close this as "won't do", but if anyone really wants this, please reach out and describe your scenario and we can consider re-opening it.

**Comment by bjakubowskiVNSNY** [comment]
Hi @dbeatty10 + @graciegoheen -

We have a scenario that could be addressed by overriding the schema/DB where the unit test temp tables are built. But, I think a better solution would be to **allow unit tests to create custom schemas** (consistent with [dbt's approach to building models in custom schemas](https://docs.getdbt.com/faqs/Models/create-a-schema#:~:text=dbt%20will%20check%20if%20the,will%20create%20it%20for%20you.)).

We're running `dbt run` and `dbt test` in a slim-CI pipeline. When a developer opens a MR, their changed models are built and tested in a transient, MR-linked custom schema.

We're now migrating to `dbt>1.7`, and we want to be able to add unit tests to our legacy models.

Unfortunately, when developers open new MRs contributing just unit tests, the tested models aren't rebuilt in the MR-linked custom schema --since the model hasn't changed. As a result, dbt isn't creating transient, MR-linked schema. So, when `dbt test`  runs `unit_tests`, they are failing on `create {DB}.{MR_LINKED_SCHEMA}.{UNIT_TEST}__dbt_tmp` since the custom MR-linked schema `{MR_LINKED_SCHEMA}` doesn't exist.

Since dbt behavior already includes creating custom schemas where needed, it seems reasonable for dbt to create custom schemas for unit test tmp tables.

Let me know if that's unclear -- happy to try to provide a MRE, and thanks for all your work on `dbt` 🙂

**Comment by pransito** [comment]
We also struggle with this! Unit tests should be idempotent because they depend only on fixtures. It should be possible to run them in a bespoke schema where the temporary tables can be created. We have eg. the case that in CICD we run unit tests first because they are quick and small and independent and if they fail the whole ci pipeline should not continue. Now if we introduce a completely new target schema(s) (target schema prefix) only for the cicd run (to not disturb the production schema) then on the first such cicd run those schemas do not even yet exists and then the unit tests complain: 

```
16:28:50    Runtime Error in unit_test test_onboarding_table_pv_unnested (models/intermediate/_unit_tests.yml)
  An error occurred during execution of unit test 'test_onboarding_table_pv_unnested'. There may be an error in the unit test definition: check the data types.
   Runtime Error
    NOT_FOUND: Schema dbt_aip_transformations_dscicds_stg not found.
```

However the schema: `dbt_aip_transformations_dscicds_stg` is not needed for the unit test. It could be in any other schema. This makes the unit tests not idempotent...

OR...

The unit tests should also notice: "schema does not yet exist"; So I will create it! :-)
