### ISSUE TITLE
[Show] Results for show command should be return in Result from DBT Runner

### ISSUE THREAD

**Issue by hash-data** [dbt-labs/dbt-core#9716]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

dbtRunnerResult (have success, exception and logs)but it does not return show command result (preview which comes from dbt show command)
More information about the feature can be found here: 
https://getdbt.slack.com/archives/CBSQTAPLG/p1708674952675789

**Comment by dbeatty10** [comment]
Thanks for reaching out @hash-data !

You can get that data from `RunResult.agate_table` which gives an [`agate.Table`](https://agate.readthedocs.io/en/latest/api/table.html).

Here's an example script (that is a slight variation on [this](https://docs.getdbt.com/reference/programmatic-invocations) one):

```python
from dbt.cli.main import dbtRunner, dbtRunnerResult

# initialize
dbt = dbtRunner()

# create CLI args as a list of strings
cli_args = ["--quiet", "show", "--select", "my_model"]

# run the command
res: dbtRunnerResult = dbt.invoke(cli_args)

# inspect the results
for r in res.result:
    table = r.agate_table

    for row in table:
        print(row.dict())
```

Since I think this will give you what you're after, I'm going to close this as "not planned". Please let us know if we overlooked something important.
