### ISSUE TITLE
[Bug] column with text type expand error

### ISSUE THREAD

**Issue by pengyusong** [dbt-labs/dbt-core#9751]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

column text type  will be change varchar(256)

### Expected Behavior

column text type  will be sticked

### Steps To Reproduce

1. create postgres table A: with id column type int, desc column with text type,
2. create postgres table ods_a table with desc column with varchar(512) type
3. dbt incremental model A like that
`select id, desc from {{source('ods', 'ods_a')}}`

exec model, postgres table A will be change to varchar(256)

### Relevant log output

it may be `Column.can_expand_to` function somethin wrong.
`Column.string_size` return text type as size 256, so `Column.can_expand_to` condition wrong

### Environment

```markdown
- OS:windows
- Python:3.9
- dbt: 1.7.9
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
Do you have a text string longer than 256 that dbt is truncating?

Or does the column only contain strings that fit within varchar(256)?

### Short story

If dbt is truncating a string longer than 256, then we'd consider this a bug. But otherwise, this doesn't sound like a bug to me.

### More detail

In general, dbt lets postgres decide the size, precision and/or scale of data types (like `varchar` or `numeric`, etc). That way, you don't have to worry about a long string being accidentally truncated.

But we do allow for configuring and enforcing [dbt model contracts](https://docs.getdbt.com/reference/resource-configs/contract) for folks that want to be explicit about data types (and optionally their size, scale, precision, etc).

In your particular case, here is one thing you could try:
```sql
select id, desc::varchar(512) from {{ source('ods', 'ods_a') }}
```

But we'd consider artificially constraining the size to be an anti-practice that we don't recommend.

**Comment by pengyusong** [comment]
> If dbt is truncating a string longer than 256, then we'd consider this a bug. But otherwise, this doesn't sound like a bug to me.
This is not my problem, `dbt ` not truncate `desc` column, but change my target table `desc` column type. because my target table column type is `text`,  dbt should not change to `varchar(512)` .

I want my target table column  `desc`  stick `text ` type, not change to varchar(512) .  It change column type by using add and delete column, when table size larger, it take too much time.

That is to say， I can control `dbt ` when and where  alter the target table.

**Comment by dbeatty10** [comment]
It sounds like your source / reference table has a column type of `varchar(512)`. But you want your target column in your incremental model to be `text` (rather than `varchar(512)`).

Since these data types differ, you'll need to cast to the `text` data type within your incremental model no matter what. Otherwise, dbt will think you want to preserve the original `varchar(512)` data type.

### Step 1: Casting to `text`

Within your target model, you'll need to cast to the text data type.

Here's one syntax option to accomplish this:
```sql
select id, description::text from {{ source('ods', 'ods_a') }}
```

Here's another option:

```sql
select id, cast(description as text) from {{ source('ods', 'ods_a') }}
```

### Step 2: Alter your incremental model

If the database table for your incremental model currently has the `text` data type, then you don't need to do anything further for this step.

But if not, then you'll need to alter the data type within the database as well.

There are two ways to do this:
1. Do a [full refresh](https://docs.getdbt.com/reference/resource-configs/full_refresh) on your model. If you have a very large table, this could take a while and/or incur monetary costs.
2. Manually do an [`alter` statement](https://www.postgresql.org/docs/8.0/sql-altertable.html) in your database to change the data type.

### Step 3: disable schema changes (optional)

If you don't want your incremental model to ever make any schema changes (not even add new columns), then you can using the [`on_schema_change`](https://docs.getdbt.com/docs/build/incremental-models#what-if-the-columns-of-my-incremental-model-change) config:

```sql
on_schema_change="fail"
```

Configuring and enforcing [dbt model contracts](https://docs.getdbt.com/reference/resource-configs/contract) is another option. Depending on the database and the specific data types involved, this might require dropping the target table and starting from scratch (or using [`--full-refresh`](https://docs.getdbt.com/reference/resource-configs/full_refresh)).

<details>
<summary>

### Example
</summary>

When starting from scratch, the following example works for me to have `varchar(512)` in the reference table and `text` in the target table.

`seeds/ods_a.csv`

```csv
id,description
1,this is a description from the reference system using the VARCHAR(512) data type
```

`seeds/_seeds.yml`

```yaml

seeds:
  - name: ods_a
    config:
      column_types:
        id: integer
        description: varchar(512)
```

`models/my_model.sql`

```
{{ config(
    materialized="incremental",
    on_schema_change="sync_all_columns",
) }}

select
    id,
    description::text as description
    
from {{ ref("ods_a") }}
```

(Re)build the incremental model and all its upstream parents:
```shell
dbt build -s +my_model --full-refresh
```

Check data types of reference and target tables:

```shell
dbt show --inline "select ordinal_position, column_name, data_type, character_maximum_length from information_schema.columns where table_schema = '{{ target.schema }}' and table_name = '{{ ref(\"ods_a\").identifier }}' order by ordinal_position"
dbt show --inline "select ordinal_position, column_name, data_type, character_maximum_length from information_schema.columns where table_schema = '{{ target.schema }}' and table_name = '{{ ref(\"my_model\").identifier }}' order by ordinal_position"
```

Output
```
15:39:19  Previewing inline node:
| ordinal_position | column_name | data_type         | character_maximum... |
| ---------------- | ----------- | ----------------- | -------------------- |
|                1 | id          | integer           |                      |
|                2 | description | character varying |                  512 |

15:39:26  Previewing inline node:
| ordinal_position | column_name | data_type | character_maximum... |
| ---------------- | ----------- | --------- | -------------------- |
|                1 | id          | integer   |                      |
|                2 | description | text      |                      |
```

</details>

Since the steps above  to be working for me, I'm going to close this as "not planned". However, if the steps above don't work for some reason, please reach out and we can take another look at this.

**Comment by pengyusong** [comment]
but `text `  type size should larger then `varchar(512)`, shoul not expand .

**Comment by dbeatty10** [comment]
Hi @pengyusong, if you can provided a detailed step-by-step example similar to the code examples in https://github.com/dbt-labs/dbt-core/issues/9751#issuecomment-1994758101, then we can take another look at this.

Here's what it looks like when you expand this section:

<img width="600" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/9473f40f-8b53-40c2-9233-73b1c42862b3">

**Comment by pengyusong** [comment]
When starting from scratch, the following example works for me to have varchar(512) in the reference table and text in the target table.

`seeds/ods_a.csv`

```
id,description
1,this is a description from the reference system using the VARCHAR(512) data type
```
`seeds/_seeds.yml`
```

seeds:
  - name: ods_a
    config:
      column_types:
        id: integer
        description: varchar(512)
```
`models/my_model.sql`  
### There is change, i do not want `description::text`, I think converting to `text ` is redundant because in common sense, `text ` should be larger than the size of any ` varchar (n)`

```
{{ config(
    materialized="incremental",
    on_schema_change="sync_all_columns",
) }}

select
    id,
   description as description
    --description::text as description
    
from {{ ref("ods_a") }}
```
(Re)build the incremental model and all its upstream parents:

`dbt build -s +my_model --full-refresh`
Check data types of reference and target tables:

```
dbt show --inline "select ordinal_position, column_name, data_type, character_maximum_length from information_schema.columns where table_schema = '{{ target.schema }}' and table_name = '{{ ref(\"ods_a\").identifier }}' order by ordinal_position"
dbt show --inline "select ordinal_position, column_name, data_type, character_maximum_length from information_schema.columns where table_schema = '{{ target.schema }}' and table_name = '{{ ref(\"my_model\").identifier }}' order by ordinal_position"
```
Output

```
15:39:19  Previewing inline node:
| ordinal_position | column_name | data_type         | character_maximum... |
| ---------------- | ----------- | ----------------- | -------------------- |
|                1 | id          | integer           |                      |
|                2 | description | character varying |                  512 |

15:39:26  Previewing inline node:
| ordinal_position | column_name | data_type | character_maximum... |
| ---------------- | ----------- | --------- | -------------------- |
|                1 | id          | integer   |                      |
|                2 | description | character varying |                  512 |
```

### There is change, i do not want `description::text`, I think converting to `text ` is redundant because in common sense, `text ` should be larger than the size of any ` varchar (n)`, 
### So text can be larger then varchar(512), column type change in this situation is incorrect
