### ISSUE TITLE
[Feature] Update documentation website without restarting the service

### ISSUE THREAD

**Issue by WangSleep** [dbt-labs/dbt-core#9777]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

hello 

my dbt version : 1.7.2

my question :  can i not need to restart the dbt docs service every time?

if it dose work, so how can i do

thanks for ur answer

**Comment by dbeatty10** [comment]
> my question : can i not need to restart the dbt docs service every time?

I just did an experiment to see how this behaves. Here's what I found:

You can re-run [`dbt docs generate`](https://docs.getdbt.com/reference/commands/cmd-docs#dbt-docs-generate) without needing to re-run [`dbt docs serve`](https://docs.getdbt.com/reference/commands/cmd-docs#dbt-docs-serve) (as long as the service is still running).

However, the website user will need to refresh the web page to get the latest updates.

Since we don't have plans to change the deployment workflow or how this behaves, I'm closing this as "not planned".
