### ISSUE TITLE
[Feature] Add fnMatch (Wildcard support) to group selectors

### ISSUE THREAD

**Issue by heysweet** [dbt-labs/dbt-core#9811]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Many selector methods support wildcard:

- fqn
- tag
- source
- exposure
- metric
- file
- package
- test

Group is similar to tags, and it's possible user may want to use characters like spaces in group names. If a group or tag has a space in it, it's impossible to use selector syntax to target it without fnMatch, where you can substitute the ` ` with a `?`.

### Describe alternatives you've considered

The alternatives of banning spaces outright in things like group names is much more prohibitive, and the alternative of adding support for spaces in sector values is a larger ask.

### Who will this benefit?

Anybody using groups will be able to better target them. In Explorer, it'd be valuable to support groups with spaces via `?` substitution, instead of filtering out groups which have spaces in them.

### Are you interested in contributing this feature?

Yes

**Comment by dbeatty10** [comment]
Makes sense @heysweet !

Absolutely buy the argument that you should be able to select by a certain group, even if it has a space in it.

Overall, it seems like wildcard selection can be useful whenever a selector method targets a string value that users can control (and in which they might have common prefixes or postfixes). The scenario in which it doesn’t seem to have value is when a selector method targets a field that doesn’t/can't have any groupings by prefix or postfix (e.g., a small enumeration that dbt controls).

So it makes sense to add to add wildcard selection to the ["group" selector method](https://docs.getdbt.com/reference/node-selection/methods#the-group-method) like you did in https://github.com/dbt-labs/dbt-core/pull/9812 to support spaces, but also because users can control the valid values 🚀
