### ISSUE TITLE
[Bug] fqn method in selectors.yml is selecting path, not model

### ISSUE THREAD

**Issue by SunriseLong** [dbt-labs/dbt-core#9829]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When the `value` of  `method: fqn` matches that of a directory under `models/`, the selector will select all models under that directory as opposed to just the model.

As per [docs](https://docs.getdbt.com/reference/node-selection/methods#the-fqn-method): `The fqn  method is used to select nodes based off their "fully qualified names" (FQN) within the dbt graph`.

This causes an issue for us as there is overlap between directories and model names

### Expected Behavior

`value` passed to `method: fqn` should identify and select models, not the path. 

### Steps To Reproduce

<img width="285" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44146580/4ad79b5a-da7c-44ea-b91b-89f41b7dfed8">

selectors.yml: 
```yaml
selectors:
  - name: test_selector
    definition:
      union:
        - method: fqn
          value: "a_test_directory"
```

Output of `dbt ls --selector test_selector`:
```
app# dbt ls --selector test_selector
22:48:17  Running with dbt=1.5.1
22:48:17  Found 53 models, 0 tests, 0 snapshots, 1 analysis, 394 macros, 1 operation, 3 seed files, 37 sources, 0 exposures, 0 metrics, 0 groups
thirdwave_dbt.a_test_directory.model_1
thirdwave_dbt.a_test_directory.model_2
thirdwave_dbt.a_test_directory.model_3
```
<img width="762" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44146580/499186fa-2e79-4f17-8173-ae16b8e37b35">

### Environment

```markdown
docker python:3.9.1-slim
- dbt: dbt-snowflake==1.5.1
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reaching out @SunriseLong !

This is a feature of the FQN selector method in dbt rather than a bug, so I'm going to close this as "not planned".

### More detail

If you run a plain [`dbt list`](https://docs.getdbt.com/reference/commands/list) (without any selector), you'll see something like this:
```
thirdwave_dbt.a_test_directory.model_1
thirdwave_dbt.a_test_directory.model_2
thirdwave_dbt.a_test_directory.model_3
```

And if you look at a pretty-printed version of your [`manifest.json`](https://docs.getdbt.com/reference/artifacts/manifest-json), you'll see something like this:
```yaml
            "fqn": [
                "thirdwave_dbt",
                "a_test_directory",
                "model_1"
            ],
```

Since `a_test_directory` is a subdirectory name that is part of the FQN, it is matched by [this](https://github.com/dbt-labs/dbt-core/blob/02d7727365cfb2fc7664797938412aec07018db2/core/dbt/graph/selector_methods.py#L62) code.

Thank you for pointing out that [our documentation](https://docs.getdbt.com/reference/node-selection/methods#the-fqn-method) isn't clear on this -- I've opened up this issue as a result: https://github.com/dbt-labs/docs.getdbt.com/issues/5191
