### ISSUE TITLE
A tests: key of None/Null at the model level fails parsing validation in 1.7, but didn't in 1.4

### ISSUE THREAD

**Issue by will-sargent-dbtlabs** [dbt-labs/dbt-core#9845]
An empty tests: key in the model shema YAML file throws a parsing error in 1.7+, when it is working or ignored in 1.4 (core especially)

Why does this matter?  I have customer looking to migrate from 1.4 core/cloud to 1.7, and we had to painfully work through the parse and reparse to find each error, because the parser dies on these errors. (Find one and die, fix, full parse, find next and die).

Sample:

```
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      tests:
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
  ```
  The `tests:` key under `description:` is the problem.

Error message:
```
Parsing Error
  Invalid models config given in models/example/schema.yml @ models: {'name': 'my_first_dbt_model', 'description': 'A starter dbt model', 'tests': None, 'columns': [{'name': 'id', 'description': 'The primary key for this table', 'tests': ['unique', 'not_null']}], 'original_file_path': 'models/example/schema.yml', 'yaml_key': 'models', 'package_name': 'my_new_project'} - at path ['tests']: None is not of type 'array'
23:08:09 Parsing Error
  Invalid models config given in models/example/schema.yml @ models: {'name': 'my_first_dbt_model', 'description': 'A starter dbt model', 'tests': None, 'columns': [{'name': 'id', 'description': 'The primary key for this table', 'tests': ['unique', 'not_null']}], 'original_file_path': 'models/example/schema.yml', 'yaml_key': 'models', 'package_name': 'my_new_project'} - at path ['tests']: None is not of type 'array'
```

**Comment by dbeatty10** [comment]
> we had to painfully work through the parse and reparse to find each error, because the parser dies on these errors. (Find one and die, fix, full parse, find next and die).

@will-sargent-dbtlabs Oooch 😬

I'm not sure yet if we'll choose to change anything in 1.7 or not to directly address this type of situation.

But as a workaround, see below for a simple Python script that will recursively search for this type of thing within a dbt project in your current working directory.

<details>
<summary>
Toggle to see Python code
</summary>

`python search_none_tests.py`

```python
import yaml
import glob
import os


def find_none_tests(data, path=[]):
    """
    Recursively search for keys named 'tests' with None values in the given data.
    :param data: The current part of the data to search through.
    :param path: The current path to this point in the data.
    :return: A list of paths to 'tests' keys with None values.
    """
    if isinstance(data, dict):
        for key, value in data.items():
            if key == "tests" and value is None:
                yield path + [key]
            else:
                yield from find_none_tests(value, path + [key])
    elif isinstance(data, list):
        for index, item in enumerate(data):
            yield from find_none_tests(item, path + [index])


def examine_yaml_file(yaml_file_path):
    if os.path.isfile(yaml_file_path):
        with open(yaml_file_path, "r") as file:
            data = yaml.safe_load(file)

        none_tests_paths = list(find_none_tests(data))
        if none_tests_paths:
            print(f"Found `tests` key with None values in {yaml_file_path}:")
            for path in none_tests_paths:
                print("    " + " -> ".join(map(str, path)))


def search_and_examine_yaml_files():
    # Search for all YAML files in the current directory and all subdirectories
    yaml_files = glob.glob("**/*.yaml", recursive=True) + glob.glob(
        "**/*.yml", recursive=True
    )

    if not yaml_files:
        print("No YAML files found.")
        return

    for yaml_file in yaml_files:
        examine_yaml_file(yaml_file)


if __name__ == "__main__":
    search_and_examine_yaml_files()
```

</details>


Then run it like this:
```shell
python search_none_tests.py
```

And get output like this:
```
Found `tests` key with None values in models/schema.yaml:
    models -> 0 -> columns -> 0 -> tests
Found `tests` key with None values in models/_properties.yml:
    models -> 0 -> tests
    models -> 0 -> columns -> 0 -> tests
```

**Comment by dbeatty10** [comment]
I took a look at this scenario in version 1.4 vs. 1.5, and it started giving the following error in 1.5 (whereas it was allowed in 1.4):

```
00:19:44  Encountered an error:
Parsing Error
  Invalid models config given in models/_models.yml @ models: {'name': 'my_model', 'tests': None, 'columns': [{'name': 'id', 'tests': ['not_null']}], 'original_file_path': 'models/_models.yml', 'yaml_key': 'models', 'package_name': 'my_project'} - at path ['tests']: None is not of type 'array'
```

Since this scenario is explicitly called out in the [migration guide for 1.5](https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.5#:~:text=An%20empty%20tests%3A%20key%20in%20a%20yaml%20file%20will%20now%20raise%20a%20validation%20error) (see screenshot below), I'm going to close this as "not planned".

<img width="450" alt="image" src="https://github.com/dbt-labs/dbt-core/assets/44704949/4b3de74e-fe4e-44b1-a5ae-0bff806dffe9">

**Comment by will-sargent-dbtlabs** [comment]
Thanks for the docs link @dbeatty10.
Makes sense to me on the not planned on allowing it.

However, is there a way that the parser won't die completely each time it hits one?  We had to wait to parse the project 4-5 times just to find the next error and it was extremely painful...

**Comment by dbeatty10** [comment]
> However, is there a way that the parser won't die completely each time it hits an error like this?

We hear you on how painful this was 😢

Due to the complexities involved, I don't see us moving off the "die upon first parsing failure" approach.

> We also had no idea how many of these we would hit because of that, so we are kind of like, how long do we keep this up, (can we fix in a few minutes) or is this like a sprint-impacting spike we need to do...

If you were to do this migration from 1.4 over again from scratch, I'd suggest running the Python script in https://github.com/dbt-labs/dbt-core/issues/9845#issuecomment-2040664868 to see how many of these you were facing. Then that would help you assess and estimate how much effort it would take to resolve this particular upgrade edge case.

Alternatively, I could imagine some of the YAML-editing strategies used in [dbt-meshify](https://github.com/dbt-labs/dbt-meshify) or [dbt-osmosis](https://github.com/z3z1ma/dbt-osmosis) being adopted in a custom program that tries to perform an updated. i.e., it would attempt to edit all the relevant YAML files in-place to achieve this part of the migration from 1.4 to 1.5.

**Comment by will-sargent-dbtlabs** [comment]
Yeah, thanks. I suspected it's a complex issue. It's not hard to imagine a scenario where continuing on in the parse actually creates a bunch of false errors.

Scripts!  I'm definitely game.  Perhaps someday we can have a toolbox of these in the Cloud IDE.  Thanks!!
