### ISSUE TITLE
[Bug] Line Comment after config and Jinja call/set functions causes incorrect compilation of sql

### ISSUE THREAD

**Issue by MosBabe** [dbt-labs/dbt-core#9858]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In a sql file, I added a single comment line with "--" characters after the config block. Then I called and set some variables with jinja templates. After jinja I wrote an basic SQL. But the compiled version of SQL is incorrect because lack of "break line".
It only happens when I add comment line with "--" characters between config and jinja call statements.
There is no error , if I add comment line above the config.
There is no error, if I add comment line with comment block (/* .... */) 

The sql file :
***********************************************************************
```sql
{{
  config(
    materialized = 'incremental',
    )
}}

--comment

{%- call statement('MONTH_INFO', fetch_result=True) -%}
      ...
{%- endcall -%}

{%- call statement('YEAR_INFO', fetch_result=True) -%}
      ...
{%- endcall -%}

{%- set MONTH_INFO = load_result('MONTH_INFO')['data'][0][0] -%}
{%- set YEAR_INFO = load_result('YEAR_INFO')['data'][0][0] -%}

{%- call statement('query1', fetch_result = True) -%}
	    ...
{%- endcall -%}

{%- set query1 = load_result('query1')['data'][0][0] -%}

SELECT *
  FROM ...
```

***********************************************************************
  Compiled version:
```sql
  --commentSELECT *
  FROM ...
```

### Expected Behavior

 Expected Compiled version:
```sql
  --comment
SELECT *
  FROM ...
```

### Steps To Reproduce

I am using dbt-core. I checked the log files to find the reason of the error but I can't figure out what causes the mistake. 
I am sharing the log files details below. I think these files and lines will show the source of the mistake.

Lib>site-packages>jinja2>sandbox.py (line 393)
Lib>site-packages>jinja2>runtime.py (lines 298,763, 777)
Lib>site-packages>dbt>clients>jinja.py (lines 329,256)

### Environment

```markdown
- OS:Windows 10 Enterprise 2016 LTSB (x64)
- Python:Python 3.11.4
- dbt:1.6
'ODBC Driver 17 for SQL Server'
```

### Which database adapter are you using with dbt?

'ODBC Driver 17 for SQL Server'

**Comment by dbeatty10** [comment]
Thanks for reaching out @MosBabe !

Do you need a SQL comment? Or would a [Jinja comment](https://jinja.palletsprojects.com/en/3.1.x/templates/#comments) like the following work?

```
{# comment #}
```

If you need/want a SQL comment instead of a Jinja comment, I'm guessing you can resolve this yourself by changing some of your `{%-` or `-%}`  into just `{%` or `%}` by removing the `-` character.

Whitespace control in Jinja is notoriously tricky, so you'll need to play around a bit.

This looks to me like something you'll be able to resolve on your end rather than an issue with dbt-core, so I'm going to close this as "not planned". But if you still think this is an issue after trying the above, please reach out and we can revisit this.
