### ISSUE TITLE
[Feature] Update `agate` version

### ISSUE THREAD

**Issue by mjkanji** [dbt-labs/dbt-core#9934]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Agate is currently pinned to `agate>=1.7.0,<1.8"`. If it doesn't raise breaking changes, can the version be increased to the latest version of `agate` (currently 1.9.1).

Installing the latest version of `dbt-core` using `conda-forge` on `osx-arm64` was previously not possible because there was no support for `agate`. The feedstock for `agate` [has now been updated with a `noarch` package](https://github.com/conda-forge/agate-feedstock/issues/21) for the latest version (1.9.1), but none of the available candidates on `conda-forge` match the current pin (`agate>=1.7.0,<1.8"`). As a result, I still can't install `dbt-core` using `conda-forge`.

### Describe alternatives you've considered

N/A

### Who will this benefit?

Anyone trying to install `dbt-core` via `conda-forge`.

### Are you interested in contributing this feature?

If it's a simple change to the pin and running some tests, I can do that.

**Comment by dbeatty10** [comment]
Thanks for reaching out @mjkanji !

As noted in https://github.com/dbt-labs/dbt-core/pull/7368, we put an upper bound on `agate` out of an abundance of caution because there have been breaking changes in past patch/minor versions.

The easiest solution would be if https://github.com/conda-forge/agate-feedstock/issues/21 is resolved by including the relevant versions of `agate`.

But we'd also be willing to look at raising the upper bound so that it includes these more recent versions of `agate` available on [PyPI](https://pypi.org/project/agate/#history):


- 1.9.1 Dec 21, 2023
- 1.9.0 Oct 17, 2023
- 1.8.0 Oct 10, 2023

> If it's a simple change to the pin and running some tests, I can do that.

Yep, to the best of my knowledge, that's what it would involve so I'm going to label this as a `good first issue`. Maybe just update [here](https://github.com/dbt-labs/dbt-core/blob/7e164e3ab723c357cb638ad6c1e1beef19a7fec6/core/setup.py#L52) to be:
```python
        "agate>=1.7.0,<1.10",
```

If you change the upper bound, then the CI tests will run automatically when you open a PR.

**Comment by mjkanji** [comment]
Hi @dbeatty10, thank you for your reply and the input on what's needed to make the change. Please see #9948, which should resolve this. However, it seems that the CI checks were not run because they require a maintainer's approval first. If you could take a look at the PR, that'd be much appreciated!
