### ISSUE TITLE
[Feature] parse model variables to manifest response

### ISSUE THREAD

**Issue by devinaconley** [dbt-labs/dbt-core#9955]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

when calling `parse` programmatically with the `dbtRunner`, it would be useful to also return a list of variables expected for each model node. This would help with introspection, validation, and job definition

### Describe alternatives you've considered

currently, I am just building a string parser against the `ModelNode.raw_code` field to match against `var("x")` patterns

### Who will this benefit?

anyone building an abstraction layer, visual interface, or automation system on top of a set of parameterized dbt models

**Comment by dbeatty10** [comment]
Thanks for opening this @devinaconley ! 💡 

I can definitely see why you'd want something in the [manifest](https://docs.getdbt.com/reference/artifacts/manifest-json) that already does all that parsing rather than needing to roll your own -- especially since dbt is already doing it.

But this isn't something we'd be keen to put our effort towards building and supporting at this time.

So the alternative you mentioned is your best bet.

**Comment by devinaconley** [comment]
Thanks for the response @dbeatty10 ! Totally understand.

Would you open to accepting contributions on this one? If so, could you provide a quick couple lines on how you'd like to see it implemented or preferred pattern for exposing that kind of core data? Happy to take a pass
